### ISSUE TITLE
Packer 1.6.3 vsphere-iso power on with communicator:none

### ISSUE THREAD

**Issue by ctorkington-craven** [hashicorp/packer#10002]
I am working on Packer 1.6.3 with vSphere and have an unusual scenario. 
I want to use the vsphere-iso Builder to create a VM shell with boot_command for BIOS config and configuration_parameters for VM hardening, but no OS installation (This will be done later by PXE boot.)

When I set communicator to "none", it seems to apply the config perfectly, but never powers the VM on, which means the boot_command config is not applied, yet Packer completes successfully and quickly.

I've tried few different configs but I cant seem to get it to power on, apply BIOS settings and then finish successfully.
"communicator": "none",
"disable_shutdown": true,
"force_bios_setup":true,
"boot_order":"ethernet,disk",
"boot_wait": "10s",
"boot_command":[
        "<down><down><down><down><down><down><enter><spacebar><spacebar><esc><right><down><down><down><down><enter><spacebar><down><spacebar><down><spacebar><down><spacebar><spacebar><esc><esc><enter><enter>"],
"configuration_parameters":{ <lots of settings>}

I tried with and without provisioners so I assume it is in the Builder config.

**Comment by sylviamoss** [comment]
Hey there, I think this a duplicate from https://github.com/hashicorp/packer/issues/9924. The vsphere-iso builder currently doesn't do much without a communicator. There's an open PR that will change that https://github.com/hashicorp/packer/pull/9964.
I'll close this issue because we are already keeping track of these changes in the above. Thanks for reaching out!
