### ISSUE TITLE
Serial console boot_command support

### ISSUE THREAD

**Issue by ramereth** [hashicorp/packer#1004]
On some special hardware that supports kvm, the vga console is not supported thus the `boot_command` does not function. However the serial console works perfectly fine.

Would it be possible to add a feature which allows `boot_command` to redirect its typing over the serial character device instead of the vnc console? I could see other applications to do this that could be useful but this specific use case would be great.

**Comment by pingberlin** [comment]
What would be the best way to implement this?
Is a communicator of type "serial" the way to go?
That way the "Shell Provisioner" could be invoked without using a network shared by the host and the guest.

Possible builders are qemu and bhyve.
A use case would be using packer on hosts which mustn't have a TCP connection to the guest due to security restrictions. Another would be running packer on hosts also not using Xorg due to the same reason.

**Comment by mwhooker** [comment]
a serial communicator could be useful, but I don't think that would solve the problem of typing a boot command. I think either adding a "serial_boot_command" option or a "boot_command_mode" with the option of either `serial` or `vnc` would be the way to go. 

unfortunately not much of the boot_command logic is shared, since the scancodes vary between hypervisors

```
./builder/hyperv/common/step_type_boot_command.go
./builder/parallels/common/step_type_boot_command.go
./builder/qemu/step_type_boot_command.go
./builder/virtualbox/common/step_type_boot_command.go
./builder/vmware/common/step_type_boot_command.go
```

so you'd want to figure out a way to make it work with each of the boot command steps.

**Comment by rickard-von-essen** [comment]
I spent some time testing this out when I was looking into creating a bhyve/xhyve builder (which I still hope to finish some day). Serial can be used to type a boot command, but there is a big limitation that most installer ISO don't have serial configured by default and thus it still requires "keyboard" to get started.

But for bhyve/xhyve it is useful since they load the kernel separately. 

One further obstacle when researching this is that there isn't any (to my knowledge) serial com library for Go that cross compiles (i.e. with out cgo). This is less of a problem for bhyve/xhyve since it's only useful on two platforms.

**Comment by mwhooker** [comment]
I saw https://github.com/tarm/serial the other day, which looks like it
only uses cgo for the posix implementation, with a note about possibly
replacing it with syscall package + ioctl

**Comment by rickard-von-essen** [comment]
Yes https://github.com/tarm/serial the one I test the most with. But it requires cgo for Darwin, FreeBSD, and OpenBSD. That can probably be fixed quite easily.

**Comment by pingberlin** [comment]
What about https://github.com/jacobsa/go-serial ?
This project avoids using cgo and instead uses the syscall package.

**Comment by rickard-von-essen** [comment]
I looked at https://github.com/jacobsa/go-serial which looked great with avoiding CGO, but it didn't support FreeBSD so I didn't use it for my POC. The later seems to have support for all the OS we need.

**Comment by pingberlin** [comment]
> I spent some time testing this out when I was looking into creating a bhyve/xhyve builder (which I still hope to finish some day). Serial can be used to type a boot command, but there is a big limitation that most installer ISO don't have serial configured by default and thus it still requires "keyboard" to get started.
> 
> But for bhyve/xhyve it is useful since they load the kernel separately.

I guess the only way to handle this is making it easier for the user to extract a given kernel from an iso.
With "virt-install" you can specify a location like "http", "ftp" or "local path". It then handles extraction automatically this way mostly by guessing: https://github.com/virt-manager/virt-manager/blob/master/virtinst/urlfetcher.py

In my opinion, letting users specify a path on the iso for kernel and initrd for extraction would need the least logic implemented. This would enable easy passing of extra boot arguments without VNC.


> One further obstacle when researching this is that there isn't any (to my knowledge) serial com library for Go that cross compiles (i.e. with out cgo). This is less of a problem for bhyve/xhyve since it's only useful on two platforms.

I played around with https://github.com/bugst/go-serial in order to build a serial provisioner in the fashion of https://github.com/pexpect/pexpect .
Users could interact with the plugin through specifying:

```
{
  "type": "serial",
  "commands": [
    [ "expect", "login:" ],
    [ "sendline", "root" ],
    [ "expect", "Password:" ],
    [ "sendline", "YouPasswordHere" ],
    [ "wait", "5" ],
    [ "sendline", "ansible all -i \"localhost,\" -c local -m shell -a 'echo hello world'" ],
    [ "expect", "hello world" ],
    [ "sendline", "shutdown -r now" ],
  ]
}
```

Any thoughts on both topics? I'll probably better open another issue for the latter.

**Comment by mwhooker** [comment]
seems useful. definitely open another issue if you want to continue discussion. Going to lock this one since I don't want anything important to get lost in a 3 year old issue
