### ISSUE TITLE
alicloud-ecs : Deprecated configuration key: 'disk_size'.  error

### ISSUE THREAD

**Issue by mick1627** [hashicorp/packer#10078]
#### Overview of the Issue

The usage of disk_size raised this error : 

Error: Failed to prepare build: "alicloud-ecs"

1 error occurred:
        * Deprecated configuration key: 'disk_size'. Please call `packer fix` against
your template to update your template to be compatible with the current version
of Packer. Visit https://www.packer.io/docs/commands/fix/ for more detail.

packer fix don't change anything related to disk_size.

#### Reproduction Steps

use disk_size option with alicloud-ecs builder

### Packer version

Packer v1.6.4

**Comment by nywilken** [comment]
Hi there thanks for reaching out. We will take a look at this in time for the next release.

**Comment by SwampDragons** [comment]
Hi there,

The issue is that disk_size and the other disk configuration options are not top-level options. If you want to modify the system disk, you need to do so via a disk mapping. Here's an example of how to create a device mapping: 

```json
  "builders": [{
    "type":"alicloud-ecs",
    "system_disk_mapping": {
      "disk_size": 50,
      "disk_name": "mydisk"
    },
    "image_disk_mappings": [
      {
        "snapshot_id": "someid",
        "disk_device": "dev/xvdb"
      }
    ],
...
}
```

I've modified the docs to make this clearer, since they were very confusing. 

I will take a look at making Packer fix not send the confusing error message.

**Comment by mick1627** [comment]
thanks @SwampDragons, it works.
