### ISSUE TITLE
output_vagrantfile field of vagrant builder not working with the parallels provider

### ISSUE THREAD

**Issue by jamesla** [hashicorp/packer#10086]
Given the following files
```
#packer.json
{
  "builders": [
    {
      "type": "vagrant",
      "communicator": "ssh",
      "source_path": "jamesla/debian-basebox",
      "provider": "virtualbox",
      "output_vagrantfile": "Vagrantfile"
    }
  ]
}
```
```
#Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "test"
  config.vm.provision "shell", inline: <<-SHELL
    echo "HELLO WORLD"
  SHELL
end
```

If you run `packer build packer.json` it will create a vagrant box which can be imported and upon running `vagrant up` you will see the text HELLO WORLD.

However if you change the provider to parallels and peform the same tasks, it will create the box however the vagrant file will not be packaged with the box and you will not see the text HELLO WORLD

Any ideas how I can fix this?

**Comment by jamesla** [comment]
@SwampDragons I watched your talk and I think this is a problem with the parallels vagrant provider not implementing the spec properly. 

I've opened an issue here: https://github.com/Parallels/vagrant-parallels/issues/364

**Comment by xXxrAinZyian** [comment]
Thanks bro

**Comment by SwampDragons** [comment]
Hi, thanks for the ping. I meant to respond and then got distracted 😬 

I think you're right that this looks like an implementation issue with `vagrant package` -- especially since it looks like you were able to reproduce without Packer in that linked issue.

I'm glad you liked the talk. Feb 2019 seems like a lifetime ago! I had to go back and watch it so I could remember what I'd said. Most of what I was working with the Vagrant team on was making sure the package command inside of the Hashicorp-maintained providers was working as expected. 

I took a quick look at the parallels provider, though, and here's what I found. 

Here's the meat of the package command: https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/action.rb#L100-L118

and here's where it's selecting which file to package, with that awkward underscore prefix: https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/action/setup_package_files.rb#L33

I suspect you need to rename that file before you get to the "PackageConfigFiles" call. 

Hope that helps!

**Comment by jamesla** [comment]
> Hi, thanks for the ping. I meant to respond and then got distracted 😬 
> 
> 
> 
> I think you're right that this looks like an implementation issue with `vagrant package` -- especially since it looks like you were able to reproduce without Packer in that linked issue.
> 
> 
> 
> I'm glad you liked the talk. Feb 2019 seems like a lifetime ago! I had to go back and watch it so I could remember what I'd said. Most of what I was working with the Vagrant team on was making sure the package command inside of the Hashicorp-maintained providers was working as expected. 
> 
> 
> 
> I took a quick look at the parallels provider, though, and here's what I found. 
> 
> 
> 
> Here's the meat of the package command: https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/action.rb#L100-L118
> 
> 
> 
> and here's where it's selecting which file to package, with that awkward underscore prefix: https://github.com/Parallels/vagrant-parallels/blob/master/lib/vagrant-parallels/action/setup_package_files.rb#L33
> 
> 
> 
> I suspect you need to rename that file before you get to the "PackageConfigFiles" call. 
> 
> 
> 
> Hope that helps!

Thanks for your help @SwampDragons [https://github.com/Parallels/vagrant-parallels/pull/368](https://github.com/Parallels/vagrant-parallels/pull/368)
