### ISSUE TITLE
Builder vsphere-iso: Error running boot command

### ISSUE THREAD

**Issue by ComradeAx0n** [hashicorp/packer#10136]
#### Overview of the Issue

The problem with "boot command". When I run build on VMware ESXi, 6.5.0, 6765664 its okay. But when I run on VMware ESXi, 6.0.0, 6921384 its always failed.

```json
==> vsphere-iso: Typing boot command...
2020/10/20 16:38:41 packer-builder-vsphere-iso plugin: Special code '<esc>' found, replacing with: CodeEscape
==> vsphere-iso: Error running boot command: error typing a boot command (code, down) `41, false`: ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.
==> vsphere-iso: Power off VM...
```

### Packer version

1.6.4

### Simplified Packer Buildfile

https://gist.github.com/ComradeAx0n/889b050a2cac0e6f4d910eb6120fdb96

### Operating system and Environment details

WSL Ubuntu 20.04.1 LTS

### Log Fragments and crash.log files

https://gist.github.com/ComradeAx0n/00cbc2acb865e496854543f91356144f

**Comment by smallsam** [comment]
I believe this boot command option relies on using the PutUsbScanCodes API which was introduced in ESXi 6.5.0, this is most likely why it is failing on 6.0.0.

https://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.VirtualMachine.html

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

This builder doesn't support vSphere versions < 6.5, as documented [here](https://www.packer.io/docs/builders/vmware/vsphere-iso#packer-builder-for-vmware-vsphere):

>This builder is supported for vSphere version 6.5 and greater. Builds on lower versions may work, but some configuration options may throw errors because they do not exist in the older versions of the vSphere API.

Since we don't have plans to add backwards support, I'm going to close this issue. If you need to use an older version of esxi you may be able to use the [vmware-iso](https://www.packer.io/docs/builders/vmware/iso) builder instead.
