### ISSUE TITLE
allow us to use YAML to define templates

### ISSUE THREAD

**Issue by kidbrax** [hashicorp/packer#10153]
Please allow templates to be defined in YAML. It is easier to read and, more importantly, allows comments.

I know there has been talk/work towards allowing HCL but it has been years and still isn't available. Also, not sure what the aversion to YAML is.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

HCL has been available and in beta since Packer v1.5.0 -- as of the current version (v1.6.4), most of the issues have been ironed out and we are confident it will be out of beta by the end of the year. I encourage you to try it out. You can switch your templates using the command `packer hcl2_upgrade mytemplate.json`. Docs tailored to upgrading are [here](https://www.packer.io/guides/hcl/from-json-v1) and more detailed HCL docs are found [here](https://www.packer.io/docs/from-1.5) 

We won't be supporting YAML because we already support two configuration languages and don't want to add the maintenance burden of a third. If you want to write your templates in YAML, there are third party tools available to you; I believe the most popular one is [yacker](https://yacker.readthedocs.io/en/latest/).
