### ISSUE TITLE
Error waiting for AMI. Reason: <nil>

### ISSUE THREAD

**Issue by Binternet** [hashicorp/packer#10299]
#### Overview of the Issue

While building a large ebs-based AMI with a big ebs-volume, the following error is thrown:

`==> amazon-ebs: Error waiting for AMI. Reason: <nil>`

#### Reproduction Steps

Run a build with a 1.5TB EBS volume

### Packer version

1.5.1

### Simplified Packer Buildfile

```
18:13:27     amazon-ebs: AMI: ami-0e181d8e7bc364ede
18:13:27 ==> amazon-ebs: Waiting for AMI to become ready...
18:43:21 ==> amazon-ebs: Error waiting for AMI. Reason: <nil>
```

### Operating system and Environment details

Jenkins running on Ubuntu 16.04.7 LTS

**Comment by nywilken** [comment]
Hi there @Binternet we've seen similar issues, usually caused by timeouts when running large builds - https://github.com/hashicorp/packer/issues/8792, https://github.com/hashicorp/packer/issues/9705

Could you try the suggestions at https://packer.io/docs/builders/amazon.html#resourcenotready-error to see if it helps resolve the issue. 

With that said, you may get more useful information if you set PACKER_LOG=1 in your environment.

**Comment by Binternet** [comment]
Now it passed, probably a 'show it to the doctor' syndrome :-) closing for now.
