### ISSUE TITLE
Key Vault Soft Delete Issue

### ISSUE THREAD

**Issue by ShaneBala-keyvault** [hashicorp/packer#10339]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Soft delete will eventually be turned on for all key vaults. This will affect the behavior of the packer tool.

Documented here: https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-change

There needs to be a few changes to the packer tool in order to accommodate this change. 

Packer today does not turn on soft delete on creation of key vaults. - There was a patch submitted to fix this issue in the latest version of the packer tool. In the latest version, packer will create key vaults with soft delete enabled.

When a VM is deleted, the packer tool performs a cleanup or delete of the connected key vault. This delete will no longer permanently delete the underlying key vault but will move the key vault to the soft deleted state. The default retention period of these key vaults is 90 days. 

During the 90 days, if packer attempts to create another key vault with the same name as a key vault in the soft deleted state, the request will fail. 

Remediation steps: 

1) Immediate Mitigation - Set the retention period of key vaults with soft delete enabled to 7 days. This reduces the probability of a conflict occurring. 

2) Update cleanup scripts to delete and purge key vaults with soft delete enabled. 

3) Make tool more robust by checking if a key vault name is available before creating a key vault. 

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by sumit-kalra** [comment]
This stems from #10210 that changed azure-arm builder to create KeyVault only with soft-delete enabled. I expect this to be released in Packer v1.6.6.

**Issue**
When a KV with soft-delete enabled is deleted; it is actually retained as a deleted/hidden KV for some time (default 90 days) and till then no other KV with the same name can be created globally. However, if the KV is purged any time during the retention period, it is permanently deleted and new KV with the same name can then be created.
[Here](https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview) are more details about soft-delete policy.

Now, this should **not be a problem** for Packer, because:

1. Since Packer chooses a random 10 character suffix from 36 character-set for KV name (pkrkxxxxxxxxxxx), I don’t think there’s any significant probability of a collision of Packer choosing the same name in a different build over the rolling 90 day period. 
    - Still, we can make a code change to set the retention period to lowest possible value (7 days) instead of defaulting to 90 days while creating the KV. That will lower the probability even further.

1. azure-arm builder allows specification of [build_key_vault_name](https://www.packer.io/docs/builders/azure/arm#build_key_vault_name). In this case, Packer expects “an existing key vault”. So Packer should not be in the business of trying to create/delete this KV – so the whole “setting soft-delete on create” scenario should not be in picture. 

1. Finally, the last case is if Packer creates a KV and then fails but then retires the same build with the same ARM template. In this case the retry will fail to create the KV. And this is irrespective of whether the retention period is set to to default 90 days or a lower value like 7 days. However, inspection of code doesn’t show any such retries that could use the same name. 
    - Still, we can make a code change to also 'purge' the KV after deletion.

**Conclusion**:
I don't think this bug needs any immediate fix.

**Open Question**:
1. Should a code change be made to lower the retention period to 7 days?
1. Should a code change be made to purge the KV after deletion?
1. If yes, is there any reason to rush one or both of these changes and try catching v1.6.6 release train?

/cc: @paulmey @SwampDragons
