### ISSUE TITLE
vsphere-clone join Windows to AD domain

### ISSUE THREAD

**Issue by mbrewczynski-eis** [hashicorp/packer#10418]
#### Description
We are using vsphere-clone to update existing templates but we can't do that for Windows, because in our case winrm will be unlocked after joining to domain.

vSphere allow automatic connection to windows domain when VM is cloned with option  'Customize guest OS'.
It will be nice to have that in vsphere-clone.

**Comment by andrewamason** [comment]
It looks like this was something that was partially worked on then dropped due to lack of testing? https://github.com/hashicorp/packer/issues/8759

**Comment by SwampDragons** [comment]
That linked issue was closed because the associated PR was merged -- the option is available here https://www.packer.io/docs/builders/vmware/vsphere-clone#customize and here https://www.packer.io/docs/builders/vmware/vsphere-clone#customization

**Comment by andrewamason** [comment]
So the packer customization options for Windows, leverages sysprep. VMware has an OSCustomizationSpec which is configured ahead of time in vCenter: https://developer.vmware.com/docs/powercli/latest/vmware.vimautomation.core/structures/vmware.vimautomation.vicore.types.v1.oscustomization.oscustomizationspec/ 
it would be great if we could pass that as a variable into the vsphere-clone process instead of providing a sysprep file to just specify the name of the customization.

**Comment by park-chief5** [comment]
Ok well the name specify was super legit b....  in a creator though so I’ll go along with your experiment cuz I like huh wanna and agree + Concept is outta the state off the map☺️.  Like I really need, T for realz

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SwampDragons** [comment]
I see. Thanks for the clarification.
