### ISSUE TITLE
Add Static IP option for AWS and Azure

### ISSUE THREAD

**Issue by TechnicalMercenary** [hashicorp/packer#10435]
#### Description

When I'm building an GCP VMI, a googlecompute builder, I can specify an 'address' which allows an "pre-allocated static external IP address".  I do this because a software repo that I'm pulling from is protected by IP whitelist.

I would like something similar in the 'amazon-ebs' builder and the 'azure-arm' builder.  I'm pretty sure that both cloud platforms allow a pre-allocated Static IP to be assigned.

AWS has their Elastic IPs
Azure has 'Public IP address'

#### Use Case(s)

Allow the AMI/VMI being built to have a known IP.  This would allow access to external resources that are secured by IP whitelist ( allow list ).

#### Potential configuration

See the googlecompute documentation for reference

**Comment by SwampDragons** [comment]
You should be able to do this using the [ssh_host](https://www.packer.io/docs/communicators/ssh#ssh_host) template option. I am sure it works for Amazon -- off the top of my head I'm not sure if it works for Azure but it should be fairly straightforward to implement if not.

**Comment by gfokkema** [comment]
@SwampDragons I think you're misunderstanding this feature request. The question is not about connecting to a static IP, but about creating the packer node with a static preconfigured IP. In AWS you'd want to associate an eipalloc to the EC2 instance packer creates.

I'm running into the same problem, I want to pull ubuntu packages from an apt repository that has an IP whitelist, but I can't since the EC2 instance packer creates has a different IP address each time.

The only solution I see right now is to associate an `iam_instance_profile` to the packer instance with permissions to manage eip associations, so the packer instance is able to allocate the EIP to itself via the AWS API.

**Comment by SwampDragons** [comment]
Got it. The internal team isn't going to have time super soon to work on this, but if it is a blocker for you, you can make a PR. 

The code that handles launching source instances is here: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_run_source_instance.go, and if you're using a spot instance it's here: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_run_spot_instance.go. 

It looks like the SDK tooling for associating an elastic IP address is the AssociateAddress method which takes AssociateAddressInput in here: https://github.com/hashicorp/packer/blob/master/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go (can't link line numbers because the file is too big)
