### ISSUE TITLE
How do i install chef-client using packer in windows image and also how it will be pre connect with concern chef server or chef  workstation is there any knife code available if yes where i put that? it is for azure environment

### ISSUE THREAD

**Issue by cdtsushant** [hashicorp/packer#10448]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

#### Potential configuration

```
```

**Comment by nywilken** [comment]
If you're struggling to get Packer working for the first time, I'd recommend reaching out to the community forum for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.

I’m going to close this issue. After getting Packer up and running with Chef you find that you are running into a bug please open a new issue with the requested information in the template and we will try our best to help out.
