### ISSUE TITLE
set_host_for_datastore_uploads doc needs "use"

### ISSUE THREAD

**Issue by crisman** [hashicorp/packer#10459]
#### Overview of the Issue

vsphere-iso has "set_host_for_datastore_uploads" documented as "Set this to true if packer should the host for uploading files..." which should have a "use" like "Set this to true if packer should use the host for uploading files...".

#### Reproduction Steps

https://www.packer.io/docs/builders/vmware/vsphere-iso#set_host_for_datastore_uploads

### Packer version

From `1.6.6` and nightly

**Comment by nywilken** [comment]
Hi @crisman good catch on the documentation. I see you opened a PR against your fork. Can you [change the base branch](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) for the PR to hashicorp/packer#master so that we can merge in the update, please.

**Comment by crisman** [comment]
@nywilken Oops, did not notice I sent the pull to my fork.  Was not able to change the base branch to fix it as far as I can tell, but new pull is up going to the correct place.
