### ISSUE TITLE
template error messages and HCL2 documentation leave out a very important item

### ISSUE THREAD

**Issue by mpictor** [hashicorp/packer#10606]
#### Overview of the Issue

It's far too hard to figure out that hcl2 config files must have a specific extension, which isn't necessary for json.

Related to #8999 (closed).

In the past I've always only used JSON templates with packer. I thought I'd try HCL2 for a new file but was confronted with an error that gave no hints as to how to get hcl2 working.
```
Failed to parse template: Error parsing JSON: invalid character 's' looking for beginning of value
At line 1, column 1 (offset 1):
    1: s
      ^
```
Clearly it assumed json, but nowhere in packer's help output or documentation did I see mention of an arg (or extension) needed to get it working. I tried the obvious extensions, `.hcl2` and `.hcl`, to no avail. 

The error should (but does not) give a hint about the file name. Googling eventually led me to the issue mentioned above, which points to https://www.packer.io/docs/from-1.5#builds . The bit about extensions is far too easy to miss.

Since it matters and isn't all that obvious, I'd expect it to have its own heading on that page as well as a hint with every hcl2 example - perhaps a comment at the top like
```
# file name: myfile.pkr.hcl
```
or
```
# file extension: .pkr.hcl
```

Also, there appears to be an error in that paragraph:
> [...] a name ending with .pkr.hcl or .pkr.json will be parsed using the HCL2 format. [...]

This implies that `*.pkr.json` will be parsed as HCL2, which is surely incorrect.

When I couldn't find anything on [the page I started at](https://www.packer.io/docs/builders/docker#basic-example-export) saying how to use hcl2, I looked at the `build` command's [page](https://www.packer.io/docs/commands/build), thinking there would be an execution example showing a usable file name. There is not.

#### Reproduction Steps

Take any HCL2 example from the documentation and save to a file, such as `packer.hcl2`, then run a command like `packer build packer.hcl2`

### Packer version

```console
$ packer version
Packer v1.6.6
```

### Simplified Packer Buildfile

from https://www.packer.io/docs/builders/docker#basic-example-export
```hcl
source "docker" "example" {
    image = "ubuntu"
    export_path = "image.tar"
}

build {
  sources = ["source.docker.example"]
}
```
### Operating system and Environment details

Ubuntu, AMD64

**Comment by azr** [comment]
Hello @mpictor thanks for opening ! 

Yes I agree this is confusing, while Packer JSON and Packer HCL2 are coexisting, this will remain the case. We're currently working on making the docs easier to parse.

> In the past I've always only used JSON templates with packer. I thought I'd try HCL2 for a new file but was confronted with an error that gave no hints as to how to get hcl2 working.

Yes, this was a hard one; basically before HCL2 whatever the file extension was, Packer would treat the file as JSON. So we couldn't suddenly force users into suffixing their files to `.json`. We don't have metrics for this but often, when something is possible, someone will do it and not tell you about it ( for example name their file `something` and not `something.json`, because it was generated by a template engine, etc. ). So everything that is not our new special case (`.pkr.json` or `.pkr.hcl`) must be treated as JSON.

In the future Packer will parse `.pkr.hcl` as HCL and `.pkr.json` files as the only supported files, and the error message will be clear on that side, but because these two have to coexist for a while; this is kinda confusing.

We could have made the content guessed by peeking at the file, but we consciously went with the decision to make the file content type selectable from input arguments ( file extension or `config-type` arg ) for simplicity.

> This implies that *.pkr.json will be parsed as HCL2, which is surely incorrect.

This needs to be more precise: HCL2 *can* in fact read `.pkr.json` files, but in the new schema that was introduced by HCL2.
