### ISSUE TITLE
What would be the impact if vagrant-libvirt supported multi disk machines?

### ISSUE THREAD

**Issue by electrofelix** [hashicorp/packer#10627]
I'm currently the main active maintainer of github.com/vagrant-libvirt/vagrant-libvirt, and a PR came up last year about looking at supporting multiple disks. Virtualbox handles this scenario transparently to the vagrant provider, however for libvirt, vagrant-libvirt will need to explicitly extend the box metadata format.

While it'll probably take a bit longer before having something that will work the main PR where I've discussed this with someone interested in adding support is https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1143

Specifically I'm thinking that multi disk support should require an explicit format change in how disks are specified, to avoid issues where boxes generated by a post-processor here in packer have a hard dependency on the additional disks.

If the code tries to make existing releases forward compatible, it risks the scenario that someone bringing up a multi disk enabled box with an older version of vagrant-libvirt and the first disk is imported and booted, without the remaining disks, and consequently the VM behaves unexpectedly, possibly failing to correctly start in a non-obvious way other than being unable to connect.

The current proposal is to switch to supporting a new format that looks like:
```
{
    'disks' => [
        {
            'name' => 'disk1.img',
            'virtual_size' => 10,
            'format' => 'qcow2'
        },
        {
            'name' => 'disk2.img',
            'virtual_size' => 15,
            'format' => 'raw'
        },
        {
            'name' => 'disk3.img',
        }
    ],
    ...
}
```

For each disk, it will be imported, and default settings used for size and format if not provided. All other disk options would be ignored when the `disks` element existed in a box metadata.

The code would continue to load existing single disk boxes by taking the disk options and constructing the array as seen above to be consumed by the remaining code.

Beside the required work for packer to support exporting multi disk boxes with the correct format in the future, would this cause any unexpected side effects or issues in being able to manage multi disk boxes?

**Comment by SwampDragons** [comment]
Hi, thanks so much for reaching out and asking. 

Off the top of my head, I think this makes sense and can't think of any side effects as long as the post-processor gets updated to play nicely with the new format. 

I can't sink a ton of thinking time into this until later this week, so I will read your linked PR more deeply in a couple of days and get back to you.

**Comment by rgl** [comment]
This would also be nice for https://github.com/hashicorp/packer/issues/9160

**Comment by electrofelix** [comment]
Landed some initial support for multiple disks in vagrant-libvirt, not yet released, so only available on master for now. Keeping the old format supported so that boxes can be built with a single disk without using the format to allow time for it to be exercised enough.

To simplify some things, also looking to land support where the disk format and virtual size is read from the disk using `qemu-img info ..` on box import so that there won't be any need to write this to the metadata.json going forward.

Basically it should look mostly like the following:
```
{
  'provider': 'libvirt',
  'disks': [
    {
      'path' => 'disk1.img',
    },
    {
      'path' => 'disk2.img',
    },
    {
      'path' => 'disk3.img',
    }
  ]
}
```

Technically at the moment `path` is optional as the disk image can be named `box_<index>.img` and it'll be picked up automatically
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/98ff2dfb51752cd7a9229d5083df58dc2c418de7/lib/vagrant-libvirt/action/handle_box_image.rb#L48-L51

However I'm feeling that might be too magical to allow the following:
```
{
  'provider': 'libvirt',
  'disks': [
    {  },
    {  },
    {  }
  ]
}
```
Which would pick up box.img, box_1.img, and box_2.img, as the disk images to use.

Before being able to remove the format and virtual_size options it made sense as at least 1 option would have to be specified, but now, I think that best to ensure that the path to the disk image coming in is required.

Thoughts? Would that help avoid issues with writing out such metadata.json or doesn't make any difference?

**Comment by SwampDragons** [comment]
Awesome! I think having the path be explicit is better because I also dislike magic, but from Packer's perspective it probably doesn't matter as long as we know what to write.

**Comment by electrofelix** [comment]
I've released vagrant-libvirt 0.5.0 with the multi-disk format supported in an experimental mode, that is, it is supported being read, but currently cannot create a package from vagrant-libvirt using the standard `vagrant package <machine>` call.

https://github.com/vagrant-libvirt/vagrant-libvirt/#version-2-experimental (I've just spotted I've a json formatting issue in the readme)

Hope to see whether there are any gaps/mistakes before saying it is fixed.

Expectation is that `path` is required, `name` is optional and partially controls the volume name used in libvirt, and both format and virtual_size are no longer provided as they can be read directly from the disk referenced by `qemu-img info ...`.
```json
{
  "disks": [
    {
      "path": "disk1.img"
    },
    {
      "path": "disk2.img",
      "name": "secondary_disk"
    },
    {
      "path": "disk3.img"
    }
  ],
  "provider": "libvirt"
}
```

Hoping to re-write the action that handles packaging for vagrant-libvirt so it can be used to export multi disk boxes at some point in the near future. I suspect there are some bugs around device allocation when using additional disks which will probably get exposed when doing this as well.

In the mean time https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/tools/create_box_with_two_disks.sh can be used as a guide as well as the format above.

**Comment by lbajolet-hashicorp** [comment]
Hi @electrofelix,

Looking at @LeConTesteur's PR, I am back here to comment for visibility. I know this issue and related PR have been opened for a long time, apologies for getting to it this late.

From what I understand, the builder won't be impacted at all since it only interacts with vagrant itself, so this use-case is OK as it stands.
As @SwampDragons commented on this thread, the post-processor is the only one that can be impacted by this change, which is what @LeConTesteur's PR addresses.

Judging by the post-processor's code, the box created will use the libvirt provider only if it has been built through the qemu builder, which only outputs a single disk for now, so the current format will not block any usage AFAICT.
As such, I would think that in the current state, if the old format is still valid, we can still use it and only support one disk, the post-processor will continue working as it does, and it doesn't imply any kind of limitation.

There may be an exception with the `efivars.fd` file on UEFI builds though, so we should probably sort this one out for post-processors like libvirt, someone hit that issue a little while back on the GCE plugin, and we still have a PR open for this: https://github.com/hashicorp/packer-plugin-qemu/pull/142.
Out of curiosity, regarding the potential `efivars.fd` file, is there something that the provider does to process it? It's not a disk image, but since it contains values that may be useful for the built machine (keys typically for secure-boot images), this might be important to keep.

This being said, the PR is still valid and I'll give it a review right now, but it's not a pressing matter imo, unless you plan on removing the old format some time soon?

With that, apologies again for taking this long to answer and process this issue/PR, let's get the ball rolling to merge this!

**Comment by LeConTesteur** [comment]
Hi @lbajolet-hashicorp ,
Thanks you for your answer.
I have one question, with **disk_additional_size** option into qemu build, it's possible to have more one disk, no?

**Comment by lbajolet-hashicorp** [comment]
Well, that's a good call @LeConTesteur, it does look like it's possible to have multiple disks indeed, I forgot about this option my bad.
In this case, I would suggest maybe filtering the `efivars.fd` file from your PR so it doesn't get included as a disk, since it's raw data that is only used by the HAL, and not a disk to mount.

Alternatively, rather than using `Files()` from the artifact returned by the builder, I would maybe suggest relying on `qemu_disk_paths` from the artifact's state? This way you would yield the disks' path, then we can use `qemu-img info --output json` (it should be available since we use it to create the images), as otherwise the only disk we know the size of will be the main one.
I do wonder however, is the disk order important? Should we present the main disk first?

I also wonder regarding the virtual_size of each disk, what would be the consequence of not including it in the specification?

**Comment by electrofelix** [comment]
> Hi @electrofelix,
> 
> Looking at @LeConTesteur's PR, I am back here to comment for visibility. I know this issue and related PR have been opened for a long time, apologies for getting to it this late.

No worries, it takes time for the support added to vagrant-libvirt to appear in the distro packages anyway.

> There may be an exception with the `efivars.fd` file on UEFI builds though, so we should probably sort this one out for post-processors like libvirt, someone hit that issue a little while back on the GCE plugin, and we still have a PR open for this: [hashicorp/packer-plugin-qemu#142](https://github.com/hashicorp/packer-plugin-qemu/pull/142). Out of curiosity, regarding the potential `efivars.fd` file, is there something that the provider does to process it? It's not a disk image, but since it contains values that may be useful for the built machine (keys typically for secure-boot images), this might be important to keep. EDIT: judging by the code, the post-processor only keeps the artifact's main disk, so even the `efivars.fd` won't be a problem in the current state, the post-processor will filter it out.

Provider doesn't currently do anything explicit, though the Vagrantfile packaged with boxes may reference the file to automatically add it to certain options. I'd have to work through an example to see if they could resolve paths sensibly (if not particularly easily) or if it would require explicit support in the provider.

> This being said, the PR is still valid and I'll give it a review right now, but it's not a pressing matter imo, unless you plan on removing the old format some time soon?

No plan on removing the old format anytime soon as that would break far too many boxes. Maybe in 3-4 years if 90+% have switched, but even then only if it is causing issues trying to retain the old format.


> Alternatively, rather than using `Files()` from the artifact returned by the builder, I would maybe suggest relying on `qemu_disk_paths` from the artifact's state? This way you would yield the disks' path, then we can use `qemu-img info --output json` (it should be available since we use it to create the images), as otherwise the only disk we know the size of will be the main one. I do wonder however, is the disk order important? Should we present the main disk first?

The order represented in the format will be the order the disks are attached to the domain as well. Whether that is important will depend to a degree on the OS and whether the device names are used anywhere, vs disk IDs. I'd certainly recommend trying to match the same order to avoid issues and checking that while `wwn` can be configured for additional devices added at runtime in vagrant-libvirt it's not current supported for the domain disks, so I'm not confident there is a disk id that can be relied on that comes from the disk image. I'd expect that for it to work it would also need to be added to the format as an additional attribute. Certainly something that should consider supporting, probably best to try and retain the order from the domain definition for now.
 
> I also wonder regarding the virtual_size of each disk, what would be the consequence of not including it in the specification?

For the new format, virtual disk size will be retrieved from the disk image directly https://github.com/vagrant-libvirt/vagrant-libvirt/blob/cf37fd44f640865973749d18750d8947449e72ff/lib/vagrant-libvirt/action/handle_box_image.rb#L176-L188, should be no need to add it to the format, sorry I should have come back and updated that.

**Comment by lbajolet-hashicorp** [comment]
Hi @electrofelix,

Thanks for the response, got it for the size, @LeConTesteur excluded it from their PR, and if it's not necessary to include this is fine as-is.
For the order that's as I feared, but at the same time there's not really a lot we can do from here, so I think the approach in the PR is sound.

I believe we'll get that support in the post-processor soon then :)
