### ISSUE TITLE
Packer build not deleting OS disks in Azure after completing the build.

### ISSUE THREAD

**Issue by mydearmuthu1978** [hashicorp/packer#10686]
I have packer 1.6.6 version installed. I have created pipeline in Azure to create image using packer build.
I have two issues.
1. Whenever the build completed successfully, the OS disks is not deleting in Azure.
2. when the build failed, none of the resources(Vm, disks, etc) are deleting in Azure.

Kindly help me to resolve these issues.
Thanks.

**Comment by nywilken** [comment]
Hi there @mydearmuthu1978 thanks for reaching out. The first issue is related to a regression that was introduced back in v1.6.2 - see https://github.com/hashicorp/packer/issues/10416. The fix is slated for the next release. 

As for issue number two can you please provide a sample configuration and the debug logs. I would like to see where in the deployment state the Azure build is failing so that I can try to help pin point why the delete step is not happening. Thanks!

**Comment by mydearmuthu1978** [comment]
The second issue happens in below scenario.
For some reasons, the build is failed or cancelled by the user. During that time, the resources are not deleted in Azure.
I have to manually delete those resources. Hope this clarifies.

**Comment by nywilken** [comment]
Hi :wave: there's an open PR #10713 with a potential fix for the first issue. Would you mind pulling down one of the test binaries and confirming that the patch fixes the reported issue?

The test binaries can be downloaded from https://app.circleci.com/pipelines/github/hashicorp/packer/9492/workflows/fb3a2460-88f5-4788-affb-089a5a3ddd87/jobs/113627/artifacts

Re: The second issue the deploy template step is responsible for cleaning up items it has created, excluding the bug in issue 1, so depending on where the build is cancelled there can be some left over resources if the cleanup step is interrupted or cancelled. 

Do you know which resource es stick around?
