### ISSUE TITLE
Add remove_cdrom to vmware-iso

### ISSUE THREAD

**Issue by jeremymcgee73** [hashicorp/packer#10704]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I would like to be able to use remove_cdrom with the vmware-iso provider. I am adding a disk using cd_files with vmware-iso, then I am use vmware-vmx to import the vmx, do some more config and convert to ova. However, the conversion fails because the temporary ISO no longer exists. I would like to cleanup the CD drive in the vmware-iso run. I may be able to fix this with ovftool_options, but have not gotten that to work yet.

#### Potential configuration

```
```

**Comment by jeremymcgee73** [comment]
The root of this, may actually be a bug with cd_files. I will look at this some more, and maybe open a bug issue. The drive does not get removed from the VMX like the floppy does.

**Comment by saleemrashid** [comment]
Annoyingly, if you try to export the `vmware-iso` to OVA, the temporarily ISO will be included in the OVA and you can't work around this with `vmx_post_data` because the handling of `cdrom_files` overrides it.

However, in your specific situation, you can probably work around it temporarily by adding something like `"ide1:0.present" = "FALSE"` to `vmx_data` in your `vmware-vmx` source (since the `vmware-vmx` source won't have `cdrom_files` set).

I haven't tested it, but the fix for this should be as simple as appending the device to the `"temporaryDevices"` state item. e.g., similarly to `append(tmpBuildDevices, "floppy0")`, you'd have `append(tmpBuildDevices, cdromPrefix)`.

https://github.com/hashicorp/packer/blob/4bbeec4733a51a0e90c4d42cc45782d4c72ce01b/builder/vmware/common/step_configure_vmx.go#L68-L97

**Comment by jeremymcgee73** [comment]
I think I tried that! For now I'm using grep to remove it. Grep can't overwrite a file, so i just write it to tmp.

```
 post-processor "shell-local" {
    environment_vars = ["VMXPATH=builds/base.vmx"]
    inline = [
      "grep -v '^ide1:0' $VMXPATH > /tmp/base.vmx",
      "mv /tmp/base.vmx ./builds/base.vmx"
    ]
  }
```
