### ISSUE TITLE
pause_after for provisioner/powershell 

### ISSUE THREAD

**Issue by urbinek** [hashicorp/packer#10887]
Due to lags on azure we want to shutdown VM manually and wait some time before packer can continue.
```Json
        {
            "type": "powershell",
            "inline": [ "shutdown /s /f /t 0 /c \"Shuting down VM before final packing\"" ],
            "pause_after": "120s"
        }
```

but packer validator returns:
```
1 error occurred:
	* unknown configuration key: '"pause_after"'
```

According to doc there is no pause_after https://www.packer.io/docs/provisioners/powershell#pause_after 

Whoever for shell it is https://www.packer.io/docs/provisioners/shell#pause_after

**Comment by SwampDragons** [comment]
Yep, that option is only available for the shell provisioner. This is not something the Packer team is likely to prioritize, because all provisioners already have a pause_before feature; just add that to your following provisioner. However, I'd accept a PR that adds it to the powershell provisioner as well, if someone from the community wants to do it.

**Comment by teddylear** [comment]
I can try to take a look into this if that's alright.

**Comment by teddylear** [comment]
@SwampDragons Created PR, please let me know if I should change anything.
