### ISSUE TITLE
The source block documentation doesn't explain what the two required labels mean

### ISSUE THREAD

**Issue by jihu** [hashicorp/packer#10971]
In the main "HCL Configuration Syntax" document, it says that the source block requires two labels. The example they give looks like this:

```
source "amazon-ebs" "example" {
  ami_name = "abc123"

  tags = {
    # ...
  }
}
```

However, these two labels ("amazon-ebs" and "example" in this case) are never explained, not in the main document, and not in the document describing the source block. Also, that last document doesn't even say that the last label is required, and all examples inside the build block on that page only uses one label, not two.

I really think that the documentation should make these things clear:

1. Do these two labels have any official names? 
2. How are they used? Are both just for presentation purposes, or are they used as technical IDs somehow?
3. When is the second label required?
4. If the second label is optional, what happens when you leave it out? Is there a default value?

https://www.packer.io/docs/templates/hcl_templates/syntax
https://www.packer.io/docs/templates/hcl_templates/blocks/source

**Comment by SwampDragons** [comment]
Thanks for reaching out!  These are great points. I'll update the docs, but here are your answers:

1) label 1 is "type" and label 2 is "name"

2) label 1 is the builder type. It tells the "source" block what plugin to load. So valid values are anything documented in the builder sidbear navigation here: https://www.packer.io/docs/builders

label 2 is the name of the source block, and needs to be a unique identifier. So you may have two sources that both are of "amazon-ebs" type, but their names must be different so that the build configuration knows which one to choose for a given build. 

They're used together when defining builds that use the sources. For example: 

```
# null.pkr.hcl

source "null" "foo" {
  communicator = "none"
}

build {
  sources = ["source.null.foo"]
  provisioner "shell-local" {
    inline = ["echo hi"]
  }
}
```

I use the name "source.null.foo" to tell the build what source this build should use. This is helpful when you have a file that defines many different sources. A build takes a list of sources to run, but you may have multiple builds, some which take one source and some which take another. 

3) both are required always. 

4) if you leave the second label out, when you call "packer build" you will get this error: 

```
All source blocks must have 2 labels (type, name).

Error: Missing name for source

  on null.pkr.hcl line 1, in source "null":
   1: source "null" {
...
```

**Comment by jihu** [comment]
Thanks Megan! That was a very clear, detailed and informative response. :)

**Comment by jihu** [comment]
@SwampDragons just one thing... in "source.null.foo", is that a concatenation with the **name** appended at the end, and a "." (dot) preceding it? Meaning that packer analyzes this string, and breaks it up into the type ("null") and name ("foo") before it can use it?

So if you change "foo" to "bar" in the source definition, then you must change "source.null.foo" to "source.null.bar" for it still to work?

**Comment by SwampDragons** [comment]
Correct! This allows me to declare two different sources, foo and bar, of the same "null" type, and I can distinguish between them in different builds, so I can mix and match sources and builds.
