### ISSUE TITLE
Add option to not align assignments in "packer fmt"

### ISSUE THREAD

**Issue by damienrg** [hashicorp/packer#10984]
The fact that `packer fmt` aligns assignments makes it less usable as automatic formatter because it makes review of PR/MR harder since all lines could change:

```hcl
locals {
  foo       = "test"
  whathever = "spot_me"
  bar       = "why_not"
}
```
And the diff associated:

```diff
 locals {
-  foo       = "Hey"
-  whathever = "spot_me"
-  bar       = "or_not"
+  foo      = "Hey"
+  whatever = "spot_me"
+  bar      = "or_not"
 }
```

**Comment by azr** [comment]
Hey @damienrg, thanks for opening, `packer fmt` is using the same `hcl` lib that is shared by other Hashicorp products like Terraform, Nomad, Consul, etc. The fmt command is defined here: https://pkg.go.dev/github.com/hashicorp/hcl/v2/hclwrite#Format, so I'd recommend to maybe [open a issue on that repo](https://github.com/hashicorp/hcl/issues/new/choose).

I think it's being opinionated on purpose so that all `fmt` have the same output. If you format all your `hcl` before opening a new PR, you will have this issue less. Also, GitHub has a nice "Hide whitespace changes":

![Screenshot 2021-05-03 at 10 27 36](https://user-images.githubusercontent.com/1024852/116855765-3ab44b00-abfa-11eb-9e2f-55745b7148b6.png)

Which will make the diff easier to read. For all these reasons/solution, I think we won't address your request explicitly. You could try opening a new Issue/PR on the hcl repo though ! 🙂 

I think the "hide whitespace changes" option will suffice, so I'm closing this issue for now, don't hesitate commenting here if you think otherwise !
