### ISSUE TITLE
Using dollar signs "$" in passwords are not properly interpreted in the Linux version of Packer

### ISSUE THREAD

**Issue by kgbillk** [hashicorp/packer#11029]
We were unable to get WinRM to properly authenticate if a user's password contained the dollar sign in it.  We kept getting the 401 error code using Windows 2016 or 2019.  We see the same issue using ssh on CentOS 7 as well.  Error message appears as follows:

```
==> vmware-vmx.centos7: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

Our packer script has a vmware-vmx source and target using VMare ESXi version 6.7 to perform the VM operations.

After switching the password to not have a dollar sign in it, the same scripts work fine.

This is happening on Packer version 1.7.2 running on Windows 10 20H2 and WSL2 (using Ubuntu 20.04)

So, is there a way to escape the character if found or is this a bug?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! 

I'm able to build using WinRM on my OSX machine when a password has a dollar sign without any special escaping: `"winrm_password": "Super$3cr3t!"`.  How are you creating the password? In the windows userdata script I used for repro I did use a backtick escape for the password when creating it, since dollar signs are a special character: ``net user Administrator Super`$3cr3t!``

I think since unattend files are XML, if you're setting the password in one of those you'll need to encode it using the numeric character reference: https://www.dvteclipse.com/documentation/svlinter/How_to_use_special_characters_in_XML.3F.html

I'm pretty sure this is an escaping issue in password creation rather than a bug, so I'm going to close this issue. But if neither of the above workarounds solve the issue we can reopen.

Thanks!

**Comment by kgbillk** [comment]
Sorry, left out a detail.  We are using variables for the password, like so:

```
variable "vm_password" {
  sensitive = true
}

variable "esx_password" {
  sensitive = true
}
```

and passing them on the command line as:
```
packer build -force -var "vm_password=Dollar$test" -var "esx_password=Dollar$test" ....
```

**Comment by nywilken** [comment]
Hello again if you're passing it from the command line it's possible that your shell is trying to expand anything that follows the `$`. Have you tried wrapping the escaping the `$` on the cli ?

```
packer build -force -var "vm_password=Dollar'\$'test" -var "esx_password=Dollar'\$'test" ....
```

**Comment by kgbillk** [comment]
I have tried a lot of different combinations and have been unsuccessful running from WSL2 Ubuntu 20.04.

The following all do not work:

- "vm_password=Dollar'\$'test"
- vm_password='Dollar$test'
- vm_password='Dollar\$test'
- vm_password=Dollar\$test

So, feels like something getting messed up between the bash shell and packer handling the data from my testing.
