### ISSUE TITLE
Working JSON breaks HCL2 upgrade - unknown builder type & builder missing ‘type’

### ISSUE THREAD

**Issue by bbros-dev** [hashicorp/packer#11028]
#### Overview of the Issue

Originally described in the community forum post [Working JSON breaks HCL2 upgrade - unknown builder type & builder missing ‘type’](https://discuss.hashicorp.com/t/working-json-breaks-hcl2-upgrade-unknown-builder-type-builder-missing-type/24398):

With the release of 1.7.0 we took took a first run at converting our JSON definitions, unfortunately we made no progress and reported our problem in [Working JSON breaks after HCL2 upgrade - Error: Variables not allowed](https://discuss.hashicorp.com/t/working-json-breaks-after-hcl2-upgrade-error-variables-not-allowed/21220).

It looked like the issue was fixed in 1.7.1 and now that 1.7.2 is out we’ve tried taking another run. This time it seems we’ve hit an issue of trying to migrate JSON to HCL2 and move from Packer version < 1.7.0 to Packer 1.7.2

#### Reproduction Steps

Steps to reproduce this issue

Download gist [packer-issue-11028.pkr.json](https://gist.github.com/bbros-dev/bef4b61ffe0861c01915fb05e1c431a3#file-packer-issue-11028-pkr-json)
```
$ packer hcl2_upgrade packer-issue-11028.json 
unknown builder type: "upcloud"
```

### Packer version

From `packer version`

### Simplified Packer Buildfile

Gist:

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

```
$ uname -a
Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
### Log Fragments and crash.log files

```
$ packer hcl2_upgrade packer-issue-11028.json 
unknown builder type: "upcloud"
```

**Comment by SwampDragons** [comment]
Hi! I just investigated this and I was able to reproduce. The upcloud plugin is a community plugin and it isn't bundled with the main Packer binary. I believe the issue is that you don't have the upcloud plugin installed in any of the valid Packer plugin paths where you're trying to upgrade this template. Packer needs to be able to load the plugin to transpose the config for you, so it must be installed. 

Installation instructions are [here](https://www.packer.io/docs/plugins#installing-plugins); click on the "manually (multi-component plugins)" tab in those instructions. 

Same goes for the vultr plugin, which is also referenced in this template. 

Here are the commands I ran to get this working on my OSX box (the URLs you need to curl will be different if you are on a different arch). If you are on OSX, you need to use curl or wget to pull the plugin instead of downloading through your browser or Apple will get mad at you because the binaries aren't signed.

```shell-session
curl -L -o packer-plugin-upcloud.zip https://github.com/UpCloudLtd/packer-plugin-upcloud/releases/download/v1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_darwin_amd64.zip
unzip packer-plugin-upcloud.zip
mv packer-plugin-upcloud_v1.0.0_x5.0_darwin_amd64 packer-plugin-upcloud
rm packer-plugin-upcloud.zip
curl -L -o packer-plugin-vultr.zip https://github.com/vultr/packer-plugin-vultr/releases/download/v2.3.1/packer-plugin-vultr_v2.3.1_x5.0_darwin_amd64.zip
unzip packer-plugin-vultr.zip
mv packer-plugin-vultr_v2.3.1_x5.0_darwin_amd64 packer-plugin-vultr
rm packer-plugin-vultr.zip
packer hcl2_upgrade repro_11028.json
```

note that I just left the plugins in my current working directory; Packer looks there first for plugins. 

Hope this helps! I'll leave this open for now because I think we should document this gotcha.

**Comment by bbros-dev** [comment]
Thanks for taking the time to look into this.  Good to know you could reproduce this.

>  I believe the issue is that you don't have the upcloud plugin installed in any of the valid Packer plugin paths where you're trying to upgrade this template.

We were puzzled by that, because `packer init ....` was done **before** the upgrade was attempted, and Packer had installed the plugins without complaint as follows:

```
~/.packer.d$ tree
.
|-- checkpoint_cache
|-- checkpoint_signature
`-- plugins
    `-- github.com
        |-- upcloudltd
        |   `-- upcloud
        |       |-- packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
        |       `-- packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64_SHA256SUM
        `-- vultr
            `-- vultr
                |-- packer-plugin-vultr_v2.3.1_x5.0_linux_amd64
                `-- packer-plugin-vultr_v2.3.1_x5.0_linux_amd64_SHA256SUM
```


In fact if we move the files from where `packer init ...` placed them to under `~/.packer.d/plugins` we then get this error:

```
$ packer hcl2_upgrade repro_11082.pkr.json 
 Error loading configuration: 

fork/exec /home/user/.packer.d/plugins/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64_SHA256SUM: exec format error
```

So removing the SHA256 file `packer init ...` extracted and renaming as you suggest we are able to run.

So if we read the instructions correctly, Packer should have created this when `packer init ...`:

```
~/.packer.d$ tree
.
|-- checkpoint_cache
|-- checkpoint_signature
`-- plugins
   |-- packer-plugin-upcloud
   |-- packer-plugin-vultr
    `-- github.com
        |-- upcloudltd
        |   `-- upcloud
        |      |
        |       `-- packer-plugin-upcloud_SHA256SUM
        `-- vultr
            `-- vultr
                |
                `-- packer-plugin-vultr_SHA256SUM

```

**Comment by SwampDragons** [comment]
Thanks for the quick response here. 

`packer init` was [only implemented for HCL templates](https://www.packer.io/docs/commands/init). The JSON and HCL code paths are almost entirely separate, and even things you might expect to be generalizable, like plugin loading, aren't -- in part because init requires a change to the plugin path name and we didn't want to break backwards compatability. 

I don't think it ever occurred to the team that someone would try "init" before upgrading their templates, so the upgrade command assumes the older-style manual installation paths rather than the new ones that include version, OS arch, etc. 

This was clearly a bad assumption on our parts 😅 

While we're not going to change the `init` command or the `init` install location, I can look into whether it's possible to have the `hcl2_upgrade` command try the HCL-template plugin search tree as well.

**Comment by bbros-dev** [comment]
> I don't think it ever occurred to the team that someone would try "init" before upgrading their templates

Further confirmation Murphy's Law doesn't just apply to cockpit design ;)

We were following [these UpCloud instructions](https://github.com/UpCloudLtd/packer-plugin-upcloud).

Maybe also provide a note/warning in the relevant section of the plugin developer documentation?
