### ISSUE TITLE
packer_version not available

### ISSUE THREAD

**Issue by hegyre** [hashicorp/packer#11052]
#### Overview of the Issue

The code below was working just fine with Packer 1.5.6

I know that JSON is depreciated in favor to HCL, but the issue is also with HCL...

However it seems to work if I remove that variable and interpolate directly in the "tags" for an aws builder.

#### Reproduction Steps

Trying to interpolate packer_version as a variable.

### Packer version

1.6.6, 1.7.2, 1.7.3

### Simplified Packer Buildfile (JSON)

```
{
  "variables": {
    "CreatedWith"     : "Packer {{packer_version}}"
  },
...
}
```

### Simplified Packer Buildfile (HCL)

```
variable "CreatedWith" {
  type    = string
  default = "Packer ${packer_version()}"
}
```

### Operating system and Environment details

Windows 10.0.19041 64 bit Enterprise

### Log Fragments and crash.log files

For JSON:
```
packer validate ami.json
Error:

template: root:1:9: executing "root" at <packer_version>: error calling
packer_version: packer_version not available
```

For HCL:
```
Error: Call to unknown function

  on ami.pkr.hcl line 20, in variable "CreatedWith":
  20:   default = "Packer ${packer_version()}"

There is no function named "packer_version".
```

**Comment by azr** [comment]
Hello there, 

In JSON this should work. Thanks for reporting.

In HCL, this one comes with the `packer.version` var.

```shellsession
$ echo "packer.version" | packer console yadi.yada.pkr.hcl
1.7.2
```

**Comment by nywilken** [comment]
Hi @hegyre thanks for reaching out. I took a deeper look into this issue and found that there is indeed a regression in the 1.6.6 release where the interpolation of `{{packer_version}}` fails. I've included the failing templates below. 

Regression aside you have another issue in your example template. In HCL the results of a function can not be assigned within a variable block. In order to use expressions as the value of a variable in HCL you must use either the `local` or `locals` block. I've provided an example below that should help you here. 

Please let me know if you have any questions about the provided path forward. 

### Working HCL2 only template
<details>
<summary>source.pkr.hcl</summary>

```hcl
source "null" "example" {
  communicator = "none"
}

local "CreatedWith" {
  expression = "Packer ${packer.version}"
}

locals {
  OtherVersionOption = "Packer ${packer.version}"
}

build {
  sources = ["source.null.example"]

  provisioner "shell-local" {
    inline = ["echo Packer version function using local expression ${local.CreatedWith}"]
  }

  provisioner "shell-local" {
    inline = ["echo Packer version function using locals block ${local.OtherVersionOption}"]
  }
}

```
</details>


### Failing Test Cases that worked with Packer 1.5.6

<details>
<summary>Failing JSON</summary>

```JSON
{
  "variables": {
   "sensitive": "I am soooo sensitive",
   "CreatedWith": "{{packer_version}}"
  },
  "sensitive-variables": ["sensitive"],

        "builders": [
                {
                        "type": "null",
                        "name": "consul",
                        "communicator": "none"
    }
        ],
  "provisioners": [
                {
                        "type": "shell-local",
                        "inline": ["echo the {{build_name}} and {{build_type}} with {{user `CreatedWith`}}, sensitive var: {{user `sensitive`}}"]
                }
        ]
}
````
</details>

<details>
<summary> Failing HCL</summary>

```hcl
source "null" "example" {
  communicator = "none"
}


build {
  sources = ["source.null.example"]


  provisioner "shell-local" {
    inline = ["echo Packer version function using {{packer_version}}"]
  }

}
```
</details>

**Comment by nywilken** [comment]
For maintainer tracking purposes I was able to isolate the change back to this PR https://github.com/hashicorp/packer/pull/10235
