### ISSUE TITLE
New provisioner - keyboard command via vnc

### ISSUE THREAD

**Issue by trodemaster** [hashicorp/packer#11062]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
I have run into an increasing number of situations that the existing provisions like shell fall to address. What I propose is a new provisioner that re-uses the same functionality as the boot command in the various builders. This "keyboard command" provisioner would send keyboard commands to the guest when called. 

The vmware and qemu builders are the ones I'm most focused on having this feature. I'm sure that the vsphere and other desktop hypervisors would also benefit from this builder. 

#### Use Case(s)
OS configuration that requires keyboard input. With Linux on arm systems having the ability to change bios/uefi settings after configuring part of the install. The main use case however is with macOS machine images a number of security settings are not able to be changed via scripting in macOS 11 or later. Being able to call a provisioner to send a sequence of keys at the correct time during a build will provide a really flexible tool to make any of these kinds of changes. 

#### Potential configuration

```
  provisioner "keyboard_command" {
  key_interval      = "15ms"
  keygroup_interval = "120ms"
    commands = [
    "<leftSuperon><f5><leftSuperoff>",
    "<leftCtrlon><f2><leftCtrloff>",
    "u<down><down><down>",
    "<enter>",
    "<leftSuperon><f5><leftSuperoff><wait10>",
    "<leftCtrlon><f2><leftCtrloff>",
    "w<down><down>",
    "<enter>"
    ]
  }

```

#### Potential References

https://github.com/hashicorp/packer-plugin-vmware/blob/main/builder/vmware/common/step_vnc_boot_command.go

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! It's an interesting idea.

There are a couple of challenges with implementing this, the main one of which is that which driver to use for sending the boot command is builder-specific, and that information isn't currently passed to the provisioners. That's probably not a deal-breaker, but would require some investigation. The bigger issue I see is that long boot commands can also be flaky depending on your network and system load, so we historically have recommend people use it as little as possible. 

Because of this, we probably won't get to creating this in-house any time soon. That said, if you're interested in creating it, the docs for creating new plugins can be found here: https://www.packer.io/docs/plugins/creation and information for specifically creating provisioners can be found here: https://www.packer.io/docs/plugins/creation/custom-provisioners, and the boot-command tooling can be found here: https://github.com/hashicorp/packer-plugin-sdk/tree/main/bootcommand. 

Thanks!
