### ISSUE TITLE
Provide a way to print `packer fmt` output to stdout.

### ISSUE THREAD

**Issue by Fuco1** [hashicorp/packer#11080]
#### Description

Provide a way to print the result of the formatting to stdout.  `-write=false` seems to have no effect (actually no effect overall, I don't understand what it does).

#### Use Case(s)

Many plugins for various editors/IDEs such as [Emacs](https://github.com/lassik/emacs-format-all-the-code) or Vim support autoformatting, where the buffer is passed via stdin to a process and the stdout is then replaced into the buffer.  Streams are the default interface and we should always strive to support them.

If this is already possible, it would be good to document it better in the `packer fmt` output.

**Comment by nywilken** [comment]
Thanks for reaching out. I'm going to label this as a docs bug as the feature you are suggesting already exists, but missing from the docs. The `packer fmt` command supports reading from stdin which will write the formatted output to stdout. 

You can achieve the expected behavior by running something like `cat template.pkr.hcl | packer fmt -`. 

As for the `-write` flag when it is set to `-write=false` the Packer format command essentially behaves like `packer fmt -check`. Where it checks if template file(s) need formatting, displays the name of any file(s) that are not correctly formatted, and exits. By default the `packer fmt` command would overrwrite the source files. 

Does this help answer your question?

**Comment by Fuco1** [comment]
Thanks @nywilken, your suggestion works fine!  Thanks also for explaining the write flag.

Simpler one-liner without the `cat` is `packer fmt - < image.pkr.hcl` (my linter flags it as "useless use of cat" :man_facepalming:)
