### ISSUE TITLE
[HCL2] hcl2_upgrade command should create template without json in name 

### ISSUE THREAD

**Issue by minhluantran017** [hashicorp/packer#11105]
### Summary:
When using `packer hcl2_upgrade` command against a JSON template, Packer should not create template with remained `.json` in file name but find for the `.json` and replace with `.pkr.hcl`.

### Command:
```
packer hcl2_upgrade ubuntu1404.json
```
### Expected ouput:
```
Successfully created ubuntu1404.pkr.hcl. Exit 0
```
### Actual output:
```
Successfully created ubuntu1404.json.pkr.hcl. Exit 0
```
### Version:
```
> packer version
Packer v1.7.3
```
### Impact:
No impact. Nice-to-have enhancement.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. You can change the output path of your hcl template using the -output-file option.
 
for example:
`packer hcl2_upgrade template.json -output-file=template.pkr.hcl`

I know the .json is a little weird, but we decided to leave it in because we wanted it to be clear what hcl templates had been autogenerated from a json template.

I don't think we're going to change the established behavior for now, but we'll reconsider if the community generally agrees that this would be a better experience.
