### ISSUE TITLE
[docs] show possible builder versions

### ISSUE THREAD

**Issue by bluebrown** [hashicorp/packer#11133]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Include available version number and change log of builder in documentation. For example, what's the latest version of this builder? https://www.packer.io/docs/builders/docker#docker-builder

#### Use Case(s)

I am want to use one of the latest builders, but I don't know what version is available. So I could look it up.

**Comment by nywilken** [comment]
Hi @bluebrown this is a good idea. Let me see if and how we could achieve this in a programatic way since plugin docs are now remote. With that said the latest changelog for each of the plugins can be found in  their respective repos. Sorry, I don't have a better answer for you at this moment. 

Depending on what your required_plugins block configuration is you can use the `packer init -upgrade template.pkr.hcl` command to download the latest available version of a plugin.  The command will download the latest version but will not update your local template. 

For example I was running version v0.0.7 of docker with the following template
<details>
<summary> Template File</summary>

```
// Template used for testing issue packer-plugin-docker#22
// before running create an file to copy
packer {
  required_plugins {
    docker = {
      source = "github.com/hashicorp/docker"
      version = ">=0.0.7"
    }
  }
}
variables {
    source_image= "centos:7.3.1611"
    username= "blahblahuser"
}

source "docker" "base_setup"{
    image = var.source_image
    discard = true
}

build {
    sources = ["docker.base_setup"]

    provisioner "file" {
      source = "docker_centos_packer_init_shell.pkr.hcl"
      destination = "/tmp/"
    }
    provisioner "shell" {
      inline = ["uptime"]
    }

}
```
</details>

Running the upgrade command found that a new version of the plugin was available and downloaded it for me. The upgrade command honors the version constraint. Since I have `">=0.0.7" it will try to find any version greater than v0.0.7 and install if it is not already installed locally the new version will get downloaded and installed. 

```bash
~>  packer init -upgrade docker_centos_packer_init_shell.pkr.hcl
Installed plugin github.com/hashicorp/docker v1.0.1 in "/Users/wilken/.packer.d/plugins/github.com/hashicorp/docker/packer-plugin-docker_v1.0.1_x5.0_darwin_amd64"
```

**Comment by nywilken** [comment]
Hi @bluebrown we went ahead and implemented this request. It is now live on the packer.io site. We have [versioned docs](https://www.packer.io/docs) for core Packer plugins  (those bundled into Packer). For [External Plugins](https://www.packer.io/plugins) such as the [Azure Builder](https://www.packer.io/plugins/builders/azure) for example a new version badge is displayed at the top of the docs header to indicate latest version of the plugin that was available at the time of the last Packer.io site deployment. It is possible that the version shown in the docs is the version shipping with Packer, but since plugins have their own release cadence we recommend using `packer init` for ensuring that Packer is using the latest available version of a plugin. 

Thanks again for this request. If you have any suggestions or thoughts about the new version information please feel free to open a new issue. Cheers!
