### ISSUE TITLE
Packer init cannot download plugins behind VPN

### ISSUE THREAD

**Issue by JKalliomaki** [hashicorp/packer#11223]
#### Overview of the Issue

Using `packer init .` when using VPN results in not finding release version.

#### Reproduction Steps

1. Have a VPN connection
2. Have the attached snippet in buildfile
3. run `packer init .`
4. result:
![image](https://user-images.githubusercontent.com/59554739/130739822-3af26dbc-ae1d-49e0-b72b-a9f4e24705c6.png)

### Packer version

Packer v1.7.4

### Simplified Packer Buildfile
```
packer {
    required_plugins {
        virtualbox = {
            version = ">= 1.0.0"
            source = "github.com/hashicorp/virtualbox"
            }
        }
    }
```

### Operating system and Environment details

Windows 10
Cisco AnyConnect as VPN
I think other details doesn't matter here

### Other details

With VPN disabled there are no issues.
Cloning from Github is working fine with VPN enabled

**Comment by dbond007** [comment]
I think you need to talk to you network admin / vpn admin. It will likely be related to one of the policies for the vpn. Like any application, packer will not know or care about a VPN. You have routes setup on a virtual adapter to forward the requested traffic over the Vpn, then they can be restricted by the VPN policies, requiring proxy settings etc. So the VPN policy or that network firewall rules / proxy requirements will be the likely problem.

**Comment by JKalliomaki** [comment]
Thank you @dbond007. I guess that proxy settings are the problem here. I think it would be good to get possibility to add proxy setting to the `packer init` command or in the hcl-file on the part which defines the downloads.

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. As @dbond007 suggested  I would check to see what the VPN settings are to ensure proper communication. Packer should support the standard HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables if set. 

Have you tried setting those environment variables to point to your proxy? 

That aside we are interested in seeing the debug logs for this issue as it could help us better communicate the error caused by and Proxy settings. Can you provide a redacted version of the logs by running `PACKER_LOG=1 packer build source.pkr.hcl` . 

I see you are on Windows so you may need to set the environment variable for PACKER_LOG differently.

**Comment by JKalliomaki** [comment]
Hello! I don't know if there have been some changes on the company VPN or what, but the problem is gone now. I'm sure I haven't changed my local settings on proxies etc so that is not the reason this is working now. Little mysterious if you ask me, but now I atleast cannot get logs etc for you. 
And if I remember correctly, before filing this issue I tried with proxy-environment variables, but I'd remember they were "http_proxy", "https_proxy", "no_proxy" and "NO_PROXY" so in case packer expects upper-case for those env-vars that could have been a problem I think.
