### ISSUE TITLE
issue with packer fix command and packer version

### ISSUE THREAD

**Issue by theking750156** [hashicorp/packer#11281]
hello, 

i'm beginner in devops and i have to create os images with packer and azure devops pipeline, so i got some difficulties building Json et Yaml files because i'm not enough good in scrpting and even with it i have my script who have a behavior thant i cannot found the solution on the internet so please if you can help me i'll be grateful

actuallu i have a problem at the packer build steps, packer run a fix command and exit with an error :
##[error]Packer fix command failed with error : ''. This could happen if task does not support packer version
![image](https://user-images.githubusercontent.com/48678916/134479374-86ab1897-1ad3-45be-977a-87b7de7bdd7b.png)

i'll joint my 2 scripts here and thank you very much for your he
[buildvm(json).txt](https://github.com/hashicorp/packer/files/7216147/buildvm.json.txt)
[VM2019(yml).txt](https://github.com/hashicorp/packer/files/7216148/VM2019.yml.txt)
lp

**Comment by nywilken** [comment]
Hi @theking750156  thanks for reaching out. Welcome to the Packer community. Quickly looking at the provided error it would appear that you have an error in the json build file.

Have you tried validating your JSON file against a JSON linter (https://jsonlint.com/)? 

Packer validate will error if the input file is invalid, which is the error you are seeing here. I suggest using the online linter to identify any issues in the JSON and then trying again.  

I'm going to mark this issue as resolved, but if you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer/23) for help. There are more eyes on the forums which will help in troubleshooting such issues. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. Cheers!

**Comment by theking750156** [comment]
thank you for your answer i really appreciate it
