### ISSUE TITLE
Provide a method to run a script on Azure VM before the initial connection for the azure-arm builder

### ISSUE THREAD

**Issue by bender-the-greatest** [hashicorp/packer#11345]
#### Description

This is in frustrating response to trying to workaround the [WinRM timeout issues](https://github.com/hashicorp/packer/issues/8658) plaguing the `azure-arm` builder and Windows VM templates (this is only one example but there are multiple cases of this I've found between this project and the MicrosoftDocs/azure-docs project). I do not want the focus of this request to be on how to troubleshoot this problem however; I've tried all the suggestions and it's clear this issue still haunts several. I am providing this information for context around this feature request.

I am requesting a new feature to the `azure-arm` builder which allows a script to be run via Azure's `run-command` API with the intent of performing a pre-connection bootstrap before the builder verifies the connector configuration is working.

[This comment on a closed issue](https://github.com/hashicorp/packer/issues/6548#issuecomment-646218492) (related reasoning behind the feature but overall asking for a different feature) seems to imply that this is not something Packer can do from the builder. However, [that is not a true statement](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command). I am in fact able to work around the timeout problem by using `Invoke-AzVMRunCommand` to run my own script which configures WinRM and the firewall, but currently there is no such mechanism to have this run _during_ the Packer build itself.

Since the intent here is to allow the image maintainer to setup winrm, ssh, or potentially another communication service prior to connecting I suggest naming the builder attribute to the tune of this intent (e.g. `communicator_setup_script`). In addition to  this, perhaps a timeout attribute would also be useful. However, I don't believe this should be limited to winrm only, as other setup might be required for SSH or other possible communicators.

#### Use Case(s)

Run a script required before connecting with the communicator. This would allow the image maintainer to setup the communicator service according to their needs before connecting. This may also be able to execute what is provided as `custom-data`.

As this isn't intended to replace proper provisioners any timeouts might be desired to be capped, and should be named for the intent of communicator setup. I don't expect configuration of a communication protocol to take long, generally only a few minutes maximum should be needed.

#### Potential configuration

```
source "azure-arm" {
  communicator_setup_script  = "./packer-scripts/Setup-WinRM.ps1"
  communicator_setup_timeout = "5m"
}
```

**Comment by nywilken** [comment]
Hi @bender-the-greatest sorry to hear about the frustration. I definitely understand your pain points around the WinRm communicator. I agree the setup needs more attention. 

Nonetheless, this sounds like a nice feature to offer as an alternative bootstrap setup for the the Azure builder. But instead of calling it communicator_setup_script. Maybe something like `run_command` that users could leverage for running a single command or script during the instance bootstrap. 

As for the timeout we have a communicator timeout that should handle this case already, but if you are thinking of using a timeout differently we would be happy to see what it can bring to the table. 

We will most likely focus more on WinRM and SSH communicators as a whole and not this specific request.  But If you are interested in working on this feature please feel free to open a PR on the [packer-plugin-azure](https://github.com/hashicorp/packer-plugin-azure) repository.
