### ISSUE TITLE
vagrant post processor metadata

### ISSUE THREAD

**Issue by luxifer** [hashicorp/packer#1143]
Curently, it's possible to provide a template for the `Vagrantfile` embedded in the box. Is it possible to have the same feature, but for the `metadata.json`?
My point is, I want to add versioning to the boxes I build and I don't want to have to extract the box, change the metadata and then recompress it.

**Comment by gpakosz** [comment]
@luxifer out of curiosity, how does that help with versioning?

The Vagrant manual states

> Within the archive, Vagrant does expect a single file: `metadata.json`. This is a JSON file that is completely unrelated to the above box catalog metadata component;

> If there is no `metadata.json` file or the file does not contain valid JSON with at least a "provider" key, then Vagrant will error when adding the box, because it can't verify the provider.

> Other keys/values may be added to the metadata without issue. The value of the metadata file is passed opaquely into Vagrant and plugins can make use of it. At this point, Vagrant core does not use any other keys in this file.

To my understanding, versioning is achieved by yet another JSON document that sits beside box files

**Comment by luxifer** [comment]
Yes, I made some tests and in the result, the JSON file which handles box
versioming sits outside of the box, I'm now trying to build a small tool to
help manging and pusblishing box version sithout using vagrant cloud

Florent Viel
*Lead Developer Symfony 2*

*@florent_viel*blog.luxifer.fr

2015-02-05 11:06 GMT+00:00 Gregory Pakosz <notifications@github.com>:

**Comment by yves-vogl** [comment]
@luxifer @gpakosz I already built such a tool (based on Ruby on Rails) (http://boxes.dock42.com) - at the moment it's for private use but maybe I find the time to make it OSS.

The design of placing a versioning file outside instead of using the already included metadata.json is not what I'd choose at first glance. 
Encapsulating versioning information into the box itself would be a better approach. 
A webapp for distributing  those boxes needs to inspect those versioning information and build an index upon it.
