### ISSUE TITLE
Does packer support the azure windows vm that communicate with ssh

### ISSUE THREAD

**Issue by elvis-sun** [hashicorp/packer#11514]

**Comment by elvis-sun** [comment]
the detail is below:
https://github.com/hashicorp/packer-plugin-azure/issues/178

**Comment by nywilken** [comment]
I commented on the issue. The azure builder does not currently support SSH for Windows as it does try to configure WinRM even if the ssh communicator type is selected.  This is a bug for sure. Closing here so we can track on the Azure repo.

**Comment by elvis-sun** [comment]
> I commented on the issue. The azure builder does not currently support SSH for Windows as it does try to configure WinRM even if the ssh communicator type is selected. This is a bug for sure. Closing here so we can track on the Azure repo.

Appreciate for your reply

**Comment by elvis-sun** [comment]
> I commented on the issue. The azure builder does not currently support SSH for Windows as it does try to configure WinRM even if the ssh communicator type is selected. This is a bug for sure. Closing here so we can track on the Azure repo.

@nywilken I modify the source code on my local compute and rebuild, now it can work with SSH. Waiting for your fixing.

**Comment by nywilken** [comment]
Hi @elvis-sun since you modified the code locally to get things working would you be open to submitting a PR with your changes? We would be happy to review and help push the changes through. Let us know .

For reference here is our [contributing guide](https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md#opening-a-pull-request)
