### ISSUE TITLE
Inherit GITHUB_TOKEN in `packer init`

### ISSUE THREAD

**Issue by pwillis-els** [hashicorp/packer#11542]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.

#### Description

The `packer init` command will use the environment variable `PACKER_GITHUB_API_TOKEN` to pull from GitHub to prevent hitting anonymous API limits. However, this variable is only used by Packer, meaning all workflows that call Packer must now set this variable explicitly, rather than inherit a pre-existing environment variable.

The [GitHub CLI](https://cli.github.com/manual/gh_help_environment) uses environment variables `GH_TOKEN` and `GITHUB_TOKEN`. [GitHub Actions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) uses the same name.

My suggestion is to look first for your current `PACKER_GITHUB_API_TOKEN` environment variable, and if it does not exist, look for a `GITHUB_TOKEN` or `GH_TOKEN` environment variable.

#### Use Case(s)

Using Packer from GitHub Actions, or anywhere GitHub CLI is used, without needing to explicitly set `PACKER_GITHUB_API_TOKEN`.

#### Potential configuration

```
```

**Comment by nywilken** [comment]
Hi @pwillis-els, thanks for opening up this issue. We spoke about this request internally and decided to mark this as a wontfix and close. By default Packer does not require a token to communicate with GitHub, which is why `PACKER_GITHUB_API_TOKEN` is not required. The ability to use the token follows an explicit opt-in approach for bypassing GitHub rate limiting on unauthenticated requests. 

Having Packer automatically fallback to `GITHUB_TOKEN`, when `PACKER_GITHUB_API_TOKEN` is not available, would grant Packer access an environment variable that the operator may have not intended to be used. So we see this fallback as a potential security risk.

Internally for other HashiCorp tools we follow the same approach using `BINARYNAME_GITHUB_TOKEN`.  I do want to call out that the Terrform GitHub provider uses the `GITHUB_TOKEN` by default but that integration is owned by GitHub and the token is required by the provider if no token is specified in the HCL. 

I'm going to close this issue as we will not be taking any further actions on it. But if you wish to follow up on the thread please drop us a comment. Cheers!
