### ISSUE TITLE
tail a file while waiting for SSH to be available

### ISSUE THREAD

**Issue by brianjmurrell** [hashicorp/packer#11718]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Description

While _Waiting for SSH to become available_, optionally `tail -f` a file until ssh does become available.  In my configuration I have the VM's serial console configured to log to a file so that all console output is logged there.  It would be nice to be able to watch the progress of that while waiting.

**Comment by nywilken** [comment]
Hi @brianjmurrell thanks for reaching out. I can see the interest in wanting to tail the serial console log while waiting for the SSH connection to happen but this is out of scope for Packer, as the SSH experience does vary per builder. The recommended approach in this case would be to use multiple terminal sessions. 

I'm going to close this issue and mark it as wontfix. But if I've misunderstood the request please feel free to leave a clarifying comment on the issue.

**Comment by brianjmurrell** [comment]
@nywilken Thanks for responding.  Maybe I have tunnel-vision on this, but what do you mean by _the SSH experience does vary per builder_ exactly and how does that impact the usefuless of this concept -- particularly if it's optional and only happens if defined to happen?

**Comment by nywilken** [comment]
Hi @brianjmurrell thanks for the additional clarity and apologies for not providing enough context in my response.

Allow me to answer your questions inline.

> Maybe I have tunnel-vision on this, but what do you mean by the SSH experience does vary per builder exactly and how does that impact the usefuless of this concept -- particularly if it's optional and only happens if defined to happen?

The SSH communicator is provided to all the builders by the Packer plugin SDK, any feature available in the communicator may expose its config as an `ssh_*` input argument to a builder but it is up to the builder to honor it. This essentially means that builders need to opt into this functionality unless it is part of the StepConnectSSH function, which is required for the SSH connection to occur. This is not functionality we would want to include within the SSH connection step logic.

> I'm also not sure I understand how multiple terminal sessions results in the single output stream from a packer command including the contents of the tailed file while packer waits.

Multiple terminal sessions will not result in a single output stream for sure. I took your request to mean gaining visibility to the serial console while waiting for the build and not creating a single stream of output. Which is now clear to me, thank you.

This new information does further the thought that this is out of Scope for Packer.

In the simplest implementation of trying to tail a file that works for the supported platforms, Packer would run into the same limitations described in the proposed wrapper. It may be further limited, in that the contents of the log file may differ per user per builder and what gets outputted to the screen may not be usable or blended in a way that both the Packer output and file being tailed become difficult to read.
 
A more robust implementation would work to properly coordinate the running processes to help alleviate potential logging issues. What I am explaining is possible but it is out of scope for Packer. 

Since there are alternative solutions that could assist in solving this problem the team decided to mark this as wontfix.  As we believe it can be better handled by the user who knows more about their logging requirements and their respective Packer build environment. 

I hope that my answers help provide a bit more clarity. 

Thanks again! I appreciate your response and thoughtful questions.
