### ISSUE TITLE
[question] How to set a date to one year later in packer

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/packer#11729]
Issues on GitHub are intended to be related to bugs or feature requests, so we
recommend using our other community resources instead of asking here if you
have a question.

- Packer Guides: https://www.packer.io/guides
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community

Mine is a quick one. 

I need set "shared_gallery_image_version_end_of_life_date" in Azure ARM, to one year later. 

```
"shared_gallery_image_version_end_of_life_date":  "{{isotime \"2006-01-02\"}}"
```

How to change it to the date one year later?

**Comment by nywilken** [comment]
@ozbillwang are you still looking for help here? The isotime function formats and outputs the current time from Unix epoch. Packer does not have a function that would allow you to calculate one year from the current date/time. As an alternative you can use a variable and pass in a date one year from today via the cli. Below is a example I've written using the BSD `date` command on macOs. 


```hcl
variable "oneyear" {
  type = string
}

source "null" "example" {
  communicator = "none"
}

build {
  sources = ["source.null.example"]

  provisioner "shell-local" {
    inline = ["echo ${var.oneyear}"]
  }
}
```
```shell
~>  packer build -var oneyear=$(date -v +12m "+%Y-%m-%d") /tmp/source.pkr.hcl
null.example: output will be in this color.

==> null.example: Running local shell script: /var/folders/vz/rv7bk6v15211jxg8q801f7kw0000gq/T/packer-shell1509351732
    null.example: 2023-05-26
Build 'null.example' finished after 318 milliseconds 380 microseconds.

==> Wait completed after 318 milliseconds 484 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
```

If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for help. The github issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions.

**Comment by ozbillwang** [comment]
Great, let me try.
