### ISSUE TITLE
More than 2 parallel builds cause packer crash

### ISSUE THREAD

**Issue by mickeyoc76** [hashicorp/packer#11769]
Packer version 1.8.0
https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_windows_amd64.zip

I have 3 builders defined in the packer json.  I'm running each build on a separate gitlab runner via a gitlab pipeline. 
Each build is a separate job in the pipeline e.g

As the jobs are running separate runners this not an issue with the runner running out of memory.

E.G.
job 1 - packer build -only eng  - (dedicated gitlab runner - windows2016)
job 2 - packer build -only prod - (dedicated gitlab runner - windows2016)
job 3 - packer build -only test - (dedicated gitlab runner - windows2016)

they are all triggered at the same time.

2 builds complete and 1 always fails.

![image](https://user-images.githubusercontent.com/29862196/167644945-597aa11c-b88b-432f-a51b-190f90d98c6e.png)

**Comment by nywilken** [comment]
Hi @mickeyoc76 thanks for reaching out. Apologies for the delayed response here. Taking a look at the provide screenshot it looks like there might be some shared resources between the builds that gets deleted by one, which causes the other to fail because its resources have been deleted from underneath it. But that is an assumption. 

Do you know if two of the builds sharing some resource group or name? 

In order to best help with this issue can you please provide a redacted version of the template being used along with the full debug logs `PACKER_LOG=1 packer build template.pkr.hcl`. Cheers!
