### ISSUE TITLE
Packer Validate: Provide means to overwrite the default file format  

### ISSUE THREAD

**Issue by bloudraak** [hashicorp/packer#11857]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

When calling `packer validate`, add an option to specify which format the file is in, just in case the extension isn't known.

#### Use Case(s)

I have a configuration file, specifying the operating systems I'd like to install. From there, I generate the packer configurations.  In PowerShell, it looks something like this, generating a variables file.  

```
$Contents = Get-PackerAutoVariablesFileContents -Image $Image
$TempFile = New-TemporaryFile 
try {
    $rc = Set-Content -Path $TempFile -Value $Contents
    packer validate -syntax-only $TempFile
    packer fmt $TempFile
    Copy-PackerFile -Source $TempFile -Destination "packer.autovars.pkrvars.hcl"
}
finally {
    $TempFile.Delete()
}
```

Despite HCL being the preferred method for packer templates, in this case, `packer validate` assumes the temporary file is a JSON file, which is perhaps a poor assumption.

A workaround could be to rename the temporary file, but that has side effects in terms of cleaning up code and whatnot.

#### Potential configuration

```
packer validate -format hcl -syntax-only $TempFile
```

Another possibility would be for the user to overwrite the default behavior when the file extension isn't recognized such as:

```
export PACKER_DEFAULT_FORMAT=hcl
```

or 

```
export PACKER_DEFAULT_FORMAT=json
```

**Comment by teddylear** [comment]
@nywilken @JenGoldstrich Is this already being worked on? Else I would love to give it a shot if that's alright. If so, would the first option be preferred with doing something like: `packer validate -format hcl -syntax-only $TempFile` as listed in the issue?

**Comment by JenGoldstrich** [comment]
Hey folks, I meant to reply to this earlier, my apologies.

I don't know if we currently want add this functionality into `packer validate` actually @teddylear, currently JSON is the default because it is what Packer used originally, and many users are still using JSON, the Packer team's long term plan is to deprecate JSON, and so when we do  so the -format flag would also be deprecated.

I think a smaller change that might accomplish something similar here would be to switch Packer to assuming a template is hcl when the file format is not hcl or json.  This change is something we'll eventually do before the deprecation of JSON I believe, but I am not sure when we would want to make this change.

**Comment by nywilken** [comment]
@JenGoldstrich this sounds like the right call for the time. I'm going to close this issue and apply the hcl2 label so that we can revisit once HCL is the default template format.
