### ISSUE TITLE
No response to run command

### ISSUE THREAD

**Issue by Jolin-blank** [hashicorp/packer#11901]
yum install packer

when i run packer , no respnse 
![image](https://user-images.githubusercontent.com/55644946/180592138-ac61caae-2d01-4dd1-9d7e-7ca61f1979d0.png)
my os is centos7

**Comment by nywilken** [comment]
Hi there @Jolin-blank it looks like you are running into the Centos/RHEL Linux packer command issue, where instead of running the Packer binary `/usr/bin/packer` you are actually running the RPM packaging command that comes stock with Centos/REHL distributions `/usr/sbin/packer`. 

To fix this issue you must run Packer using the full path `/usr/bin/packer`. I'm going to close this issue but do feel free to reach out if you run into further issues.
