### ISSUE TITLE
Using packer and type qemu in the json file to create a RHEL 8.4 guest kvm vm, but ssh timeout error coming, but same is working in RHEL 7

### ISSUE THREAD

**Issue by PravinKumar3001** [hashicorp/packer#12017]
I have RHEL 8.5 as the KVM host. I want to create a guest vm of RHEL 8.4 through packer type qemu and have a json file where all the configurations are mentioned.

{

“builders”: [

{

“type”: “qemu”,

“iso_url”: “/var/lib/libvirt/images/test.iso”,

“iso_checksum”: “md5:3959597d89e8c20d58c4514a7cf3bc7f”,

“output_directory”: “/var/lib/libvirt/images/iso-dir/test”,

“disk_size”: “55G”,

“headless”: “true”,

“qemuargs”: [

        [

            "-m",

            "4096"

        ],

        [

            "-smp",

            "2"

        ]
],

“format”: “qcow2”,

“shutdown_command”: “echo ‘siedgerexuser’ | sudo -S shutdown -P now”,

“accelerator”: “kvm”,

“ssh_username”: “nonrootuser”,

“ssh_password”: “********”,

“ssh_timeout”: “20m”,

“vm_name”: “test”,

“net_device”: “virtio-net”,

“disk_interface”: “virtio”,

“http_directory”: “/home/azureuser/http”,

“boot_wait”: “10s”,

“boot_command”: [

“e inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/anaconda-ks.cfg”

]

}

],

“provisioners”:

[

{

  "type": "file",

  "source": "/home/azureuser/service_status_check.sh",

  "destination": "/tmp/service_status_check.sh"

},

{

  "type": "file",

  "source": "/home/azureuser/service_check.sh",

  "destination": "/tmp/service_check.sh"

},  

{

  "type": "file",

  "source": "/home/azureuser/azure.sh",

  "destination": "/tmp/azure.sh"

},

{

  "type": "file",

  "source": "/home/azureuser/params.cfg",

  "destination": "/tmp/params.cfg"

},

{ 

  "type": "shell" ,

  "execute_command": "echo 'siedgerexuser' | {{.Vars}} sudo -E -S bash '{{.Path}}'",

  "inline": [
"echo copying" , "cp /tmp/params.cfg  /root/",
    "sudo ls -lrt /root/params.cfg",
    "sudo ls -lrt /opt/scripts/"
  ],

    "inline_shebang": "/bin/sh -x"

},

{

  "type": "shell",

  "pause_before": "5s",
  "expect_disconnect": true ,

  "inline": [
    "echo runningconfigurescript" , "sudo sh /opt/scripts/configure-env.sh"

  ]

},

{

  "type": "shell",

  "pause_before": "200s",

  "inline": [
    
    "sudo sh /tmp/service_check.sh",
    "sudo sh /tmp/azure.sh"

  ]

}
]

}

It is working fine in rhel 7.9, but the same thing giving ssh timeout error in RHEL 8.4.

==> qemu: Waiting for SSH to become available…

2022/09/23 12:53:15 packer-builder-qemu plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake

2022/09/23 12:53:22 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:3565…

2022/09/23 12:53:22 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH

2022/09/23 12:53:22 packer-builder-qemu plugin: [DEBUG] handshaking with SSH

2022/09/23 12:54:22 packer-builder-qemu plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake

2022/09/23 12:54:29 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:3565…

2022/09/23 12:54:29 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH

2022/09/23 12:54:29 packer-builder-qemu plugin: [DEBUG] handshaking with SSH

2022/09/23 12:55:29 packer-builder-qemu plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake

But when i am creating guest vm with virt-install it is able to create a vm and i am able to see it in cockpit web ui, but when i initiate packer build then while giving ssh timeout error it is not visible in cockpit UI, so not able to see where the guest vm created get stuck.

Note: Through virt-install I am able to create a VM from this iso of rhel 8.4, but not able to create through packer qemu

[azureuser@SiedgeKVMTest-Rhel8 ~]$ /usr/local/bin/qemu-system-x86_64 --version
QEMU emulator version 6.2.0 (qemu-kvm-6.2.0-11.module+el8.6.0+16516+f8cbd5fe.5)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
[azureuser@SiedgeKVMTest-Rhel8 ~]$ packer --version
1.8.3

Can anyone please help me to fix this issue

**Comment by lbajolet-hashicorp** [comment]
Hi @PravinKumar3001,

From the information you share it's a bit hard to infer what is the cause of the problem. First thing I'd like to clarify, you mention the build succeeds with RHEL7, and fails with 8.4, I assume in both cases you mean the guest system is RHEL7 or 8.4, and both are running on a RHEL 8.5 as host, correct?

If so, I'd take a look at the guest system, it is possible that the scripts you run to boot the OS may take longer, or that maybe `sshd` is not installed properly.

Also, since the error is a timeout, have you considered fiddling with the communicator config? There's some options available to change the timeout behaviour here (see: https://www.packer.io/docs/communicators/ssh#ssh_handshake_attempts for example), maybe this'll fix your problem.

On a side note, questions like this are best asked on our Discuss forums (https://discuss.hashicorp.com/c/packer/23). The community is generally helpful, and you will probably get better insights on how to fix your problem.
Github issues are generally reserved for bugs or enhancement proposals, anything that the dev team can do in the code directly to improve the product. If it turns out your problem is due to a bug in packer or the Qemu plugin, feel free to send another message on this issue, or open a new one with the information that can help us understand and fix it.

Thanks, and good luck for fixing your issue!

**Comment by PravinKumar3001** [comment]
Yes correct guest vm iso is of 8.4 where issue is coming, earlier 7.9 was the guest vm and it worked well with the same json configuration.

I have already posted in packer community before creating this bug but didn't get any reply.

As there is no log apart from ssh timeout so it is tough for me to identify what is the issue.

I have already try ssh communicator option and increased the timeout from 20m to 40m but it didn't work.

Why I raised a bug because when I am creating guest vm through virt-install it is able to create a guest vm and same I can be able to see from cockpit web UI, but through packer qemu I am not able to see anything on cockpit UI or virsh list about this vm so not getting what is causing timeout error.

As when we run through virt-install then in web ui we can see the progress of the guest vm but here not the case, if possible either someone check my  request on community, mailer or here, i have raised concern at all 3 places.

**Comment by lbajolet-hashicorp** [comment]
Hi @PravinKumar3001,

From what you say, it still looks like there's a problem with your configuration, not with Packer itself. As such, I persist in saying this is probably not the right place to look for insights, as the issues on this repository is for reporting issues with Packer itself.

Now to go back to your problem, you can have more verbose logs through the environment variable `PACKER_LOG`. If you set it to `1` for example (`export PACKER_LOG=1`), you will have more information to help you with the error, but given that your configuration is rather complex, I'm not sure I can help more on that front.

That being said, it looks like the handshakes fail too many times, which causes the error you're experiencing. This may be due to `sshd` not behaving properly. The reason for that is not something I can infer from the information you're providing, so in this case I would advise you to start with a minimal template in order to boot qemu, and try to startup the image.
Another option you may want to consider would be `ssh_handshake_attempts`, which will try to connect more times to the server.

Another thing you may try is to use the `--on-error=ask` option when invoking `packer build`. This will not automatically kill the qemu instance running, which will let you open a shell on the machine so you can inspect what's happening with your sshd.

Outside from these suggestions, I'm not sure I can help anymore on that.

Good luck again trying to fix your problem!

**Comment by PravinKumar3001** [comment]
I can fix this issue if i can get to know what is the issue, as there is no web console for packer qemu.
when i have manually ran virt-install with the iso it is able to create a vm and also i can see it in cockpit web ui
but is there a way to see the packer qemu guest vm can we able to see in some web ui?

**Comment by PravinKumar3001** [comment]
Resolved the issue by adding inst.sshd in the boot command

<img width="494" alt="image" src="https://user-images.githubusercontent.com/114403198/197187913-b42dc2f2-42d4-4f7b-8c95-ed82ab116bab.png">
