### ISSUE TITLE
Packer not adding Name to AWS source instance

### ISSUE THREAD

**Issue by alpana17** [hashicorp/packer#12146]
Packer version: 1.8.3
I can see that no "Name" is added to AWS instance like:
2020/03/11 15:32:47 ui: ==> centos7-ami: Adding tags to source instance
2020/03/11 15:32:47 ui:     centos7-ami: Adding tag: "Name": "Packer Builder"

Has this feature been removed from this packer version?
How can I add Name to source instance?

**Comment by keithalpichi** [comment]
That's correct. Newer versions removed adding "Packer Builder" as the value to the `Name` tag on the AMI. This is noted in the [documentation](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#tags)- "The builder no longer adds a "Name": "Packer Builder" entry to the tags."

If you'd like to add a `Name` tag use the [`tags`](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#tags) map or [`tag`](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#tag) block.

**Comment by alpana17** [comment]
ok, Thanks
I have one more query. There was a python module named aws-hashicorp-packer-reaper
It used to filter instances based on tag: "Name": "Packer Builder"
Is there any other python module that can work for instances created by packer but not having tag: "Name": "Packer Builder"

**Comment by nywilken** [comment]
@keithalpichi thank you for the assist with this issue.  @alpana17 apologies for the delayed response. As mentioned by Keith the default tag was removed since version [packer-plugin-amazon v1.0.9)(https://github.com/hashicorp/packer-plugin-amazon/releases/tag/v1.0.9), and can be added back using the [`run_tags`](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#run_tags) configuration attribute. I believe the `tags` only applied to the resulting AMI created by Packer. 

I recommend running  `packer plugins install github.com/hashicorp/packer-plugin-amazon` or using `packer init` if using HCL2 templates to install the latest version of the Amazon plugin for Packer. 


I'm going to close this issue as there is nothing to be done in Packer or within the plugin.
