### ISSUE TITLE
Error creating AMI: RequestLimitExceeded: Request limit exceeded

### ISSUE THREAD

**Issue by yossisp1972** [hashicorp/packer#12160]
Hi,

When running packer i am getting the below error when trying to create an AMI

Error creating AMI: RequestLimitExceeded: Request limit exceeded.
INFO   2022-12-13 13:10:07    	status code: 503

Nothing else in the log that shown anything to analyze further.
It just fails when it gets to the point to create the AMI.

Not sure why. 

Thanks,

**Comment by frittsy** [comment]
Were you building in us-east-1? From the [AWS status page](https://health.aws.amazon.com/health/status):

> 4:54 AM PST Between December 12 8:09 PM and December 13 4:32 AM PST, we experienced increased error rates and latencies for the CreateImage API in the US-EAST-1 Region. This issue affected the creation of new Amazon Machine Images (AMIs) but did not affect the launching (RunInstances) of existing AMIs. The issue has been resolved and the service is operating normally.

**Comment by nywilken** [comment]
@frittsy thanks for posting the details from the AWS status page. @yossisp1972 It is likely that these errors are related seeing as the RequestLimitExceeded error is an upstream AWS error being reported by Packer. I recommend retrying your builds. 

If you have since retried and are still running into the same issue you may want to try setting the AWS polling configuration settings. 

The AWS builder has configuration arguments for allowing you to override the number of retries and the delays between each retry. A direct link to the documentation is available [here](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#polling-configuration)

I'm going to close this issue as it seems related to the upstream CreateImage API errors. But if I'm wrong please feel free to follow up on this thread.
