### ISSUE TITLE
Plugin host rate limited the plugin getter. Try again

### ISSUE THREAD

**Issue by VAIBHAV7500** [hashicorp/packer#12179]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

During `packer init` the packer is trying to pull the plugins but it says  `Plugin host rate limited the plugin getter`. I'm using GitHub actions and have no control over the host.

#### Reproduction Steps

Create a GitHub action to run packer and it's coming intermittently.

**Comment by BillWeiss** [comment]
After running into this this morning, as a quick fix, I added this to a workflow of mine and I think it works:

```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 603f2dd..4c720e4 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,9 @@ on:
     - cron: "0 0 * * 5"
   workflow_dispatch:
 
+env:
+  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 jobs:
   build:
     runs-on: ubuntu-latest
```

**Comment by mbrunn** [comment]
Having the same issue with Azure DevOps Pipelines

**Comment by nywilken** [comment]
👋 Hi there, packer init can only fetch binaries from public projects on GitHub. GitHub's public API, [limits the number of unauthenticated requests per hour one IP can do](https://docs.github.com/en/developers/apps/rate-limits-for-github-apps#normal-user-to-server-rate-limits). Packer will do its best to avoid hitting those limits. You can set the PACKER_GITHUB_API_TOKEN env var in order to get more requests per hour.
