### ISSUE TITLE
Incomplete HCL support for data sources

### ISSUE THREAD

**Issue by nfx** [hashicorp/packer#12186]
it seems that a valid HCL (TF) config is not valid for packer, even though implemented in https://github.com/hashicorp/packer/pull/11658

```hcl
data "http" "raspios_images" {
  url = local.raspios_url
}

data "http" "raspios_latest" {
  url = "${local.raspios_url}/${local.raspios_latest}/"
}

locals {
  raspios_url = "https://downloads.raspberrypi.org/raspios_lite_armhf/images/"
  raspios_versions = regexall("raspios_lite_armhf-[0-9]{4}-[0-9]{2}-[0-9]{2}", data.http.raspios_images.body)
  raspios_latest = reverse(local.raspios_versions[0])
  raspios_files = regexall("href=\"[^\"]+\"", data.http.raspios_latest.body)
  raspios_iso_url = [for f in local.raspios_files : f if substr(f, -3, 3) == ".gz"][0]
}
```

**Comment by nywilken** [comment]
Hi @nfx this is a current limitation of the HCL implementation in Packer, where locals can not be used within data sources. This issue is essentially the same as https://github.com/hashicorp/packer/issues/11011. It looks like the community has a workaround for now. I'm going to close this issue, and ask that you add any additional thought or comments to #11011
