### ISSUE TITLE
packer provisioning failed with exit code 2300218

### ISSUE THREAD

**Issue by sagartrivedi11** [hashicorp/packer#12265]
I'm using vsphere-clone to clone a vm and in provisioning installing one product which takes around 1hr to complete installation. Getting this error in most of the run while executing packer. 
packer version : 1.8.5
Guest OS : Win10

```
vsphere-clone: Provisioning step had errors: Running the cleanup provisioner, if present...
vsphere-clone: Power off VM...
vsphere-clone: Destroying VM...
Build 'vsphere-clone' errored after 1 hour 5 minutes: Script exited with non-zero exit status: 2300218.  
```

**Comment by nywilken** [comment]
Hi there @sagartrivedi11 thanks for reaching out. This looks to be an issue with the provisioner not exiting correctly, which cause the Packer to fail the build since the provisioner did not execute successfully. 

Do you have any information on the provisioner; specifically on what it is doing during that time? 

Looking at the provided exit status there appears to be an old issue with the Windows update provisioner for Packer that was resulting in long updates exiting with that exit status. If this is a windows update step please check that you are running the latest available version of the plugin.

**Comment by sagartrivedi11** [comment]
Thanks for looking into this issue. I have observed that packer is unable to communicate with guest os after some time. I changed sleep configuration from windows and it worked.
