### ISSUE TITLE
Encrypted AMI across multiple accounts

### ISSUE THREAD

**Issue by acrane-vitacare** [hashicorp/packer#12349]
We are looking to share our encrypted AMI's across multiple AWS accounts. I see in the documentation the config region_kms_key_ids
(https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#region_kms_key_ids). This would allow you to share your AMI's across regions and specify the KMS key used for each region. I don't see a similar option for across accounts. Is there a way around this without sharing my KMS key to the other accounts?

**Comment by nywilken** [comment]
Hi @acrane-vitacare thanks for reaching out. As of right now the only option for sharing encrypted AMIs across accounts is to create a CMK with the one or more accounts targeted as external accounts that can use the key to decrypt any shared AMIs. There is a blog post on this [here](https://aws.amazon.com/blogs/security/how-to-create-a-custom-ami-with-encrypted-amazon-ebs-snapshots-and-share-it-with-other-accounts-and-regions/).

Once you have that key created you specify the key in the Packer configuration with [kms_key_id](https://packer.io/docs/builders/amazon-ebs.html#kms_key_id) and provide a list of target account IDs that are allowed to use the snapshots with [snapshot_users](https://packer.io/docs/builders/amazon-ebs.html#snapshot_users) and the AMIs [ami_users](https://packer.io/docs/builders/amazon-ebs.html#ami_users).

I don't know enough about the latest versions of the AWS SDK, without going through the code, to know if this is something that can be achieved without adding external accounts to the Key policy. If the issue is having to manage such KMS policies via the console, the Terraform AWS provider has resources `aws_kms_key` and `aws_kms_key_policy` to create a custom key with the policy for sharing to one or more external accounts. 

That said, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You may have a better chance of finding someone who can help provide alternate options in the forum.
