### ISSUE TITLE
Cannot clone private repository from github

### ISSUE THREAD

**Issue by juliusoh** [hashicorp/packer#12545]
I have a packer script:

```
build {
  sources = ["source.amazon-ebs.devbox"]

  provisioner "file" {
    source      = "./ssh/"
    destination = "/home/ubuntu/.ssh/"
  }

  provisioner "shell" {
    inline = [
      "chmod 600 /home/ubuntu/.ssh/kubernetes-cluster-provision-devbox",
      "chmod 644 /home/ubuntu/.ssh/kubernetes-cluster-provision-devbox.pub",
      "chmod 600 /home/ubuntu/.ssh/config"
    ]
  }

  provisioner "shell" {
    script = "./packer-files/bootstrap.sh"
  }
}

```

The bootstrap is running this file:

```
echo "ls"
ls -a ~/.ssh
# Clone the repository
echo "Cloning the repository"
ssh-keyscan github.companyname.net >> ~/.ssh/known_hosts
eval ssh-agent
ssh-add ~/.ssh/test
git clone git@test:test2/test3.git
```

Currently getting

==> amazon-ebs.devbox: Load key "/home/ubuntu/.ssh/keyname": error in libcrypto
==> amazon-ebs.devbox: git@github.companymae.net: Permission denied (publickey).
==> amazon-ebs.devbox: fatal: Could not read from remote repository.

**Comment by nywilken** [comment]
Hi @juliusoh this looks like an issue with the ssh key not being loaded properly. Please validate that the is formatted properly and loaded it properly. 

If you are still running into issues you can use troubleshoot this issue further by adding a breakpoint provisioner to the template, which will pause the build so that you can try connecting manually. 

```hcl
build {
  sources = ["source.amazon-ebs.devbox"]

  provisioner "file" {
    source      = "./ssh/"
    destination = "/home/ubuntu/.ssh/"
  }

  provisioner "shell" {
    inline = [
      "chmod 600 /home/ubuntu/.ssh/kubernetes-cluster-provision-devbox",
      "chmod 644 /home/ubuntu/.ssh/kubernetes-cluster-provision-devbox.pub",
      "chmod 600 /home/ubuntu/.ssh/config"
    ]
  }

  provisioner "breakpoint" {}

  provisioner "shell" {
    script = "./packer-files/bootstrap.sh"
  }
}

```

You can also run Packer build with the debug flag `packer build -debug template.pkr.hcl` to steps through the build process. This will output the ssh key created by Packer.

Since this doesn't appear to be an issue with Packer I'm going to close this issue and recommend you reach out to the [community forum](https://discuss.hashicorp.com/c/packer) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.
