### ISSUE TITLE
rpm package on rocky linux 8 is unusable

### ISSUE THREAD

**Issue by msoulier** [hashicorp/packer#12563]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I have installed packer on Rocky Linux 8 using yum. 

soulierm@callisto:~$ rpm -q packer
packer-1.9.2-1.x86_64

packer init just hangs, and running packer with no arguments results in this

soulierm@callisto:~$ packer
/usr/share/cracklib/pw_dict.pwd: Permission denied
/usr/share/cracklib/pw_dict: Permission denied

Following the packer documentation, there is no explanation for this.

**Comment by descensus** [comment]
This packer binary is probably not hashicorp packers binary, but something that comes with cracklib.
Check the paths.

**Comment by lbajolet-hashicorp** [comment]
Hi @msoulier,

@descensus has a lead, by default, on a stock `rockylinux` 9.2 container (pulled from https://hub.docker.com/_/rockylinux), there is already a `packer` command installed, in `/usr/sbin`, which comes from the `cracklib-dicts` package. I would think that in real-life usage this would behave the same.
I believe on your `PATH` you will see that it has precedence over `/usr/bin`, in which we install packer, so that when you try to invoke packer, it defaults to the one from cracklib, and not the one you're installing now.

This is not something we can fix ourselves unfortunately, and in your case there are two possible solutions that comes to mind:

1. Change your PATH so that `/usr/local/bin` has precedence over `/usr/sbin` (I would discourage that)
2. Invoke `packer` through its absolute path.

Alternatively, it seems that the `packer` installed in `/usr/sbin` in in fact a symlink to `cracklib-packer`, so you can probably also change that to point to `/usr/bin/packer` and it will resolve as the `packer` you want to execute in this case.

Hope that helps!

**Comment by nywilken** [comment]
Hi there :wave:, I'm going to close this issue since there hasn't been any updates to it. But if you are still running into issues please feel free to leave a comment on the issue and we will gladly reopen.
