### ISSUE TITLE
get HTTPIP and HTTPPORT in shell provision

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/packer#1277]
How can i get HTTPIP and HTTPPORT and pass it to shell script in provisions ?

**Comment by colemickens** [comment]
I have a need for this. File provisioner means that the files get copied to disk in the VM, which I need to prevent because I don't want traces of the scripts/assets left behind on the image. Shred is unreliable and wiping free space winds up causing the disk image to get expanded on disk and has potential downsides at the FS level.

My workaround was to have the "provisioner" just curl the install script and pipe it into bash, and the install script would then be able to talk to the http server to retrieve other assets and handle them appropriately.

Is there any chance this would be reconsidered, or that there's a work around?

**Comment by rickard-von-essen** [comment]
@colemickens your use case would be easily solved by using a in memory tmp fs. (and no or encrypted swap).
