### ISSUE TITLE
Not found KingsoftCloud documentation on https://developer.hashicorp.com/packer/integrations

### ISSUE THREAD

**Issue by notone0010** [hashicorp/packer#12856]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Hi, I want to view [plugins' documentation called KingSoftCloud](https://developer.hashicorp.com/packer/plugins/builders/ksyun/kec), but I got the wrong page.

<img width="1230" alt="image" src="https://github.com/hashicorp/packer/assets/42347556/88039e9a-ab26-4676-aed3-9524d8e7dae2">

#### Reproduction Steps

Steps to reproduce this issue

https://developer.hashicorp.com/packer/plugins/builders/ksyun/kec

**Comment by nywilken** [comment]
Hi @notone0010 thanks for bubbling up this issue. It looks like this is due to a recent cutover from remote docs to Packer integration portal - apologies for not catching this sooner.  I've disabled the integration temporarily. 

Below is a set of steps that you can take to resolve this issue. To help bootstrap this process I created [a pull-request](https://github.com/kingsoftcloud/packer-plugin-ksyun/pull/33) against your repo with the base layout of the needed changes. Please validate the changes and review them for consistency.
----

#### Checklist
- [ ] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [ ] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [ ] Has added top-level integration README.md file to plugin `docs` directory.
- [ ] All plugins components have one README.md describing their usage.
- [ ] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by nywilken** [comment]
Hi there the integration is live at https://developer.hashicorp.com/packer/integrations/kingsoftcloud/ksyun

The previous URL is no longer valid. I can look into adding a redirect for it if needed. I'm going to close this issue but if you find that a redirect is needed please ping the thread and I can reopen.
