### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by dgl247** [hashicorp/packer#12985]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When trying to create a metasploitable3 VM in the section:
qemu (vagrant): Creating Vagrant box for 'libvirt' provider the following error is displayed:
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x40569d]

#### Reproduction Steps

Run /build.sh windows2008 from metasploitable3 git

### Packer version

Packer v1.6.6

### Simplified Packer Template

https://github.com/rapid7/metasploitable3

### Operating system and Environment details

      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Kernel: 6.8.0-76060800daily20240311-generic 
   /////76767//7676767//////////////      Uptime: 4 days, 15 hours, 16 mins 
  /////767676///*76767///////////////     Packages: 2835 (dpkg), 43 (flatpak), 9 (snap) 
 ///////767676///76767.///7676*///////    Shell: bash 5.1.16 
/////////767676//76767///767676////////   Resolution: 2560x1440, 2560x1440 
//////////76767676767////76767/////////   DE: GNOME 42.9 
///////////76767676//////7676//////////   WM: Mutter 
////////////,7676,///////767///////////   WM Theme: Pop 
/////////////*7676///////76////////////   Theme: Pop [GTK2/3] 
///////////////7676////////////////////   Icons: Pop [GTK2/3] 
 ///////////////7676///767////////////    Terminal: gnome-terminal 
  //////////////////////'////////////     CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
   //////.7676767676767676767,//////      GPU: AMD ATI Radeon RX 7700 XT / 7800 XT 
    /////767676767676767676767/////       Memory: 6263MiB / 31996MiB 

### Log Fragments and crash.log files

https://gist.github.com/dgl247/e62747027ab7d2e7cd979d05104ac4c4

Set the env var `PACKER_LOG=1` for maximum log detail.
[crash.log] (https://github.com/hashicorp/packer/files/15353879/crash.log)

**Comment by nywilken** [comment]
Hi @dgl247 thank you for reaching out. It looks like you may be running into a decoding issue within one of the dependencies for the Packer SDK, which was bundled into Packer 1.6.6. Looking at the project template you are looking to build I see users reporting successful builds with Packer 1.9.1. 

Is there a reason why you are using Packer 1.6.6? 

I would suggest updating to a newer version of Packer, at least 1.9.1, and trying again to see if you run into the same issue. There have been a number of improvements to the SDK and the underlying SDK dependencies since 1.6.6. 

In 1.9.1 the plugins you need to build may no longer be bundled with Packer so you will need to install them using the following commands. 

```shell
packer plugins install github.com/hashicorp/vmware
packer plugins install github.com/hashicorp/qemu
packer plugins install github.com/hashicorp/chef
packer plugins install github.com/hashicorp/parallels
packer plugins install github.com/hashicorp/vagrant
```
