### ISSUE TITLE
Ovirt integration 

### ISSUE THREAD

**Issue by hemak88** [hashicorp/packer#13220]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

Packer until now doesn't have any plugin or post processor for ovirt (https://www.ovirt.org/community/). Ovirt is a KVM based virtualization. RedHat and Oracle has enterprise version of this namely RHEV and OLVM respectively. It would be a nice to have if official support from packer is available. At the moment QEMU is available but it requires a dedicated KVM host which can create turbulence in Ovirt ecosystem. 

#### Use Case(s)
An Ovirt API based plugin something similar to Vsphere. Post processor as well 

#### Potential configuration
Packer template file should be able to specify config as below
ovirt_url= https://ovirtengine.com/ovirt-engine/api
ovirt_username=admin@internal
ovirt_pass=somepass
insecure=true/false

#### Potential References
https://github.com/ganto/packer-builder-ovirt

**Comment by lbajolet-hashicorp** [comment]
Hi @hemak88,

Thanks for opening the issue!

Regarding your request, this is not something we'll add to Packer, principally because integration with external tools are served via plugins, please feel free to refer to our documentation for more info on this: https://developer.hashicorp.com/packer/docs/plugins/creation.

We are a small team with a large amount of code and repositories to maintain, and as such we do not have the bandwidth to add and maintain more at the current time.
If you or some other members of the community are interested in developing such a plugin however, we can help by supporting your endeavours by improving the documentation or the plugin SDK if applicable, and adding the plugin when it's ready to our integrations: we also have [documentation](https://developer.hashicorp.com/packer/docs/plugins/creation#registering-plugins) on how to register one so we can serve the plugin docs on our website.

Since this is not something we'll do anytime soon, I'll close the issue now, but please feel free to reopen if you think I've done this prematurely.

Please let me know if you need anything else, thanks again!
