### ISSUE TITLE
Link for downloading the latest version

### ISSUE THREAD

**Issue by joonas** [hashicorp/packer#134]
So as I mentioned on IRC, it would be nice to have a link that you could just wget to download the latest version of Packer rather than having to know the version number.

**Comment by alexharv074** [comment]
I'm not sure why this is closed but there it still seems there is no URL I can go to that allows me to simply get the latest Packer. This URL [here](https://www.packer.io/downloads.html) allows a human to find the latest Packer pretty easily but what is really needed is a single URL that always points to the latest packer. e.g. `https://releases.hashicorp.com/packer/latest/packer_latest_linux_amd64.zip` which could redirect to a URL with a version in the filename. Surely this would be really easy to do?

**Comment by SwampDragons** [comment]
Hi there!  It does appear that since this issue was closed in 2013, that link Mitchell posted has gone the way of the dodo.  This seems like a valid thing to address, but given the old nature of this issue, do you mind leaving this one dead and opening a new one for us?  It helps us track things much more efficiently.

Thanks!
