### ISSUE TITLE
amazon-ebs: Error querying AMI: AWS was not able to validate the provided access credentials (AuthFailure)

### ISSUE THREAD

**Issue by kuberkaul** [hashicorp/packer#1544]
I have a standard script where I supply secret key ,access key and session token in :

""""
{
  "variables": {
    "aws_access_key": "SIAIELO5HGPABGMLPUA",
    "aws_secret_key": "cgXP0Yy3KUkxRAyVqnUCA5EWS/b4fzN82UFgJC+",
    "token": "QoDYXdzEDMagAJG6NK0xCiPtjbZe81wjIJZf9Wc1RHn3WkR6gIraDD+LdvHLsTNyWDRe04yq9Z+HkDr5Kp6u21obeniiaMuXlS8Erv5mV4Tf9K6RdWHwKezVgFjn40LOK11TqPGNg2ORrQiOQGQUxc3pSH0h8Vm8YLpn+qYXygQniS2kD/WuI9EF3llLcIv+A1YEdwqw2F/2r3Xt3dtv6cjYrZ6ZwFzC+unzm7ZptZ8elomH0a7EY6cErFoY7N656iFz9jCmtBT2pqmdH3f0tdc0n2GBGLK0QkryEJ5PExAIgCGv9oIsgeyPAMXn6c/ZDPxOLIC9g/hk7HTcTVd3nxToMDP/csuS0XrIITmq6EF"
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "token": "{{user `token`}}",
    "ssh_username": "ec2-user",
    "region": "us-east-1",
    "instance_type": "t2.micro",
    "subnet_id": "subnet-f49d429b",
    "security_group_id": "sg-008a9962",
    "source_ami": "ami-76817c1e",
    "ami_name": "packer-{{timestamp}}"
  }]
}

""""

This validates fine but gives auth failure?
![image](https://cloud.githubusercontent.com/assets/2179966/4463877/de7ac8c2-48ce-11e4-9961-8e3756440f21.png)

**Comment by haraldsk** [comment]
I 0.7.5 I have the a similar issue.

However, this issue is only seen when using temporary credentals. (Meaning: Only when using a session token and temporary keys).

Everything works fine when when loading AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SECURITY_TOKEN from environment variables variables.

The follwing doesn't work:
```json
{                                                                                                                                                                               "type"                          : "amazon-ebs",
...
"access_key"                   : "{{user `aws_access_key`}}",
"secret_key"                    : "{{user `aws_secret_key`}}",
"token"                            : "{{user `aws_security_token`}}",
..
}
```
However: If i remove "access_key" and load it from environment while keeping "secret_key" and "token" it works fine.

So the bug is basically down to the access_key malfunctioning when also using token.
