### ISSUE TITLE
Issues with AMI's created with Packer from official CentOS AMI's

### ISSUE THREAD

**Issue by jayjanssen** [hashicorp/packer#185]
I'm using CentOS 6 x86_64 AMI with updates from here: http://wiki.centos.org/Cloud/AWS

This AMI sets up the EC2 security key in the root user to allow SSH access.  However, when I use packer on this AMI, the resulting output AMI builds images where the security key specified does not get applied (anywhere, AFAICT).  If I look at /root/.ssh/authorized_keys, I see the temporary packer key and nothing else.  

I'm sorry for not being more specific here, but I'm trying to understand what Packer is expecting and possibly doing to prevent this from working.

**Comment by dmourati** [comment]
This saved my bacon. Thanks.

**Comment by Rican7** [comment]
Ha, this took me a bit... Thank god it was near the top of a quick Google search. :P

**Comment by cintiadr** [comment]
For future google search references, I had a different problem with the same symptoms in CentOS 7. 
Using https://aws.amazon.com/marketplace/pp/B00O7WM7QW as the source AMIs, the resultant AMIs were not accessible using the default key defined in amazon when launching the EC2 instance. 

Turns out now this process of setting the user SSH authorized_keys is executed by cloud init, and something else in my packer scripts was accidentally uninstalling cloud-init.

So, make sure your AMI has cloud init, and it's running on the first boot of your AMI.
