### ISSUE TITLE
windows-shell provisioner incorrectly sets environment variables

### ISSUE THREAD

**Issue by ebrusseau** [hashicorp/packer#2318]
I have scripts that use the %PACKER_BUILDER_TYPE% variable to determine which variant of the tools to install. When using the windows-shell provisioner, these fail as the value of this variable is empty.

I looked through the code, and it appears the windows-shell provisioner expands variables to: set "variable=value", which will not work. The syntax needs to be one of the following:
1. If the value contains spaces, it needs double quotations: set variable="some value"
2. If the value does not contain spaces, it should be: set variable=value
3. If the value contains double quotes, just use it verbatim #2 above: set variable=value

In Windows it seems if you double quote the value, you have to explicitly refer to the unquoted version %~VAR% otherwise it will include the quotes, so its probably best to distinguish whether or not quotes are necessary at all rather than to always include them. If the user uses them, they most likely understand this, e.g. in the case of "Program Files" in a path statement.

**Comment by AndrewFarley** [comment]
Perhaps I need to open a separate bug... but this problem is really biting me hard at the moment specifically around setting an empty variable because the Windows provisioner thinks the scripts succeed when it fails during the environment variable setting before it actually calls a script.  When environment variables fail to set properly, the provision scripts fail to run, but they do so in a way that is not caught properly so then it says the build succeeds.  For example, if a variable is trying to be set to an empty string (if no value is set)... 

`"environment_vars": [
	"MY_SAMPLE_VAR={{user `USER_DID_NOT_SET_ME`}}"
],`

Then when running packer the output looks like...
```
Provisioning with Powershell...
Provisioning with shell script: ./001-AWS_Sysprep.ps1
The string is missing the terminator: ".
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
ception
+ FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

Provisioning with shell script: ./002-Install_IIS.ps1
The string is missing the terminator: ".
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
ception
+ FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

Stopping the source instance...
Waiting for the instance to stop...
Creating the AMI: packer-windows-clientname-0.0.0.0-2016-07-13_083342
AMI: ami-XXXXXXXX
Waiting for AMI to become ready...
Tagging snapshot: snap-XXXXXXXX
Terminating the source AWS instance...
Cleaning up any extra volumes...
No volumes to clean up, skipping
Deleting temporary security group...
Deleting temporary keypair...
Build 'base-ami' finished.

==> Builds finished. The artifacts of successful builds are:
--> base-ami: AMIs were created:

eu-west-1: ami-XXXXXXXX
```

**Comment by AlPhi247** [comment]
Hi daftpunk74,

I experienced the same symptoms while provisioning a Windows 8.1 Box using the latest packer version 1.1.0:
The packer environment variables are all empty when used within a batch script called from the windows-provisioner.

For troubleshooting I added the 'SET' command as the very first line of my batch file, which prints all the defined environment variables. Unfortunately no packer variables are set in the environment.
This is especially weird as the command logged by packer works when I executed it manually in a windows shell:

`set "PACKER_BUILDER_TYPE=vmware-iso" && set "PACKER_BUILD_NAME=vmware-iso" && set "PACKER_HTTP_ADDR=xxx.xxx.xxx.xxx" && "c:/Windows/Temp/script.bat"`

The three packer variables are listed by the 'SET' when executed.

You claim that the command would be wrong with regards to quoting. Nevertheless it is working locally. I currently do not have an explanation for this.
Did you already find a solution to this problem?

Many thanks in advance

**Comment by SwampDragons** [comment]
I can't reproduce the original issue: 
```
"provisioners": [
    {
      "type": "windows-shell",
       "environment_vars": [
        "VAR1=simple",
        "VAR2=contains spaces",
        "VAR3=contains^&escapedChar",
        "VAR4=contains^^carrot",
        "VAR5=contains\"quotes\"y",
        "VAR6=contains$dollars"
      ],      
      "inline": "echo %PACKER_BUILDER_TYPE%; echo %PACKER_BUILD_NAME%; echo %VAR1%; echo %VAR2%; echo %VAR3%; echo %VAR4%; echo %VAR5%; echo %VAR6%
    }
  ]
```
The ONLY thing I see that could be affecting you @AlPhi247 is that %PACKER_HTTP_ADDR%" is only set if the comman `httpAddr := common.GetHTTPAddr()` returns something other than an empty string.  Assuming this env var is set could be making your script error.

Can you verify for me whether that's your problem, and if so, open a separate issue? It's only tangentially related to the one described here.

Thanks!

**Comment by SwampDragons** [comment]
@AndrewFarley, I'm confused about what behavior you expect here?  This missing variable to be defined as an empty string?

**Comment by SwampDragons** [comment]
Only two years late to this party; I can't reproduce the original issue (by @ebrusseau) without a failing example; all of my attempts at breaking the variable definitions worked fine.  If anyone has a quoting-related issue, please comment here and I'll reopen.  If any of the other variable-related issues mentioned above are still problems and users would like to see different default behavior from packer, please open separate issues.

Thanks!

**Comment by AndrewFarley** [comment]
@SwampDragons Yeah, it should be defined as an empty variable, not fail, eh?  I finished my windows-packer project a bit ago so I haven't been doing much in the arena since I filed this bug.  But I ran into a number of similar bugs which caused this "terminator" error which was a result of a packer bug.  I haven't evaluated it lately if these issues still occur, I worked around a lot of them in parent scripts to ensure invalid/empty values for example, were never sent to packer/powershell.  Another such oddity is if a variable passed into a powershell env variable ever ended in a = character (for example, a base64's string) then it would cause this error.  I wrote a wrapper which converted all ==='s at the end of a string into a special CHR code, which then in powershell I decoded and converted back to ='s.  _fun_ huh?  :P  Try the = at the end of a env variable if you have a second, if that bug still exists, please file that as a bug and fix it?  Would love to have most of these things not an issue the next time I have to packerize windows  :P

**Comment by SwampDragons** [comment]
I'm not convinced that failing is the wrong behavior if an expected var isn't defined.  If your batch script expects an env var to be a path and ends up with an empty string, it might execute but it won't actually behave in an expected or correct way. If anything, I feel like Packer would ideally catch undefined environment vars in validation and fail earlier.

I just checked the "var=somethingWithAnEqualSign=" though.  Looks like it's been resolved since you worked on Packer/Windows. 🎉
