### ISSUE TITLE
flag to skip postprocessor

### ISSUE THREAD

**Issue by rrva** [hashicorp/packer#2679]
I'd like a flag to skip certain postprocessors, for example atlas when I only want to do a local build.

**Comment by rrva** [comment]
Similar to -only:

packer -postprocessors vagrant

will only run the vagrant postprocessor

**Comment by Andrew415** [comment]
2nd this. I know docker really wants us to use dockerhub but I don't have any need for that.

**Comment by Alaneor** [comment]
:+1: 

Yes, this would be a welcome addition. I frequently find myself testing my builds locally to catch any errors before I am ready for publishing and so far I had to manually remove the atlas post-processor when I wanted to only do a local build.

**Comment by mwrock** [comment]
:+1: yes. this would be a welcome feature

**Comment by simbo** [comment]
+1
Yes, please.

**Comment by mvermaes** [comment]
:+1:

Currently we maintain two templates, one to generate AWS/Vagrant images via Atlas, another with the details required for the vSphere postprocessor (which is otherwise identical to the Atlas one).

**Comment by sharumpe** [comment]
+1

We also maintain two .json files: one for vagrant box build for testing and one for vSphere. It would be wonderful to be able to overload `-only=` or add `-only-post=` (or similar) to limit the post-processor.

**Comment by bdwyertech** [comment]
:+1:

**Comment by wyaeld** [comment]
@cbednarski any love for this?  Seems consistent with the DRY design.

Only comment I would make it that potentially rather than referring to provisioners/builders/post-processors by type, being able to 'tag' them, and filter the tags to run would give more flexibility, and its a pattern used successfully in some other tools.

eg.

```sh
packer build -tags vmware my-packer-template-with-everything.json

packer build --help
...
Options:

  -tags=foo,bar,baz         Only include the builds, provisioners and post-processors that match the tags
...
```

**Comment by cbednarski** [comment]
Thanks for the suggestion, folks. This sounds like a good feature addition to me, but it's not on my short list right now.

> rather than referring to provisioners/builders/post-processors by type, being able to 'tag' them, and filter the tags to run would give more flexibility

I like this idea. At least from a UX perspective this is a nice way to do things since you won't need to remember a bunch of different flags. I think we can actually overload the `-only` to use tags _or_ builds. By default nothing will have a tag (and tags will not exist in anyone's build templates) so it should be backwards-compatible.

**Comment by steve-jansen** [comment]
Ran into this problem with local packer builds that include an Atlas post-processor.

As a one-liner workaround, the awesome `[jq](https://stedolan.github.io/jq/)` can strip the post-processor block, then pipe it via stdin to packer...
 
```
jq 'del(."post-processors")' packer.json | packer build -
```

**Comment by bdwyertech** [comment]
Thank you sir @steve-jansen, didn't know `jq` existed.  Great addition to the arsenal.

**Comment by bdwyertech** [comment]
It seems stripping post-processors caused no build artifacts to be produced, not even a local box.  If you want to target a specific post-processor, use this `jq '.["post-processors"][0] |= map(select(.type != "atlas"))' packer.json | packer build - `

Credit goes to @parkershepherd

**Comment by marcusportmann** [comment]
+1

Also struggling with local packer builds that include an Atlas post-processor.

**Comment by panpan0000** [comment]
+1

**Comment by pierreant-p** [comment]
+1

**Comment by rverchere** [comment]
+1

**Comment by awiddersheim** [comment]
+1

**Comment by lfarnell** [comment]
please don't +1 in a comment. Please use a reaction stead. It generates unnecessary emails when a +1 comment is made
