### ISSUE TITLE
Template file is json and hence doesnt have support for comments.

### ISSUE THREAD

**Issue by rluiten** [hashicorp/packer#283]
Comments are something I already miss.
We discussed briefly on IRC and you suggested I raise issue.
You also suggested maybe can add support for rifled "comment": for some comment support.

I am in windows 7 64 bit, using packer v0.3.1

**Comment by wolfhechel** [comment]
I would argue that this is something that should not be put on packer. Pre-processing is just another step that could easily be managed by some other script or tool prior to inputting it to packer.

If anyone needs a simple way to feed template with // comments into packer, here's my approach.
```
sed -e 's@//.*@@g' build.json | packer build -
```

**Comment by mfischer-zd** [comment]
The simplest solution seems like the best solution to me: ignore any keys that start with `_`.

**Comment by jcoutch** [comment]
The simplest solution would be just to pick something and implement it...rather than dragging on this discussion for 2 years.  Put an underscore in, implement an enabled flag, implement HCL/YAML/etc...just pick something!

**Comment by sparkprime** [comment]
I think the value is actually kinda low because a lot of people use Packer as part of a larger toolchain.   By the time your configs are large enough to need comments, you're probably generating the JSON anyway.  And even if you're not in that situation, you can use whatever language you like, as long as you're prepared to write a 10 line Python wrapper.

**Comment by knope** [comment]
comments.  json needs them.  

 json sucks until it has them.  something as simple as an enclosing \\ \\ or ## ## or ... be creative... would be awesome... testing and running and running and testing sucks when a line (key) can't be commented out and back in for science. . . .

+1 for spamming: https://tools.ietf.org/html/rfc7159 ; in order to get json comments...

**Comment by kidbrax** [comment]
people obviously want YAML
