### ISSUE TITLE
Specify AMI source volume

### ISSUE THREAD

**Issue by ProTip** [hashicorp/packer#3024]
Recently I needed to change the inode count for the root EBS volume. This required me to use the pattern of a custom init script that copies the system to a tmpfs in order to format the EBS volume.

I believe making these sort of "from scratch" AMI's could be much easier. Currently the main EBS volume is used implicitly to create the AMI. I believe if we could specify which EBS volume to base the AMI on it would add the flexibility necessary to create completely customized images in a much more user-friendly way.

**Comment by cbednarski** [comment]
Thanks for the suggestion. I _think_ #3040 added a similar feature for the `chroot` builder. Does this approximate what you're trying to accomplish?

Also, there is PR #2962 open for importing images to EC2. This might be another way to address the same issue. Please let me know if there are additional details in your use-case that aren't met by those options. Thanks!

**Comment by ProTip** [comment]
#3040 Appears to be more about selecting which partition to mount before changing the root.

#2962 Looks interesting however I would like to build the image entirely on AWS.

The main issue is that I'm able to create the image with multiple EBS volumes attached, but packer assumes I want to create the AMI from the original boot volume. In the AWS console I can select any EBS snapshot and create an AMI from it. If packer would allow me to create the AMI from any of the EBS volumes attached I would be able to create the system without relying on tmpfs and reboots.

**Comment by dave2** [comment]
#2962 could be extended to import other artfiact types, so chroot -> img -> AMI is supportable with the import interface provided by AWS. I hadn't implemented that yet, but there's no technical reason it can't support a variety of formats other than OVA. It just needs a hook to accept raw images as a valid artifact.

**Comment by dave2** [comment]
Looking into this some more, it seems amazon-chroot expects a pre-existing AMI and mounts a copy of the AMI's root volume to then provision into. This isn't the same as a clean install, since you would need a base image to work from already uploaded first.

I wonder if there's a place for a chroot builder that is agnostic on what it's running on, makes and mounts multiple .img files as volumes, and relies on post-processors to upload to whatever platform you are aiming the template/images at.

This would also then close off clean image creation for a number of platforms.

**Comment by ProTip** [comment]
That might work, if the instance does not need to be running. The use-case difference between the amazon-chroot and amazon-ebs builder seems to be wanting to keep a running instance for building.

It looks like the chroot builder snapshots the volumes and registers an AMI from that.. What I'm after is a hybrid of EBS and chroot I believe; I would like to launch an existing AMI and build my final image from snapshots of attached EBS volumes. This would allow me to completely customize the root volume(encryption, filesystem, etc).

**Comment by lorengordon** [comment]
I have this use case as well. I want to be able to create an AMI from scratch, without it being based on an existing AMI. We do this manually now by launching an instance, attaching a blank EBS volume, partioning it and using chroot to install the OS. 

I could see extensions to either the amazon-ebs or amazon-chroot builders to provide this type of functionality... amazon-ebs already has the ability to launch an instance, which is very convenient for building from my own system, and amazon-chroot runs within an instance and already has the ability to attach a volume and of course uses chroot. Or this functionality could be provided by a new, dedicated builder rather than extending an existing one.

I did find a custom builder for packer that was designed with this use case in mind, but it seems to no longer work with current versions of packer. :(

- https://github.com/sorah/packer-builder-amazon-scratch

The person who wrote that plugin also worked out an alternate method for creating an AMI from scratch, which I'm exploring now, that uses an init trick to boot from tmpfs and then unmount and format the root volume. This method is compatible with the existing amazon-ebs builder, but I haven't yet managed to get the init trick to work with CentOS 6...

- http://blog.sorah.jp/2015/05/11/building-ami-from-scratch-using-packer-amazon-ebs-builder

**Comment by amosshapira** [comment]
I'd like to add my vote for this request. I found blog.sorah.jp too and managed to use this technique manually (for now, until I get around to configure Packer) to create a virgin VyOS 1.1.7 AMI from the official ISO image. It would be so much more straight forward if I could just tell Packer which of the EBS volumes it should use for the AMI burning.

**Comment by lorengordon** [comment]
Following up on my previous comment, I did eventually get a [working script](https://gist.github.com/lorengordon/ee94a2cc1da72bd1b4262cfb0aadce7c) that moves /root to tmpfs and then unmounts the root EBS volume so I can re-partition it and install a new OS. I'm pretty happy with this process, as it also works for AMIs with license restrictions implemented via the billingProduct (such as RHEL). If it helps anyone, feel free to crib anything you like from that gist.

**Comment by Oloremo** [comment]
Really want this too

**Comment by subbu11** [comment]
Hi @ProTip @cbednarski  @dave2 @lorengordon @amosshapira 

After using the parameter 'from_scratch'  in Packer `amazon-chroot`, can we specify an already existing EBS volume containing OS so that Packer can provision/harden/etc on top of this EBS volume instead of creating new EBS volume ?

**Comment by SwampDragons** [comment]
Cleaning up old issues -- I believe this request was fulfilled back in 2016 by the [ebs-surrogate](https://www.packer.io/docs/builders/amazon-ebssurrogate.html) builder.
