### ISSUE TITLE
atlas build SSH timeout

### ISSUE THREAD

**Issue by dpalomar** [hashicorp/packer#3089]
Running packer locally with vagrant provisioner and push section configurated works fine.
Packer creates the .ovf and .box files and uploads to atlas with no problems.

So, when I use `packer push` command, always returns a SSH timeout error.
I tried to increase the timeout with `ssh_timeout` but after 3 hours the error appears.

https://github.com/dpalomar/packer-uc3mTiw/blob/master/template.json

**Comment by cbednarski** [comment]
Thanks for opening an issue.

Can you try doing the build using a standard ISO instead of the netboot one? I suspect there is something with our build server network environment that differs from the one you have on your computer and this may be causing some difficulty.

`ssh_timeout` failure generally indicates that your ISO, boot_command or preseed has a problem but it's hard to see which. If you hop into your Atlas configuration for this job you can add an environment variable `PACKER_LOG=1` to see some more verbose output for this build.

**Comment by dpalomar** [comment]
Hi @cbednarski, I've changed  `headless` and re-running push with the `PACKER_LOG` with the same result.
Here is the [log](https://gist.github.com/dpalomar/ae28736a291c2a7fa8d4)

**Comment by cbednarski** [comment]
Thanks for posting the log. I tried building this locally and the build gets stuck here on mirror selection, though I'm not sure that this is the reason it's getting stuck in Atlas:

![screen shot 2016-01-21 at 10 29 03 am](https://cloud.githubusercontent.com/assets/649798/12490345/ececcca6-c029-11e5-928a-383230994ea8.png)

I'm still speculating this is related to the `netboot` image. Can you try a regular release iso like http://releases.ubuntu.com/trusty/ubuntu-14.04.3-desktop-amd64.iso ?

`netboot` is a special installer that is intended to fetch the boot ISO and other packages via LAN to speed up installing the OS on many machines in a datacenter or corporate network. Since the LAN environment changes between your computer and Atlas and my laptop, there is some unaccounted variability here. Also, you may have cached an older version on your computer that still works, though the latest version has a problem.

Another thing you should try is increasing the `boot_wait` to something like `20s`. Longer `boot_wait` is more reliable on Atlas since it's shared infrastructure and there may be other activity on a host when the build starts running. When `boot_wait` is too short packer will start typing the boot command before the VM has started running and the command will be truncated.

**Comment by dpalomar** [comment]
Weird, on my laptop manual build works fine. This screen must not appear after boot command.
Thanks for the recommendations. I'll change the `boot_wait` and i'll try with another image

**Comment by dpalomar** [comment]
Hi, I've changed mentioned properties (`boot_wait`, `ssh_wait`, `headless`) and the iso from netboot to server, the end lines from CRLF to LF also, and the same result on atlas service, but in local works fine, it creates the ovf and .box. importing from vagarant and running works fine.
Here is the new atlas error: https://gist.github.com/dpalomar/ae28736a291c2a7fa8d4

**Comment by SwampDragons** [comment]
Closing since Atlas is deprecated.
