### ISSUE TITLE
Intermittent test failure in Google TestProcessPrivateKeyFile_encrypted

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/packer#3337]
Not sure if this is a race in the test or some other weirdness, but I got this error running the tests locally:

```
--- FAIL: TestProcessPrivateKeyFile_encrypted (0.00s)
    private_key_test.go:72: should error
...
FAIL
FAIL    github.com/mitchellh/packer/builder/googlecompute   1.776s
```

**Comment by SwampDragons** [comment]
@azr looks like you closed that issue but don't yet have resolution for it in the context of our tests -- should we reopen this until we find a workaround?

**Comment by azr** [comment]
Actually, `processPrivateKeyFile` - the tested func here - is never used, so maybe a correct resolution would be to remove it and tests.

____
But,
From doc of crypto/x509 `DecryptPEMBlock`, the func was is causing the error in our case:
```go
// Because of deficiencies
// in the encrypted-PEM format, it's not always possible to detect an incorrect
// password. In these cases no error will be returned but the decrypted DER
// bytes will be random noise.
```
There is no way we can prevent this from our side ( `DecryptPEMBlock` returns no error and random noise ) , but since the decrypted data is random noise; something else down the line should fail.
