### ISSUE TITLE
virtualbox-iso builder fails if iso_url is a symlink

### ISSUE THREAD

**Issue by johnLate** [hashicorp/packer#3437]
When I specify a symlink for "iso_url" and the symlink name has a ".iso" extension but the symlink target does not have a ".iso" extension, "packer build" fails:

> ==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not get the storage format of the medium '**_symlink target**_' (VERR_NOT_SUPPORTED)

This is a problem for example if you store your ISO files in git annex (which uses symlinks).

Suggested solutions:
- don't resolve symlinks before handing them to 'vboxmanage' or
- copy symlink target to ./packer_cache and add '.iso' extension or
- somehow force vboxmanage to recognize .iso files without extension

.
- Packer Version: 0.10.0 and git from today
- Linux x86_86 (Arch Linux)
- gist: https://gist.github.com/johnLate/9c0c569c21f486af8563a0f80856fe6c

**Comment by tb3088** [comment]
I don't have a PR since I don't know where a Packer-wide function needs to be defined. I have this in one of my local Provisioners but that's not where it belongs. There are a SLEW of these naive "validation" checks across the code-base. Just replace os.Stat() with StatFinal().

`func StatFinal(name string) (FileInfo, error) {
	// prevent symlink loop or excessive depth
	i := 0

	for ( info, err := os.LStat(name); (i <= 10) && (err == nil) && (info.Mode() & os.ModeSymlink); ) {
		name, err := Readlink(info.Name())
	}
	return info, err
}`
