### ISSUE TITLE
new `go-getter` provisioner

### ISSUE THREAD

**Issue by sbfaulkner** [hashicorp/packer#351]
Does it make sense to support a URL source for the file provisioner?

ie. instead of using curl/wget in a script, you could use a file provisioner to download a tarball on the machine running packer, and then copy it to the destination

seems like a relatively small change... would you be interested?

**Comment by lfarnell** [comment]
Has anyone actually sent a PR for this? I didn't see anything in the code so i assume not? If no one has, i will give it a shot.

**Comment by michaeltlombardi** [comment]
I'm thinking it doesn't seem likely that a PR for this has been submitted, @lfarnell.

**Comment by lfarnell** [comment]
@mwhooker I plan on sending a PR for this feature request. Does something like go-getter make more sense and cover a wider array of "things" to be downloaded? Wondering on what your thoughts are.

**Comment by mwhooker** [comment]
@lfarnell That would be awesome. There's a bunch of history about this that I think you should be aware of before starting:

* https://github.com/hashicorp/packer/issues/4587
* https://github.com/hashicorp/packer/pull/3118
* https://github.com/hashicorp/packer/pull/2877

To summarize, yes we should use go-getter so we can download anything, but I don't think extending the file provisioner is the way to go. In one of those tickets I suggest creating a "go-getter" provisioner. I think that's probably the right decision, but I'd be open to discussing it.

The reason I think a new provisioner might be best is so that we can keep the the provisioner behaviors internally consistent. If we support arbitrary file URLs for uploading to the guest, then it breaks symmetry, since downloading would work differently. There's also the problem of maintaining validation. We want to be able to tell if a template will fail before running, so we want to keep file validation around.

**Comment by mwhooker** [comment]
@lfarnell I think what would probably be best is to replace the code in https://github.com/hashicorp/packer/blob/master/common/download.go with go-getter, and then use that inside of the new `go-getter` provisioner. That would give us access to the same functionality everywhere we download a file. It's a lot more work but I think it has a better chance of getting accepted

**Comment by lfarnell** [comment]
> I think what would probably be best is to replace the code in https://github.com/hashicorp/packer/blob/master/common/download.go with go-getter, and then use that inside of the new go-getter provisioner- go-getter provisioner? I think I may be misunderstanding something

**Comment by mwhooker** [comment]
How so?

**Comment by lfarnell** [comment]
Sorry! I didn't see your comment detailing all the issues to consider. I will have a look and get some thought together become i implement something.

**Comment by mwhooker** [comment]
ah yeah, sorry. I know multiple replies can have that problem. Feel free to reach out to me at mhooker@hashicorp.com if you want to brainstorm ideas

**Comment by eaygar** [comment]
Is it already implemented?

**Comment by lfarnell** [comment]
@eaygar No it is not. I'm still thinking about how to best approach this. Many use cases have to be considered.

**Comment by eaygar** [comment]
Ok thank you. Sounds like it'll be nice feature.

**Comment by SwampDragons** [comment]
I have been looking at this for a while and there are a couple of things that will need to be changed in go-getter before we can implement it in place of packer's bespoke downloader.  Particularly, go-getter in its current form does not have progress tracking or ranged http requests, both of which Packer currently makes use of.  I'll be spending some time getting the necessary patches into go-getter and will comment here when we're ready to pull it into Packer

**Comment by azr** [comment]
Hello there, the go-getter has been incorporated in packer in the following PR: https://github.com/hashicorp/packer/pull/6999, mainly the download step uses http://github.com/hashicorp/go-getter, I think it is now safe enough to close this issue 🙂
