### ISSUE TITLE
format OVA hangs if using remote_private_key_file instead of remote_password

### ISSUE THREAD

**Issue by BeverlyBrown** [hashicorp/packer#3572]
I'm using Packer 0.10.1 on Linux. I'm using an ESX 6.0 host to build the VM.

When it gets to the part where it is exporting the VM, it hangs at this step:
==> vmware-iso: Exporting virtual machine...
    vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@esxhost.localdomain/vm-packer.13034 vm-packer.13034/vm-packer.13034.ova

If I supply a remote_password, it works. But I'm using the SSH key so that I don't have to use the password.

Can I skip the export step altogether and use scp to copy the files down and then use ovftool on the local files?

**Comment by cbednarski** [comment]
Thanks for the report!

> Can I skip the export step altogether and use scp to copy the files down and then use ovftool on the local files?

You may be able to do this using the shell-local post-processor, but you'll need to know how to bring everything down yourself. The VM files include metadata and (usually) split files for each disk. When you export these get packaged up into a single archive for portability.

I don't recall which format ESXi uses to store the files on disk (it's not the same format as VMware Desktop, for example) but you can take a look at the packer code for export to get an idea of what type of procedure it's going to run on the remote host in order to get everything downloaded properly.

**Comment by BeverlyBrown** [comment]
I can scp the files with no problem, but if I remove the "format": "ova" line packer still looks for the output-directory and returns an error if it's not there. I'm trying to control building the VM via a makefile and it won't proceed to the next step if packer returns an error. I'm looking for something like a "no_export" option to let packer know not to expect the output directory to exist. I want the VM to be unregistered and left on the ESXi server until I pull the files off and then ssh in to delete them.

Or even better, packer could have an option to export using scp. Just grab the output directory on the ESX host and all the files in them and put them in the output directory on the system running packer.

**Comment by jpsecher** [comment]
The same happens for me: If I use `remote_password` the export succeeds, if I use `remote_private_key_file` to access ESXi, then the upload fails.

**Comment by SwampDragons** [comment]
There's now a `skip_export` option which should provide a workaround to this. I don't think ovftool directly allows you to download using a key.
