### ISSUE TITLE
Amazon: fails on upload bundle to S3

### ISSUE THREAD

**Issue by opokhvalit** [hashicorp/packer#3615]
I tried to create new instance store AMI on Amazon (us-east-1 location)
Unfortunately packer is unable to upload bundle:

```
AmazonLnx-IS: Created image-1465834236.part.70
   AmazonLnx-IS: Generating digests for each part...
   AmazonLnx-IS: Digests generated.
   AmazonLnx-IS: Unable to read instance meta-data for ramdisk-id
   AmazonLnx-IS: Unable to read instance meta-data for product-codes
    AmazonLnx-IS: Creating bundle manifest...
    AmazonLnx-IS: Bundle manifest is /tmp/image-1465834236.manifest.xml
    AmazonLnx-IS: ec2-bundle-vol complete.
==> AmazonLnx-IS: Uploading the bundle...
    AmazonLnx-IS: Signature version 4 authentication failed, trying different signature version
    AmazonLnx-IS: ERROR: Error talking to S3: Server.NotImplemented(501): A header you provided
 implies functionality that is not implemented
==> AmazonLnx-IS: Bundle upload failed. Please see the output above for more
==> AmazonLnx-IS: details on what went wrong.
==> AmazonLnx-IS: Terminating the source AWS instance...
Build 'AmazonLnx-IS' errored: Bundle upload failed. Please see the output above for more
details on what went wrong.
```
- packer version is 0.10.1
- host platform: amazon linux 2016.03 with latest updates
- aws-amitools-ec2  version is  1.5.7-1.0.amzn1

Any ideas for workaround?

**Comment by rickard-von-essen** [comment]
Could you provide which AWS region you have this problem in?

**Comment by opokhvalit** [comment]
us-east-1 region.

I found workaround:
```"bundle_upload_command": "sudo -i -n ec2-upload-bundle -b {{.BucketName}} -m {{.ManifestPath}} -a {{.AccessKey}} -s {{.SecretKey}} -d {{.BundleDirectory}} --batch --region {{.Region}} --retry --sigv 2"```

**Comment by modiji** [comment]
facing the same issue in frankfurt region,  --sigv 2 is not helping

**Comment by rswarthout** [comment]
In our case we needed to modify the command to add in the access key and secret values for it to complete successfully.

**Comment by newzac** [comment]
I am experiencing the same issue when trying to create instance backed AMIs in us-east-1 as well.

**Comment by camronlevanger** [comment]
Same problem. us-east-1.

**Comment by jf** [comment]
I'd like to credit @mwhooker 's note at https://github.com/hashicorp/packer/issues/4648#issuecomment-285450904 for the inspiration and the push to go dig at stuff and investigate things myself, and see what I can find out. I too, have been getting stuck here at this last crucial bit for a while now - checked out this issue, saw the comments, saw the outstanding status... and simply gave this up as unfixable until somebody from hashicorp takes a look at it **and** hopefully amazon's api cooperates.

So the inspiration came when I saw that the tool actually uses a hostname to upload the image to:

```
# sudo -i -n ec2-upload-bundle -b instance-amis -m /tmp/*xml  -a [AWS_KEY] -s [AWS_SECRET] -d /tmp --batch --region ap-southeast-1 --retry --debug
No location specified, setting location to conform with region: ap-southeast-1
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
curl -sSL -H "host:instance-amis.s3-ap-southeast-1.amazonaws.com" -H "x-amz-date:20171005T191138Z" -H "x-amz-content-sha256:[redacted]" -H "authorization:AWS4-HMAC-SHA256 Credential=[redacted]/20171005/ap-southeast-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[redacted]" -o /tmp/ec2-get-response20171005-7684-r0wn9w 'https://instance-amis.s3-ap-southeast-1.amazonaws.com?location' -w "Response-Code: %{http_code}\nContent-Type: %{content_type}"
Signature version 4 authentication failed, trying different signature version
curl -sSL -H "host:instance-amis.s3-ap-southeast-1.amazonaws.com" -H "x-amz-date:20171005T191138Z" -H "x-amz-content-sha256:[redacted]" -H "authorization:AWS4-HMAC-SHA256 Credential=[redacted]/20171005/ap-southeast-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[redacted]" -H "date:Thu, 05 Oct 2017 19:11:39 GMT" -H "content-type:application/x-www-form-urlencoded" -H "Authorization:AWS [redacted]:[redacted]=" -o /tmp/ec2-get-response20171005-7684-11a9qgj 'https://instance-amis.s3-ap-southeast-1.amazonaws.com?location' -w "Response-Code: %{http_code}\nContent-Type: %{content_type}"
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/http.rb:277:in `rescue in get'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/http.rb:284:in `get'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/s3support.rb:132:in `block in get_bucket_location'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/s3support.rb:206:in `block in http_fallback'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/s3support.rb:201:in `each'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/s3support.rb:201:in `http_fallback'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/common/s3support.rb:131:in `get_bucket_location'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:113:in `get_bucket_location'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:283:in `upload_bundle'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:339:in `main'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/tool_base.rb:201:in `run'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:360:in `<main>'
ERROR: Error talking to S3: Server.NotImplemented(501): A header you provided implies functionality that is not implemented
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:322:in `rescue in upload_bundle'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:275:in `upload_bundle'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:339:in `main'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/tool_base.rb:201:in `run'
/usr/local/ec2/ec2-ami-tools-1.5.7/lib/ec2/amitools/uploadbundle.rb:360:in `<main>'
```

See that `instance-amis.s3-ap-southeast-1.amazonaws.com` hostname in there? That's a pretty generic name! Does that belong to me? A bit more investigation made me go and check my s3 buckets and what-the-hey, I *dont* have a bucket in that list called `instance-amis`???

So the answer to this riddle - and I curse amazon for making you have to do this thing where you have to go fight for a stupid hostname with everybody else with this s3 thingie, and creating an instance-store AMI is just so complicated/tedious - is to make sure you claim ownership of that s3 bucket / hostname first... or you have a really unique s3 bucket name that wont clash with anybody else. Otherwise with a really generic name like `instance-amis`, you can bet that that belongs to somebody else already, and you'll be trying to upload to somebody else's bucket.... And you'll get that unhelpful message from the tool, when it really is an authorization problem.

Btw: if anybody from hashicorp is looking and is happy to oblige, I'd like some shwag, please. Some stuff is just hard to get here. Thank you, everybody.

**Comment by mwhooker** [comment]
@jf thanks for investigating this. Having the wrong bucket name certainly seems like a plausible explanation. @opokhvalit can you verify that the bucked passed to `s3_bucket` is owned by you?

Seems like we should be able to catch this error and print a better error.

If you email me mhooker@hashicorp.com with your address, I'll see about some stickers.

**Comment by mwhooker** [comment]
Actually I see that a workaround for signature version was found above. Going to close this but open an issue to pop up a better error message.

**Comment by jf** [comment]
Thanks, @mwhooker . I did try using a different signature version. But I got a different error message (I forget now) than reported here. In my case, it was definitely a case of not owning the s3 bucket.
