### ISSUE TITLE
Custom Commands documentation wrong

### ISSUE THREAD

**Issue by dploeger** [hashicorp/packer#3830]
I wanted to create a custom command referring to https://www.packer.io/docs/extend/command.html.

However, in the current master all referenced packages are not available. Is that documentation deprecated or for future use?

**Comment by rickard-von-essen** [comment]
The docs should be up to date. Can you specify what's wrong?

**Comment by dploeger** [comment]
I specifically can not find packer.Environment and plugin.ServeCommand.

**Comment by rickard-von-essen** [comment]
Hmm, yeh the docs seems to be a bit dated. I'm not sure if it's possible to plugin command anymore. Other plugins register by calling Register* in
https://github.com/mitchellh/packer/blob/master/packer/rpc/server.go

@cbednarski

**Comment by rickard-von-essen** [comment]
@mwhooker can we sort this out when you are back.

**Comment by lfarnell** [comment]
I remember Matthew and I had a email thread regarding this and it seems like all the code for custom commands was removed in 779b6d1719ced0828ccc0acb21c62f114284f8dd.Basically it was hard to maintain. I think a common pattern now is to build custom tools to accomplish the same goals.

**Comment by cbednarski** [comment]
Yep, sorry about this! I am not aware of this part of the API being widely used, but our recommendation is to run your tooling before/after you run packer. The most common use-case I'm aware of is template pre-processing.

Please note that custom plugins (builders, provisioners, etc.) are still supported as before -- this only applies to custom _commands_.

Since the docs are up-to-date (e.g. gone, in this case) I'm going to close this. Thanks for the update here, @lfarnell !

**Comment by rickard-von-essen** [comment]
[This page need some updating](https://www.packer.io/docs/extending/plugins.html).

**Comment by lfarnell** [comment]
I will send a PR for it.

**Comment by lfarnell** [comment]
@SwampDragons @rickard-von-essen This can be closed now , #5092 was merged
