### ISSUE TITLE
Feature request: Define output directory for the exported virtual machine

### ISSUE THREAD

**Issue by BijsT** [hashicorp/packer#3896]
Since my Go coding skills are limitted, I would like to ask you guys for a new feature. In the vmware builder, there is an option (format) to export the VM to your local machine. Currently it outputs the OVA, or OVF in the base directory, but I would like to define the output folder in the JSON, e.g. "format_output_dir": "./OVA". Is this possible to make?

**Comment by rickard-von-essen** [comment]
Sorry am I misunderstanding something or are you asking for [output_directory](https://www.packer.io/docs/builders/virtualbox-iso.html#output_directory)?

**Comment by BijsT** [comment]
Hey,
I'm not sure, but I don't think so. The part where the directory is created during the exporting of the OVA file is (in builder/vmware/iso/step_export.go):
	// Export the VM
	outputPath := filepath.Join(c.VMName, c.VMName+"."+s.Format)

	if s.Format == "ova" {
		os.MkdirAll(outputPath, 0755)
	}

At first I also thought I should use Output_Directory, but this did not work for me.

**Comment by rickard-von-essen** [comment]
There is lots of information missing here, please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by mpdude** [comment]
*join*

Running packer `0.10.1`.

Using the `vmware-iso` builder, using `"format": "ova"`, `"output_directory": "output/some/where"`.

The log shows (abridged):
```
... 
Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@myhost/packer-vmware-iso packer-vmware-iso/packer-vmware-iso.ova
2016/10/14 19:30:42 ui:     vmware-iso: Opening VI source: vi://root@myhost:443/packer-vmware-iso
    vmware-iso: Opening OVA target: packer-vmware-iso/packer-vmware-iso.ova
    vmware-iso: Writing OVA package: packer-vmware-iso/packer-vmware-iso.ova/packer-vmware-iso.ova
```

So, although the `output_directory` is set, the `ovftool` command places the `.ova` artifact elsewhere, due to the way the command is set up [here](https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/step_export.go#L55).

**Comment by eschrock** [comment]
I am encountering the same issue - there is no way to control the local output directory when using the "format" (ovftool) options. In addition to not being configurable, packer doesn't clean up the directory automatically as it does with the standard output directory (in builder/vmware/common/step_output_dir.go). The result is that if you try to run two builds in a row with -force, it will fail because the file already exists:

==> vmware: Exporting virtual machine...
    vmware: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://<elided>/vname vname/vname.ova
==> vmware: Error exporting virtual machine: exit status 1
==> vmware: Opening VI source: vi://<elided>/vname
==> vmware: Opening OVA target: vname/vname.ova
==> vmware: Error: File already exists: vname/vname.ova/vname.ova
==> vmware: Completed with errors

If this becomes a configurable option, it should also be cleared in the same fashion.

**Comment by moserke** [comment]
For now, I have gotten around the collision by using a uuid per build:

```
"variables": {
    "build_uuid": "{{ uuid }}"
  }
```

```
"vm_name": "{{ build_name }}-{{ user `build_uuid` }}"
```

So this way at least each build vm, and therefore the exported vm, is a unique name.  Not ideal obviously, but works.

**Comment by mwhooker** [comment]
can anyone test https://github.com/mitchellh/packer/pull/4447 ?

I don't have access to a remote server

**Comment by mwhooker** [comment]
There's a PR for this in #4591 but it's too big a change to put in 1.0, so retargeting for 1.1

**Comment by mwhooker** [comment]
@BijsT any chance you can test the PR in #4592?
