### ISSUE TITLE
azure: Communication configuration 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#4174]
Related to #4172

- [ ] Don't set a default `ssh_username` [in a builder](https://github.com/hashicorp/packer/blob/676c3a21bf1858d5786ea3c74efbd1e7a2a24ad4/builder/azure/arm/config.go#L688).
- [ ] [The default to both](https://github.com/hashicorp/packer/blob/676c3a21bf1858d5786ea3c74efbd1e7a2a24ad4/builder/azure/arm/config.go#L580) `ssh`and `winrm` communicator is really weird and undocumented. I think it should be removed, even if it breaks BC, or at least clearly documented. Currently some valid configurations will be ignored or not work as expected.

**Comment by boumenot** [comment]
Most Azure VMs are configured to disallow root SSH access, so not picking a default is a recipe for a poor UX.  I have not seen issues with picking a default in practice.  Please forward any bugs.

A default of ssh and winrm communicator was done unintentionally, and then maintained to ensure we did not break anyone.  I would have reverted the change for 0.11, but I didn't know when that was going to ship, so I could not plan accordingly.  I am happy to make the change for the next major release.

/cc @mwhooker

**Comment by rickard-von-essen** [comment]
> Most Azure VMs are configured to disallow root SSH access, so not picking a default is a recipe for a poor UX.

#4172 Will set the default `ssh_username` to `root` in the communicator and clearly state that in the Communicator docs. I think that is the best available option.

> A default of ssh and winrm communicator was done unintentionally, and then maintained to ensure we did not break anyone.

@mwhooker any opinion on this.

**Comment by boumenot** [comment]
> #4172 Will set the default `ssh_username` to `root` in the communicator and clearly state that in the Communicator docs. I think that is the best available option.

Why the push to change the default to root everywhere?  I am fine with documenting and explaining the choice, but I think having it just work (as much as reasonably possible) is better.

**Comment by rickard-von-essen** [comment]
As I see it there are three different alternatives:
1) No default, force everyone to set `ssh_username`
2) Default defined by comm ssh - `root` is the only reasonable default.
3) Per provisioner default. The only reason this would be better than 2) is if all images have the same default user. To my knowledge this is not the case in any cloud provider. Why is setting the `ssh_username` to `packer` useful?

**Comment by boumenot** [comment]
Thank you for explaining, now I understand the thinking.

If this change needs to be made I would prefer 3, 1, 2 (in that order).

Setting the value to packer isn't useful.  Setting the value to not root is what is useful.  (The name packer was just the first thing that came to mind.)  If the user picks root the build will fail because root is generally not allowed to SSH directly to the VM per the various distro defaults available on Azure.

**Comment by mwhooker** [comment]
this hits that weird area where we're trying to guess things that are unknowable to satisfy the majority of cases. Since the user will be different in almost every scenario I can think of, I'd recommend not setting a default.

In the past we've tried to be really clever and try to understand the state of the systems we're operating on, but imo that's caused more problems than it's worth (c.f. provisioners needing to know about guest os type). I think the direction we want to go now is to have users tell us what to do rather than guessing.

**Comment by boumenot** [comment]
One vote each for (1), (2), and (3). 😄 

I am happy to remove the default, but can we delay this until the next major release.  A couple of days warning is more than sufficient, if you don't known when the release will be.

**Comment by rickard-von-essen** [comment]
> Since the user will be different in almost every scenario I can think of, I'd recommend not setting a default.

Definitely agree with this. The only reason that I picked `root` was that otherwise we break digitalocean, cloudstack, googlecompute, and openstack templates which don't have a value defined.

So I would pick 1, 2, 3, but since the problem above I took my second choice.

**Comment by mwhooker** [comment]
current release schedule is to taper off feature releases in preparation for a 1.0 which will be early next year. the purpose of the 1.0 is to claim stability and freedom from most major bugs. Double checking with some people now about breaking BC in 1.0

**Comment by cbednarski** [comment]
> Definitely agree with this. The only reason that I picked `root` was that otherwise we break digitalocean, cloudstack, googlecompute, and openstack templates which don't have a value defined.

@mwhooker Asked me to take a look at the thread here. I don't have enough context to weigh in on the best way to proceed but I want to reframe the convo slightly.

@boumenot is advocating for the perspective of let's make things "just work" based on the assumptions in Azure. This may not be the same behavior as packer in the typical case. I think the question here is "What does the user expect?"

1. If the user is an experienced packer user who is starting to use Azure, they will expect this to work the same way that it works in other parts of packer.
2. If the user is an experienced Azure user who is starting to use Packer, they will expect this to work the way Azure typically works.
3. If this user is new to both Azure and Packer, they won't expect anything in particular.

By point 1 I do not mean "make the low level details the same" I mean "meet users expectations". For example, if we are building Ubuntu then `root` is _probably_ not going to work, but we should probably not default to `ec2-user` either, unless we're in AWS. Since chef/puppet/vagrant/etc. use reasonable defaults, Azure and SSH should too.

In any case I think this is somewhat arbitrary, but to answer this question for users we will need to write documentation. So let's make sure this is clearly explained, however it is decided.

**Comment by mwhooker** [comment]
going to target this for post-1.0

**Comment by rickard-von-essen** [comment]
@SwampDragons this is still a disturbing discrepancy that should be removed. See #4172.

This has also snuck into the `oracle-classic` builder.
