### ISSUE TITLE
manifest post-processor doesn't save artifact details from azure-arm builder

### ISSUE THREAD

**Issue by jgreat** [hashicorp/packer#4350]
The manifest post-processor doesn't seem to save artifact information from the azure-arm builder.  

Azure image vhd needs to be in the same storage account as the os vhd, and it's best practice to distribute your VMs across many storage accounts. I need some way to run a post-processor to copy my vhd artifact to a bunch of various storage accounts.

As a side note it would be really useful to include the Azure ARM subscription id in with the artifact details. 

* Version `Packer v0.12.1`
* Platform: `Ubuntu 16.04, 4.4.0-57-generic`

Packer Debug Output, Manifest output and Template:
https://gist.github.com/jgreat/baf716de4026d2d9d4662d7a905910f3

**Comment by lordgordon** [comment]
👍 

Same here: would be really useful to have a working manifest export so we can integrate Packer with Terraform.

**Comment by bpoland** [comment]
I ended up just creating a VM with Terraform and then using packer's null builder to run through my provisioners.  It's faster than using packer alone and you can name the resulting vhd yourself, rather than ending up with a long GUID from packer.  After packer is done, run terraform destroy and you're done (make sure to use delete_os_disk_on_termination = "false" in your terraform so the VHD sticks around afterwards).

**Comment by lordgordon** [comment]
@bpoland thanks for the idea! I'll surely give a try.

**Comment by mwhooker** [comment]
solved in https://github.com/hashicorp/packer/pull/4953

**Comment by nabarunchatterjee** [comment]
Still facing the same problem in packer version 1.2.1

**Comment by mwhooker** [comment]
@nabarunchatterjee please open a new issue with steps to reproduce
