### ISSUE TITLE
[feature] Add support for vsphere vcenter/host

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#4475]
Trying to deploy an image to a vCenter on a specific host and it seems that the `ovftool --help examples` supports it

```
  ovftool /ovfs/my_vapp.ovf \
           vi://username:pass@my_vc_server/?ip=10.20.30.40
   (.ovf file to vCenter server using managed ESX host ip address)

   ovftool vi://username:pass@my_vc_server/my_datacenter?ds=\
           [Storage1] foo/foo.vmx c:\ovfs\
   (VM on ESX/vCenter server to OVF using datastore location query)

   ovftool /ovfs/my_vapp.ovf \
           vi://username:pass@my_vc_server/my_datacenter/host/my_host
   (.ovf file to vCenter server using vCenter inventory path)
```

According to the parameters https://www.packer.io/docs/post-processors/vsphere.html the only option is to pass the `host` value but not the `<vcenter ip>`

**Comment by mwhooker** [comment]
This should be a pretty easy fix if anyone wants to take a stab

**Comment by lmayorga1980** [comment]
@mwhooker something like ...

```go

type Config struct {
	common.PackerConfig `mapstructure:",squash"`
 ...
	VCenterIp    string   `mapstructure:"vcenterip"`
  ...
}
```

```go

	if p.config.VCenterIp == "" {

	ovftool_uri := fmt.Sprintf("vi://%s:%s@%s/%s/host/%s",
		url.QueryEscape(p.config.Username),
		url.QueryEscape(p.config.Password),
		p.config.Host,
		p.config.Datacenter,
		p.config.Cluster)
    } else {

	ovftool_uri := fmt.Sprintf("vi://%s:%s@%s/%s/host/%s",
		url.QueryEscape(p.config.Username),
		url.QueryEscape(p.config.Password),
		p.config.VCenterIp,
		p.config.Datacenter,
		p.config.Host)
    }
```

**Comment by mwhooker** [comment]
yeah, plus lines to the docs

**Comment by mwhooker** [comment]
Apologies, I didn't read this close enough. Unless I am misreading, this is just a naming issue? I'm not quite clear on which form of the ovftool docs you're interested in. Is it the first form, or third form? Perhaps the best solution is a docs update, since in the patch you provided, you'd be able to accomplish this now by just setting your vcenter ip to "host" and your host to "cluster".

**Comment by martinmosegaard** [comment]
Maybe I can contribute from an ovftool background: In the string `"vi://%s:%s@%s/%s/host/%s"`, the fifth argument (after `/host/`) identifies what is called a ComputeResource in the VIM API: This can either be a cluster (then it is called a ClusterComputeResource) or an ESX host that is not in a cluster.

I think we should have been able to solve the use case before the commits in this issue. 

For example, to deploy to a cluster in vCenter, `p.config.Host` points to vCenter and `p.config.Cluster` points to a cluster:

`vi://user:pass@vcenter-ip/datacenter-name/host/cluster-name`

But to deploy directly to a host that is not in a cluster, `p.config.Cluster` can also be set to that ESX host's IP:

`vi://user:pass@vcenter-ip/datacenter-name/host/10.20.30.40`

In that case, the documentation could use an update, since `cluster` can be any kind of ComputeResource.

I am worried that adding vCenter IP as an option will make the configuration of the post-processor unnecessarily complex.

**Comment by thor** [comment]
Scrolling through issues tagged with _good first issue_ I came across this one; is this something that would be adequately covered by [the `vsphere-iso` or `vsphere-clone` builders and the `host` configuration they have](https://www.packer.io/docs/builders/vmware/vsphere-iso#host)?

I can see that pushing images to a vCenter afterwards is a possibility, but I'd be curious if there is a demand for the functionality when `vsphere-iso` and `vsphere-clone` are part of Packer now, @lmayorga1980?

**Comment by SwampDragons** [comment]
Hi! I think there's probably still some demand for this functionality for people who want to build a vmware image locally and then push up to a remote vsphere instance.

I'm planning to pick this up this week while working on another issue in the Vsphere postprocessor.

**Comment by SwampDragons** [comment]
I confirmed that this already works and is just a documentation issue; I made a tweak to the docs to make it clear that you can select a specific host rather than a cluster.
