### ISSUE TITLE
Multiple disk support for VMware & VirtualBox builder

### ISSUE THREAD

**Issue by ringods** [hashicorp/packer#462]
Currently, I can only specify the size of a single disk. I would like to use Packer to create base machines with multiple disks. Please extend Packer in order to specify the number of disks and the size of each disk.

This support would be handy in the VMware & VirtualBox builder.

**Comment by cliff-svt** [comment]
Configuring extra disks via vobxmanage and/or vmx_data would be fine if packer provided a way to create the underlying vmdks.  Otherwise, all you can do is add references to non-existent disk image files.

**Comment by pecigonzalo** [comment]
I believe this needs to be re opened, this seriously limits the ability to work with VMWare builders. On VirtualBox you can work around the issue since vboxmanage allows you to CREATE the additional disks. vmx_data Allows only to specify the data inside the vmx and map an existing disk but not the create one.

**Comment by jameskyle** [comment]
@pecigonzalo While I do think would still be an excellent improvement for vagrant, would it be possible to work around your particular problem by creating a shell script that created the disks before creating the machines?

You could use /Applications/VMware\ Fusion.app/Contents/Library/vmware-vdiskmanager to do this.

**Comment by pecigonzalo** [comment]
@jameskyle As i work around im working on wrapping it inside a gradle script (cross platform and stuff) but it is less than an ideal solution. 

Im already doing this due to the fact that we dont have a OVA/OVF post processor like virtualbox (VirtualBox is a problem becuase the OVA/OVF exports are not standard and cant be imported in many other platforms), i think we need to make VMWare a first class citizen here, otherwise we end up with 10 workaround for using the tool.

Vagrant also requires us to Pay for the license of using it, so i guess Hashicorp is aiming at supporting it properly and while i know this is not Vagrant, i think packer is a key component on that workflow.

**Comment by dhartford** [comment]
Also running into this challenge, and adding another usecase would be for downstream adding of disks.  

For example, creating a vmware-iso image, then using the base vmware-iso on mulitiple vmware-vmx profiles where you want to add additional diskspace/drives on a per-vmware-vmx profile basis.

**Comment by Ham5ter** [comment]
There is still no Workaround/Fix for this, am I right?
