### ISSUE TITLE
encrypt_boot should not delete snapshots specified in ami_block_device_mappings

### ISSUE THREAD

**Issue by msnelling** [hashicorp/packer#4653]
When creating an AMI with an encrypted boot volume and a second volume based on an unencrypted snapshot, Packer deletes the snapshot during its final cleanup.

Version: Packer v0.12.3
Host Platform: Windows 10 x64 (Build 1607)
Packer File: https://gist.github.com/msnelling/92982651ef42bdf726f68a6b2b74d8e9
Packer Output: https://gist.github.com/msnelling/6ba6519b6a672a34bfa09163de3ee95f

**Comment by SwampDragons** [comment]
Hey, thanks for reporting this.  Working on replicating now.  In the meantime... does this happen if you don't have delete_on_termination": true?  I assume your intention is to delete the encrypted second volume and keep the unencrypted one?

**Comment by rickard-von-essen** [comment]
`"delete_on_termination"` is for the volume, not snapshot that volume is created from. Also alot of this logic has changed in recent versions so it's probably best to try to repro this on master.

**Comment by msnelling** [comment]
I tested this again with the latest Packer release (1.0.3) and it is still an issue. @SwampDragons, yes you're right, the intention would be to delete the encrypted second volume, not the unencrypted snapshot.

**Comment by SwampDragons** [comment]
Okay, based on where this exists in the code I'm pretty sure that this is  intended behavior: 
https://github.com/hashicorp/packer/blob/8cfef76cdd1f7220a0b9081a162766b93bf8a3d4/builder/amazon/common/step_encrypted_ami.go#L116-L130

So "bug" may not have been the right label.  Gonna replace with "enhancement" -- I'm thinking that if this is a thing people want, the right approach is probably to make the snapshot-deleting optional.  

We could do this two ways: all-or-nothing, or per-block-device.  I'd rather do per-block-device, because it seems more useful.  But I'm gonna have to think about how.  It would be easy to manage if we could add a field to `ami_block_device_mappings`, but that mapping has a direct 1:1 relationship with the aws sdk's "EbsBlockDevice" struct and I'd rather not break that relationship. We might need to create a new optional config option that's a list of snapshots to keep. That would preserve current behavior.  I'm gonna chew on this for a bit.

**Comment by rickard-von-essen** [comment]
This is a bug. Packer didn't create this snapshot and should not delete it.

```
$ env AWS_PROFILE=packer-demo aws --region=us-east-1 ec2 describe-snapshots --snapshot-ids snap-02c7b633208b3895f --output text
SNAPSHOTS       My precious data        False   965990659467    100%    snap-02c7b633208b3895f  2017-07-20T18:44:38.000Z        completed       vol-ffffffff    8
```

```
==> amazon-ebs: Creating Encrypted AMI Copy
2017/07/20 20:56:07 ui: ==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-east-1(ami-5ad2c24c)
2017/07/20 20:56:07 ui: ==> amazon-ebs: Copying AMI: us-east-1(ami-5ad2c24c)
2017/07/20 20:56:08 ui: ==> amazon-ebs: Waiting for AMI copy to become ready...
2017/07/20 20:56:08 packer: 2017/07/20 20:56:08 Waiting for state to become: available
2017/07/20 20:56:08 packer: 2017/07/20 20:56:08 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/07/20 20:56:08 packer: 2017/07/20 20:56:08 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Deregistering unencrypted AMI
2017/07/20 21:06:23 ui: ==> amazon-ebs: Deregistering unencrypted AMI
2017/07/20 21:06:23 ui: ==> amazon-ebs: Deleting unencrypted snapshots
==> amazon-ebs: Deleting unencrypted snapshots
2017/07/20 21:06:23 ui:     amazon-ebs: Snapshot ID: snap-0520bfb443143d963
    amazon-ebs: Snapshot ID: snap-0520bfb443143d963
2017/07/20 21:06:23 ui:     amazon-ebs: Snapshot ID: snap-02c7b633208b3895f
    amazon-ebs: Snapshot ID: snap-02c7b633208b3895f
2017/07/20 21:06:24 ui: ==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Terminating the source AWS instance...
```

```
$ env AWS_PROFILE=packer-demo aws --region=us-east-1 ec2 describe-snapshots --snapshot-ids snap-02c7b633208b3895f --output text

An error occurred (InvalidSnapshot.NotFound) when calling the DescribeSnapshots operation: The snapshot 'snap-02c7b633208b3895f' does not exist.
```

And I think this is also broken because the device mapping is missing `encrypted: true` and thus should probably not be encrypted at all. Just added unencrypted.

And if a packer build failes after it has created the encrypted copy of the snapshot and deleted the original I beleve it will clean up the encrypted version to. And all my precious data is gone. 💥 😱 😢

**Comment by SwampDragons** [comment]
Good point.  Bug it is.  Even if this was intended behavior, it's the wrong behavior. And I also like the point you made about "if we didn't create it, we shouldn't delete it" -- this should be the default. Which means we need to track whether we created something or not, which I don't think we currently do.  I'm going to need to read the code a lot more closely than I have in order to figure out how we should best store this information.

**Comment by SwampDragons** [comment]
hey @msnelling I just pushed a patch (linked above) that should fix this behavior.  When you get a chance, can you try it out and let me know if it works as you expect?

**Comment by msnelling** [comment]
Hi @SwampDragons, I just tried a couple of times, once when creating an unencrypted volume and the other an encrypted volume, both from the same unencrypted snapshot and both time the snapshot was deleted unfortunately.

**Comment by SwampDragons** [comment]
Huh.  Weird.  It seemed to work for me.  Just to make sure I'm not replicating this all wrong -- in your example packer template ` "snapshot_id": "snap-092aee30f19152443",` is the unencrypted snapshot that you want to see not-deleted, right?

**Comment by msnelling** [comment]
Yes that's right.

**Comment by SwampDragons** [comment]
Okay, I must have done something different. I'll go back and retest.

**Comment by SwampDragons** [comment]
I went back and retested -- I can't replicate the unwanted deletion when I run the build with my patch on master.  I waited like half an hour to make sure it wasn't just slow to update.  Not sure where to go from here.

**Comment by SwampDragons** [comment]
ah, try `make dev` instead of `go build`. Should drop a binary in the same place, but it'll have the changes in it. (or grab this and unzip it and drop it into the bin folder :D)
[packerzip.zip](https://github.com/hashicorp/packer/files/1201197/packerzip.zip)

**Comment by msnelling** [comment]
@SwampDragons  I think I mentioned somewhere that I'm on Windows, I doubt the Makefile will work and I think the binary you posted is Linux?

**Comment by SwampDragons** [comment]
![image](https://user-images.githubusercontent.com/1008838/29036873-1e3889ec-7b56-11e7-83f2-de4605442127.png)
Try this one.
[packer.zip](https://github.com/hashicorp/packer/files/1205497/packer.zip)

**Comment by msnelling** [comment]
Ok, that doesn't delete the snapshot specified in the Packer file, however it also doesn't delete the unencrypted boot volume snapshot associated with the temporary AMI.

**Comment by SwampDragons** [comment]
Okay, thanks.  Got it.  Fixed the PR.  Saw the same bugginess as you; I've resolved it and I'm confident that it'll fix it for you too.  Targeting this for Friday's release.
