### ISSUE TITLE
vmware-iso builder output_directory not being created in when using jenkins folder plugin

### ISSUE THREAD

**Issue by jonmosco** [hashicorp/packer#4674]
When building a vmware-iso template from Jenkins, it fails to create the correct output_directories when its done from a folder in Jenkins.  I moved the build out of the folder to the top level, and it built successfully.  

==> vmware-iso: Error creating VMX file: open rhel-7.3-x86_64/server_imaging/packer_rhel7_64.vmx: no such file or directory

The folder in Jenkins is called 'server_imaging'.  

- Packer version: Packer v0.12.3
- RedHat Enterprise Linux 6.4
- Debug log output: https://gist.github.com/jonmosco/57a5d34dff676fa8d752caebbfa93978
- Template file: https://gist.github.com/jonmosco/c79d56c59807b700efc59117993e94e4

**Comment by jonmosco** [comment]
I am trying to rule out this is Jenkins, so I upgraded the folders plugin to the latest release as an FYI.

**Comment by SwampDragons** [comment]
I'm going through old vmware issues and found this one -- as of v0.12.3 we did have the `output_directory` option which isn't being set in the example template, so I think this may be a configuration issue. I'm not seeing where the "server-imaging" name is being provided to the template. 

Since then, we've cleaned up docs and added a remote_output_directory so I think this issue can probably be closed.  If you're still experiencing an issue with jenkins, we can reopen but I think I need a little more info about how the folders are being created and what you expect to be created.
