### ISSUE TITLE
Packer push should support sensitive variables in Terraform Enterprise

### ISSUE THREAD

**Issue by clstokes** [hashicorp/packer#4727]
When doing a `packer push` to Terraform Enterprise, variables can be pushed as well. Terraform Enterprise supports marking variables as sensitive, however this is not supported through `packer push` meaning variables can be inadvertently left able to be viewed.

Packer push should allow variables to marked as sensitive so they're masked in Terraform Enterprise.

**Comment by mwhooker** [comment]
cc @justincampbell

**Comment by justincampbell** [comment]
@mwhooker I believe setting `sensitive: true` in the vars payload will work with no TFE changes, but let me confirm tomorrow.

**Comment by mwhooker** [comment]
Thanks, @justincampbell! If it's that easy, this shouldn't be too bad. The only problem is that we really only understand variable name and value, and not meta information about the variable itself. We'd probably have to either create a `-priv-var` flag, or accept some list of private vars to match against.

@clstokes do you know how people are pushing vars? Is it using `-var` or `-var-file`? If we can just support sensitive vars with just the former approach, this should be a lot easier.

**Comment by clstokes** [comment]
Both with `-var` and `-var-file`.

**Comment by SwampDragons** [comment]
what if we just add two new command line options, -priv-var and -priv-var-file?  

```
- `-priv-var` - Set a private variable in your packer template. This option can 
  be used multiple times. priv-vars will be masked in Terraform Enterprise.

- `-priv-var-file` - Set private/sensitive template variables from a file. 
  These variables will be masked in Terraform Enterprise.
```

**Comment by mwhooker** [comment]
I think that would be acceptable. Dig in a little and see how much work it would be.

The only reason I suggest accepting a list of key names which we want to make private is that the var file stuff is pretty low level. There's a well defined variable order, which describes which key takes precedent when it appears multiple times. I don't recall right now if that's handled in a library, or if it's obvious how it works. See https://github.com/hashicorp/packer/pull/3076 for a recent change to this part of the code.

If it's possible to do it that way, great. otherwise, if we want to preserve existing ordering and not worry about adding additional complexity, I'd recommend a new flag that's something like `-priv-var-list=mysecret,mypassword,etc`
