### ISSUE TITLE
Changelog on master does not have 1.0 entries

### ISSUE THREAD

**Issue by gjastrab** [hashicorp/packer#4766]
Apologies if this isn't the best place to report this, but just wanted to point out that the [Packer 1.0 blog announcement](https://www.hashicorp.com/blog/packer-1-0/) is linking directly to master's changelog, which as of now is behind the 1.0 branch and thus has no release notes explicitly tagged under 1.0.

**Comment by rickard-von-essen** [comment]
Thanks!

**Comment by mwhooker** [comment]
For some reason I didn't think it made sense to put 1.0 in the master changelog, since 1.1 and 1.0 kind of diverge, but after thinking more about it, I realized that was wrong.

Updated the changelog in master here https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#100-april-4-2017

thanks for your report!
