### ISSUE TITLE
Packer Docker builder using chmod on Windows 10

### ISSUE THREAD

**Issue by sdyarnell** [hashicorp/packer#4778]
I am using: 
    Packer version 1.0.0
    Windows 10

The attached template is very simple. Creates a directory and tries to upload a directory. However, it fails saying that "chmod is not supported on Windows".

Why is Packer trying to chmod something on Windows? I believe this is a bug.

Gist: https://gist.github.com/sdyarnell/905ef78d88e8500ea201b5bae59059ff

Associated Stack Overflow question: https://stackoverflow.com/questions/43283491/packer-docker-builder-using-chmod-on-windows-10

Let me know if more is needed.

**Comment by mwhooker** [comment]
Thanks for the report. Yeah this seems like a bug

**Comment by sdyarnell** [comment]
Hi,

How will I know when this is fixed and in a release? Just watch and refresh?

**Comment by rickard-von-essen** [comment]
You will get a email from github when this is closed and the it will be out in the next release. Releases are usually announced on the mailing list.

**Comment by mwhooker** [comment]
1.0.1 is shaping up to be fairly big. PRs welcome!

**Comment by sdyarnell** [comment]
I just noticed the milestone got changed from 1.0.1 to 1.0.2. Am I the only person in the world looking to use Packer to build Docker VMs on Windows? lol

**Comment by SwampDragons** [comment]
I looked into this and there are several other roadblocks to getting docker to work for windows, ultimately because the Docker builder was written before Docker for Windows was even a thing. 

We intend to (eventually) work around these issues by using the docker API (see the WIP branch here: https://github.com/hashicorp/packer/pull/4186) but in the meantime addressing this specific bug won't immediately make Packer's Docker builder work for you on Windows (file uploads are broken in multiple ways). I am going to update the documentation to clarify that Packer's Docker builder is not guaranteed to work on a Windows host, and create a meta-ticket to add support.

Of course PRs are always welcome, so let me know if you decide to take a stab at it yourself.
