### ISSUE TITLE
Feature Request - Add support for multiple hard drives in Hyper-V builder

### ISSUE THREAD

**Issue by PowderedToastMan** [hashicorp/packer#4823]
There doesn't appear to be any way of creating machines with multiple hard drives.  Something similar to [disk_additional_size](https://www.packer.io/docs/builders/vmware-iso.html#disk_additional_size) in the vmware builder would be nice.

**Comment by mwhooker** [comment]
Can someone test the code in #5491? If I can get some help testing I can merge this for the next release

**Comment by pvandervelde** [comment]
@mwhooker I might be able to. I've got a hacked packer config that adds disks via the provisioner step. Should be relatively easy to replace that with the code in the PR I hope ... Will have a check tonight

**Comment by BenPhegan** [comment]
@pvandervelde Let me know if you need any help or encounter any issues.

**Comment by BenPhegan** [comment]
@pvandervelde How are you going with testing?  Do you need anything from me to help?

**Comment by pvandervelde** [comment]
@BenPhegan I just managed to run a few tests. I did the following:
- Grab your branch and locally merge it to packer master and build a copy of packer
- Build an Ubuntu 16.04 base image with just the OS. The VM was created correctly (with 3 additional drives) but then my build failed because my preseed configuration wasn't expecting extra drives :(.
- Building a Windows 2016 Core base image with just the OS. That build is still running but the drives were attached correctly. Once the build finishes I will verify that Windows can see them correctly.

All in all, I would say your code works. I just need to figure out how to make my preseed work with multiple drives. And like I commented on the PR I'd more need this for the hyperv-vmcx builder than the hypverv-iso builder.

**Comment by BenPhegan** [comment]
@pvandervelde Great!  I will start a PR for the vmcx builder this week, but will hold off submitting it until this is one is in master so as not to confuse things (it will be building on top of this code).  Will flag you on the PR to test when ready?

**Comment by pvandervelde** [comment]
@BenPhegan Just as an FYI. I just checked the windows VM (they take forever to build) and Windows can see all 3 drives (only the OS one has been formatted, but the others are there, waiting to be used).

And yes ping me when you have a PR for the vmcx builder.

**Comment by BenPhegan** [comment]
@pvandervelde Will do, and thanks for all your help!
