### ISSUE TITLE
Feature request - amazon-chroot builder - post_provision steps and custom chroot_path

### ISSUE THREAD

**Issue by anderssvanqvist** [hashicorp/packer#4824]
I am using the amazon-chroot builder to do an image installation of VyOS which mounts the actual disk at /boot and has the root device as an overlay on a squashfs and a version subdirectory under boot for writes.

The amazon-chroot builder tightly couples the ebs device and the chroot path which does not work in this case. It also does not have a post_provision step which means that I can't do any cleanup of the various mounts. Right now I'm doing everything in the post_mount_commands step which means manually scripting the mounts and copy files.

My request is this:

* Implement a post_provision_commands step, that runs after provision but before unmount.

* Add a chroot_path variable to support use cases like writable squashfs overlays.

Tia,
Anders

**Comment by eldondevcg** [comment]
@anderssvanqvist would #4845 work for your use case as well?

**Comment by anderssvanqvist** [comment]
No, not everything can be mounted under the mount_path in a squashfs/overlay build. It also doesn't address the chroot_path issue.

**Comment by eldondevcg** [comment]
@anderssvanqvist Can you give an example of what your various mounts look like? If you could give a minimal example of how you would like a post_provision_commands step to look in an packer config, and how the mounts are set up, I could make a similar setup to develop against. Also, to be clear, are you repacking the squashfs as a part of the post-mount step?

**Comment by anderssvanqvist** [comment]
In general, the post_provision_commands step should mirror the post_mount_commands functionality.

I am not repackaging the squashfs, I'm copying it from an iso to the mounted disk, mounting it from the destination and then mounting an overlayfs on a subdirectory from the disk  and the mounted squashfs. This is my root.

```bash
CDROM=${PACKER_MOUNTPATH}-cdrom
CDSQUASH=${PACKER_MOUNTPATH}-cdsquash
WROOT=${PACKER_MOUNTPATH}-wroot
SQUASHFS=${PACKER_MOUNTPATH}-squashfs

# So yeah, we need an overlayfs on this path
umount "$PACKER_MOUNTPATH"

# install VyOS from ISO
curl -o /tmp/vyos.iso -L http://packages.vyos.net/iso/release/${VYOS_RELEASE}/vyos-${VYOS_RELEASE}-amd64.iso
mkdir -p "$CDSQUASH" "$CDROM" "$WROOT"
mount -o loop,ro /tmp/vyos.iso "$CDROM"
mount -o loop,ro "${CDROM}/live/filesystem.squashfs" "$CDSQUASH"
mount "${PACKER_DEVICE}1" "$WROOT"
mkdir -p "${WROOT}/boot/${VYOS_RELEASE}/live-rw"
cp -p "${CDROM}/live/filesystem.squashfs" "${WROOT}/boot/${VYOS_RELEASE}/${VYOS_RELEASE}.squashfs"
find "${CDSQUASH}/boot" -maxdepth 1 \( -type f -o -type l \) -exec cp -dpv {} "${WROOT}/boot/${VYOS_RELEASE}/" \;
mkdir -p "$SQUASHFS"
mount -o loop,ro "${WROOT}/boot/${VYOS_RELEASE}/${VYOS_RELEASE}.squashfs" "$SQUASHFS"
echo "/ union" > "${WROOT}/persistence.conf"
mount -o "noatime,upperdir=${WROOT}/boot/${VYOS_RELEASE}/live-rw,lowerdir=${SQUASHFS}" -t overlayfs overlayfs "$PACKER_MOUNTPATH"
```

**Comment by eldondevcg** [comment]
@anderssvanqvist Also, I was curious if you had considered using chroot as a second level of chrooting in [command_wrapper](https://www.packer.io/docs/builders/amazon-chroot.html#command_wrapper). I find this a little cumbersome/ungainly myself, but if you had tried it and failed due to some piece of information, that might be a useful datapoint.

**Comment by eldondevcg** [comment]
@mwhooker do you want to come up with a set of specifics to implement for this ticket? It's much broader than #4845 I filed, and seems to have several additional moving parts for which I'm not sure of the use case.

**Comment by mwhooker** [comment]
@eldondevcg yes of course, happy to. I realize you're just looking for a solution to your problem and this issue is much more work, but I appreciate your gameness =)

I've got two possible solutions. Could you give me some of your thoughts on which would work best for your use case?

1. allow mount_command to be overridable, so you could, for example, make it `umount -R {{.MountPath}}`
2. Add a pre_unmount_commands field, which would work essentially the same as [post_mount_commands](https://www.packer.io/docs/builders/amazon-chroot.html#post_mount_commands), but run just before unmount. This way you could unmount all the mounts created during your script.


I don't think you need to worry about configuring the mount path, as mentioned in this PR. That can come separately if it's not exactly related to what you're doing

**Comment by eldondevcg** [comment]
@mwhooker Ok, that makes sense to me, I'll give it a try some evening this week.

**Comment by maiconbaumx** [comment]
> @eldondevcg yes of course, happy to. I realize you're just looking for a solution to your problem and this issue is much more work, but I appreciate your gameness =)
> 
> I've got two possible solutions. Could you give me some of your thoughts on which would work best for your use case?
> 
> 1. allow mount_command to be overridable, so you could, for example, make it `umount -R {{.MountPath}}`
> 2. Add a pre_unmount_commands field, which would work essentially the same as [post_mount_commands](https://www.packer.io/docs/builders/amazon-chroot.html#post_mount_commands), but run just before unmount. This way you could unmount all the mounts created during your script.
> 
> I don't think you need to worry about configuring the mount path, as mentioned in this PR. That can come separately if it's not exactly related to what you're doing

Do you know if this is working right now? I'm facing an issue while trying to build multiple amazon-chroot in parallel where at least one of my builds (randomly) stuck in busy device's problem. I'm thinking about a lazy unmount to solve this, but I need something like a umount command wrapper/override to accomplish this.
