### ISSUE TITLE
amazon-ebs builder enhanced_networking AMI's won't start on I3 instance types

### ISSUE THREAD

**Issue by savelandr** [hashicorp/packer#4833]
When building an AMI and enabling `enhanced_networking` from the latest (2017-Mar-31) CentOS 7 image, the resultant AMI will not start up properly on an `I3` instance type in AWS.  The instance will have no network connectivity, preventing access to the host as well as errors in the system log (accessible via the console) trying to connect out.

Run the `example.json` listed below (you'll have to delete or change the vpc and subnet id's).  Then take the resulting AMI and launch it on an `I3.large`.  

While this might seem like (or in fact, be) a CentOS 7 issue, this worked when using Packer 0.8.6, in the sense that the resulting AMI could be started on an `I3` instance. (I don't know if the networking was actually being enhanced)

- Packer version: **1.0.0**
- Host platform: **Ubuntu 16.04**

- Debug log output from `PACKER_LOG=1 packer build template.json`:
- The _simplest example template and scripts_ needed to reproduce the bug:
**https://gist.github.com/savelandr/44d089a8f8eaf0dd7c2ea7ddcb5a9d6f**

**Comment by savelandr** [comment]
I believe this is due to the fact that the CentOS AMI's do not have the _ena_ networking drivers installed.  I suspect the difference in behavior from *0.8.6* to *1.0.0* is because the older Packer did not actually enable the _ena_ type of enhanced networking, just the _ixgbevf_ type.

As such I will close this defect, but if it is caused by something else, feel free to re-open it or someone can open a new defect with perhaps more specific information about the real cause.

**Comment by mwhooker** [comment]
Thanks for the report. We merged https://github.com/hashicorp/packer/pull/4578 which enables ena and sets sriov to `simple when `enhanced_networking` is true. Before, we simply set sriov. 

according to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

> F1, I3, P2, R4, X1, and m4.16xlarge instances use the Elastic Network Adapter for enhanced networking. To find out which instance types support 20 Gbps network speeds, see the Instance Type Matrix.

since I3 responds only to ENA, I think enhanced networking wasn't having any effect before the above change.

You'll have to follow the following steps to get your OS to work on your instance type with ENA enabled: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

Is the problem that you want to build an image with sriov support and not ena support? We debated if enhanced networking should be broken out into two flags to support this, but the thinking was that that wouldn't be useful (you can see our reasoning in the ticket). If so, we can look into breaking out the config a bit more. Let me know and I'll reopen this ticket and change the title. In the meantime, this doesn't appear to be a bug with packer, so I'm going to close.

**Comment by mwhooker** [comment]
ahh looks like you came to the same conclusion I did. good sleuthing!
