### ISSUE TITLE
Make a pre-comiled arm64 build

### ISSUE THREAD

**Issue by Knight1** [hashicorp/packer#4886]
Problem:
There is only a pre-compiled arm version for Packer available the arm64/aarch64 versions is missing. I was able to build it with go 1.8.1 without any errors on a Thunder X.

Fix:
Please make a pre-compiled arm64 version from Packer available unter the download section.

Thanks!

**Comment by mwhooker** [comment]
Sorry we don't have an arm64 binary available for you. It doesn't work with our build tools at the moment.

If you can help get our build tools to cross compile arm64 on darwin, please submit a patch and we'll make sure the next release has an arm binary available. I suspect we'll have to use docker or something to build on linux, since cgo is required

**Comment by Knight1** [comment]
Consul fixed it with this commit: https://github.com/hashicorp/consul/commit/437222fbe7231189213977d164a00dc1310f88c3

Vault also with this: https://github.com/hashicorp/vault/commit/7bce60290f2103365c4fedd9e28fbb28c0930fa1

Consul removed the arm64 from there darwin architecture. Is that a solution for you?

Thanks!
