### ISSUE TITLE
ebs-surrogate: Make AMI registration optional

### ISSUE THREAD

**Issue by cetex** [hashicorp/packer#4899]
I want to build images for netboot (pxe) for our on-premise hardware using packer and i want to do this on Amazon EC2. Since the result of the build won't run in AWS it would be great if taking a snapshot and registering it as an AMI was optional for the amazon builders.

If this was optional i could use something like Amazon ebs surrogate builder:

- Run debootstrap to create a chroot on the mounted ebs volume.
- Run my ansible playbook inside the chrooted directory.
- Run a script to pack the entire directory up into a cpio/gz archive.
- Send the created output files to s3 or something similar.
- **Skip snapshot + AMI registration <- this is what's missing.**
- Cleanup / delete instance and volume directly as the resulting images would be useless for any purpose on AWS.

**Comment by mwhooker** [comment]
thanks for the request. This will actually be an option in the next release! See #4681

**Comment by mwhooker** [comment]
actually reopening because #4681 isn't implemented for ebs surrogate

**Comment by cetex** [comment]
Sweet! Didn't know that!

Thanks a lot! :)

**Comment by gregsymons** [comment]
Since it looks like #4681 was closed without merging, while this issue is still open, I'd like to make the case for this being a useful option.

In my case, I have branch builds and PR builds for my packer images. I'm never going to use the artifacts generated by either of these builds, but I want quick feedback on whether or not the rest of the build succeeded before either opening a PR (which will do the build on a merged branch, so it's potentially different than the branch build) or merging that PR after the builds complete successfully.

**Comment by rickard-von-essen** [comment]
@SwampDragons maybe this should be closed with the same motivation as #4681 ?
