### ISSUE TITLE
amazon/ebs-surrogate: Keeping RedHat hourly license

### ISSUE THREAD

**Issue by dnlprplt** [hashicorp/packer#4922]
Hello,

This is a feature request.

When using the Amazon EBS surrogate builder, a snapshot is created from the volume and then an AMI is created from the snapshot.

This will unfortunately dismiss the license for products from the AWS marketplace. In our case it's the RedHat hourly license.

The solution to retain the license is to create an AMI directly from the instance as stated here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-launch-snapshot.html.

> Note that some Linux distributions, such as Red Hat Enterprise Linux (RHEL) and SUSE Linux Enterprise Server (SLES), use the billing product code associated with an AMI to verify subscription status for package updates. Creating an AMI from an EBS snapshot does not maintain this billing code, and subsequent instances launched from such an AMI will not be able to connect to package update infrastructure. To retain the billing product codes, create the AMI from the instance not from a snapshot. For more information, see Creating an Amazon EBS-Backed Linux AMI or Creating an Instance Store-Backed Linux AMI.

There is the **ami_product_codes** option, but this doesn't seem to apply in this case. When listing the EC2 instance metadata this what we get. So there is no product codes but a billing code.

```
{
  "devpayProductCodes" : null,
  "billingProducts" : [ "bp-6fa54006" ]
}
```

We have for now scripted the whole process without packer. Maybe there is a way to achieve this currently with packer?

Thank you

**Comment by mwhooker** [comment]
Isn't what you're describing the ebs builder?

**Comment by danielprplt** [comment]
Indeed, the EBS builder creates the AMI from the instance. But the EBS surrogate builder allows to provision an attached volume different form the root volume. This is what we need because we want to partition the volume a certain way.

So I guess we need a mix of both.

This is how we proceed currently with simple bash scripts:

1. Start an instance with an attached volume
2. Partition this volume to our liking
3. Stop the instance
4. Detach all volumes
5. Reattach the volume we partitioned as the root volume
6. Boot the instance
7. Create the AMI from the instance
8. Terminate all resources

What we'll try is to use the EBS builder and use the shell or custom provisioner. I'll keep you informed about the outcome.

But it would be great if packer provides this out-of-the-box.

**Comment by rickard-von-essen** [comment]
I did a quick review of the code and found that we need to pass the `billingProduct` option when we do [`RegisterImage`](https://github.com/hashicorp/packer/blob/master/builder/amazon/ebssurrogate/step_register_ami.go#L57).

This option was introduced in [AWS Go SDK v 1.6.26](
https://github.com/aws/aws-sdk-go/blob/0bc99f4aa1cf50245de234b1ce0b33463a3ad5fe/CHANGELOG.md#service-client-updates-41), so we need to upgrade to that.

I don't think this value should be automatically copied from the `source_ami` since strictly you can build something else with the `ebs-surrogate` builder. Instead we should introduce a new option: `billing_product` (array of strings).

**Comment by lorengordon** [comment]
Oh that's interesting. I didn't think AWS exposed `billingProduct` as a settable attribute! Thus far, I think the only was to get it has been to inherit from the source instance (as implied by the docs).

We have similar requirements for partitioning the root volume, and our approach when using packer with the `ebs` builder has been to pivot root to tmpfs via userdata, and then re-partition the root volume.

Feel free to check it out and re-use if you like, https://github.com/plus3it/spel/tree/develop/spel/userdata.

**Comment by lorengordon** [comment]
@rickard-von-essen According to the AWS API docs, only authorized accounts can register an image using `billingProduct`.

> **BillingProduct.N**: The billing product codes. Your account must be authorized to specify billing product codes. Otherwise, you can use the AWS Marketplace to bill for the use of an AMI.

- Source: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html#API_RegisterImage_RequestParameters

**Comment by rickard-von-essen** [comment]
> only authorized accounts can register an image using `billingProduct`.

Yes that is most likely a showstopper for that. There is a important difference between `ebs- surrogate` and the other AWS builders which we should document more clearly. They create an AMI by `CreateImage` but `ebs-surrogate` uses `RegisterImage`. In the former case the new AMI inherits properties from the instance (or the source AMI).

**Comment by frunzales** [comment]
Based on the previous comments on this issue I assume that Action=RegisterImage&BillingProduct.N=<billing_product_code> is not supported.

What I'm trying to achieve is to partition my root EBS volume as per the CIS Security benchmark; The benchmark in question expects separate filesystem volumes at various locations, such as /var, /tmp etc.

I came across https://github.com/plus3it/spel which managed to achieve this by pivoting the rootfs to tmpfs and then taking it from there but it seems to be way too complicated.

Can this be achieved in a different manner?

**Comment by amdonov** [comment]
I think this issue is now fixed. The note about RHEL and SUSE has been removed from the AWS documentation. In addition, I found the following article, https://www.suse.com/support/kb/doc/?id=7023900 which seems to indicate that the AWS snapshot process changed in June 2019 to preserve the billing code.
