### ISSUE TITLE
Azure Builder does not output .pem key when -debug is set

### ISSUE THREAD

**Issue by cberner** [hashicorp/packer#4939]
- Packer version: 0.12.3
- OSX
- Steps to reproduce: run `packer -debug` with an Azure Builder, and observe that no `.pem` key is created

**Comment by rickard-von-essen** [comment]
Confirmed

**Comment by rickard-von-essen** [comment]
This is probably applicable to WinRM password too.

**Comment by cberner** [comment]
Are there any workarounds for this issue?

**Comment by boumenot** [comment]
Sorry, it has been a while since I have had to debug an issue with a Windows build.  Have you tried connecting to the VM using WinRM and it failed?  If I remember correctly, the PEM was not required for authentication, and is used to satisfies Azure's requirements.  The certificate is necessary to configure and enable WinRM only.  The Azure examples for Windows explicitly set winrm_insecure to skip certificate validation.

**Comment by cberner** [comment]
I'm not using windows, this is a Ubuntu VM

**Comment by boumenot** [comment]
Sorry, I saw WinRM and misread the rest.

The workaround is to supply your own public key to the builder.

**Comment by cberner** [comment]
I read through the documentation for the Azure builder and didn't see an option for that. How do I supply a key?

**Comment by boumenot** [comment]
SSH is a shared concept among all builders, so please see [communicator](https://www.packer.io/docs/templates/communicator.html) docs.   After thinking about this more, it still may not help you.  Are you starting with a platform image or a custom image?  If it's the latter, you can inject your public key ahead of time to make it work.

The best answer is still to modify the code to dump the key used for provisioning.

**Comment by cberner** [comment]
Ya, that doesn't sound like it will work. We're using a platform image, and that communicator doesn't offer any way to set the public key: it just allows you to specify your private key
