### ISSUE TITLE
How to get the account number to use with source_ami_filter 

### ISSUE THREAD

**Issue by afaleti** [hashicorp/packer#5026]
I build AMI's monthly and currently hardcode the AMI ID in my builders template but would like to use the source_ami_filter to always get the latest AMI but I need to figure out the Account Number to us so that I get the vendor version published by Amazon, RedHat or Canonical.

Amazon Linux/Ubuntu 14/16 & RHEL ?

 source_ami_filter  (object) - Filters used to populate the  source_ami  field. Example:

{
  "source_ami_filter": {
    "filters": {
      "virtualization-type": "hvm",
      "name": "*ubuntu-xenial-16.04-amd64-server-*",
      "root-device-type": "ebs"
    },
    "owners": ["099720109477"],
    "most_recent": true
  }
}

From the documentation @ https://www.packer.io/docs/builders/amazon-ebs.html 

This selects the most recent Ubuntu 16.04 HVM EBS AMI from Canonical. NOTE: This will fail unless exactly one AMI is returned. In the above example,  most_recent  will cause this to succeed by selecting the newest image.

◦ filters  (map of strings) - filters used to select a  source_ami . NOTE: This will fail unless exactly one AMI is returned. Any filter described in the docs for DescribeImages is valid.

**Comment by SwampDragons** [comment]
Hi! Thanks for writing. 099720109477 is the account number for Canonical, so this example should work right out of the box.

**Comment by mwhooker** [comment]
If you have an image already that you'd like to get the owner of, you can use [`describe-images`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html)

You can find AMIs on the marketplace here https://aws.amazon.com/marketplace/b/2649367011?ref_=hmpg_categories_2649367011

Otherwise, there are resources on the internet that might be helpful. For example, you can find ubuntu images through https://cloud-images.ubuntu.com/locator/ec2/

If you still need help, please post to the mailing list https://groups.google.com/forum/#!forum/packer-tool since people there might be more able to help then in a github issue

**Comment by mcalhoun** [comment]
I wrote a blog post on how to do this step-by-step: https://blog.gruntwork.io/locating-aws-ami-owner-id-and-image-name-for-packer-builds-7616fe46b49a
