### ISSUE TITLE
Packer 1.0.1 cant run scripts on ubuntu with environment variables

### ISSUE THREAD

**Issue by matt-richardson** [hashicorp/packer#5031]
I've just upgraded to packer 1.0.1, and I've found that its not able to run scripts on Ubuntu 16.04. It appears that its due to [this change](https://github.com/hashicorp/packer/commit/1ba7f9cc20d5947c7c562f799cebcf3b5601fcce).

Adding 
```
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} {{ .Path }}",
```
to the provisioner to revert to the old behaviour resolves the problem.

- Packer version from `packer version`: `1.0.1`
- Host platform: `Windows 10, version 1607 (OS Build 14393.1358)`
- Debug log output from `PACKER_LOG=1 packer build template.json`" https://gist.github.com/matt-richardson/58adfc1b9d3dbb72ab2fdaf6a989d2f9
- The _simplest example template and scripts_ needed to reproduce the bug: https://gist.github.com/matt-richardson/58adfc1b9d3dbb72ab2fdaf6a989d2f9

**Comment by mwhooker** [comment]
sorry about that. thanks for the report

**Comment by mwhooker** [comment]
hmm, fwiw, running your script on docker with the change in #4909 reverted shows the same error.

We definitely should not have broken existing behavior in a minor version change, but I believe your script is buggy, since it doesn't have a shebang. If you add `#!/usr/bin/env bash` to the top, I believe it will work.

What was happening is that when you execute the script through the shell, it properly runs as `bash`, but if you execute it with env, you get `sh`.

**Comment by matt-richardson** [comment]
Thanks for resolving so quickly, @mwhooker.
I'll add shebang's to all my scripts so it should be good when this is re-implemented.

(When this does get re-implemented, I wonder if there is something Packer could do to detect and warn about this situation???)
