### ISSUE TITLE
Cannot compile v1.0.2 on ppc64le using go1.8.3 or go 1.6.3

### ISSUE THREAD

**Issue by knightsamar** [hashicorp/packer#5108]
- Packer version :  `v1.0.2`
- Host platform: `ppc64le`
- Go version:  `go version go1.8.3 linux/ppc64le` (latest stable)
- `make` output: https://pastebin.osuosl.org/59961/

I followed the instructions in the developer docs at `CONTRIBUTING.md` because the `make bootstrap` and `make dev` steps at https://www.packer.io/docs/install/index.html#compiling-from-source don't seem to work for me. 

I have tried the  with the `go version go1.6.3 linux/ppc64le` and the result was https://pastebin.osuosl.org/59971/

My aim is to build a stable version for use on ppc64le. Am I missing something ?

**Comment by rickard-von-essen** [comment]
Use `make dev` to build for a single platform.  If you need to build a release version with that I think you need hack the makefile.

**Comment by rickard-von-essen** [comment]
Also there are some outstanding corrections to the websites instructions on howto build.

**Comment by knightsamar** [comment]
So on go 1.6.3, I get an error about `context`, when using `make dev`: https://pastebin.osuosl.org/60071/

compiling on go 1.8.3 succeeded with `make dev` and that  constant set to `dev` but it produces the file named as `bin` instead of packer which says `Your version of Packer is out of date! The latest version is 1.0.2. You can update by downloading from www.packer.io` on running . This seems to be trivial.

I also tried running `make release` on 1.8.3 and it seems to have issues where it starts building all releases but `ppc64le`. The output is here: https://pastebin.osuosl.org/60076/
I seem to not able to fix or change the error by passing a `VERSION=` to `make release` because I obviously don't seem to have the gpg key to sign the release. I will look into hacking the `Makefile` later.

**Comment by mwhooker** [comment]
go 1.6 is not supported (sorry, I don't know that we have that documented anywhere. I will update CONTRIBUTING.md).

try `XC_ARCH=$(go env GOARCH) XC_OS=$(go env GOOS) ./scripts/build.sh`

You can also download that version here:
[linux_ppc64le.zip](https://github.com/hashicorp/packer/files/1171057/linux_ppc64le.zip)

I've signed it with our signing key (https://www.hashicorp.com/security/).

The reason you were getting a failure with go 1.8 is that the version of packer you are trying to build has a go vet failure, which is run as part of our `make` target. The `go vet` failure has been fixed in recent versions. Building it directly with the command above bypasses that step.

**Comment by mwhooker** [comment]
closed via b9d1fada2
