### ISSUE TITLE
Region Copying + Encrypting AMIs does not work.

### ISSUE THREAD

**Issue by sbaxter** [hashicorp/packer#5122]
#4948 added a really nifty feature that I don't think is working quite yet. The code that [deregisters the unencrypted AMI](https://github.com/hashicorp/packer/blob/b8c2a5fd438909619bb22f6c648172bd629fc47f/builder/amazon/common/step_encrypted_ami.go#L107-L113) executes before the AMI copy; the copy fails due to a lack of an available unencrypted AMI to copy.

* Packer v1.0.2 on linux and OSX.
* [Log output (sorry, no debug output)](https://gist.github.com/sbaxter/9cad3ba2fb417be13a5026bd087ef177)
* [Minimum config](https://gist.github.com/sbaxter/5f1a4b284942143459b5b71e29a070f7)

**Comment by SwampDragons** [comment]
I can't replicate this given your minimum config -- my entire config is [here](https://gist.github.com/SwampDragons/16795dbe6fdc7e588bc967f0a66bc5d8) Without debug logs it isn't super easy for me to tell, but I think the failure might be somewhere else for you and then the deregister step is failing because we're trying to do it twice.

**Comment by SwampDragons** [comment]
@sbaxter any luck figuring this out / tips that can help me replicate?

**Comment by sbaxter** [comment]
@SwampDragons I just ran a debug build and the copy succeeded. The issue must have been on my end.

The ordering of the output message `==> amazon-ebs: Deregistering unencrypted AMI` caused me to jump to conclusions; my apologies.

**Comment by SwampDragons** [comment]
No problem; glad it's fixed!  Let me know if you see any more issues with the feature!
