### ISSUE TITLE
Remote esx5 vmware-iso builder should use ISO files from datastore without downloading to local machine

### ISSUE THREAD

**Issue by jozefizso** [hashicorp/packer#5157]
When I use `vmware-iso` builder with `remote_type=esx5` to run build on remote ESXi server, I would expect that the `iso_url` containing an ISO filename would be matched against files in the `remote_cache_directory`.

Right now, packer will try to download the file to local machine and it will upload it to ESXi.

We already have all the ISO files downloaded to ESXi server to special datastore named **iso-store**. I think packer should be able to use those files directly.

**Comment by bugbuilder** [comment]
@jozefizso Excellent idea!

@rickard-von-essen what do you think about this approach:

- [Wrap](https://github.com/bennu/packer/blob/esx5-remote-iso/builder/vmware/iso/builder.go#L223-L232) the common download  
- [Verified](https://github.com/bennu/packer/blob/esx5-remote-iso/builder/vmware/iso/step_download.go) remote iso 
- [Skip upload](https://github.com/bennu/packer/blob/esx5-remote-iso/builder/vmware/iso/step_remote_upload.go#L37-L50)

**Comment by rickard-von-essen** [comment]
@bugbuilder something like that, but I'm not a fan of adding a custom protocol.

My first solution that comes to mind is something like this. Add `remote_iso_path` which points out a directory on your ESXi datastore where ISO's are keept. If the file name of the `iso_url` exists in `remote_iso_path` then try to use it from there and skip local download etc. If it doesn't then dowload it as localy as normal and then upload it to `remote_iso_path`. 

If `remote_iso_path` is undefined keep the current behaviour.

But I think you have the basic pieces, open a PR.

**Comment by bugbuilder** [comment]
I think that your proposal is easier to understand I'll think about how to implement it without breaking things (cache, builder, driver, etc...)

**Comment by bugbuilder** [comment]
@rickard-von-essen I'm still thinking about it and if we add a ``remote_iso_path`` how we can differentiated it with the actual ``remote_cache_directory``, maybe support one of them, same behavior with ``iso_url`` and ``iso_urls``. But this doesn't fit me.

I think that this behavior could be better if is applied without adding a extra parameter just using the actual ``remote_cache_directory`` and if the ``remote_type`` is enabled we need to verified the cache otherwise we'll keep the current behavior.

What do you think?

**Comment by rickard-von-essen** [comment]
Yes, that is probably better. Chacking the code a bit - it looks like it doesn't upload it if it's already in the cache and the checksum matches ([driver_esx5.go#L126](https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/driver_esx5.go#L126)).

If you wrap the generic download step and and do the shecksum check in the cache before downloading, it can be skipped if the checksum matches.

**Comment by bugbuilder** [comment]
We need to find the correct cache ISO name, because when we updated the name it could have had any of following options:

- targetPath [step_download.go#L68](https://github.com/hashicorp/packer/blob/master/common/step_download.go#L68): Name given by the user.
- cache.Lock [step_download.go#L81](https://github.com/hashicorp/packer/blob/master/common/step_download.go#L81): Name given by [cache.go#L99 ](https://github.com/bennu/packer/blob/esxi-remote-cache/packer/cache.go#L99)
- fileName [download.go#L119](https://github.com/hashicorp/packer/blob/master/common/download.go#L119): Name given by the fileName in the local path.

The wrap ([step_download.go#L20](https://github.com/bennu/packer/blob/esxi-remote-cache/builder/vmware/iso/step_download.go#L20)) is a bit messy but it accomplish this three options.

I'm trying to figure out how to solve this in a more elegant way but as you can see it seems that the download logic its too tied to the core.

I can open a PR if you think that this is an appropriate solution.

**Comment by marema31** [comment]
Currently with the vmware-iso builder the ISOs are downloaded in two steps:
- From iso_url to the machine where packer is run.
- To packer_cache directory on the datastore by the UploadISO function of iso/driver_esx5.go. For this step there is a security to avoid uploading if the checksum is correct but to my experience, it has never worked and the ISO are copied to the ESX at each run (I never took the time to have a look why).

For the specific solution wanted by @jozefizso, theses steps could be made skippable by a parameter that will avoid the step in the builder.

For the Vsphere builder I've proposed in PR, the problem is the same, and I would be happy to add the result of this PR.

**Comment by bugbuilder** [comment]
@marema31 I'm glad to see you PR, a new point of view is always welcome :+1: 

If you wish you can check my [PR](https://github.com/bennu/packer/tree/esxi-remote-cache) I tested it and it works fine, this PR doesn't need any additional parameters,  it would be also great if @jozefizso could give it a test.

**Comment by kharnam** [comment]
Any progress here guys?

**Comment by bugbuilder** [comment]
Coud you try the PR and give few feedback??.
