### ISSUE TITLE
Feature Request: Disaggregation for CI/CD pipeline

### ISSUE THREAD

**Issue by BSick7** [hashicorp/packer#5223]
## Context

Currently, packer has a single command `build` that executes creation, configuration, provisioning, teardown, packaging, and publishing.

This is extremely valuable; however, I would like to submit future PRs to add additional commands to execute these individually.  I would like to ensure that it fits within the vision of packer before expending enormous effort.

## Proposal

- Keep `packer build` command.
- Add the following additional commands
  - `packer create`
  - `packer provision`
  - `packer destroy`
  - `packer post-process`

Obviously, this would require some maneuvering of existing architecture, but I would narrow it to function splitting.  In other words, taking the `Run` method and splitting across the separate commands.

## Benefits

I see the following benefits:
- Facilitate CI/CD pipeline visualization
  - build step
  - test step
  - package step
  - publish step
- Easier incorporation of testing
  - long-running functional tests
  - external integration tests
- Quicker diagnosis of errors
  - create step can take 10-15 minutes, potentially hours if downloading
  - quickly iterate on provisioners without going through entire process
  - quickly identify which phase an error occurs on CI server

**Comment by rickard-von-essen** [comment]
Some quick reflections on this...

- It will be _allot_ of work 💦 
- State needs to be keep externally
- Allot of testing is not actually good do in the build but should be done starting with the image as artifact.
- In general I dislike breaking up the first step _source-to-image_

**Comment by BSick7** [comment]
Thanks for the feedback!

> It will be allot of work 
My main reason for the proposal. :)

> State needs to be keep externally
I imagine a palatable solution exists assuming this idea appears valuable to the community.

> Allot of testing is not actually good do in the build but should be done starting with the image as artifact.
Running tests from a single immutable artifact would be ideal.
However, packaging, publishing, and reprovisioning is expensive (time mostly, but money too).
Timely feedback is sometimes more valuable than perfect feedback.
I see importance in running tests after provisioning *and* after exporting.

> In general I dislike breaking up the first step source-to-image
I'm not following this comment.  Can you elaborate?

**Comment by mwhooker** [comment]
You've mentioned a few problems you'd like to solve with this feature, and I'd like to address the problems directly rather than jump to a solution. I think the problems you mentioned deserve some attention, but I don't know that we'd want to break `packer build` into sub-steps.

> Facilitate CI/CD pipeline visualization

I would prefer to solve this with better logging. I feel like right now you should be able to tell from the logs what "sub step" we're in, but if not I would accept a PR that logged something like "starting provisioners", etc.

> Quicker diagnosis of errors

I think this is a fair thing to want to solve. I don't think adding "sub step" commands is the right way to solve it. This is a big change and it's outside of packer's core mission, so we probably would not accept a PR for it.

One thing I think might be fair is to add something like a `-continue` flag. Packer could store its state information to a file that it deletes at the end of the build. If the build fails it could leave the state file around. `-continue` would read the state file and start from where it failed. It would need to work in concert with `-on-error=abort`, which will leave all the resources it created up.

This is still a lot of work, and it may not be applicable to future versions of packer (i.e. we might need to remove it during any major code refactoring).

If this sounds like something you are interested in doing, I would create an `RFC` issue which goes into detail about how it would be implemented. We could weigh in on it and give it a better chance of being merged before you start work.

Thanks!
