### ISSUE TITLE
Packer fails at AWS register instance step

### ISSUE THREAD

**Issue by patrickqbis** [hashicorp/packer#5231]
Packer Version: 1.0.3
Host Platform: Running packer on OS X 10.12.6 trying to create an Ubuntu 16.04 instance

I am attempting to create an an instance-backed AMI. Packer runs to the point of registering the AMI then fails with:
Error registering AMI: InvalidManifest: HTTP 403 (Forbidden) response for URL http://s3.amazonaws.com:80/qbis-oc-techops/amis//image-1502303560.manifest.xml

For debugging purposes I also tried giving world list/read to the bucket (but since it is able to write to the bucket successfully that didn't seem like it would be the problem) and that resulted in a 404 error. 

Build output and relevant configs are in the gist:
https://gist.github.com/patrickqbis/38b6b0c5bbb4860fe4a0dc86f75667d1

**Comment by mwhooker** [comment]
thanks for the report. The issue is that your `s3_bucket` is incorrect. It should be the name of a bucket, not a path. If you'd like to change the path the manifest gets uploaded to, you can override the bundle upload command: https://www.packer.io/docs/builders/amazon-instance.html#bundle-upload-command

Hope this helps. If you need more help, the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) is a good place to go
