### ISSUE TITLE
Link to download latest version

### ISSUE THREAD

**Issue by kBite** [hashicorp/packer#5265]
In #134 @SwampDragons suggested opening a new issue for this request:

Please provide a link for downloading latest packer version.

I propose `https://releases.hashicorp.com/packer/latest/packer_latest_<os>_<arch>.zip` (e.g. `https://releases.hashicorp.com/packer/latest/packer_latest_linux_amd64.zip`)

As a workaround, mitchellh posted http://dl.bintray.com/mitchellh/packer (2013), but the link has died. To automate downloading of latest version one could parse https://releases.hashicorp.com/packer/, but a dynamic link would be a better.

**Comment by mwhooker** [comment]
Hi @kBite,

thanks for opening this issue. @sethvargo, who manages our release service has weighed in on this very thing here https://github.com/hashicorp/terraform/issues/9803

To summarize, we try to discourage this behavior because we believe it will lead to a bad experience in the general case.

Seth has some good pointers if you wanted to implement this behavior yourself.

**Comment by kBite** [comment]
Hey @mwhooker,

thanks for the link. I've read sethvargos post and get why this isn't implemented for any HashiCorp tool. Given this question was asked quite often, maybe there should be a link at the tools' download pages to this post or some other post.

**Comment by yar05** [comment]
Have a look at this small script, will download latest packer or terraform depending of your system architecture. 

https://github.com/yar05/hashicorp-latest-bin

curl -s https://raw.githubusercontent.com/yar05/hashicorp-latest-bin/master/get-latest-bin.sh | sh /dev/stdin -p packer

curl -s https://raw.githubusercontent.com/yar05/hashicorp-latest-bin/master/get-latest-bin.sh | sh /dev/stdin -p terraform
