### ISSUE TITLE
Support for native Docker on Windows 2016

### ISSUE THREAD

**Issue by martijnvandongen** [hashicorp/packer#5280]
It seems the current Docker Builder doesn't support native Docker on Windows 2016. Note the version numbers in the code snippet below. 

```
PS> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```
I ran into the following issue with the volume mounting of Packer. To mount a volume in a Docker container based on Windows, you need the following syntax: `-v C:\Directory:C:\ContainerDirectory`, while Packer uses: `-v /c/Users/Administrator:/packer-files`. It probably should generate and use something like `-v C:/Users/Administrator:/C:/packer-files`. 

```json
{
  "builders": [
    {
      "type": "docker",
      "image": "microsoft/nanoserver",
      "commit": true
    }
  ]
}
```

```
==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: microsoft/nanoserver
    docker: Using default tag: latest
    docker: latest: Pulling from microsoft/nanoserver
    docker: Digest: sha256:0ac4b5bb8e23c5145fdae8b6a19e8b2456816d7b23b208a45e2471468cbae743
    docker: Status: Image is up to date for microsoft/nanoserver:latest
==> docker: Starting docker container...
    docker: Run command: docker run -v /c/Users/Administrator/AppData/Roaming/packer.d/tmp/packer-docker656794967:/packer-files -d -i -t microsoft/nanoserver /bin/bash
==> docker: Error running container: Docker exited with a non-zero exit status.
==> docker: Stderr: docker: Error response from daemon: invalid bind mount spec "/c/Users/Administrator/AppData/Roaming/packer.d/tmp/packer-docker656794967:/packer-files": invalid volume specification: '\c\Users\Administrator\AppData\Roaming\packer.d\tmp\packer-docker656794967:\packer-files'.
==> docker: See 'docker run --help'.
==> docker:
Build 'docker' errored: Error running container: Docker exited with a non-zero exit status.
Stderr: docker: Error response from daemon: invalid bind mount spec "/c/Users/Administrator/AppData/Roaming/packer.d/tmp
/packer-docker656794967:/packer-files": invalid volume specification: '\c\Users\Administrator\AppData\Roaming\packer.d\t
mp\packer-docker656794967:\packer-files'.
See 'docker run --help'.
```

**Comment by lfarnell** [comment]
It seems like this is intentional due to the fact that the Docker driver really only supports "
Docker Toolbox" and not "Docker for Windows" for Windows builds. The reason you get that command syntax is because that's how Docker Toolbox works. The code replaces "C:/" with "/c/". The driver would need to be enhanced to support Docker for Windows. I know that #4186 is in the works but I'm not sure if even using the API would solve this explicitly as volume support hasn't been completed yet on that PR.

**Comment by mwhooker** [comment]
I can't be sure since I did this research a while ago: https://github.com/hashicorp/packer/issues/3734#issuecomment-289595544

but I believe docker on windows works with "docker for windows" but not the toolbox or native docker. The ecosystem is a bit of a mess, and the docker builder was written before there was great support for docker on windows.

You're definitely right that we need to spend more time getting docker to work on windows

**Comment by slime-uk** [comment]
This is quite old I know, but probably worth saying.

As a workaround try...

1 - set the env var as follows 
```
set PACKER_TMP_DIR=c:\tmp
```

2 - Add a container folder into your JSON packer template
```
"container_dir": "c:/app"
```
Here's a full example:
```
{
	"builders": [
		{
			"type": "docker",
			"image": "microsoft/windowsservercore:1709",
			"container_dir": "c:/app",
			"run_command": ["-d", "-i", "-t", "-p", "5986:5986", "-e powershell", "{{.Image}}"],
			"export_path": "image.zip",
		}
	]
}
```

Those paths aren't set in stone but doing that allows the docker builder to progress - at least until the next issue (which for me is getting any provisioners to work).
