### ISSUE TITLE
Allow PKR_VAR_name to set variables

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/packer#5312]
Similar to how Terraform handles environment variables it would be really handy to have Packer detect environment variables with a prefix like 'PKR_VAR_'.

The variables would still need to be defined in 'variables' block of the template but this would save creating JSON files on the fly and passing them in as '-var-file', or having really long lists of '-var' params.

**Comment by rickard-von-essen** [comment]
Can you explain why that would be any different from:

```json
{
  "variables": {
    "var1": "{{env `PKG_VAR_var1`}}"
  }
}
```

**Comment by tristanmorgan** [comment]
It's a subtle difference but if the environment variable wasn't set it would allow falling back to a default value like in 

`{
  "variables": {
    "var1": "default_value"
  }
}`

**Comment by tristanmorgan** [comment]
Mainly its a convenience thing, could use envconsul to set the variables in a CI system, a dev could have overrides to the default in a script. For Terraform of all the methods I find the TF_VAR_ system the most useful and though it could be a simple addition to Packer to make all the tools play nicer together. Next up would be HCL formatted templates and common plugins for provisioners.

**Comment by mwhooker** [comment]
This sounds reasonable, but is not something we're planning to accomplish right now. We will be revisiting the configuration format in the future, hopefully with an eye toward HCL, and we might get this for free. I've tagged this with a label to help us keep track of config enhancements, but closing for now since we're not going to be working on it. Thanks!
