### ISSUE TITLE
Can't build against Cloudstack 4.8 using Packer 1.0.3+

### ISSUE THREAD

**Issue by IanTheIan** [hashicorp/packer#5328]
Strangely, since Packer 1.0.3, I'm unable to use Packer to create instances against my Cloudstack 
4.8 cluster...

Packer version: 1.0.3+
Host Platform:  Mac OSX AND RHEL 6 (tested Packer versions on both)

The config and the crash dump can be found in at the following gist:
https://gist.github.com/IanTheIan/a916b8e0bd4bf83cfbd73da9d206c8e9

What's odd is that this only started to happen AFTER the 1.0.3 release, which we need because we want the Cloudstack Expunge support.  But the 1.0.3 release (while supporting Expunge) broke regular builds, and 1.0.4 doesn't seem to work for us either, even with an identical (Expunge setting notwithstanding) config being used...

Any ideas?

**Comment by mwhooker** [comment]
Thanks for the report. I'm sorry this stopped working for you. It looks like this may have been introduced in https://github.com/hashicorp/packer/pull/5130

Let me see if I can come up with a patch. Would you be able to test something for me?

**Comment by mwhooker** [comment]
@IanTheIan I see the issue. It appears to have been fixed in https://github.com/hashicorp/packer/pull/5174, which should be going out in packer 1.1.0 in the next couple of days. If you'd like to test on master, that would give us some confidence that this has been fixed, otherwise feel free to open a new issue once 1.1.0 has been released. Going to close since I believe it's been fixed.

**Comment by IanTheIan** [comment]
Much appreciated.  I'll test with off master and let you know the results.

**Comment by IanTheIan** [comment]
Works perfectly.  Matt - I wholeheartedly thank you very much.
