### ISSUE TITLE
lxd: Add description, aliases, etc

### ISSUE THREAD

**Issue by jfgibbins** [hashicorp/packer#5349]
When you can, please add in parameters for the builder, such that when it gets to the publish stage, metadata, such as description, aliases, , etc will be made part of the image and show up during lxc image list.

If possible, it would also be nice, when creating an image, if a prior image of the same name exists, if the old one is not being used, then to go ahead and delete it.  Maybe as an option under the builder, such as "replace: true".  Help keep the image list clean when testing new builds.

**Comment by ChrisLundquist** [comment]
@jfgibbins You had a lot of asks here:
To recap them:
- arbitrary metadata file?
- publish properties
- auto deletion of old builds

Re arbitrary metadata files. When I wrote this builder way back when, there was virtually no documentation on the metadata file format.

I took the "repackage another image" approach to work around this, thinking that you could craft a base image as you needed, then repackage that. (https://stgraber.org/2016/03/30/lxd-2-0-image-management-512/ This blog series was the state of the art and was actively being published)

I guess my questions are:
- Is there a better documentation on metadata files now for the split image format?
- What is the use case for the metadata file? I know it is *needed* because at one point I tried to import .tar.gzs from docker / debootstrap and it failed miserably. In either case though, I can't think of a time I needed to munge a metadata file.

**Comment by jfgibbins** [comment]
For this particular case, I'm not referring to the metadata.yaml file, but rather the metadata that is viewed when doing lxc image list and changed with lxc image edit xxx.  description, alias, etc are set when you publish an image. Example

| xenial-puppet | ffc24c0e4bb5 | no     | Ubuntu 16.04 LTS Xenial Xerus w/Puppet | x86_64 | 226.80MB | Sep 17, 2017 at 3:43am (UTC) |

As for the deletion, when packing a new image, if a prior image with the same metadata is being created, to go ahead and delete the previous one, which will differ only by fingerprint, if it's not being used.  Useful, when testing packer and images, and generating multiple duplicate images.

However, as you said, the metadata.yaml info wasn't well documented when you first started.  It is much better now.  But easy method to learn and modify is just to use "lxc config metadata edit <container>" and "lxc config template edit <container>"

**Comment by ChrisLundquist** [comment]
Cool, my linked PR will let you set those things. I called them publish
properties for lack of a better term

**Comment by mwhooker** [comment]
Closing this as we merged in #5475

please open a new issue if you're looking for something else.
