### ISSUE TITLE
docs: Clearly document built in template variables 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#5382]
The docs doesn't clearly enumerate the builtin template variables  such as `{{ .Name }}` (and possibly some more).

**Comment by rickard-von-essen** [comment]
See https://stackoverflow.com/questions/46393734/what-is-the-value-of-name-in-a-packer-template

**Comment by brianeclow** [comment]
It would be grand to have this documentation. Especially, as I am attempting to find a suitable replacement for the previous template variable `.Provider`.

**Comment by vfiftyfive** [comment]
This would be very useful indeed. Any taker?

**Comment by evancox10** [comment]
Does the templating engine also support conditional logic as shown [here](https://golang.org/pkg/text/template/)? If so, that would also be good to document. (Or at least reference that page, possibly with a few packer-specific examples.)

**Comment by Mr-Nietzsche** [comment]
unsubscribe    On Sunday, May 6, 2018, 12:44:25 PM MDT, Evan Cox <notifications@github.com> wrote:  
 
 
Does the templating engine also support conditional logic as shown here? If so, that would also be good to document. (Or at least reference that page, possibly with a few packer-specific examples.)

**Comment by SwampDragons** [comment]
@Mr-Nietzsche I'm pretty sure to unsubscribe from a github issue you have to do so via the unsubscribe button in the issue UI.

@evancox10 Yes, you can use that conditional logic and it's a good idea to document it somewhere.  I know the puppet docs have some examples because the defaults contain some of this kind of logic: https://www.packer.io/docs/provisioners/puppet-masterless.html but we could probably link these docs in our general discussion of how the template engine works.

**Comment by noshky** [comment]
Why has this been closed? The ``{{ .Name }}`` built-in variable is still not mentioned in the docs.

**Comment by rickard-von-essen** [comment]
@noshky this isn't closed..?
