### ISSUE TITLE
Ansible provisioner should not clean up until after -on-error=ask

### ISSUE THREAD

**Issue by pjnagel** [hashicorp/packer#5419]
When running a packer build with -on-error=ask, and when using the ansible provisioner, and the ansible build fails, the container is left running while packer waits for you to answer the -on-error prompt. This gives one an opportunity to debug the failed build before cleanup happens.

The obvious way to debug the issue is to re-run the ansible command that the provisioner ran (maybe after making some changes to the playbooks). Unfortunately this does not work, for a few reasons:

1. The ansible provisioner creates a temporary inventory file, which one can see on the command-line as a parameter like "-i /tmp/packer-provisioner-ansible981180270". But this temporary file is deleted, even before one answers the -on-error prompt.

2. Even if one preservers the contents of the temporary inventory file, one still can not re-run the ansible command. The temporary forwarded port used by the SSH communicator to communicate with the virtualbox guest is also deleted at this point.

Both of the above resources should only be cleaned up after one answered 'clean up' to the -on-error prompt. 

(A related cosmetic issue has already been reported as issue #5412 : the ansible command line that the provisioner prints has no shell escaping, and thus can not be executed via straight copy & paste).

**Comment by pjnagel** [comment]
The same problem may also exist with the temporary private key file that is created and passed to the ansible command line in a form like "--private-key /tmp/ansible-key241878411"

**Comment by pjnagel** [comment]
Actually, the root cause of this bug report is that answering "retry" to the on-error prompt  does not work.

When using a virtualbox-ovf builder and an ansible provisioner with an ssh communicator, and when answering retry to the prompt, I ansible prints the error message:

fatal: [container.lautus.net]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}

It is entirely possible that the underlying reason for this failure is exactly the same as I reported above.

**Comment by pmarques** [comment]
@pjnagel having the same problem, but I notice that when I retry the ids changed

`packer-provisioner-ansible619986831` (First execution )
**VS**
`packer-provisioner-ansible268870297` (on retry)

**Comment by mwhooker** [comment]
Unfortunately, due to some very fundamental design decisions, we're unable to support this behavior. Provisioners don't know the difference between doing work and cleaning themselves up, like the builders do. We can't try to do work and pause if it fails before cleaning up.

I know the `-on-error` documentation is lacking, but it's really only for debugging builders. This is on our mind as we look to the future with packer. We'll be trying to make the behavior between builders and provisioners more consistent, so surprises like this won't happen.

Ansible would need to do some work to support retrying, since I'm sure it wasn't written with the thought that it could be re-run. We're also trying to figure out how we could support this natively.

**Comment by MyNameIsCosmo** [comment]
Is there any update to this?

**Comment by rickard-von-essen** [comment]
As @mwhooker writes above, this won't be fixed. This is only kept open since we should clarify the current behavior in the docs.

**Comment by AndrewSav** [comment]
@rickard-von-essen Uhm ". We'll be trying to make the behavior between builders and provisioners more consistent, so surprises like this won't happen."  and "We're also trying to figure out how we could support this natively." does not read like "won't be fixed".

Could you clarify?

**Comment by rickard-von-essen** [comment]
This is the important part:

> Unfortunately, due to some very fundamental design decisions, we're unable to support this behavior. Provisioners don't know the difference between doing work and cleaning themselves up, like the builders do. We can't try to do work and pause if it fails before cleaning up.

> This is on our mind as we look to the future with packer.

Should be read as in some distant version Packer (2.0, 3.0 or later) we would like to change this to support this.

**Comment by tmmruk** [comment]
+1 for this functionality

**Comment by SwampDragons** [comment]
This should be fixed by the two options added in #8625 -- `"use_proxy":false` combined with `"keep_inventory_file": true` Note that the inventory file will remain in your temp directory if you set keep_inventory_file:true; this Pr doesn't create a cleanup step, it just makes the provisioner not cleanup so that you can debug. Hopefully, since the file is in a tempdir, it's not a big deal that it sticks around for the user to manually clean.
