### ISSUE TITLE
Run Puppet Masterless provisioner as elevated user on Windows

### ISSUE THREAD

**Issue by lfarnell** [hashicorp/packer#5478]
When using the Puppet Masterless on Windows it fails when trying to install SQL Server as it needs administrative privileges. I always thought that cmd commands would execute in an elevated command prompt? Is this not the case? At least on Windows, installations for a good amount of tools do require administrative rights and this would prohibit that.

The work around for now is to execute Puppet from a elevated powershell script.

- Packer version: 1.1.0
- Windows 7 / Ubuntu 16.04

**Comment by SwampDragons** [comment]
You're right -- we allow the user to toggle whether or not to use sudo on unix systems, but we don't have anything similar built into the puppet provisioner for running in windows with elevated permissions.  I'm glad you have a workaround.  

I'd welcome a PR fixing this; a good solution will probably have to involve abstracting away some of the elevated stuff that is currently solely in the powershell provisioner and then using that generalized code for both provisioners so that we don't have hundreds of lines of copypasta to maintain.

**Comment by bodgit** [comment]
I've run into this same issue, trying to refactor some Windows Packer builds to use the built-in `puppet-server` provisioner like on Linux instead of maintaining a handful of powershell-based scripts. In my ignorance I forgot that on Windows the Administrator user is not always equivalent to root on Linux.

What what would need to be exposed here? Would something similar to the `powershell` provisioner with its `"elevated_user": "Administrator"` and `"elevated_password": "{{.WinRMPassword}}"` work?

**Comment by SwampDragons** [comment]
yeah, I think using that same pattern would make sense.

**Comment by bodgit** [comment]
I think github possibly mis-parsed my/a comment and closed this by accident.

**Comment by azr** [comment]
This was closed by merging #6972, because there was the keyword `fix #5478`
