### ISSUE TITLE
Allow Puppet/Chef standalone provisioners to use remote files instead of uploading local

### ISSUE THREAD

**Issue by lfarnell** [hashicorp/packer#5479]
When using the Puppet Masterless you provide the directories on the local system to upload to the machine in order to start the puppet run. On Linux based systems the default upload mechanisms will be scp over ssh which is incredibly fast. For Windows the default upload mechanism is done via winrm which is incredibly slow. Takes over 2 hours to upload around 4 mb's of files on my current system. I wanted to start on a discussion to possibly support the ability to supply directories present on the machine instead of uploading. I know this isn't a Packer problem per say due to the WinRM dependency but I believe this would make sense. Any thoughts on this approach?

This would also be applicable to the Chef solo provisioner as well.

The work around for now is to execute Puppet from a elevated powershell script and use something like git to clone a repo to the machine using the shell provisioner ahead of the Puppet run.

- Packer version: 1.1.0
- Windows 7 / Ubuntu 16.04

**Comment by mwhooker** [comment]
sorry I'm ignorant about puppet, but can you not just set the working directory to some directory already containing puppet files, and have your manifest just reference them? If not, that seems like a workflow we should support.

As an aside, when it comes to windows, I recommend setting up an SSH server and using the ssh communicator directly. You can see how some of our community boxes do that. 

https://www.packer.io/community-tools.html#templates

**Comment by cheeseplus** [comment]
I do think this is already tacitly supported and the workaround mentioned is exactly how it's done. Packer can't know what to use for remote_file grabbing so that's something you'd do in a script provisioner prior and then feed those value a la https://www.packer.io/docs/provisioners/chef-solo.html#chef-configuration.

That is to say, I think this workflow is entirely supported but Packer can't and shouldn't do much more here. We work around this with the Chef provisioner as mentioned but i don't think there is anything Packer can do reasonably here to further support that.

**Comment by nywilken** [comment]
Hi there :wave”, I'm going to close this issue since it appears that there is no work for us to do here. But if you are still running into issues please feel free to leave a comment on the issue and we will gladly reopen.

Please note that the puppet provisioner is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
