### ISSUE TITLE
build -force does not overwrite managed image in ARM

### ISSUE THREAD

**Issue by choppedpork** [hashicorp/packer#5509]
Packer 1.1.1 does not seem to be able to overwrite AzureRM managed images using the `-force` flag to `build`:

```
$ packer version
Packer v1.1.1
$ packer build -force build-azure-ansible.json
azure-arm output will be in this color.

==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: A managed image named base-test already exists in the resource group test.

==> Some builds didn't complete successfully and had errors:
--> azure-arm: A managed image named base-test already exists in the resource group test.

==> Builds finished but no artifacts were created.
```

This looks like the same issue as #2993 but for a different provider (#2993 dealt with GCE and AWS).

**Comment by zanecodes** [comment]
+1, this is a big problem for our workflow since we will have to deploy our VMs directly from the images Packer produces (because managed images can't be copied, moved or renamed in Azure). This issue forces us to delete the images before each Packer run, which means we can't provision any VMs during the Packer run, and if the run fails we're left without an image at all and can't deploy.
