### ISSUE TITLE
AWS Builder is not using Region from Profile when running on EC2 instance

### ISSUE THREAD

**Issue by mini-sledge** [hashicorp/packer#5558]
The packer code for the AWS builder is using the region from the EC2 instance, instead of using region from the profile (~/.aws/config).

Use case is a Jenkins server running on an EC2 in us-east-1, creating an AMI for us-west-2.  The packer code has the argument for profile.  The same packer file is used by developers to test in us-east-1 and/or  us-west-2.

The same packer code runs on a VM (also linux) locally on my Windows machine and correctly reads the region from the profile (because the ec2 metadata command fails).

Packer version: 1.1.1
Host Platform: AWS base 64 Linux

Packer.json file:
https://gist.github.com/mini-sledge/c6d6360c1eac051a0e628a32f2baeb3f

The AWS CLI is setup correctly, and is able to run commands like aws ec2 describe-instances --profile=the_various_profile_names_here and produce the desired results.

~/.aws/config:
[default]
region = us-east-1

[profile dev-virginia]
region = us-east-1
role_arn = arn:aws:iam::$ACCOUNT_NUM:role/$ROLE_NAME
source_profile = default

[profile dev-oregon]
region = us-west-2
role_arn = arn:aws:iam::$ACCOUNT_NUM:role/$ROLE_NAME
source_profile = default

Command I ran the file with:
packer build --var 'aws_profile=dev-oregon' packer.json

And the output:
https://gist.github.com/mini-sledge/f401bd01be475cd72d8cff421037e6e8

The above creates the AMI in the us-east-1 region since that's where the EC2 box I was using to run packer is located.  If I run the same exact code above on my local, it will create the AMI in us-west-2.

I have a potential fix, but wanted to put this out here before submitting it, as there may be more elegant solutions than I have found.

**Comment by rickard-von-essen** [comment]
It shouldn't use settings from profile if you use a EC2 instance role.

**Comment by rickard-von-essen** [comment]
This might be related to #5524.

**Comment by mini-sledge** [comment]
A potential fix would be to return from the region function before attempting to grab the region from the ec2 metadata if the profilename is set.  There may be a more elegant solution for it, but wanted to float the potential fix that I could submit for PR.

**Comment by mwhooker** [comment]
don't think we can do that because the profile might not have a region. We should be preferring to use the SDKs credential chaining where possible. I haven't looked for the issue yet, but I have a pretty good idea that we're not doing that

**Comment by mini-sledge** [comment]
Region is currently required in the profile according to the AWS CLI commands I just used to test.

**Comment by mwhooker** [comment]
oh yeah? That's a good data point. I see that here http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

I'm thinking maybe it's not correct to get the region from the metadata service. The correct solution might be to always require it. Either that or your solution would probably work.

I'm a little hesitant to add logic like "don't look up region if we've passed a profile" since it smells edge-casey. I'd much rather be explicit and require a region be set.

**Comment by mini-sledge** [comment]
Suddenly requiring region would probably break a lot of people's current packer scripts (including all the ones here).

Depends on people's current implementations, but definitely won't be backwards compatible.

**Comment by mwhooker** [comment]
yeah, that's the problem. Technically, since the documentation says it's required, it would be a backwards incompatible bug fix, which we're okay with releasing on minor releases, but it's not critical so I don't think we should do it.

I think what we should do is take your suggestion now, since it's backwards compatible, and then for 1.2.0 we can require region (if we still think it's a good idea).

I saw you wanted to take a swing at making a PR. Want to write something up, test it, and then we can merge?
