### ISSUE TITLE
`azure-arm` builder "fails" to find your desired resource group when your service principal credentials are incorrect

### ISSUE THREAD

**Issue by carlosonunez** [hashicorp/packer#5610]
Summary
=======

**Given** an `azure-arm` builder and a Packer template consumer,
**When** I run `packer build` but provide an invalid `client_id`/`client_secret` pair,
**Then** `azure-arm` tells me that it cannot find the resource group instead of telling me that my credentials are incorrect.

Bug Details
========

- **Packer version from `packer version`**:  1.1.2
- **Host platform**: Alpine 3.6.2
- **Debug log output and template**: https://gist.github.com/carlosonunez/3627fed4fba82cd9f97df858672f511d

Actual and expected output are included in the Gist sample above.
  
Additional Context
=============

This was verified by running Charles and dropping into packet contents. See [this](https://contino.slack.com/files/U5D038J2F/F8386KC66/troubleshooting_azure_arm_packer_builder.md) Gist for instructions, if needed.

**Comment by v6** [comment]
// , The following seems to be an example of this: 

https://stackoverflow.com/questions/47871191/packer-azure-arm-cannot-locate-the-managed-image-resource-group

**Comment by SwampDragons** [comment]
@boumenot does this seem like a packer bug to you or us just passing through a not-useful API error response?

**Comment by boumenot** [comment]
This is an Azure builder bug.

**Comment by v6** [comment]
// , There is a long, and ever increasing list of error messages from Azure, of _varying_ helpfulness, that Packer doesn't even parse. 

Azure RM API lookup failure errors have the ambiguity of possibly referring to a permissions issue, rather than a missing resource. 

But the problems with Packer's error message happen before any successful authentication into Azure in the first place. 

Packer's error message adds icing on the ambiguity cake, by implying this:

_authentication_ was successful, but resource lookup was not

In reality, authentication was unsuccessful, and the error had nothing to do with any resources.

**Comment by SwampDragons** [comment]
Cool, thanks for the context.

**Comment by azr** [comment]
Howdy @paulmey, do you know of a way to check wether packer is correctly authenticated before going though ? This would be a great UX benefit for packer-azure beginners. 
I can probably help ! 🙂

**Comment by paulmey** [comment]
Hmm, yes, I agree that would be so much better.
For most, including the ClientId/Secret token provider, the actual authentication is done when the [ADAL framework](https://github.com/Azure/go-autorest/tree/master/autorest/adal) [detects that the token is either not there or expired](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L722). Typically, this will happen the first time a token is used. The ['unauthorized' error](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L850) is burried in the response error object from that call. I'm not sure that it is easy to peel that out.
I did notice that [we do call](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/clientconfig.go#L205) `EnsureFresh` for all token types now [fairly early in the builder Run()](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/builder.go#L75). I wonder if this might just be fixed already now, since I refactored the Azure client setup code earlier this year.

**Comment by azr** [comment]
Yup, all fixed now !

I remember having a weird 'wrong group' error in a centos azure vm last week which was fixed regenerating credentials & this is why I commented here;
I just double checked now and it turns out the credentials were just old ones and the error was correct.

I tested again and :

* No credentials at all, it failed very early with :
> Build 'azure-arm' errored: adal: Failed to execute the refresh request. Error = 'Get http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F: dial tcp 169.254.169.254:80: i/o timeout'

* Wrong secret, it also failed very early with :
> Build 'azure-arm' errored: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.

I think this issue can be closed. Thanks !!!
