### ISSUE TITLE
AWS AMI copying to region of build now fails

### ISSUE THREAD

**Issue by manicai** [hashicorp/packer#5625]
On AWS https://github.com/hashicorp/packer/pull/5562 appears to have changed the semantics of the `ami-region` field.

We specify the builder as:

```
[{
    "type"                      : "amazon-ebs",
    "region"                    : "eu-west-1",
    "source_ami"                : "{{user `base_ami`}}",
    "instance_type"             : "t2.micro",
    "ami_name"                  : "Proxy",
    "ami_virtualization_type"   : "hvm",
    "ami_regions"               : ["eu-central-1", "eu-west-1", "eu-west-2", "us-east-1"]
}],
```

This worked in Packer 1.0.0 but fails in in Packer 1.1.2 with the error

"Cannot copy AMI to AWS session region 'eu-west-1', please remove it from `ami_regions`"

Previously the copy to the same region as the one specified by `region` was a no-op.

The same behaviour occurs in the `amazon-instance` builder.

Was this intentional? It is convenient to have the same region in `region` and `ami_regions` as it allows us to change the region being used for the build easily.

**Comment by SwampDragons** [comment]
@mwhooker what do you think about this one?  I believe the linked issue was yours.

**Comment by jobwat** [comment]
Same here!

And it's newliy introduce from that version:
- 1.1.1 was still working
- 1.1.2 is definitely failing

**Comment by SwampDragons** [comment]
Wondering if this would be as simple as changing the logic here https://github.com/hashicorp/packer/blob/master/builder/amazon/common/ami_config.go#L48-L51 to just axe the extra region from c.AMIRegions instead of throwing an error.  Might also need to do some manipulation of the kms_key_ids map.

**Comment by mwhooker** [comment]
ahh, thanks for the report. We didn't expect that the source region would be in the ami_regions field. Is it possible to just remove the source image from the ami_regions field? We tend to prefer it the way it is now, since it's explicit what's happening.

If there's a good reason, we can see about implicitly ignoring it, but our preference would definitely be to fix the user scripts

**Comment by SwampDragons** [comment]
the OP commented that removing it from the ami_regions field adds some work for them.  I made a PR that would address this, if we don't mind it being implicit. 
 I don't believe that having this particular fix be implicit is a bad thing, since all regions in ami_regions will still have an ami at the end of the build. 
 https://github.com/hashicorp/packer/pull/5660

**Comment by manicai** [comment]
Thanks.

Bit more detail about why we like having the region repeated. We build 99% of our images in `eu-west-1`. However we have to use the specialist instances types (GPGPU ones) for some AMIs and can have issues with those instances not being available within the region. At that point we switch regions used for the build (we haven't found a region we can use that will reliably get the instance types). Having the region repeated in both places reduces the chances of manual misconfiguration in these cases. 

That said, instance unavailability seems to be becoming an increasing rare occurrence so if having the region in both lists is a problem then it's not going be that inconvenient. I mainly wasn't sure if the change was deliberate/preferred or a regression.
