### ISSUE TITLE
add validation for virtualb-iso with vsphere-postprocessor

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#5636]
It would be nice to know beforehand that running a post-processor vsphere is not compatible with virtualbox-iso builder type. 

```
==> virtualbox-iso: Running post-processor: vsphere
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.virtualbox

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.virtualbox

==> Builds finished but no artifacts were created.
```

**Comment by SwampDragons** [comment]
Thanks for reporting -- sounds like this needs to be fixed in validation so that the build can fail early, and clearly.

**Comment by sylviamoss** [comment]
I'm closing this issue because https://github.com/hashicorp/packer/pull/8064/files removes the check that fails the vsphere post-processor when used with virtualbox builder.
The post-processor validates the type of file instead and it should work for any file of any of the valid types. See the validation code [here](https://github.com/hashicorp/packer/blob/master/post-processor/vsphere/post-processor.go#L121)
