### ISSUE TITLE
[Feature Request] Add a source_ami variable for AWS builder

### ISSUE THREAD

**Issue by Erouan50** [hashicorp/packer#5667]
Add a new variable named source_ami which content the result of the source_ami_filter of the aws builder.

**Use case:**
We are currently using the source AMI filter to get the latest AMI available on AWS, and we would like to put the AMI source as a tag on the new AMI. It will allow us to create a scheduled job to check if our AMIs are up to date.

**Example:**
The result might look like this:
``` json
"source_ami_filter": {
    "filters": {
        "virtualization-type": "hvm",
        "name": "*CentOS Linux 7 x86_64 HVM EBS*",
        "root-device-type": "ebs"
    },
    "owners": ["679593333241"],
    "most_recent": true
},
"tags": {
  "ami_source": "{{amazon-ebs `source_ami`}}",
  "ami_source_named_builder": "{{my_builder `source_ami`}}",
}
```
I'm aware that change might be difficult to do, but do you think if one day you will implement this feature?

**Comment by SwampDragons** [comment]
My gut instinct is no, since this would require a big change to when we get that information.  

Currently, when you set the filter we determine the ami name from _inside_ the builder, which makes it impossible to set before the builder runs during the template-parsing stage. 

I know it's hacky, but you could probably work around this by running a sham build, getting the ami id out of the logs (the log line looks like `amazon-ebs: Found Image ID: ami-aa2ea6d0`), and set the id as an env variable; you can then bring that env variable into the template for your "real" build for use when setting the tags.  In order not to rack up extra artifacts, you can use the `force_deregister` and `force_delete_snapshot` options

**Comment by Erouan50** [comment]
Make sense, thanks for your answer. I'll try your hack.

**Comment by SNikalaichyk** [comment]
This functionality is already there. Try the following:
```
"tags": {
	"source-ami": "{{ .SourceAMI }}"
}
```

**Comment by Erouan50** [comment]
It works perfectly thank you @SNikalaichyk, but it's not in the documentation? Or I didn't find it.

**Comment by SNikalaichyk** [comment]
@Erouan50,
The `SourceAMI` variable is mentioned several times on the following page:
https://www.packer.io/docs/builders/amazon-instance.html

**Comment by campanellaf** [comment]
Should I be able to use that variable to seet the name of the new AMI as follows?
`"ami_name": "My-{{ .SourceAMIName }}-Encrypted",`

I get the following when I try the above:

> * AMIName should only contain alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_). You can use the `clean_ami_name` template filter to automatically clean your ami name.

**Comment by rickard-von-essen** [comment]
@campanellaf No `.SourceAMIName` can only be used in `ami_description` and the different `tags` options.
