### ISSUE TITLE
* Post-processor failed: unexpected EOF

### ISSUE THREAD

**Issue by jamiesonbc** [hashicorp/packer#5675]
was having this problem on 0.8.6 and had a memory prob, upgraded to 1.1.2  and still getting error but no memory error.  Can you take a quick look at the log in the gist.  I included the script and also the template.json

https://gist.github.com/jamiesonbc/7ecef07c2cf97c1cec7b3ac130beb10f

**Comment by SwampDragons** [comment]
Hmm.  Looks like it got hung up for over an hour on the vsphere post-processor here: 
```
2017/12/06 17:12:15 ui: [0;32m    sod-rhel-7-9bcc003c-201712061651 (vsphere): Uploading output/build-sod-rhel-7-9bcc003c-201712061651/packer-sod-rhel-7-9bcc003c-201712061651.vmx to vSphere[0m
2017/12/06 17:12:15 packer_1.1.2: 2017/12/06 17:12:15 Starting ovftool with parameters: --acceptAllEulas --name=sod-rhel_7-9bcc003c-201712061651-aprag05-atc-zone_a --datastore=APRAG05_NTNX_AP --noSSLVerify=true --diskMode=thin --vmFolder=ServerOnDemand/Templates --network=dvpg_ZA_Primary_VL2231_10.72.168.x-22 output/build-sod-rhel-7-9bcc003c-201712061651/packer-sod-rhel-7-9bcc003c-201712061651.vmx vi://amer%5C_svcServerCentral:<password>@waprsm030.amer.homedepot.com/ATC/host/APRAG05/Resources/CloudBolt_05A
2017/12/06 18:30:31 [INFO] (telemetry) ending vsphere
2
```
I know several versions ago there were issues with "unexpected EOF" occurring because we didn't have the vm_network set as a required variable, the command would hang, and packer would gobble memory until things crashed.  What happens if you manually run the ovftool command with the same parameters as set out in the log?  Does vsphere give you a more useful error? (see this comment for context: https://github.com/hashicorp/packer/issues/2595#issuecomment-153963793)

**Comment by jamiesonbc** [comment]
found the problem,   there was a newline in the pasword

**Comment by SwampDragons** [comment]
Glad you got it figured out!  Reach out if you have any other issues.  looks like you're getting close to a complete workflow :)
