### ISSUE TITLE
virtualbox-ovf - when source_path is URL -> VERR_TAR_UNEXPECTED_EOS

### ISSUE THREAD

**Issue by jcrben** [hashicorp/packer#5753]
Minimal reproduction repo at https://gitlab.com/jcrben-repro/packer-cache
Steps:
`packer build template.json` (wait for it to complete, should have no errors)
`packer build -force template.json`

This screenshot illustrates what I'm seeing:
![image](https://user-images.githubusercontent.com/5614134/34465676-44cab9b6-ee6c-11e7-8781-4268191f5a2e.png)

Describe the problem and include the following information:
* Virtualbox: Version 5.1.26 r117224 (Qt5.6.2)
* Packer - 1.1.3
* Host OS - 10.11.6 (15G1611)

**Comment by rickard-von-essen** [comment]
Your ovan file is only 1.2 MB which seems a bit to small.

**Comment by jcrben** [comment]
ovan file? do you mean ova? I'm probably missing something obvious, but it appears to be 808MB as I expect:

![image](https://user-images.githubusercontent.com/5614134/34471372-84efbfe2-eefc-11e7-96fa-18437841851d.png)

**Comment by rickard-von-essen** [comment]
Yeah, sorry it seems to work.

**Comment by pgroudas** [comment]
I've bumped into this as well with packer 1.2.2.

When running packer with `virtualbox-ovf` builder, if the `source_path` is a local file, I can repeatedly use packer, and it successfully imports the source .ova file repeatedly without modifying it.

When the `source_path` is a URL, it downloads the file, and runs successfully the first time, but somehow modifies the file in the cache so that on subsequent runs it fails.

**Comment by jcrben** [comment]
@pgroudas if you add a reaction it might be easier to sort as hitting more people

@rickard-von-essen I think you can remove the `awaiting-reply` here
