### ISSUE TITLE
builder/azure_rm change needed for add a way to share virtual machine images

### ISSUE THREAD

**Issue by EtienneDeneuve** [hashicorp/packer#5755]
# Problem:
When using Packer to build Azure Virtual Machine Images we can't copy to multiple subscriptions because Azure (Api Rest or other) doesn't let us copy directly the VM Image in or across subscription (only move to other resource groups). 
As Microsoft didn't plan something yet, we will need to do something for images sharing easily with Packer and Ansible. I'm working on an Open Source OS Factory [link](https://github.com/societe-generale/os-factory) (Feel free to fork and give us feedback). We use Ansible and Packer.

# Solutions :

We have two options :
1. "do not delete managed disk" (easier)
This way let us to use api to create snapshot with toolings (Cli or Ansible)
1. "create snapshot of managed disk before suppress" (harder)
This way is harder but cleaner. 

# Issue ?

I need a little help for contributing in the azure_rm builder, I'm not really Go fluent :) I already created a fork [link](https://github.com/EtienneDeneuve/packer) and I will commit my code even if it's not working yet. 

Happy new year !

**Comment by flemzord** [comment]
👍

**Comment by EtienneDeneuve** [comment]
@boumenot ,

Have you some time to help me to manage that feature ?

I'm trying to understand the builder and I think you are the best for that !

Etienne

**Comment by boumenot** [comment]
If you want to share images the correct way is to use a SAS URL.  There are two ways that I can think of to do that.

 1. Switch to VHD, and use a SAS URL to the VHD.
 1. Export the managed disk (check the API docs), get a SAS URL, and use that.

This issue has popped up a couple of times, but I have not implemented it yet.  I think the correct answer is to use a Packer post-processor instead of changing the flow of the existing builder.  I happy to review a post-processor, but I have not actually implemented one yet.  There are plenty of code samples in the repo to get you started, and the implementation does look that hard.

**Comment by EtienneDeneuve** [comment]
Hi @boumenot ,

I think the only choice is VHD way. We can't export the managed disk without changing stuff in the builder. 
When packer destroy the temp resources group, it delete the underlying managed disk so we can't create SAS Url as the following extract, blobUri is null and  : 
```Json
{
    "additionalProperties": {},
    "id": "/subscriptions/1417c648-cxcdd-ba8255b/resourceGroups/OSFACTORY/providers/Microsoft.Compute/images/Ubuntu_16_04_AMI_001-2017-12-20-09.55",
    "location": "westeurope",
    "name": "Ubuntu_16_04_AMI_001-2017-12-20-09.55",
    "provisioningState": "Succeeded",
    "resourceGroup": "OSFACTORY",
    "sourceVirtualMachine": {
      "additionalProperties": {},
      "id": "/subscriptions/1417c648xxxxa6fba8255b/resourceGroups/rg-temp-osf-66795961/providers/Microsoft.Compute/virtualMachines/vm-temp-osf-27717581",
      "resourceGroup": "rg-temp-osf-66795961"
    },
    "storageProfile": {
      "additionalProperties": {},
      "dataDisks": [],
      "osDisk": {
        "additionalProperties": {},
        "blobUri": null,
        "caching": "ReadWrite",
        "diskSizeGb": 30,
        "managedDisk": {
          "additionalProperties": {},
          "id": "/subscriptions/1417c648-xxxx-8255b/resourceGroups/rg-temp-osf-66795961/providers/Microsoft.Compute/disks/osdisk",
          "resourceGroup": "rg-temp-osf-66795961"
        },
        "osState": "Generalized",
        "osType": "Linux",
        "snapshot": null,
        "storageAccountType": "Standard_LRS"
      }
    },
    "tags": {
      "Name": "Ubuntu_16_04_AMI_001-2017-12-20-09.55",
      "Release": "1513763762"
    },
    "type": "Microsoft.Compute/images"
  },
```
So I think the post processor should support the VHD to Managed disk convert right ?

I'm try to start the post processor in my own fork, I will remove the branch I started to support snapshots.

What is your feeling about this way ?

**Comment by boumenot** [comment]
My first thought was why can't you create a managed disk from the managed image that Packer produces.  I reviewed the API [docs](https://docs.microsoft.com/en-us/rest/api/compute/manageddisks/disks/disks-create-or-update), and I see that you can *Create a managed disk from a platform image*.  I don't see any documentation to say that a custom image could be use, but I would probably try this API with a custom image reference and see if it works.

My search skills have not turned up anything to support my assumption, so it may not work.  The CLI does not support my assumption in any way either.

Regardless, the VHD route is sound, so if you want to avoid the guess work I would just start with VHDs.  I would convert the VHD to a managed image because that's your ultimate goal.

**Comment by boumenot** [comment]
Please reopen if my response does not address your issue.
