### ISSUE TITLE
Add source_path to vagrant-cloud post-processor

### ISSUE THREAD

**Issue by genebean** [hashicorp/packer#5782]
I like to build and test vagrant boxes locally before uploading them anywhere. With that in mind, I would like to have a setting like the `source_path` one builders have in the vagrant-cloud post-processor so that after testing I could run packer again, point it at the boxes created earlier, and have it upload them. The upload template would look something like this:

```sh
{
  "variables": {
    "box_tag": "genebean/somebox",
    "cloud_token": "{{ env `VAGRANT_CLOUD_TOKEN` }}",
    "version": "{{ env `VAGRANT_BOX_VERSION`}}"
  },
  "post-processors": [
    {
      "type": "vagrant-cloud",
      "source_path: "boxes/somebox.box",
      "keep_input_artifact": true,
      "box_tag": "{{user `box_tag`}}",
      "access_token": "{{user `cloud_token`}}",
      "version": "{{user `version`}}"
    }
  ]
}
```

**Comment by ndench** [comment]
Even if there was a flag to skip the `vagrant-cloud` post-processor would solve the problem too, as detailed in #2679. That way you could skip it and test the box locally then rebuild without skipping `vagrant-cloud`. Only problem is it would have to rebuild the whole box which would be slow (not something I'm worried about because I get CircleCI to build and push to Vagrant Cloud when I push to the master branch).

**Comment by SwampDragons** [comment]
I added this to the 1.3.4 milestone so that I would remember to take a look at it, but I think that I'm going to close as wontfix. My reasoning here is that if you're planning to post-process separately from the build, it's better to just use the vagrant-cloud cli for uploads.

That said, we are adding the ability to "skip" post-processors using the "-except" flag in the next release, v1.3.4, so you'll be able to use @ndench's workaround if you're really determined.
