### ISSUE TITLE
Use `DescribeRegions` for region validation

### ISSUE THREAD

**Issue by mohanasudhan** [hashicorp/packer#5786]
When we use packer for copying AMI to all public region (including the one newly released eu-west-3), we get validation error. In our tool, we get regions from describe-regions api and pass region list to packer. But packer maintains its own list of region which lag behind the actual list. Hence at present we can't use packer to copy to new region at the same time we need to change our tool (to remove eu-west-3) to make packer validation happy. 

Code: 
Packer already has the code change with describe-regions api but is commented https://github.com/hashicorp/packer/blob/cb2ad49b21e4fcbf30ee888bee9c28bcb7d066df/builder/amazon/common/regions.go#L3 . we understand that describe-regions will list only limited regions (for example if you in us-east-1, you won't get us-gov-west-1 etc) but when you are running packer for a public region (us-east-1) you don't to know about us-gov-west-1 for validation. Correct me if i am wrong

If you guys are ok, we can change the code and cut new PR.

**Comment by mwhooker** [comment]
Hi @mohanasudhan,

I'm trying to track down the reason we use a static list, rather than query the API. I agree that asking `DescribeRegions` for the region list seems like a better idea, but I'm sure there was a good reason for using a static list at the time.

One thing to note is that you can always set `skip_region_validation` to true if you have a region you want to copy to that isn't on the list.

I'm thinking we should either

1. query `DescribeRegions` as you suggest, or
2. use go code generation to populate the list in `builder/amazon/common/regions.go`, which would be updated automatically every release.

Let me do some more research and get back to you about which way I think we should do it.

**Comment by mwhooker** [comment]
fwiw eu-west-3 _is_ in the region list https://github.com/hashicorp/packer/blob/cb2ad49b21e4fcbf30ee888bee9c28bcb7d066df/builder/amazon/common/regions.go#L15

**Comment by mwhooker** [comment]
If you want to submit a PR that calls `DescribeRegions` and then adds [this static list of regions](https://github.com/hashicorp/packer/blob/cb2ad49b21e4fcbf30ee888bee9c28bcb7d066df/builder/amazon/common/regions.go#L21-L23) we will definitely take a look at it.

Thanks!

**Comment by mohanasudhan** [comment]
Thanks for quick response on the issue. 

My point is to remove static list. Having static list, will not help us anyway. We need to wait for next release of packer to get updated region list. This is same as today, eu-west-3 is added 24 days back and it's not yet released. Hence we need to wait for next release of packer to use eu-west-1. @mwhooker 

Looking back at your list
1. I want to go with this option, is there any problem in do so ? (will wait for your answer here)
2. This will not help us, we just automating manual step here (In this case we are always behind actual region list in latest release version of packer)

**Comment by lorengordon** [comment]
@mwhooker I think you can get away _without_ adding any static list. Just rely on the DescribeRegions API call at runtime to provide the valid list of regions _based on the active aws credential_.

Using an aws commercial credential:

```
> aws ec2 describe-regions --query 'Regions[].{Name:RegionName}' --output text
ap-south-1
eu-west-3
eu-west-2
eu-west-1
ap-northeast-2
ap-northeast-1
sa-east-1
ca-central-1
ap-southeast-1
ap-southeast-2
eu-central-1
us-east-1
us-east-2
us-west-1
us-west-2
```

Using an aws us govcloud credential:

```
> aws ec2 describe-regions --query 'Regions[].{Name:RegionName}' --output text
us-gov-west-1
```

**Comment by lorengordon** [comment]
Or if you did want to keep the static list for some reason, you could lean on the method incorporated into the [AWS GO SDK a while back](https://github.com/aws/aws-sdk-go/pull/961), rather than maintaining the list in packer...

Doc: https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/

**Comment by jen20** [comment]
@mwhooker To shed some light on this - DescribeRegions wasn't originally supported in `goamz`, and when I ported the AWS builders to use the official Go SDK a few years back I just left that code alone, and never came back to it.

Unlike Terraform where metadata is required which is not availabe in machine readable form (for example the account ID for ELB logs), Packer shold be able to get by with just the list from DescribeRegions - as @lorengordon says, that API endpoint will be filtered by what is accessible by the active set of credentials and so is a better check, since copying is less likely to fail at "runtime" rather than at validation.

Other systems implementing the EC2 API (Eucalyptus?) should also work using this approach if they are implemented correctly.

I am somewhat unlikely to ever get to this work but can review a pull request that implements this.
