### ISSUE TITLE
Failed to refresh the Token for request

### ISSUE THREAD

**Issue by miat-asowers** [hashicorp/packer#5803]
Hi all,

I'm new to Packer, and after a few successful local packer sessions I tried to set up Packer with Azure. 

I ran through the example [document by Microsoft](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer) to build the RG and Azure service principal. When I actually try to use `packer build` on my template, it immediately fails with the following result:

==> Some builds didn't complete successfully and had errors:
--> vhd: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/934617eb-7394-4a54-903e-0c6cbc096cb0/resourceGroups/bespin-texapi-packer-rg/providers/Microsoft.Storage/storageAccounts/bespinpacker/listKeys?api-version=2016-12-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'

I've tried creating other service principals and using them to no avail. Is this a packer issue?

- Packer version from `packer version`

`Packer v1.1.3`

- Host platform

Windows

- Debug log output from `PACKER_LOG=1 packer build template.json`.

https://gist.github.com/miat-asowers/fd30bb4d6e544c61dc83c908165b8d3c

- The _simplest example template and scripts_ needed to reproduce the bug.

(in the gist above)

Thanks,
Adam

**Comment by boumenot** [comment]
The build is dying within seconds, which leads me to believe the builder is incorrectly configured.

My best recommendation is re-review the Packers [docs](https://www.packer.io/docs/builders/azure-setup.html) and ensure you are supply the correct parameters.  People generally have the hardest time with object_id.

**Comment by miat-asowers** [comment]
Thanks for your quick response. I've double-checked my guids based on the Microsoft link above. If that page is inaccurate, that could be the cause of my trouble.

```
> Get-AzureRmADServicePrincipal | ? { $_.DisplayName -like '*Packer*' }

ServicePrincipalNames : {http://Azure_Packer, [spAppIdGuid]}
ApplicationId         : [spAppIdGuid]
DisplayName           : Azure Packer
Id                    : [spIdGuid]
Type                  : ServicePrincipal

> Get-AzureRmSubscription

Name     : Enterprise Dev/Test
Id       : [subIdGuid]
TenantId : [tenantIdGuid]
State    : Enabled


in template.json:
{
    "builders": [
        {
            "name": "vhd",
            "type": "azure-arm",

            "tenant_id": [tenantIdGuid],
            "subscription_id": [subIdGuid],

            "client_id": [spAppIdGuid],            
            "object_id": [spIdGuid],
    [...]
```

**Comment by boumenot** [comment]
I re-created what you have using the same cmdlets, and I believe everything is correct.  You have the right GUIDs, in the right places.

I don't know what the issue is, so we'll have to try a few different things.

The builder tries to query your storage account, and fails with an exception.  It may be that this exception message is not indicating the real issue.

```text
 https://management.azure.com/subscriptions/934617eb-7394-4a54-903e-0c6cbc096cb0/resourceGroups/bespin-t
exapi-packer-rg/providers/Microsoft.Storage/storageAccounts/bespinpacker/listKeys?api-version=2016-12-01
```

Would you please verify the existence of this storage account, and that the resource group name is correct.  Please verify that you are deploying a VM in the same region as the resource group and storage account (I believe the builder will error on this already).

My other suggestions would be

 1. Validate you can execute a Packer build using the Device Login workflow. There's a [sample](https://github.com/hashicorp/packer/blob/master/examples/azure/ubuntu_quickstart.json) in the repo that you can use.
 1. Try logging in with your SPN, and validate it works.  If it does, we can easily rule that out.

**Comment by miat-asowers** [comment]
Hi again,

Thanks for looking deeper into this. I recreated the RG and storage account just to make sure, with the same error. 

I was able to generate a Linux image using the Device Login workflow. That's great, in that it seems like the subscription ID works.

Stupid question: how do I log in as a service principal? Where do I do that?

In addition, I tried following the Microsoft tutorial a little more closely and rebuilt the json file to use the `managed_image_resource_group` and `managed_image_name` variables instead, and got a different error:

```
==> Some builds didn't complete successfully and had errors:
2018/01/23 17:25:33 machine readable: azure-arm,error []string{"Cannot locate the managed image resource group TexApi-Packer."}
2018/01/23 17:25:33 ui error: --> azure-arm: Cannot locate the managed image resource group TexApi-Packer.
2018/01/23 17:25:33 ui:
==> Builds finished but no artifacts were created.
2018/01/23 17:25:33 [INFO] (telemetry) Finalizing.
```

Looking at that error message, I found this issue, answered by you!
https://gist.github.com/carlosonunez/3627fed4fba82cd9f97df858672f511d#gistcomment-2264312

So it certainly would seem that there is an issue with authentication of some sort. I've tried and retried creating new SPs using Powershell, and making sure I copy not only the ids but also the password exactly as I typed it into the terminal, with no luck. I'm wondering if there's something about my environment that Packer isn't expecting. For instance, I get the following when running `Get-AzureRmSubscription`: 

```
Name     : Enterprise Dev/Test
Id       : 934617eb-7394-4a54-903e-0c6cbc096cb0
TenantId : fd5782a9-8eb3-46c7-adcc-65e4f1cb0c83
State    : Enabled

Name     : Visual Studio Enterprise - NPasqua
Id       : b4ef6bae-92ad-443b-91fe-24e7da4863f3
TenantId : fd5782a9-8eb3-46c7-adcc-65e4f1cb0c83
State    : Enabled

Name     : Enterprise Dev/Test
Id       : be4ce52a-3baf-46df-b297-584d884626ba
TenantId : bb77783c-1e9b-4b82-83ea-222bc4bed352
State    : Enabled
```

Would this have anything to do with the issues we're seeing? FWIW I'm using the `Id` and `TenantId` from the first (default) one, but I've tried the other Dev/Test subscription information as well with no luck.

Thanks again,
Adam

**Comment by boumenot** [comment]
Are you still having trouble logging in?

**Comment by pug205** [comment]
I'm running into the same error
vhd output will be in this color.

==> vhd: Running builder ...
    vhd: Creating Azure Resource Manager (ARM) client ...
Build 'vhd' errored: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxx/resourceGroups/MyResourceGroup/providers/Microsoft.Storage
/storageAccounts/MyStorageAccount/listKeys?api-version=2016-12-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'

==> Some builds didn't complete successfully and had errors:
--> vhd: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxx/resourceGroups/MyResourceGroup/providers/Microsoft.Storage
/storageAccounts/MyStorageAccount: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'

When I try to access the URL from my browser I get the following result: 
{"error":{"code":"AuthenticationFailed","message":"Authentication failed. The 'Authorization' header is missing."}}
Which makes sence, since the browser doesn't send the authorization header.

Any thoughts?

**Comment by miat-asowers** [comment]
@boumenot,
Thanks for your help, and sorry for not responding earlier. As you suspected, there is an issue with the way I created the Service Principal. There must be some ACL mismatch or something. 

This is how I was finally able to build a Service Principal that worked with Packer and AzureRM: 

```az ad sp create-for-rbac --name "http://localhost/packer" --password "Here is my strong password"```

The command will output a JSON snippet of the form:
```
{
  "appId": {guid},
  "displayName": "azure-cli-2018-02-24-16-08-42",
  "name": "http://localhost/packer",
  "password": "Here is my strong password",
  "tenant": {guid}
}
```
2. Using Powershell, run: 
```
> Login-AzureRmAccount
```
which will produce something like:
```
Environment           : AzureCloud
Account               : your@email.address
TenantId              : {guid}
SubscriptionId        : {guid}
SubscriptionName      : Enterprise Dev/Test
CurrentStorageAccount :
```
3. Finally, run:
```
> Get-AzureRmADServicePrincipal | ? { $_.DisplayName -like "azure-cli*" }
```
which will produce something like:
```
ServicePrincipalNames : {http://localhost/packer, {guid}}
ApplicationId         : {guid}
DisplayName           : azure-cli-2018-02-24-16-08-42
Id                    : {guid}
Type                  : ServicePrincipal
```
4. Then in the Packer json file, add the following in the `"builders"` element:
```
"tenant_id": "{use tenant from `az ad sp create-for-rbac`}",
"subscription_id": "{use SubscriptionId from `Login-AzureRmAccount`}",

"client_id": "{use appId from az ad `sp create-for-rbac`}",            
"object_id": "{use Id from `Get-AzureRmADServicePrincipal`}",
"client_secret": "{password you used above}",
```

Thanks again for your help!
-Adam
