### ISSUE TITLE
Feature Request: builders/amazon-ebs/source_ami_filter with override

### ISSUE THREAD

**Issue by jmassara** [hashicorp/packer#5804]
## Today
The `source_ami_filter`  takes the following options:

```json
{
  "source_ami_filter": {
    "filters": {
      "virtualization-type": "hvm",
      "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
      "root-device-type": "ebs"
    },
    "owners": ["099720109477"],
    "most_recent": true
  }
}
```

## Request
I'd like to propose adding an additional option, `override_ami_id`, that when specified, is used regardless of the filter options.

## Use Case

There are times when I need to use the same AMI ID, regardless of the search filter.  In this scenario, I'd prefer to not have to change the configuration, but instead override it with an environment variable, e.g.:

```json
{
  "variables": {
    "override_ami_id": "{{env `OVERRIDE_AMI_ID`}}"
  },
  "builders":[{
    "type": "amazon-ebs",
    "access_key": "YOUR KEY HERE",
    "secret_key": "YOUR SECRET KEY HERE",
    "region": "us-east-1",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-quick-start {{timestamp}}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
        "root-device-type": "ebs"
      },
      "owners": ["099720109477"],
      "most_recent": true,
      "override_ami_id": "{{user `override_ami_id`}}"
    }
  }]
}
```

It sort of marries `source_ami` and `source_ami_filter` into one, which are mutually exclusive today.

**Comment by mwhooker** [comment]
If you want to pin an AMI returned by the filter, you can always set `source_ami`. the search then becomes "ami matches filter AND ami has id `source_ami`".

If you want to pin an AMI that's not returned by the filter, then currently there's no option for that. However, I'm not sure that's something we want to support, since this gets into turning the config into a programming language which we're not interested in right now. I'll tag this with the future config tag so we can take it into advice when we start to refactor our config format.

**Comment by jmassara** [comment]
@mwhooker your solution does exactly what I want. I couldn't find it in the documentation, however, that `source_ami` and `source_ami_filter` work that way. Unless I missed it...

**Comment by mwhooker** [comment]
no it's not documented.... will think about adding it.
