### ISSUE TITLE
vagrant post-processor metadata.json

### ISSUE THREAD

**Issue by bcg62** [hashicorp/packer#5833]
Packer Version 1.1.3

Looking over the docs and some practical testing/usage, it seems like there is no way to change the content of metadata.json packed inside the box unless you use atlas/vagrant-cloud.

I am self-hosting my images and do not want to push them to vagrant-cloud.

I've tried various configurations including `no_release ` and `box_download_url` but yet it still tries to reach out and authenticate to vagrant-cloud.

What is the best way have packer create a valid metadata.json for self hosting? Also it would be helpful to have a way to store the same metadata.json outside of the box for uploading elsewhere.

**Comment by SwampDragons** [comment]
The vagrant postprocessor doesn't create a valid metadata.json file?

**Comment by bcg62** [comment]
This is what i see it generating.

```
{"provider":"virtualbox"}
```

To self-host my own builds typically I would do something like this in vagrant:

```
config.vm.box = "box/centos7"
config.vm.box_url = "https://internal_web_server/vagrant/box/centos7/metadata.json"
```

I was under the assumption there was a way for packer to create the json used with config.vm.box_url. It seems kind of odd to do that manually, or to extend packer to do so when it already has all this information. Maybe this isn't the case.

**Comment by SwampDragons** [comment]
So, I think there's a little confusion around the metadata files being generated; there are two separate metadata files. The one that Packer generates in the vagrant-postprocessor is packaged inside the vagrant box itself, and only has the provider information, as you've seen.  The one that I think you're actually wanting packer to generate here is a metadata file that is external to the box.

I talked this ticket over with the Vagrant team, and having Packer automatically generate that external file is not actually straight forward. This is because the metadata.json file referenced by box_url contains version information on boxes that are available, not just for a single box... it _can_ just be for a single box, but then previous versions of that box would not be available, which diminishes the point of creating this file.

Unfortunately, the dramatically different use cases for this file make this feature very difficult to support in a meaningful way; there isn't really a correct "default".

I'm sorry to say, I think your best option is to generate the file yourself using the shell-local postprocessor.
