### ISSUE TITLE
fix/replace winrm ntlmssp client

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5865]
The ntlm winrm client has caused occasional panics. I believe the ultimate solution is to rewrite it. We have a cheap workaround at https://github.com/hashicorp/packer/pull/5864, but this calls for a more permanent solution

c.f. https://github.com/hashicorp/packer/issues/5257, https://github.com/Azure/go-ntlmssp/issues/9

longer term solution might entail using https://github.com/ThomsonReutersEikon/go-ntlm and creating our own client

**Comment by SwampDragons** [comment]
This should be closed by #8369; long story short, the ntlm client was sometimes returning `nil, nil`, instead of `resp, nil` or `nil, err` because of a bad error assignment. I think this is the source of all the ntlm related bugs we've seen; the fact that the round tripper does a little extra processing will probably not be an issue for us now that this root bug has been handled upstream.
