### ISSUE TITLE
Berkshelf support for the chef-solo provisioner?

### ISSUE THREAD

**Issue by netsensei** [hashicorp/packer#590]
Hi,

Is there support for something like Berkshelf on the roadmap? In #126 a chef-solo provisioner was implemented. The cookbook_paths directive points to locations where various vendor/app specific cookbooks are located. 

Since Berkshelf manages cookbooks much like Bundler, there is not really a specific cookbooks directory for a given runlist. (chef-librarian, on the other hand, does exactly that)

The vagrant-berkshelf plugin from RiotGames (https://github.com/RiotGames/vagrant-berkshelf) integrates Berkshelf with the Vagrantfile. But since Packer allows you to "pre-package" software into the image rather then provision it on runtime, I don't think this is what I'm looking for.

**Comment by mstrache** [comment]
The solution pointed out in this thread multiple times is, to run Berkshelf prior to packer. I am not very happy with that solution, since it requires chef, or at least Berkshelf, to be installed on the machine that runs packer AND on the the virtual machine that is being provisioned (even though only one of them needs chef for provisioning). 

Since I try to keep my systems as clean as possible that doesn't make much sense to me. Wouldn't it be more reasonable to run Berkshelf from INSIDE the VM? 

The solution I came up with requires one chef installation:
First install chef inside the VM (e.g. with a shell provisioner or by running chef-solo provisioner with an empty runlist), then run Berkshelf inside the VM (shell provisioner) and then (again) run chef-solo provisioner with the cookbooks already inside the VM.

Even though this works, I am not very happy with it (it requires two to three provisioner to run just one). What I would like to have is the ability to run Berkshelf (vendor) from within the chef-solo provisioner: after chef installation but before chef-solo is executed

**Comment by Joseph-R** [comment]
```
Even though this works, it is a hack and I am not very happy with it. What I would like to have is an official way to run Berkshelf (vendor) from within the chef-solo provisioner: after chef is installed but before chef-solo is executed
```

Same.  

For better or worse, Berkshelf is a very commonly used (the default?) tool to package and version chef cookbook dependencies.  It's integral to every Chef workflow I've seen.  

Trying to use a Chef provisioner without integrating Berkshelf is like trying to build a Ruby app deployment tool without integrating Bundler.  It's not that you can't hack around it.  It's that those hacks are going to be janky and suck.

**Comment by jkburges** [comment]
FWIW, I've run in to this same issue.

I want to be able to run packer builds from [atlas](https://atlas.hashicorp.com), so AFAICT, installing berkshelf and what not on the host running packer is not an option (maybe I'm wrong about this though).

I then went down the road of vendoring cookbooks on the target, but the first problem I ran in to was the fact that `git` is missing there (needed to fetch cookbooks from github) - git being one of the very dependencies that would be installed with chef.  Nothing that can't be solved, but it's definitely a bit of an ugly chicken and egg scenario.

**Comment by jkburges** [comment]
> I want to be able to run packer builds from atlas, so AFAICT, installing berkshelf and what not on the host running packer is not an option (maybe I'm wrong about this though).

I was wrong - it *is* possible to install software on the host from an atlas/packer context.  Ref: https://atlas.hashicorp.com/help/packer/builds/installing-software

**Comment by DarwinJS** [comment]
@Joseph-R and @mstrache - do either of you have examples of (or a repo demonstrating) your modified "execute_command" for the chef-solo provisioner?

I am interested in this approach, but having difficulty.

Also does the chef install that results from the chef-solo provisioner contain berks or does it have to be placed on the machine being built by a specific action?
