### ISSUE TITLE
New ISO on same URL requires two executions to download

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#5907]
I am publishing a base ISO on a certain URL, with a checksum file on another URL. Both URLs are static, with only the contents changing between versions.

When the ISO and checksum file change, Packer detects that the ISO it downloaded in the past is out out date but instead of downloading a new ISO, it just errors out:

```
==> Windows1709-HyperV: Downloading or copying ISO
    Windows1709-HyperV: Downloading or copying: https://xxxx/windows1709-setupiso.iso?xxxxxxxx
    Windows1709-HyperV: Download progress: 100%
    Windows1709-HyperV: Download progress: 100%
    Windows1709-HyperV: Error downloading: checksums didn't match expected: bf0a4096947e8cd1491bde93754bcf43007515761b7b4f1d741119c4c5c3ae48
==> Windows1709-HyperV: ISO download failed.
==> Windows1709-HyperV: Step "StepDownload" failed, aborting...
Build 'Windows1709-HyperV' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> Windows1709-HyperV: unexpected EOF
```

However, if I then re-run the build it correctly starts downloading the ISO (presumably because the previous checksum mismatch resulted in it getting deleted).

I would expect Packer to perform the download on the first run if it detects out of date already-downloaded files.

Packer version: master branch from early February
Host platform: Windows 10 v1709
Builder type: Hyper-V ISO

**Comment by SwampDragons** [comment]
The problem here is that Packer doesn't know it's "out of date" -- it just knows the checksum doesn't match the ISO. Your use case breaks a fundamental assumption we make in our download code, which is that a given static URL's files will be unique -- the way the Packer cache works, if you haven't provided a specific TargetPath, Packer will generate the filename in the cache by hashing the URL. https://github.com/hashicorp/packer/blob/master/common/step_download.go#L74-L85

On thinking about your use case, I don't think I like the idea of adding your use case's assumption to the Packer code -- I don't think most setups would assume that an ISO downloaded from a static URL is prone to changing, and I think most people would prefer Packer to fail in the situation where the same-named file doesn't match the provided checksum _before_ downloading what could be tens of gigabytes of extra data. 

The good news is that this sounds like something that can be solved in your case with a simple wrapping bash script that verifies the ISO against the checksum and deletes it from the Packer cache if it's out of date, before calling Packer.

**Comment by espoelstra** [comment]
I ran into this same thing while testing the Ubuntu 18.04 daily builds, and I agree this is annoying but I also completely understand that it doesn't make sense to have an override adding extra code complexity when you can simply clear the packer_cache on every run if you are doing daily patching or whatever.
