### ISSUE TITLE
googlecompute: possible to support instances without a service account?

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/packer#5924]
I'm launching packer with service account credentials to build GCE images.  My provisioners do not require any Google API access, so I'd prefer to launch the build instance without any service account.  But packer doesn't expose the ability to set the service account for a compute instance, or disable it.

Benefits:
* no unnecessary api access provided to the build instance
* if your provisioning process doesn't need API access, no need to give packer `roles/iam.serviceAccountActor` 
* supports both use cases from #5825 and #4608 

Packer could implement the gcloud behavior: use the default service account by default, allow the user to specify a specific service account, or request that none be assigned.

**Comment by kri5** [comment]
@rvandegrift I wrote this https://github.com/hashicorp/packer/pull/5928 to allow at least specifying the service account you want to use instead of the "default" service account only.

I do not see a clean way of providing the ability to specify no service account at all.

Feel free to comment on the PR.

**Comment by rvandegrift** [comment]
Here's a kind of clunky suggestion: add a second parameter, `no_service_account`.  If set to true, the instance is created without a service account.

**Comment by mwhooker** [comment]
done in #5991
