### ISSUE TITLE
Error sending boot command, Failed to send a scancode

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#6054]
I'm slowly working out the kinks from my Darwin VirtualBox base box, but I keep running into this error:

```console
ui error: Build 'virtualbox-iso' errored: Error sending boot command: VBoxManage error: VBoxManage: error: Failed to send a scancode
```

For some reason, VirtualBox is having trouble processing the scancodes sent by packer. Maybe VirtualBox is running out of space in some buffer? This error occurs towards the end of my `boot_command`, several hours into the packing build.

- Packer version `Packer v1.2.2-dev`, with [bugfixes](https://github.com/mcandre/packer/tree/super-keys-for-virtualbox) for how packer parses keys. I plan to submit a pull request for the bugfixes once I can show that the Darwin box packs with the packer patch.
- Host platform: macOS 10.13 High Sierra.

Example:

https://github.com/mcandre/packer-templates/blob/e8b395a060f6fdd1e23f61c80bd3b413d3cecb9b/macos/macos.json

**Comment by mwhooker** [comment]
"failed to send a scancode" comes from [vboxmanage](https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Frontends/VBoxManage/VBoxManageControlVM.cpp). There's not much we can do here. It might be helpful to post here if there's anything in the logs. Would also like to see the last command it sent to vboxmanage before erroring.

Since I don't see a bug with packer, and there's nothing we can do, I'm going to close this. If you inspect your logs and you see packer doing something it shouldn't, I'd be interested to hear and we can open a new ticket.
