### ISSUE TITLE
Add a progress bar to the UI module

### ISSUE THREAD

**Issue by thedrow** [hashicorp/packer#6068]
Currently the UI module does not include a progress bar.
This could be useful for steps which take a very long time to complete such as downloading or copying an image or creating a new disk.

I'd like to propose that we add a `ui.ProgressBar()` method which will report progress of a build step.

**Comment by SwampDragons** [comment]
It's a cool idea for download steps, and in fact someone has already created a PR  for adding a progress bar to the iso downloader. We'll be reviewing that once we make some of the other planned changes to our download code.  But for provisioning steps I don't think it makes sense. Packer doesn't know how long your shell provisioner scripts will take to run, for example, because it isn't inspecting what you're doing.

If you really want to see how the download is going right now, you can set the environment variable PACKER_LOG=1 and it'll track your percent progress; it's a bit spammy but you'll be able to see how long you have left to wait.

**Comment by SwampDragons** [comment]
See the Progress Bar PR here: https://github.com/hashicorp/packer/pull/5851

**Comment by thedrow** [comment]
I have seen some steps here which I can create a progress bar for.
For example, the qemu step CopyDiskImage does not display progress.
We could specify -p to qemu-img, capture stdout and create our own progress bar based on the progress printed on stdout.

**Comment by arizvisa** [comment]
@thedrow, my PR at https://github.com/arizvisa/packer/tree/multi-proto-progressbar was rejected. But, I added support for the progress-bar for some places such as the file transfer (upload/download) during provisioning.

The one issue with adding a progress-bar to the different provisioners/post-processors/builders is that in most of these places the `ui` structure isn't exposed, so depending on the step the current user interface will need to be passed down to the lower-level `io.Reader`/`io.Writer` apis in order to track the current progress. Regardless, are there any other places that you'd care to have a progress-bar?

Currently the downloading looks like this. The appearance is the same for the file provisioner too.
```
==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
    vmware-iso:  0 B / 364.00 MiB [----------------------------------------------------]   0.00%
    vmware-iso:  110.41 KiB / 364.00 MiB [>--------------------------------------------]   0.03%
```

**Comment by arizvisa** [comment]
```
...
    vmware-iso:  350.30 MiB / 364.00 MiB [===========================================>-]  96.24%
    vmware-iso:  353.90 MiB / 364.00 MiB [===========================================>-]  97.22%
    vmware-iso:  357.71 MiB / 364.00 MiB [=============================================]  98.27%
    vmware-iso:  361.62 MiB / 364.00 MiB [=============================================]  99.34%
    vmware-iso:  364.00 MiB / 364.00 MiB [=============================================] 100.00%
```
