### ISSUE TITLE
Template executed with -parallel=false still parallelizes

### ISSUE THREAD

**Issue by alexgottschalkmedal** [hashicorp/packer#6171]
FOR BUGS:

Describe the problem and include the following information:

- Packer version 1.2.2
- Ubuntu 16.04
- log output: https://gist.github.com/alexgottschalkmedal/2d1b206c2ad80dd5411944f560a49b90

Even when specifying -parallel=false, the scripts run in parallel and the reboot at the end of apt-update.sh interrupts packages.sh and causes the whole build to fail.

**Comment by alexgottschalkmedal** [comment]
Just as a concrete example of what I'm talking about, take a look at this run:

``
$ ./packer build -parallel=false build.json
[...]
==> amazon-ebs: Provisioning with shell script: scripts/packages.sh
    amazon-ebs: Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
    amazon-ebs: Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
    amazon-ebs: Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
    amazon-ebs: Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
    amazon-ebs: Reading package lists...
==> amazon-ebs: Provisioning with shell script: scripts/pip.sh
    amazon-ebs: /tmp/script_6335.sh: line 3: pip3: command not found
    amazon-ebs: /tmp/script_6335.sh: line 4: pip3: command not found
    amazon-ebs: /tmp/script_6335.sh: line 5: pip3: command not found
    amazon-ebs: /tmp/script_6335.sh: line 6: pip3: command not found
    amazon-ebs: /tmp/script_6335.sh: line 7: pip3: command not found
    amazon-ebs: /tmp/script_6335.sh: line 8: pip: command not found
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 127
```

"scripts/pip.sh" is clearly being run before "scripts/packages.sh" is able to install pip3.

**Comment by mwhooker** [comment]
Hi @alexgottschalkmedal,

Thanks for the report. First off I want to clarify some things. `-parallel` instructs packer where to run the _builders_ in parallel, and not the provisioners. Provisioners are always run in sequence. I think what's going on here is that you first script, `scripts/apt-upgrade.sh` causes your remote machine to restart. This action takes a couple of seconds, by which time packer has started on your second script, `scripts/packages.sh`. When the machine does reboot, the packages.sh script is in the middle of running. I would suggest creating two different provisioners, and having the second one wait a little. Maybe something like

```
{
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "sudo -H sh -c '{{ .Vars }} {{ .Path }}'",
      "script": "scripts/apt-upgrade.sh",
      "expect_disconnect": true
    },
    {
      "type": "shell",
      "pause_before": "30s",
      "execute_command": "sudo -H sh -c '{{ .Vars }} {{ .Path }}'",
      "script": "scripts/packages.sh"
    }
  ]
}
```

Since I don't think this is a packer bug, I'm going to close this. If you need further assistance I would recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool).
