### ISSUE TITLE
Make {{.WinRMPassword}} template option available in ansible provisioner

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#6180]
see https://github.com/hashicorp/packer/issues/5895 for context

**Comment by shadycuz** [comment]
Hey =)

I'm trying to build a windows server on AWS and then provision with Ansible but I'm stuck. Packer has no problem with connection to the instance and using the powershell provisioner, but when trying something with ansible I get auth errors. I believe its because I need to pass the temporary password to ansible for its basic auth session to win_rm. 

Any thoughts or comments?

**Comment by shadycuz** [comment]
@SwampDragons I took a crack at getting some basic functionality working, mostly for internal usage 😊. 

I had trouble getting the `getWinRMPassword(p.config.PackerBuildName)` call to work? I think it's returning an empty string? Maybe you could take a look at the PR, I know you wrote some or most of this for the PowerShell provisioner. 

Thanks

**Comment by SwampDragons** [comment]
Oh I think I have an idea of what's going on -- I'll take a look at your WIP and see if I can push a change (apologies for the slow reply, I was on vacation last week)

**Comment by SwampDragons** [comment]
Commented on the PR -- I'm not gonna push the change, but I explained what's wrong. Really solid start though 😄
