### ISSUE TITLE
Block project-wide SSH keys option (Google Cloud builder)

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#6201]
When using the Google Cloud  builder, there does not seem to be a way to "uncheck" `Block project-wide SSH keys` on the Packer instance. I'd actually like the Packer instance to inject project wide SSH keys.

Is possible to get an option to support this in Packer?

**Comment by rickard-von-essen** [comment]
This is controlled by [`metadata`](https://www.packer.io/docs/builders/googlecompute.html#metadata) option `block-project-ssh-keys` `true` or `false`.

I'll close this and I'll reopen if that doesn't work for you.

**Comment by anujguptatecnotree** [comment]
Is there any way where we can add
**Block project-wide SSH keys** **checkbox in GCP solution package for the custom image** . so that when the user creates any VM from the image, that checkbox should come at the time of creation the VM and user must be able to check or uncheck Block project-wide SSH key.

**Comment by rickard-von-essen** [comment]
No

**Comment by SwampDragons** [comment]
@anujguptatecnotree good question! I agree with Rickard on this one, but I'll provide a bit more explanation.  

In the vast majority of cases, Packer is running in a CI system, so user interaction during the build is a something we avoid wherever possible. In this situation, since there is a flag you can set in the user data yourself, Packer forcing all GCP builds to stop until the user manually checks a box would violate the philosophy of the project. 

If you have trouble with the suggestion Rickard made using metadata, you can reach out to the mailing list to get help implementing it.  Thanks!
