### ISSUE TITLE
Increase resource state timeout on AWS EBS Backed Builders

### ISSUE THREAD

**Issue by tedivm** [hashicorp/packer#6223]
Occasionally AWS takes longer than expected to bring a new instance to the ready state. When this occurs it can cause build errors from packer, specifically-

> ==> amazon-ebs: Error waiting for instance (i-####) to become ready: ResourceNotReady: failed waiting for successful resource state

Full logs are [in this gist](https://gist.github.com/tedivm/d17e04a2b99458d35e566e773d981da6).

This build occurs on CircleCI (but in a private repo, so I can't link to the build) using packer 1.2.2. It is really hard to replicate- out of roughly 50 builds I've seen it happen three times (all with the "AWS Deeplearning AMI", specifically `ami-80bcd4f8` in `us-west-2`). In all three cases the instance did eventually launch, and it was not properly cleaned up by packer.

**Comment by mwhooker** [comment]
Hi @tedivm 

You can change the timeouts yourself by setting `AWS_POLL_DELAY_SECONDS` and `AWS_TIMEOUT_SECONDS`, which are by default 2s and 300s, respectively. Unfortunately this is not documented except for in the debug logs, but I hope to resolve this fully in #6177

Closing this since there's a workaround, and there's already a ticket for the proper fix that we'll track this in.
