### ISSUE TITLE
Building debian8+ on vmware-iso

### ISSUE THREAD

**Issue by freeseacher** [hashicorp/packer#6254]
Hi. I am trying to automate tests for our software. 
The best i found is to start from iso and get my pipeline on gitlab-ci to vmware-template. 

Scheme works like a charm for centos7, oel7. 

Then i starts to implement one with debian 8. 
My pipeline looks like that. Gitlab-ci -> custom docker image file with ovftool and needed plugins -> several workers on different machines -> vmware-iso -> vmware template. 

I've been using floppy files to set kickstart file. 
But for debian 8 there is no support for floppies. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783982
Also because of docker and the way how gitlab launches it i can't use http way. (job worker starts on some machine without any open ports)
Also i've tried to set https link for preseed file to my raw file in giltab. But there are no support for https in busybox.

According to https://www.debian.org/releases/jessie/i386/apbs02.html.en there is another options. One is to build custom vdmk file and place it to hd-media. Another is mount is as second cdrom. But there is no support from packer side. 

Any ideas how to make it work ?

**Comment by SwampDragons** [comment]
Hi! Sorry you're struggling; you're right that packer doesn't have native support for this use case. Since you're asking for advice rather than making a feature request or reporting an issue with Packer, I think you will be more likely to get the help you want if you reach out to our mailing list: https://groups.google.com/forum/#!forum/packer-tool
