### ISSUE TITLE
amazon-ebs authentication failures with ansible provisioner

### ISSUE THREAD

**Issue by justinhohner** [hashicorp/packer#6255]
After the packer ssh proxy establishes a connection ansible is not able to authenticate to the instance. Authentication fails with either a message similar to "Failed to connect to the host via ssh ... too many authentication failures..." or by asking for a password, the difference is likely due to ssh policy on different hosts. I am able to use the packer generated ssh to to connect to the instance via the packer ssh proxy.

Host platform:
macOS 10.13.4

Packer version:
1.2.3

PACKER LOG:
https://gist.github.com/justinhohner/e85ad4957790833e1004d4bb882435e2

JSON file:
https://gist.github.com/justinhohner/7437bfc9c5db47c2b97a3419242ba59f

**Comment by KyleMartin901** [comment]
I have just come across this issue also.

I worked out the cause is when you use the parameter **groups** to add the host to a group. When unspecified, the host is not associated with any groups and if role use the `hosts: all` then it works as expected but as soon as you add the **groups** param to associate the host with the groups you want you get the error.

`amazon-ebs: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Received disconnect from 127.0.0.1 port 64660:2: too many authentication failures\r\nDisconnected from 127.0.0.1 port 64660", "unreachable": true}`
