### ISSUE TITLE
Device Login for Azure Builder doesnt support Windows Build

### ISSUE THREAD

**Issue by harijayms** [hashicorp/packer#6284]
Feature Request: Extend support for device login for Azure builder for building Windows. Currently this is not supported.

**Comment by SwampDragons** [comment]
@boumenot do you know what this means? I'm not totally clear.

**Comment by boumenot** [comment]
Allow me to translate. 😀 

There are a couple of different ways to authenticate against Azure.  You can use your own credentials, you can create a Service Principal (service account) aka SPN, or you can have an `Application` do work on your behalf.

 1. Typing in your own credentials makes automation hard, so we don't use it.
 1. Service Principals (SPN) support automation, but can be tricky to create. There are a lot of GUIDs one has to manage.  This has gotten easier, but there's still a burden.
 1. Device Login allows you to logon as yourself and have something work on your behalf.  An OAuth token is created, and cached, so repeated access does not require re-entry of your credentials.  Device Login is the least burdensome way to try something out with Packer because you don't have to create an SPN - you just **go go go**.  Any it still looks like you despite something working on your behalf.

Device Login only supported Linux builds.  Windows builds were not supported because Azure Windows VMs require certificate based authentication for WinRM.  To support certificate authentication you need to inject a certificate into the Azure VM, and that is facilitated via KeyVault.  Access to the KeyVault certificate is authorized by an Azure Active Directory ID aka an ObjectId.

> NOTE: ObjectID is a generic term, and is reused.  It is easy to confuse with other ObjectIDs. Gah!

The Azure builder orchestrates all of this.

 1. Deploys a KeyVault ARM template.
 1. Creates a new certificate at runtime, and inject it into KeyVault and secures it with the ObjectId.
 1. Deploys a VM ARM template, and links it to the KeyVault certificate.

Packer uses the WinRM communicator to complete the VM build, and WinRM properly authenticates using certificate based auth.

The reason the Azure builder has only supported Linux is due to the orchestration involved in getting the ObjectID of the user when they authenticated with the Device Login flow. The ObjectID was not readily available, and had to be looked up. The support was never implemented.  @harijayms is working on addressing those shortcomings.  An added benefit of this work is that there is one less GUID in the world. 👍 

HTH.

**Comment by SwampDragons** [comment]
It does help!  Thanks so much for the explanation 😄 

So if there's ongoing work on this kind of thing already, should I close this as a duplicate, or leave it open and link it to something else?
