### ISSUE TITLE
Packer crashing non-deterministically

### ISSUE THREAD

**Issue by oguzhanunlu** [hashicorp/packer#6310]
Packer version: 0.12.3

Crash report is [here](https://gist.github.com/oguzhanunlu/4e8539fdc51dce15e83eb7d6e9a4f41e)

Today, I published first release candidate of a project successfully however publishing second release candidate failed where only change was a variable representing project version in `Packerfile`.

Thanks in advance.

**Comment by SwampDragons** [comment]
There's a very, very good chance that we've fixed this crash in the time since 0.12.3 came out.  I know I've done work on the ami region copy step that's failing here. Try with a more recent version of Packer and let me know if it's still an issue. You may want to run `Packer fix yourconfig.json` to check for any backwards incompatibilities that have popped up since you upgraded.
