### ISSUE TITLE
Vagrant post-processor tar fails if user name is not GnuTar format compatible

### ISSUE THREAD

**Issue by snesbittsea** [hashicorp/packer#6318]
Packer version:  1.2.3
Host Platform: Ubuntu Bionic
User logged in to Active Domain Controller via sssd with a fully qualified username - e.g. snesbitt@fuzzbutt.aussieswithtails.com

Basic issue I believe is that in this scenario the uname associated with a file is snesbitt@fuzzbutt.aussieswithtails.com which seems to be incompatible with GNU tar format and will result in a Vagrant post-processor failure. One work around is to add a full_name_format option to the sssd.conf file that removes the incompatibilities (whatever those are). In my case setting it to full_name_format = %1$s solved the issue.

Even so, it would be nicer if it were possible for Packer to check for incompatibility and reformat as necessary.

The [base vagrant template ](https://gist.github.com/snesbittsea/7e2810584304c5d26b98e26181329b86#file-gistfile1-txt) 

The [vagrant error message](https://gist.github.com/snesbittsea/90ab7e950b75d581de54496602d6afdc#file-vagrant_error-md)

**Comment by hwang381** [comment]
@SwampDragons May I take a stab? :)

**Comment by SwampDragons** [comment]
Sure, though I think you've managed to find a good first issue that does require some investigation before knowing how to implement a fix.

Looks to me like the error message is coming from the tar libaray here: https://golang.org/src/archive/tar/common.go#L346, which shows the code they're using to validate. My guess is that the best approach here is to add similar validation code before we create the header. 

We're creating the header here: https://github.com/hashicorp/packer/blob/master/post-processor/vagrant/util.go#L124

The big question to figure out is whether there's some way to figure out that this is going to be a problem _before_ the build has been running for a long time; ideally we'd be able to determine this issue during the Configure() method rather than the PostProcess() one.

If there is a way to figure this out ahead of time, we can go ahead and fail early saying "this won't work because the output directory's header is no good".

If not, it may be worth considering adding code to fix the header, although I'm not wild about modifying the file info in the header. I'd want to test to make sure doing so doesn't break anything.

**Comment by hwang381** [comment]
If I understand the problem correctly, it is caused by the host system environment having a username that tar cannot process into tar file headers. The proposed PR thus is to create a dummy Vagrant box (using `DirToBox`) in the configure stage so that this can be caught early.
However I do have difficulty in reproducing the original bug (and thus verifying the fix) in my home lab environment. Any suggestion on that from @snesbittsea would be appreciated :)
