### ISSUE TITLE
Powershell inline scripts to not cause abort if a script is missing

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#6319]
**Example**	
```
"type": "powershell",
	"inline": [ 
		"C:\\buildscripts\\OS_and_Utils\\Script1.ps1",
		"C:\\buildscripts\\Our_Apps\\Script2.ps1",
		"C:\\buildscripts\\Our_Apps\\Script3.ps1",
		"C:\\buildscripts\\Our_Apps\\Script4.ps1",
		"C:\\buildscripts\\Our_Apps\\Script5.ps1",
		"C:\\buildscripts\\Our_Apps\\Script6.ps1"
		 ]
        },
```

If Script4.ps1 is missing the console displays it doe not exist but carries on with the provision and eventually makes the build - It should give the clean/retry/abort as the build is incorrect.

**Comment by SwampDragons** [comment]
If you provide these values as [scripts](https://www.packer.io/docs/provisioners/powershell.html#scripts) instead of inline, does this problem still occur?

**Comment by SwampDragons** [comment]
I'm going to close this as a duplicate of https://github.com/hashicorp/packer/issues/4916 because that's the root of why the build silently continues even though there's been a failure. HOWEVER in this particular situation I think that using the scripts option instead of the inline option will fix things.
