### ISSUE TITLE
<no value> as a .Provider variable value

### ISSUE THREAD

**Issue by brodriguesneto** [hashicorp/packer#6333]
Packer is not setting the .Provider on the vagrant post-processor
-----------------------------------------------------------------

__Packer version__: 1.2.4
__Host Platform__: macOS 10.13.4
__Provider__: VirtualBox 5.2.12
__Gist__: https://gist.github.com/brodriguesneto/73600c762fecb1a230a7f92747a59730

I run a packer build to upload a custom Vagrant box. A have this code as a post-processor:

```JSON
"post-processors": [
    [
      {
        "type": "vagrant",
        "keep_input_artifact": false,
        "only": [
          "virtualbox-iso"
        ],
        "output": "{{ user `artifact_root` }}/{{ user `vm_name`}}/{{ .Provider }}/{{ user `vm_name` }}.box"
      },
      {
        "type": "vagrant-cloud",
        "box_tag": "{{user `vagrant_cloud_account`}}/{{ user `vm_name` }}",
        "version": "{{ timestamp }}",
        "version_description": "{{user `vagrant_version_description`}}"
      }
    ]
  ]
```

In the context of vagrant post-processors, the .Provider has no value:

```sh
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: artifact/ubuntu-1604/<no value>/ubuntu-1604-disk001.vmdk
    virtualbox-iso (vagrant): Copying from artifact: artifact/ubuntu-1604/<no value>/ubuntu-1604.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: ubuntu-1604-disk001.vmdk
```

But in the context of vagrant-cloud it sets the .Provider as expected:

```sh
==> virtualbox-iso: Running post-processor: vagrant-cloud
==> virtualbox-iso (vagrant-cloud): Verifying box is accessible: everproven/ubuntu-1604
    virtualbox-iso (vagrant-cloud): Box accessible and matches tag
==> virtualbox-iso (vagrant-cloud): Creating version: 1527966362
==> virtualbox-iso (vagrant-cloud): Creating provider: virtualbox
==> virtualbox-iso (vagrant-cloud): Preparing upload of box: artifact/ubuntu-1604/virtualbox/ubuntu-1604.box
==> virtualbox-iso (vagrant-cloud): Uploading box: artifact/ubuntu-1604/virtualbox/ubuntu-1604.box
    virtualbox-iso (vagrant-cloud): Depending on your internet connection and the size of the box,
    virtualbox-iso (vagrant-cloud): this may take some time
    virtualbox-iso (vagrant-cloud): Uploading box, attempt 1
    virtualbox-iso (vagrant-cloud): Box successfully uploaded
==> virtualbox-iso (vagrant-cloud): Releasing version: 1527966362
    virtualbox-iso (vagrant-cloud): Version successfully released and available
```

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by brodriguesneto** [comment]
Gist updated whith full debug log.

**Comment by dingus9** [comment]
This is happening for me as well

```
  "post-processors": [
    [
      {
        "type": "vagrant",
        "keep_input_artifact": false,
        "output": "windows_10_{{.Provider}}.box",
        "vagrantfile_template": "windows-10/vagrantfile-windows_10.template"
      },
      {
        "type": "vagrant-cloud",
        "box_tag": "test/windows_10_{{.Provider}}.box",
        "version": "{{user `version`}}",
        "vagrant_cloud_url": "http://172.28.128.10:9000",
        "only": ["virtualbox-iso"]
      }
    ]
  ]
```

```
==> virtualbox-iso: Running post-processor: vagrant-cloud
==> virtualbox-iso (vagrant-cloud): Verifying box is accessible: dingus9/windows_10_<no value>.box
```

**Comment by SwampDragons** [comment]
I think both of you are experiencing scoping issues. 
the `{{.Provider}}` template engine syntax only works in the [output](https://www.packer.io/docs/post-processors/vagrant#output) field for the `vagrant` post-processor, and the [box_download_url](https://www.packer.io/docs/post-processors/vagrant-cloud#box_download_url) field for the `vagrant-cloud` post-processor. If you're using it anywhere else, it will fail with <no value> because it is not being set in the interpolation context for the template. 

In the first example, I see `virtualbox-iso (vagrant): Copying from artifact: artifact/ubuntu-1604/<no value>/ubuntu-1604-disk001.vmdk`; that logline has nothing to do with the "output" field but rather the artifact being passed into the post-processor; I suspect that your builder is being asked to set {{.Provider}} in an original artifact output name. 

in the second example, that logline is checking the box_tag, and it isn't accessible because Provider isn't in the interpolation context for box_tag. 

I checked the docs and they don't claim box_tag is a template engine, so I think this is all behaving as documented.

**Comment by SwampDragons** [comment]
Closing because I haven't heard any more after my previous comment.
