### ISSUE TITLE
PowerShell direct support for Hyper-V

### ISSUE THREAD

**Issue by Sarafian** [hashicorp/packer#6359]
Microsoft released recently this concept where PowerShell can connect to a VM just by using the VMName without the necessity to use credentials nor the target OS having a full network stack configured. This is known as [PowerShell Direct](https://blogs.technet.microsoft.com/virtualization/2015/05/14/powershell-direct-running-powershell-inside-a-virtual-machine-from-the-hyper-v-host/).

This could be very useful when working with Hyper-V network configuration as `internal`. For the current provisioner to work, somehow the network stack needs to be fully configured, then it's IP it needs to become know and then the packer client can provision.

With PowerShell direct this won't be necessary any longer.

There is a similar [request](https://github.com/hashicorp/vagrant/issues/8810) for the vagrant provisioners. There a new type of provisioner is being discussed.

**Comment by DanHam** [comment]
@Sarafian This looks really interesting. My reading of the docs is that PowerShell Direct is currently only supported between Windows 2016 or Windows 10 Host/Guest combinations though.

For anyone else interested, there is another article in the Hyper-V docs [HERE](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-windows-virtual-machines-with-powershell-direct)

**Comment by Sarafian** [comment]
@DanHam link lands to a microsoft store page. Anyhow, I still think there should be an option for this. As time passes, I expect more and more use cases to be supported by PowerShell direct. If I remember correctly it even works with linux vms.

A new provider should be enough to act as means for choice. Is the code for the provisioners shared between Vagrant and Packer? They look almost identical.

**Comment by Sarafian** [comment]
@DanHam probably I overstated the Linux support. I heard about PowerShell direct during techorama 2018 in Belgium and I'm sure the presenter had mentioned something. Unfortunately his slides are not shared. While digging into this, as I should had done before, the only useful link I found was the [Enable PowerShell Direct for Linux VMs](https://windowsserver.uservoice.com/forums/295062-linux-support/suggestions/16709011-enable-powershell-direct-for-linux-vms) entry on uservoice.
Sorry for the confussion.

**Comment by DanHam** [comment]
@Sarafian No worries - I'm grateful for the heads up with regards to PowerShell Direct; like I said I think it looks really interesting.

>  the only useful link I found was the Enable PowerShell Direct for Linux VMs entry on uservoice.

I was vaguely aware that PowerShell could now be used on GNU/Linux distros, so I did wonder about whether this would be possible. Looks as though it isn't yet unfortunately. Given the date that the feature request was proposed (2016) and the small number of votes it's got (only 11 so far), I'm not sure that is ever going to gain enough traction to be realised either. More generally, I also wonder just how much interest there is in running PowerShell on GNU/Linux systems...

That said, I still think PowerShell direct is worth a look - if for curiosities sake only. However, I am slightly concerned that there doesn't seem to have been much further work done on PowerShell Direct since its debut in 2016 - at least there doesn't seem to be have been too many articles or 'insider' blogs talking about PowerShell Direct since then. Of course I could be wrong and Microsoft could well be actively extending PowerShell Direct... 

Given the currently limited usage scenario e.g. Windows 2016 and Windows 10 Host/Guest combinations on Hyper-V only, I'm not sure the amount of effort in building a new provisioner to implement this would be worth the return.
