### ISSUE TITLE
-force command should only delete image AFTER provisioners are run.

### ISSUE THREAD

**Issue by jabbera** [hashicorp/packer#6399]
Azure: It would be good if the existing managed image was only deleted, via -force, after the VM is provisioned and generalized, but right before image creation. This way the existing image is available while the new image is being built. Also, if there is a transient error building the image, the existing image is not deleted! I'm basically stuck writing a script that does a delete\copy step after the fact and I can't imagine I'm the only one.

Thanks for listening!

**Comment by ladar** [comment]
@jabbera I think you have the `-force` option all wrong. In most cases, Packer uses the `name` value to set the either VM name/output directory. Either way, those values are usually static. The `-force` flag exists to tell packer it can unregister and delete those VMs rather than fail.

I'm not an expert on the Azure builder, but can't you add `{{timestamp}}` to the end of the image name (or some other field), so you avoid this problem? If you need a predictable value, then use the `{{timestamp}}` strategy to build the image, and then overwrite the predictably named image as a post processor step. Me thinks Jar Jar would use a `shell-local` step to perform the overwrite.

**Comment by ladar** [comment]
See #6296.

**Comment by jabbera** [comment]
Hi,

Force does exactly what I think it does, for the azure builder at least. It allows image creation to being even if the destination image exists already. Per below the only thing that would prevent a new image from building is a destination image existing. I could use a time stamp, but would prefer not to. Moving resources is time consuming and the process I’m building images for expects a fixed name format. (Not within my control)

Forces a builder to run when artifacts from a previous build prevent a build from running. The exact behavior of a forced build is left to the builder. In general, a builder supporting the forced build will remove the artifacts from the previous build. This will allow the user to repeat a build without having to manually clean these artifacts beforehand.
