### ISSUE TITLE
Windows hangs due to old VMWare hardware version

### ISSUE THREAD

**Issue by discentem** [hashicorp/packer#6459]
- `packer version`
1.2.4
- Host platform
macOS 10.13.5
- Debug log output from `PACKER_LOG=1 packer build template.json`
I don't believe this is relevant
- The _simplest example template and scripts_ needed to reproduce the bug.
`packer build windows_10.json` from my repo: https://github.com/discentem/bk_packer_win10
- The issue: 
Windows hangs due to Packer defaulting to an old VMWare hardware version. 
<img width="890" alt="windows hangs" src="https://user-images.githubusercontent.com/2560432/42338429-d0c6135c-8057-11e8-9257-aade0c23f846.png">

- Resolution
I'm able to resolve by manually changing the hardware version. I'd rather not have to manually change it. 

![packer-vmware-iso hardware version](https://user-images.githubusercontent.com/2560432/42338726-c744d736-8058-11e8-9eb0-977e5afd3f9a.png)

Why is the hardware version old by default? is there hard to fix?

**Comment by rickard-von-essen** [comment]
Just set [version](https://www.packer.io/docs/builders/vmware-iso.html#version) Default is `9`.

**Comment by discentem** [comment]
Oh, good catch @rickard-von-essen. Thanks! I am still curious why the other version are not officially tested (according to the documentation you linked)?

**Comment by DanHam** [comment]
> Why is the hardware version old by default

@discentem This is to allow Packer to build VMs on older versions of VMware products. For example VM Hardware version 9 is the highest hardware version that ESXi 5.1 can support. See [HERE](https://kb.vmware.com/s/article/1003746) for the hardware versions supported by VMware product version.

Generally speaking, you should set `version` so that your VM is compatible with the oldest VMware product you intend to use your VM on e.g. If I set the Hardware version to 11, I could run the VM on ESXi 6 and up, and Fusion 7.x and up.

If you only intend to run on one VMware product, set `version` to the latest Hardware version supported by that product.

> I am still curious why the other version are not officially tested

I'm guessing that documentation could be changed - I don't think that's been meaningfully updated since 2015! Since then, I'm sure plenty of people have successfully used the VMware builder with VM hardware versions > 9!

**Comment by discentem** [comment]
I guess most people aren't running production Packer builds in Fusion (I'm not either haha). And I'm assuming people aren't seeing freezing for Hardware Version 9 on other platforms. So we can close this issue?

**Comment by DanHam** [comment]
> And I'm assuming people aren't seeing freezing for Hardware Version 9 on other platforms.

At a guess, it's possible your seeing a freeze because your config specifies hardware that's only supported/works with a more recent Virtual HW version.

Personally, I haven't experienced a freeze with my builds (all use Hardware Version 9). I have had to upgrade the HW version though - this was to allow Hyper-V to run 'nested' under VMware. Windows does seem to be more sensitive to HW version than other OSes...

> So we can close this issue?

If you are happy, yes, go ahead and close.

Good luck with your builds!

**Comment by discentem** [comment]
Thanks for the info @DanHam! cheers.
