### ISSUE TITLE
Show SSH/WinRM IP address while waiting

### ISSUE THREAD

**Issue by dglinder** [hashicorp/packer#6491]
Enhancement request:

Can the "Waiting for SSH to become available..." output in https://github.com/hashicorp/packer/blob/master/helper/communicator/step_connect_ssh.go be updated to include the SSH IP address and port that Packer is trying to connect to?

I believe this is shown when run in debug mode, but that produces a lot of extra output that isn't usually needed and the ability to quickly check that the address/port is viable.  Good sanity check for casual users to validate their build process is working, especially in cases where local firewalls (corporate enforced) might be impacting communications with new VMs.

**Comment by SwampDragons** [comment]
Thanks for opening this issue -- this seems like a nice idea!

**Comment by arizvisa** [comment]
Would it be better to add the output of the host/port in `helper/communicator/step_connect.go` so both communicators (and future ones) are supported? Or would it be best to just dump the configuration for each individual communicator?

Was asking because I have a debugging patch somewhere that clocked the execution of the communicator "substep" in `helper/communicator/step_connect.go` when I was trying to figure out why the winrm (really winrmcp) performance was so shitty. I can clean it up and just add some more output to that communicator step as it's one of the few steps that communicates externally and doesn't output anything about what it's doing...

**Comment by dglinder** [comment]
@arizvisa That makes more sense - I only use the SSH communicator, so I tracked down where it would work there.  Your idea is more applicable to the other existing and new communicators.

**Comment by arizvisa** [comment]
I removed some of the timing things from my older patch and submitted PR #6559 which should emit the host that will be connected to.

With regards to emitting the port number, it seems like it's based on the communicator type (in the substep) and so to do that, it seems like we'd need to refactor it and consolidate the port number code so that it's reachable from the primary step (I think we'd need to like partially run the step, or "calculate" it and expose it from the substep). That seems like unnecessary complexity for a minor aesthetic so it just outputs the target host for now.
