### ISSUE TITLE
Building an AMI on top of Windows 10 - Packer does not wait for commands to finish

### ISSUE THREAD

**Issue by philwinder** [hashicorp/packer#6499]
`Packer v1.2.4` on `OSX`, gist [here](https://gist.github.com/philwinder/21c51635a2b7ff1eb06b32f513a9d45c).

Problem:
When building on top of a custom built Windows 10 image (from a windows iso, exported to AWS as an AMI), packer does not wait for some Powershell scripts to finish before moving onto the next step.

Expected behaviour: 
It should wait for the Powershell script to finish before moving to the next step.

Details:
- My main problem is when running `choco install` packer does not wait for it to finish. So subsequent steps fail because dependencies are not installed.
- According to the choco logs, it is still running in the background. So adding a suitable sleep after running the install command works.
- I haven't found another command that similarly fails, so it may be something to do with the way the `choco install` command runs.
- Tested scripts/code manually on the same windows image and it works; the Powershell terminal does wait for it to finish.
- Also tested on Windows server and *did not* see the same problem.
- Doesn't matter whether you copy Powershell files or run them inline, same issue.
- The gist shows that packer did receive an exit code from the RPC client. I'm not sure if this is packer misinterpreting something or choco really sending an exit code.

Recreate:
I can't provide a nice recreation script, because it uses a Licensed Windows 10 ISO. I'm hoping that someone has experience using choco/packer and has some ideas.

Also cross-posted as a choco issue.

**Comment by DanHam** [comment]
@philwinder 

I took a quick look at the gist you provided.

```
2018/07/17 11:18:33 ... Elevating permissions and running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\admin\AppData\Local\Temp\chocolatey\awscli\1.15.59\AWSCLI64-1.15.59.msi" /qn /norestart /l*v "C:\Users\admin\AppData\Local\Temp\chocolatey\awscli.1.15.59.MsiInstall.log" ] ...
```

That tells us that the Chocolatey install script is using msiexec to install the awscli. The problem with this is that msiexec immediately returns control back to the calling process and then runs in the background. In other words the install script won't wait for msiexec to finish installing the package before moving on. Clearly this means the Chocolatey installer, and the PowerShell script that wraps it, then complete and Packer moves on to the next script or provisioner before the system is actually ready...

If you were installing awscli directly with PowerShell (rather than using PowerShell + Chocolatey) the solution would be quite straight forward - see [HERE](https://kevinmarquette.github.io/2016-10-21-powershell-installing-msi-files/) for a neat explanation of using `Start-Process -Wait` to solve this particular problem. I'm no expert on Chocolatey, but perhaps there's a similar flag to ensure the install completes before moving on that you could make use of.

I can't explain why you don't see the same problem on Windows server. I can only think that the chocolatey installer might differ between platforms somehow.

Long and short I think this is a problem is being caused by the chocolatey installer rather than being a Packer issue

**Comment by philwinder** [comment]
Thanks @DanHam. Yes, I think you're right. After more debugging yesterday I also saw the msi being installed and assumed that it was returning before it had finished.

The simplest workaround is to install the msi's manually, so you have full control over the `-Wait`. Unfortunately, I couldn't find a choco setting that would magically wait for MSI's to finish.

Thanks for your time.
