### ISSUE TITLE
 https WinRM Timeout error with and "winrm_insecure": removed

### ISSUE THREAD

**Issue by spursn17uk** [hashicorp/packer#6592]
i have a packer build which works fine with "winrm_use_ssl": true,"winrm_insecure": true, however if i remove "winrm_insecure" the builds fails with WinRM timeout.

bootstrap win

<powershell>
netsh advfirewall set allprofiles state off

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse

Set-Item WSMan:\localhost\MaxTimeoutms 1800000
Set-Item WSMan:\localhost\Service\Auth\Basic $true

$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

</powershell>

**Comment by SwampDragons** [comment]
Thanks for reaching out! In the future, questions are best sent to the mailing list (https://groups.google.com/forum/#!forum/packer-tool) and we normally save GitHub issues for bugs and feature requests. In this case, I believe this is happening because you're using a self-signed certificate. If you want to be able to turn off "insecure" you need a real certificate.
