### ISSUE TITLE
Opaque error message when invalid value passed to kms_key_id

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/packer#6599]
I received the following error when I copied too much of the ARN of a KMS key, resulting in an invalid value being passed to `kms_key_id`:

"Build 'amazon-ebs' errored: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state"

I suspect that validating the existence of the key would be problematic due to potential access issues. Alternatively, it would be useful to receive an error with more details about the failure mode. I understand that the status returned by AWS ("Copy image failed with an internal error") leaves something to be desired as well, but even returning the actual status of the AMI copy would be helpful in this case. It might also be worthwhile to add a short blurb similar to the following:

"This may be caused by invalid values being passed to the CopyImage request. Please validate the values in the requestParameters block of the request in CloudTrail."

**Comment by tomelliff** [comment]
This just bit us when we were missing the `alias/` prefix from the `kms_key_id` and we were originally thrown because we were also using it in combination with the AMI Copy post processor so ended up looking for the issue there instead of here.

It looks like it could be added to the validations performed in `Prepare` in `builder/amazon/common/ami_config.go`:

https://github.com/hashicorp/packer/blob/9d32a75104f66cc454d2d525c7698731719b6fda/builder/amazon/common/ami_config.go#L42-L95

**Comment by farvour** [comment]
I encountered this. Turns out it wasn't that my KMS ARN was invalid, simply that I didn't have the `kms:Encrypt` operation being allowed on it for the IAM instance profile it was running on. I agree though, AWS's API error leaves a lot to be desired on the true cause of why the CopyAMI call fails due to insufficient KMS privilege, not even an STS decode payload to use.
