### ISSUE TITLE
Feature Request provisioners loop

### ISSUE THREAD

**Issue by agowa338** [hashicorp/packer#6681]
Currently there is no loop in inside of the provisioners block, with this ticket I want to request having the possibility to write something like:

```
"provisioners": [
  {
    "type": "DoUntilFileExists",
    "check_file": "C:/Windows/Temp/DoUntilUpdateCompleteCheck"
    "provisioners": [
      {
        "type": "powershell",
        "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';. {{.Vars}};. {{.Path}}; exit $LastExitCode",
        "script": "./scripts/Install-WindowsUpdates.ps1"
      },
      {
        "type": "windows-restart"
      }
    ]
  }
]
```

## Example
when handling windows servers, there are cases when one does not know how often to restart the server, as it could be 3-4 or even 10 times. Therefore I want to have something that loops the script until a break condition is met (like look until a file exists or a separate check script returns a specific exit code)

Currently I've to use this workaround:

```
"provisioners": [
{
    "type": "shell",
    "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Invoke-Expression -Command (Get-Content -Path '{{.Path}}' -Raw); exit $LastExitCode",
    "skip_clean": true,
    "remote_folder": "C:/Windows/Temp",
    "expect_disconnect": true,
    "script": "./scripts/Install-WindowsUpdates.ps1"
  },
  {
    "type": "shell",
    "pause_before": "60m",
    "start_retry_timeout": "60m",
    "remote_folder": "C:/Windows/Temp",
    "skip_clean": true,
    "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Invoke-Expression -Command (Get-Content -Path '{{.Path}}' -Raw); exit $LastExitCode",
    "script": "./scripts/Start-CleanUp.ps1"
  },
]
```

this workaround has the following problems:
 - The Install-WindowsUpdates.ps1 Skript is rebooting the server, leading to packer loosing connection
 - Packer does not know if the Updates already completed or if the server reboots once more.
 - Currently the next task requires a "pause_before" step, but it is not known if the former script already finished, or if it is still installing updates
 - the powershell executor cannot be used as it is missing "pause_before", "skip_clean" and "expect_disconnect" functionality like used in the above workaround.

**Comment by SwampDragons** [comment]
Hi! Thanks for opening an issue. 

Generally speaking, people deal with the windows update nondeterminism by providing their windows update script as a floppy file, so that it runs before the communicator connects and before provisioners run. By installing SSH or enabling winRM after your windows update script runs, you guarantee that you aren't going to accidentally start provisioners before you're ready. Here's an example: 

https://github.com/joefitzgerald/packer-windows/blob/master/windows_10.json#L23-L24

I can see why you'd want this feature but the Packer template isn't meant to be a programming language. I think that adding a loop feature to the provisioners makes some pretty dramatic changes to user expectations for what a Packer provisioner should be, and in your particular case I think it's overkill.  I'll think about it some more but for now I'm going to close this since it isn't something I will be putting on the roadmap.

**Comment by agowa338** [comment]
> I think that adding a loop feature to the provisioners makes some pretty dramatic changes to user expectations for what a Packer provisioner should be, and in your particular case I think it's overkill

I think having a loop feature is exactly what is necessary here, but maybe I should provide you more context why I want to handle windows updates in the provisioner and not before. My goal is to have the whole packer "playbook" in a gitlab repository with a configured trigger and a runner that than periodically (once a month) executes it and generates new templates. For that I want to have as much output inside of gitlab ci section. And for that to be the case it needs to be thrown at stdout or stderr by packer. If I handle updates before the provisioner runs one has no idea why a build failed (if there is a failing update, which happens from time to time), by simply looking at the GitLab Webinterface.
And if packer would have such a loop feature I would be able to see exactly which update it was attempting to install before it failed and packer deleted it.
