### ISSUE TITLE
Feature Request: Optional upload sources

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/packer#6699]
We're trying to re-use a standard packer template for many of our applications.  As such, we wish to set a standard directory to upload, which depending on the application using this template, may or may not exist.

For instance, our packer template may have:

```json
"provisioners": [
  {
    "destination": "/ops/",
    "source": "./upload-me/",
    "type": "file"
  }
]
```

In the directory from which we run this template, the `./upload-me` directory may or may not exist.  

Right now, packer will fail if this directory does not exist.  We've tried wildcards, ie `./*/`, etc, which selects the correct directory with `ls`, but not with packer.

We're proposing that packer either honors wildcards as filesystem commands like `ls` do, or add a new `ignore_missing` option to ignore missing sources, ie

```json
"provisioners": [
  {
    "destination": "/ops/",
    "source": "./upload-me/",
    "type": "file",
    "ignore_missing": true
  }
]
```

**Comment by SwampDragons** [comment]
Thanks for opening an issue :)  I can see how this would be useful in your particular use case but I am really hesitant to add it. In general, Packer templates shouldn't be shared if the final images are not going to be comparable to one another. If we add an "ignore_missing" flag Packer becomes nondeterministic really fast. Same for supporting globbing. I think the potential for misuse resulting in improperly provisioned vms is pretty high, which makes this feature contradict Packer's philosophy. 

That said, I think you can accomplish what you want by running the shell-local provisioner before your file provisioner, with a script that checks whether "./upload-me/" exists locally, and, if not, generates a dummy file to use in its place. Then you can use the "generated" flag with the file provisioner to make sure it doesn't fail on validation when the file doesn't exist.

I'm telling you this because I want you to have a workaround but I'm concerned that ultimately this kind of hack is going to bite you, and that you'd be better off using different Packer configs that are more tailored for their specific builds.

Thanks!
