### ISSUE TITLE
Amazon EBS Builder's Temporary Security Group is open to 0.0.0.0/0

### ISSUE THREAD

**Issue by thomasbiddle** [hashicorp/packer#6735]
Packer Version: 1.2.0
Host Platform: Ubuntu
Builder: Amazon AWS

I realize it's a temporary instance; but still - Would be much better to just tie this to the public IP of whatever instance the host is; rather than opening it to 0.0.0.0/0

I just had my automated security rule go off from Cloud Custodian stating that an open security group was created. Would actually be a nuisance once we setup automation to delete these security groups immediately when created.

**Comment by rickard-von-essen** [comment]
> public IP of whatever instance the host is

There is no reliable way of determining a hosts "public IP" (which is actually not a well specified term).

So `0.0.0.0/0` is our only option. If you know where all your valid host are located you can use [`temporary_security_group_source_cidr`](https://www.packer.io/docs/builders/amazon-ebs.html#temporary_security_group_source_cidr) to limit this further.

If you really want to please security/Cloud Custodian, use a predefined `security group` instead of the temporary.
