### ISSUE TITLE
communicator.go stdout_w/stderr_w should not be closed twice

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#6834]
The following code is closing stdout_w and stderr_w:

https://github.com/hashicorp/packer/blob/cdc6c57b311ce3daa68a9983b0b5eba9eb5c9dfc/packer/communicator.go#L93-L94

BUT those are also being closed at:

https://github.com/hashicorp/packer/blob/cdc6c57b311ce3daa68a9983b0b5eba9eb5c9dfc/packer/communicator.go#L133-L134

I guess the later closes should be removed.

**Comment by SwampDragons** [comment]
Huh, good catch. I'll look at the history and see how this happened.

**Comment by SwampDragons** [comment]
Okay, I looked into this. My conclusion is that it probably should stay how it is. 

There shouldn't be any ill effects from calling Close() on pipes twice; they aren't like channels, which would cause a panic if closed more than once. (If this code did cause panics, we'd probably know by now because this is a _very_ core piece of code; both instances of Close() have existed since this code was written five years ago). That first defer is there to clean up in case we never make it to the goroutine that actually calls Close(), but every time a provisioner runs and works as expected, Close() is being called both from the defer within the goroutine and the defer at the beginning of StartWithUI(), with no apparent problems.

I thought about whether we're losing anything by calling Close() twice. Theoretically, if we were calling CloseWithError() with a custom error from the goroutine, we'd be losing that information when we call Close() the second time because it'd be overwriting the error with an EOF, but that's not how we're doing it here; it's an EOF no matter what.

So I think removing that first Close() would actually break things in the case that something errors during the setup work being done in StartWithUI(), and that we should keep it. 

Thanks for bringing this up though! It made me do some research into pipes and learn a few things in the process :)

**Comment by rgl** [comment]
I was talking about removing the second set of closes. That is, the go routine should only close exitCh. But now looking more at it, the second set of closes is needed for another reason, indirectly closing the stdoutCh/stderrCh for breaking these loops:

https://github.com/hashicorp/packer/blob/cdc6c57b311ce3daa68a9983b0b5eba9eb5c9dfc/packer/communicator.go#L155-L163

So I guess all is well :-)

**Comment by SwampDragons** [comment]
Oh, yeah the second set are necessary or we'll never return from the command.
