### ISSUE TITLE
Crash when try to upload in a folder without permissions

### ISSUE THREAD

**Issue by avegao** [hashicorp/packer#6870]
I've found a bug when you try to upload a file in a folder that you haven't permissions. Without debug mode, Packer crash; but in debug mode Packer return the error and catch the exception and remove the Resource Group.
  
* Packer version: `Packer v1.3.1`
* Host platform: `macOS 10.14`
* Cloud: `Azure`
* VM OS: `Ubuntu Server 18.04-LTS`
* Crash log: [https://gist.github.com/avegao/73cf16bbcb8c76be0cac769ab1f8a1c1](https://gist.github.com/avegao/73cf16bbcb8c76be0cac769ab1f8a1c1)
* Debug log: [https://gist.github.com/avegao/061ebde9cb791954a83b7df39985a933](https://gist.github.com/avegao/061ebde9cb791954a83b7df39985a933)

**Comment by azr** [comment]
Hey Álvaro, thanks for reporting !

I believe this was fixed in #6851, my guess would be that this error happened a bit randomly for you; but can you please tell me if this build of master fixes it for you ?

[darwin_amd64_packer.zip](https://github.com/hashicorp/packer/files/2487252/darwin_amd64_packer.zip)

Thanks.

**Comment by SwampDragons** [comment]
Closing since we haven't had a response; if you are still experiencing this issue, let us know here and we can reopen.
