### ISSUE TITLE
Encrypted EBS conflict error from AWS

### ISSUE THREAD

**Issue by rysch242** [hashicorp/packer#6889]
We run packer nightly to generate new AMIs for our ECS cluster instances as the first step in a patch management strategy we have for keeping our ECS instances up to date. Recently (10/16/2018), the job began failing despite no changes being made to our template or code. The error is:

Error creating AMI: InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device /dev/xvda has a conflicting encryption setting.
  
It seems like perhaps AWS has changed something in their API to reject the request that packer is making. When I did a debug step through, it appeared that the only conflicting setting was that the volume was already encrypted. I don't think this is a misconfiguration on our side since this seems to be a fairly textbook use packer for encrypting an EBS volume.

Packer Version: Packer v1.3.1
Host platform: CentOS Linux release 7.3.1611 (Core)
Debug Log Gist: https://gist.github.com/rysch242/883f2b5d2e230e962c1530c7ca5c83fb
Template gist: https://gist.github.com/rysch242/0272ac25352b6e0b138bd629e3f46e26

**Comment by azr** [comment]
Hello @rysch242, thanks for reporting, this should be fixed by #6787; which we have planned for version 1.4.0.
If you decide to use that branch; you should not pass any encryption setting as the volume is already encrypted; encryption setting will remain.

In then meantime you can probably use a build of packer from that branch. I will try to keep the branch up to date with master.

Related: #6778 #6762

**Comment by rysch242** [comment]
I'm not sure I follow your suggestion. I'm basing my packer build on an AMI with an unencrypted root volume (Amazon Linux ECS Optimized) and adding a new encrypted ECS volume. If I were to not pass any encryption setting for either the root or the additional ECS volume, it'd result in an unencrypted volume in my AMI, which is what I'm trying to avoid. Could you give me an example template doing what you're suggesting?

**Comment by WeekendsBull** [comment]
@azr I have the same issue described here and please let me know if there is any fix or a new build I could verify the fix. 
Thank you!

**Comment by azr** [comment]
Here is a build of packer on that fix branch :
[packer_darwin_amd64.zip](https://github.com/hashicorp/packer/files/2506035/packer_darwin_amd64.zip)
[packer_linux_amd64.zip](https://github.com/hashicorp/packer/files/2506037/packer_linux_amd64.zip)
[packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/2506041/packer_windows_amd64.zip)

@rysch242; the error message I see is :
> the encrypted flag cannot be specified since device /dev/xvda has a conflicting encryption setting.

This new build of packer allows to not set the encryption setting, so that we keep whatever was set.

Now your problem is different; you would like to encrypt that unencrypted drive.
Let me run some tests to see what I can do.

**Comment by azr** [comment]
Okay, so going around in the aws console and booting machines, it turns out `/dev/xvda` is the root drive, and you cannot set it to encrypted this way.

Screenshot booting an `amazon-ecs-optimized` image from aws.amazon.com :
![screenshot 2018-10-23 at 16 39 27](https://user-images.githubusercontent.com/1024852/47368674-5a419300-d6e2-11e8-9095-7532cb6d0930.png)

When you set `"encrypt_boot": true` then the boot drive `/dev/xvda` will be encrypted in the resulting ami and you wont need to set `ami_block_device_mappings` for `/dev/xvda`

Screenshot booting an ami resulting from an `amazon-ecs-optimized` with `"encrypt_boot": true`:
![screenshot 2018-10-23 at 16 39 27](https://user-images.githubusercontent.com/1024852/47369163-61b56c00-d6e3-11e8-9eb3-5b3b2ea57503.png)

So a correct resolution would be to just remove the `ami_block_device_mappings` setting from the build file.

**Comment by rysch242** [comment]
Ahh, this makes sense, thank you for researching it so thoroughly. As you say, the issue was that I was specifying `encrypt_boot` as well as explicitly specifying that the root volume be encrypted  with `ami_block_device_mappings`. The confusion on my part was due to inheriting this packer config from someone else and believing that the `ami_block_device_mappings` was how we were attaching a second EBS volume to the AMI during build when in fact the ECS Optimized AMI already includes the second EBS volume. Removing the `ami_block_device_mappings` section entirely as you suggested allowed packer to build correctly and create an AMI with both volumes encrypted. Thanks so much for the effort and sorry for the errant bug report!

**Comment by WeekendsBull** [comment]
@azr @SwampDragons In my case, I saw kms:GenerateDataKeyWithoutPlaintext was required in the IAM permission that "encrypt_boot": true was getting denied and failed which you can find the traces from Cloud Trail using by user name and i-xxxxxxx of the packer build instance. Once I have added the KMS permissions things are done successfully.

**Comment by azr** [comment]
No problemo 🙂

**Comment by WeekendsBull** [comment]
@azr @SwampDragons need to get some help to resolve this error with "Error creating AMI: InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device xvdb has a conflicting encryption setting"

We built monthly to release a new AMI but I'm kind of trouble to release Windows AMIs due to the issue. I don't have trouble to create on AWS-ECS and Centos7 after identifying necessary IAM role permissions. However, Windows AMI can't be built currently.

I'm on Packer v1.2.3 (tested out 1.3.2-dev you guys provided me)
Templates and log files are uploaded at https://github.com/WeekendsBull/packer_debug/

Please understand that the actual values currently are using replaced by a x or multiple xxx for the public view. 

Both ECS and Centos7 works with "ami_block_device_mappings" in the template as you can see.
https://raw.githubusercontent.com/WeekendsBull/packer_debug/master/aws_ecs.json
https://raw.githubusercontent.com/WeekendsBull/packer_debug/master/centos7_packer.json

v1.2.3 and v1.3.2-dev both worked and there is the log file.
https://github.com/WeekendsBull/packer_debug/blob/master/centos7_packer_debug_v1.2.3_log

However, 
https://github.com/WeekendsBull/packer_debug/blob/master/win2012r2_failed_encrypt_setting.json, encryption is getting failed on both packer v1.2.3 (https://raw.githubusercontent.com/WeekendsBull/packer_debug/master/win2012r2_sysprep_packer_debug_v1.2.3_log) and v1.3.2-dev (https://raw.githubusercontent.com/WeekendsBull/packer_debug/master/win2012r2_sysprep_packer_debug_v1.3.2-dev_log). 

Please let me know if there is any new build or something I could try to make this working. 

Thank you guys always in advance.

**Comment by frank3427** [comment]
I does one create an image with boot and a second volume encrypted when the source image only has one volume (boot)?

**Comment by azr** [comment]
Hello @frank3427, you have to set the `ami_block_device_mappings`.
I recommend asking questions in [packer's mailing list](https://groups.google.com/forum/#!forum/packer-tool)

Also some good reads:
https://www.packer.io/docs/builders/amazon-ebs.html#ami_block_device_mappings

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
