### ISSUE TITLE
Hyper-V : clone_from_vmcx_path VM Generation ignored

### ISSUE THREAD

**Issue by clecoutre** [hashicorp/packer#6908]
Hello,

Here are the packer and windows versions :

- Packer v1.3.2
- Windows 2012 R2

I have an issue with Packer Hyper-v builder "clone_from_vmcx_path" :
I have set the option VM generation 2 in my packer template, but packer is still considering the VM generation as 1, so it's trying to Unmount the floppy drive and failed with the following error :

> ==> hyperv-vmcx: Unmount/delete floppy drive (Run)...
> ==> hyperv-vmcx: Error Unmounting floppy drive: PowerShell error: Hyper-V\Set-VMFloppyDiskDrive : A parameter is invalid. Generation 2 virtual 
> ==> hyperv-vmcx: machines do not support Floppy drives.

Here is the builder part of my packer template :

[packer-template.txt](https://github.com/hashicorp/packer/files/2509920/packer-template.txt)

Thank you,
Christophe

**Comment by azr** [comment]
Hello Christophe, thanks for reporting, this totally sounds like a bug.

It's weird because there is a check for this:

https://github.com/hashicorp/packer/blob/95d107a89c2a8be3df04fb9d2b841513b5671b44/builder/hyperv/common/step_unmount_floppydrive.go#L15-L24

Could you please send us the full log ? I will try to read code in the meantime.

**Comment by azr** [comment]
Almost similar, check the pr #6909, so sorry I put the wrong issue number in there

**Comment by clecoutre** [comment]
Perfect, thanks a lot !

**Comment by azr** [comment]
Great, merging #6909 thanks for your time
