### ISSUE TITLE
AMIs created as public by default – should be private

### ISSUE THREAD

**Issue by AndiDog** [hashicorp/packer#6915]
Packer v1.3.1's amazon* builders have no configuration to make AMIs private (which they should be by default). From quick glance, I don't even see that feature in aws-sdk-go or else would have sent a PR.

**Comment by eedwards-sk** [comment]
An AMI I created, with 1.3.1, using the [official hashicorp consul template](https://github.com/hashicorp/terraform-aws-consul/blob/master/examples/consul-ami/consul.json) appears to be private by default.

Sounds like a configuration issue or authentication issue somewhere?

Here's the documentation on public AMIs, for reference: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html

**Comment by SwampDragons** [comment]
Hi @AndiDog; builders do have this configuration, but it isn't called "private".  

By default, Packer only gives launch permissions to the user that created the AMI.  If you are not seeing this behavior, please share your config so that we can reproduce and fix it. 

Before you do so, make sure that you don't have the option [ami_groups](https://www.packer.io/docs/builders/amazon-ebs.html#ami_groups) set to "all", which would cause the behavior you're describing.

If you want to share the ami with specific users that are not the account that created it, you can use the [ami_users](https://www.packer.io/docs/builders/amazon-ebs.html#ami_users) option.

**Comment by AndiDog** [comment]
Makes sense now. The documentation didn't name the words "private" or "public", so I didn't see that config immediately. I actually had `ami_groups=all` (probably copied from a bad source). Thank you!
