### ISSUE TITLE
Error : Using Packer with Windows 2016 CIS Benchmark (Hardened) AMIs

### ISSUE THREAD

**Issue by manzil007** [hashicorp/packer#6951]
Hi Team,

I am not able to build image with packer for windows 2016 cis server 
•	If I use the regular version of Windows 2012, the script works and Packer can connect to the instance. But I have not been able to make it work with this "Hardened" version
•	I read the Packer documentation and there is a way to change the Authentication mechanism by setting the field "winrm_use_ntlm" to True. I tried doing that but Packer is still timing out when it tries to connect to the instance via WinRM.

Could you please suggest me the solution for this ?

Thanks in advance 

  
![image](https://user-images.githubusercontent.com/14828890/47915786-f7ae7b00-dec9-11e8-8be1-413b5ee48f6a.png)

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by nbshetty** [comment]
Mine is a similar use case as above basically building AMI from "CIS Microsoft Windows Server 2016 Benchmark*Level 1*" .  So I have followed details mentioned in https://github.com/hashicorp/packer/issues/6205 to use ntlm, as basic authentication is disabled as part of the hardened image. So the builder successfully manages to create the EC2 and WinRM becomes available and we manage to run few provisioning powershell scripts, but the moment we run the Windows Restart Provisioner, EC2 instance is not reachable using Win RM and we get timeout from Packer. Win Rm Gets access denied. On the Host Windows Remote Management Event viewer indicates User Authentication Error Code 5
![image](https://user-images.githubusercontent.com/32765622/48125428-8d555c00-e276-11e8-98be-59d226d6f8ac.png)
![image](https://user-images.githubusercontent.com/32765622/48125633-0f458500-e277-11e8-887b-e5f3da0cb976.png)

**Comment by rama-arun** [comment]
Definitely still persistent with latest 1.3.3 version of Packer, CIS Microsoft Windows Server 2016 Benchmark AMI. "Windows2016: Timeout waiting for WinRM"

Please let us know of any specific entries that need to go into userdata bootstrapping to enable WinRM to be connectable. Basically undoing what CIS did to block it.

Greatly Appreciated!

**Comment by SwampDragons** [comment]
@nbshetty I don't know much about these benchmark vms, but is it possible that after a restart the winrm ports are closed again?  The fact that you are able to connect via winrm says to me that the issue is a configuration issue within the vm, not with Packer.

@rama-arun Take a look at the bootstrap script that @nbshetty shared.  Sounds like that got them going with winRM to begin with.

**Comment by SwampDragons** [comment]
I suspect that this issue is a configuration question rather than a bug with Packer, because of the fact that @nbshetty was able to connect to one of these hardened instances. For further questions on how to get started with WinRM, take a look at our docs or reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), where we have a bigger community that may have people who can answer your questions better than me.
