### ISSUE TITLE
Enhancement: ability to "name" provisioner steps

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/packer#6968]
In the same vein as the ability to supply a `name` for builders.
Ideally something like:
```
...
  "provisioners": [
        {
          "inline": [
              "echo 'WAT'"
          ],
          "type": "shell",
          "name": "speak up"
        }
    ]
...
```
Which would appear as output during the build, akin to:
```
==> base: Provisioning step 'speak up' (shell script: /tmp/packer-shell310524688)
    base: WAT
```

(But I'd also settle for being able to leave a `"_comment"` on individual provisioners.)

**Comment by curiositycasualty** [comment]
This would definitely bolster the utility of `packer inspect ...`:
```
Optional variables and their defaults:

  build_host = {{env `HOST`}}
  build_user = {{env `USER`}}
  debug      = {{env `PACKER_DEBUG`}}
  svn_rev    = {{env `SVN_REV`}}
  timestamp  = {{isotime "2006-01-02"}}

Builders:

  base-aws (amazon-ebs)
  base-vb  (virtualbox-iso)

Provisioners:

  shell - "speak up"

Note: If your build names contain user variables or template
functions such as 'timestamp', these are processed at build time,
and therefore only show in their raw form here.
```

**Comment by azr** [comment]
Hey @curiositycasualty, that's a very good suggestion; I don't think the packer team will have time for this any time soon, but PRs are always welcome 🙂!

I would start by adding a `Name() string` or `String() string`  to the provisioner interface: 

https://github.com/hashicorp/packer/blob/b01f4a61f8b16815521f4feb278dbc98536f162f/packer/provisioner.go#L10-L28

Then the compiler should be a good guide.

**Comment by curiositycasualty** [comment]
Closing own stale issues.

**Comment by mloskot** [comment]
@aford-bgsa Here in https://github.com/hashicorp/packer/pull/10174#issuecomment-781595012 is response from @SwampDragons 

> Since we're trying to move users off of JSON and onto HCL templates now, I think it's probably better to skip this PR and focus our energy on the HCL templates. 

which, to me, is confusing. Although that PR subject says JSON, content of it seems to be applicable to HCL templates too.
Pity that PR was just closed without any suggestions, instead of offering help to turn it into acceptable HCL-only implementation. The provisioners name feature is very much still desired - instead of logging numerous lines like these
```
Provisioning with Powershell...
Provisioning with powershell script: /tmp/powershell-provisioner2263360933
```
Packer could equally spit out empty lines, from a human perspective.

_p.s. I'm not necromancing here, but trying to keep single place of discussion, instead of spawning new issue_
