### ISSUE TITLE
vsphere-template post-processor maybe should not enforce folder parameter bound to root

### ISSUE THREAD

**Issue by yves-vogl** [hashicorp/packer#6975]
Hi,

as I understand path.Join there should be automatically concatenated a slash inbetween dcPath and folder (https://github.com/hashicorp/packer/blob/master/post-processor/vsphere-template/step_create_folder.go#L25)

Can you explain why the binding to root is enforced?
https://github.com/hashicorp/packer/blob/b01f4a61f8b16815521f4feb278dbc98536f162f/post-processor/vsphere-template/post-processor.go#L72

Thank you!

**Comment by SwampDragons** [comment]
Maybe @bugbuilder has some context on that for us.

**Comment by bugbuilder** [comment]
Hi @yves-vogl,

You're right, the folder bound to the root doesn't do any effect at code level, that was because the[ first implementation ](https://github.com/bennu/packer/blob/2ddc07d3b9a84f59e65a6cc0fafd68db158645f5/post-processor/vsphere-template/step_create_folder.go#L43)used to use that, sadly I forgot to remove it when I changed it.

**Comment by yves-vogl** [comment]
Thanks for your reply. No problem - I'd really love to fix this and submit a pull request to get used to contribution. I'd be happy if you could guide me.

**Comment by bugbuilder** [comment]
Sure! no problem just ping me!

**Comment by Spuffnduff** [comment]
Any update on this request?  I'd like to not have the error when I do validation checks.

**Comment by SwampDragons** [comment]
Looks like there has been no movement; PRs are welcome.
