### ISSUE TITLE
Feature Request: required variables settable through environment

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [hashicorp/packer#6988]
Right now we can either specify a user variable as `null` which means it's required and it can only be set using the CLI option, or we can use ``{{env `foo`}}`` to make it settable through the environment. I am missing an option to set a variable as required, with the option to set it through the environment.

Sidenote: Terraform offers this functionality. There all variables are required by default and can be set using the `TV_VAR_` prefix for environment variables: https://www.terraform.io/docs/configuration/variables.html#environment-variables

**Comment by SwampDragons** [comment]
So to clarify, you want to be able to have Packer check for environment variables if the variable isn't already set inside your packer config?

**Comment by SwampDragons** [comment]
Okay, I can see the benefit of that. It's a good idea. Off the top of my head, I'm not totally sure how easy it will be to implement because of the way Packer's architecture handles variables, so I'll have to take a look at that before deciding if it's something we can prioritize soon. 

Meanwhile, have you considered using a `var-file`? This solves the issue of long and non-generic command lines, and gives you a fair amount of flexibility.

**Comment by SwampDragons** [comment]
I think we may get this behavior "for free" as part of the HCL2 config effort that we're hoping to land this year.

**Comment by azr** [comment]
Hello there this is implemented in #8588; only for hcl2 but basically after defining a variable; one will be able to set it by setting an env var like so: `PKR_VAR_variablename`.
