### ISSUE TITLE
Ask Vault to generate AWS creds on the fly

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/packer#6994]
Terraform has a very nice feature, which comes from the provider `vault_aws_access_credentials`. That provider asks Vault to generate a new temporal IAM user and return the credentials of that user to Terraform.

It would be very useful if Packer had the same kind of provider.

**Comment by SwampDragons** [comment]
This is absolutely something we'd like to implement some time in the future.

**Comment by alexandernst** [comment]
In the future as in later today or tomorrow? :smile:

**Comment by SwampDragons** [comment]
Hah! If you want to implement it later today, knock yourself out. 😝

**Comment by alexandernst** [comment]
I actually had a look at the code and it doesn't seem that hard. Can I get just a little bit of guidance in to where exactly should I put the new code? Maybe I can make a PR.

**Comment by SwampDragons** [comment]
I think you're right that it's not too hard. The reason we didn't implement this as part of the other vault integration, is that all of our template engine functions return a single variable. For Amazon, we'd need to return two different variables. So I decided to introduce it later and just haven't gotten around to it. 😄 

Instead of doing this as a template function like our current vault integration, we need to add a new option to the [AWS builder's access config](https://github.com/hashicorp/packer/blob/master/builder/amazon/common/access_config.go). To do that, you'll want to add a new field to the Access Config's struct, and use those mapstructure tags you see in the other fields to map that to a Packer template option, `use_vault_aws_access_credentials` or something.  Then in the Prepare() function of that same file, fix the validation and use Vault to get the and set credentials into the AccessKey and SecretKey fields.

Does that get you started? I'm happy to give more pointers if you want them!

**Comment by alexandernst** [comment]
Yes! Those instructions are more than enough (or at least I think so). 

Let me put here a small brain dump just to be easier for me to work on this:

* Terraform-provider-vault - https://github.com/terraform-providers/terraform-provider-vault
* Interesting bits: `awsAccessCredentialsDataSource`

**Comment by SwampDragons** [comment]
I am adding this issue to the 1.3.5 milestone; I'll check in on here in a couple of weeks once I've nailed down the other things that I want in this milestone and if you haven't had a chance to work on it, I'll pick it up myself :)

**Comment by SwampDragons** [comment]
I'm going to pick this task up now.

**Comment by daveadams** [comment]
Glad to see this is moving along! I'm in the middle of setting up a new service that is using Vault-created IAM credentials for automated Packer builds. I'm feeding in the credentials via environment variables right now using Vault-generated IAM users. But I'd love to see Packer more natively support Vault-generated creds of both the IAM user and STS temporary credentials types.

My main concern with STS creds and Packer has been that if the Packer run takes longer than the lifetime of the temporary credentials, then you'll get a failure, since Packer doesn't know how to renew the credentials. A custom creds provider would handle that seamlessly, but would have to be built into Packer.

Anyway, I was thinking about this and came over to check to see if there was anything about this in the Packer issues, and I found this ticket with your comment from yesterday! So, @SwampDragons, if there's anything I can do to help with this feature--testing, use cases, whatever--let me know!

**Comment by SwampDragons** [comment]
See #7282!

**Comment by SwampDragons** [comment]
@lorengordon oh that looks very cool. I'll have to read more closely and see if it can simplify our mess of credentialing.

**Comment by SwampDragons** [comment]
@daveadams the linked build works for me for IAM users but I haven't tested it with STS tokens; however, I think it should "just work" as long as the token doesn't expire during the build -- I can build you a binary if you'd like to test it out.

I will have to look at the credential_process option to see if it'd allow us to automatically renew vault-generated STS tokens.
