### ISSUE TITLE
VMware ISO: New warnings against user specified VMX settings

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#7001]
#6624 added a new function to warn users when they are overriding VMX data that 'Packer normally sets'.

Since Packer sets a fairly comprehensive/complete VMX file, it's fairly likely that the settings a user specifies in their `vmx_data` will override one or more of Packers default settings. This will generate a lot of false warnings for users. It also goes rather against the whole purpose of having the `vmx_data` option in the first place!

I appreciate the sentiments of what this is trying to achieve - namely preventing users from clobbering settings that are critical for a successful build. However, in it's present form the warning is a little too 'all encompassing'. Sometimes overriding Packers default VMX settings is 100% necessary to accomplish a successful build. 

Long and short, I'm not sure this is the right approach to take. The way the VMware builders currently work would make it very difficult to validate the `vmx_data` without generating false warnings.

I think a better approach would be to add a 'big red warning' to the documentation regarding the potential to break things with vmx_data settings.

Ping @arizvisa - interested to hear your thoughts on this.

Version: Packer v1.4.0-dev (c0d5899c3)

**Comment by arizvisa** [comment]
(this is long)

Honestly, my personal opinion would be to get rid of `vmx_data` and `vmx_data_post`. But packer has changed a lot since I first played with it and added my improvements. (I just idle around packer sometimes because I feel bad when someone else has to maintain some busted code that I wrote.)

Things like `vmx_data_post` (imnsho), should be a post-processor since it has nothing to do with the actual building and is only used by users to "lock-in" a configuration after the install, it's essentially a post-processor in disguise. Because of its existence as a build option, though, it has been completely mis-used over the years to allow people to post-process their artifacts. (I think there's one other builder exposes a similar capability too).

Next, the `vmx_data` configuration to me is a hack that I think should be tossed too. The reason being is that it's just too susceptible to misuse and easy for users to fall back on when almost always there already exists a proper way to do the sort of things that users use it for. As this option grows, it will eventually result in Packer having to comprehend the semantics of what the user is trying to use it for. Packer, though, already exposes a ton of configuration options to the user already. So the existence of this capability provides two directions for the vmware builder to have to grow. One way is where packer has to figure out how to avoid changing the semantics of what the user is trying to do, and the other way which is where packer is trying to generalize its building and expose features that are used by builders.

And actually, most of VMware's capabilities that I've seen people use `vmx_data` for are actually already supported by packer. Like disk adapters, extra hard disks, network adapter types, etc. But none of the templates I've seen actually use any of them instead preferring to rely only setting them via `vmx_data`. The only capabilities that don't exist yet (but should be) are the cpu count and the memory usage for installing the OS. If these are supported as config options, then I can't really see any reason why `vmx_data` would be needed anymore. And if some other option is needed for building, that's a perfectly good reason to submit a PR and add another configuration to vmware's builder. Plus it's nice to have only 1 document (packer.io) to customize a build instead of the combination of a .vmx reference and packer's docs.

However, the huge problem with getting rid of these is that pretty much all of us users rely on `vmx_data`. Users who're familiar with VMWare are just so used to modifying a .vmx, and so `vmx_data` really calls to them. (I was guilty of this too because I used to use `vmx_data` instead of reading Packer's docs way back when I had first tinkered with packer). My network and disk adapter patches came into existence because I realized that this "technique" of building with one .vmx files and then deploying with another .vmx was not how packer was first designed. Packer was just used for building your template. Then when you deploy with vagrant (or whatever), that next tool is then used to customize your target machine.

So, it's because of history and the user base that I really don't believe it's possible to get rid of them. My suggestions will also violently break previously existing templates. I'm not sure if backwards compatibility is one of Packer's "identities", but with how mature Packer is, breaking existing functionality with one commit doesn't seem like a courteous thing for packer devers to do to their users. It's like they're steering a giant boat to me and so everything should be done in increments. As a result of this, I believe that @SwampDragons' patch is probably the best middle-ground to start approaching this issue. Yelling at users for doing something that might interfere with packer really might be the best thing to do for now until people start fixing their templates or some other way to migrate users can be pushed.

**Comment by arizvisa** [comment]
At one point, I had some free time and tried to put some effort into deprecating the usage of `vmx_data` by modifying templates to use the correct config options for vmware-iso. I did this by going through anything that looked like a packer template repo on github and submitting PRs, I even reached out to people via irc. For most of the patches I submitted, most of them were turned down.

Still though, none of this things will fix anything nowadays because templates have been pretty much copy-pasta'd forever and since packer is already mature, there's so many "families" of templates now. I think the packer developers already recognize this too.

**Comment by DanHam** [comment]
> good to hear from you!

@SwampDragons ... even if I am moaning about something?? 😄 

> Many of these options that we warn about have recently (last year or so?) had template options added to them that do what the user wants anyway, as arizvisa pointed out

OK. So guilty as charged... most of the options I was setting via `vmx_data` can now be set via the main settings in the template... `display_name` being the latest addition.

> Yelling at users for doing something that might interfere with packer really might be the best thing to do for now until people start fixing their templates or some other way to migrate users can be pushed.

Point conceded. I've just cleaned up my templates!! 

Thanks all!

**Comment by SwampDragons** [comment]
Hah!  See?!  It works already!  😂

**Comment by arizvisa** [comment]
Yeah. I think at some point we should point out in the docs that if there's some feature that a user can only use `vmx_data` to solve (or a similar option for the other builders) that it's something that warrants a feature request. As the usage of these types of options are essentially workarounds for things that we just haven't gotten around to implementing/generalizing yet.

Plus, I'm not really sure how to word this any better than it already is in the docs exactly but somehow it needs to be made more apparent to users that Packer isn't designed wrt provisioning/deployment of VMs towards a platform, but rather it's designed wrt straight-up building the base template that is used by something else to deploy. So then tools like Terraform/Vagrant/Salt-Cloud/whatev are to be used for tweaking the configuration of the final VM. Maybe a paragraph in the docs consisting of just 300 links to Terraform would help. Heh.

I've seen a ton of open-source projects that "misuse" Packer for building \_and\_ deploying to a target infrastructure. And even though Packer is totally awesome enough to be used like this, seeing projects do it makes my hair stand up since I know it's wrong.

**Comment by SwampDragons** [comment]
Yeah we have a lot of problems for which the _correct_ answer is "Packer should not be your CI tool" but that answer makes enough people angry that we often end up saying "wellll, I guess we could do that this way..." 

Packer's greatest strength and weakness is its extensibility.
