### ISSUE TITLE
Change vmx_data_post option in vmware builders to a post-processor instead.

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#7010]
This really is a post-processing option that doesn't logically belong in the builder.

See the example code in #6856 for an implementation idea and the conversation in #6745 for context.

**Comment by arizvisa** [comment]
So, just some more info from my notes for #6856 on the existence of this paradigm in the other (local) builders.

`vmx_data_post` was added for #1149 as #1152
VirtualBox also has a similar `vboxmanage_post` for #664 in #2080
Parallels also has `prlctl_post` for #2080 in #2126

**Comment by arizvisa** [comment]
@SwampDragons, just so you know these 3 PRs (#7017, #7018, #7019) are for adding the cpu count and memory size which is the most common reason that people use `vmx_data` and `vmx_data_post`. This way users can migrate their templates to use available config options instead of leaning on `vmx_data`.

Therefore in your patch, #6987, it should be okay to warn people since it's likely they're just being lazy and that packer already supports most of the things they're trying to configure during their build.

**Comment by BeverlyBrown** [comment]
Just to give you a different use case - I build using the remote esxi builder and if I do not specify this in my vmx_data, my build hangs. Specifying "network": "VM Network" does not set the right field in the VMX file.

     "vmx_data": {
        "ethernet0.networkName": "VM Network"
      },

I don't deploy the VM using packer. I deploy the resulting OVF at a different site, so I am not sure how much use a post-processor will be for me. I don't currently use one and I hope to be able to do everything I need to do with just the ESXi host and not vCenter. 

The things I need to change post-build are the network adapter type and the display name.

Since vmware tools are not available until after the OS installs, I cannot specify vmxnet3 as the ethernet device to use until afterward. 

And the display_name variable during building needs to be based on the vm_name (to keep it unique in case multiple people are building), but the displayname in my final OVF file needs to be something different to keep it simple for the end user.

So I'm hoping that when you are done with this, I will still be able to do this:
      "vmx_data_post": {
        "displayname": "myDisplayName",
        "ethernet0.virtualDev": "vmxnet3"
      },

**Comment by BeverlyBrown** [comment]
Maybe the remote esxi builder should default to having 
    ethernet0.networkName="VM Network"
 in the VMX file

**Comment by arizvisa** [comment]
@BeverlyBrown, moving the logic into a post-processor is specifically for modifying the artifacts in the .ovf  prior to deployment to a site. So it should have the exact same effects as `vmx_data_post` where you need to tweak the .vmx to "lock-in" a configuration prior to deployment. The logic of `*_post` is actually the last thing that's done before executing the post-processors so afaict it's pretty much just shifting the logic to a more correct place. So, `vmx_data_post`, at the present is really pre-post-processor.

The semantics of the "builder" step are specifically for the actual generic building of an artifact and so anything specified within it should be intended as requirements that are necessary "only" to build the initial template (install the OS) prior to deployment. This is why one of the steps in the builder is to remove/undo all of the options that Packer needed to install the OS. Afaik \_all\_ the builders have a build step to undo/remove all the options that were needed to do the install.

Since Packer was initially written to build a generic template prior to deployment, you can use it to build your template on whatever target you want and then once the os/whatever is installed you now have a template you can then use it to instantiate a VM on whatever its final destination is. Typically a user will customize their template with site-specific options during deployment via vagrant/terraform/power-cli/salt-cloud/etc or a post-processor. This is why Packer doesn't have any generic platform-independant options for this type of configuration. So, the correct solution to make a template site-specific would be a solution similar to https://www.virtuallyghetto.com/2014/06/an-alternate-way-to-inject-ovf-properties-when-deploying-virtual-appliances-directly-onto-esxi.html

**Comment by arizvisa** [comment]
In other related news, the esx5 driver being part of the vmware-iso and vmware-vmx builders is in all actuality a hack that's avaible due to the usage of `ovftool`.. and although it works, due to the differences between ESX and the VMware app, it's actually best represented as a separate builder rather than it's current place of being hacked into the VMware builder as a driver. This is why jetbrains has a plugin for the Vsphere builder (https://github.com/jetbrains-infra/packer-builder-vsphere). Moving `vmx_data_post` into a post-processor has the benefit of augmenting this plugin too. You might want to see if this builder plugin satisfies your needs.

Packer currently has a PR/issue (somewhere I don't recall) discussing on how to properly merge this plugin, but the devers still have work to do on like a hundred other things before getting to this (such as implementing MKS for ESXi 6.7 which I might do if I can find a research project that coincides with this protocol). So I imagine that's why this issue/placeholder to eventually make`*_post` a post-processor was created.

**Comment by BeverlyBrown** [comment]
The parameters I need to set are not site-specific. 
The ethernet0.networkName="VM Network" in vmx_data needs to be set in order to build the VM and this is generally the default network name on any ESXi system. So remote ESXi builds should be setting that by default, but as long as the vmx_data option in the packer template still works, I can continue to use that.

The displayname we use for the VM during building is the vm_name which contains the username.machine.pid of the person building the VM (makes it better for distinguishuing who owns which files on the build host during development and allows for multiple people to build VMs on the same host) . When a user wants to deploy this VM, the default name for the VM to be deployed should not show that kind of detail. It should be simpler/more generic. 

The first option you suggested (using OVF properties) is not applicable for the parameters I want to set. 
The second option, using the jetbrains plugin, requires vCenter. I am building VMs on a standalone ESXi host with no vCenter and the VMs that are built may be deployed on a system with or without vCenter.

It looks like in future versions, I will have to tweak the resulting OVF file with sed.

**Comment by BeverlyBrown** [comment]
Another possibility for the network name would be to set the correct VMX parameter when the Packer option "network" is specified. If ethernet0.networkName was set (when using remote esxi) instead of setting ethernet0.vnet, that would work. Then I could just set "network": "VM Network" instead of setting it in vmx_data.

**Comment by arizvisa** [comment]
Hmm. Interesting. I began some experimental work on uncoupling ESX support from the VMware builders which might make your suggestion of specifying the network name in that instance more feasible (without having to add special cases like how it's currently being done). That "network" option was developed against VMware Workstation which is why it's not really supported for ESX.

After the committers finish some releases and maybe show interest in that particular work (and some discussion happens about the transition), I'll look at adding support for customizing the network name to the "network" option. Thanks for the insights!

**Comment by ladar** [comment]
I think the `vmx_data_post` option is a valuable part of the `vmware-iso` builder. I rely on the post setting to tweak various settings for compatibility/performance which are independent of the post processor being used. 

From a documentation/logical standpoint it also makes more sense to include this as part of the VMWare builders. Adding it the post processor would mean adding VMWare specific notes to a variety of post processors. This change would also cause problems for configs which manipulate VMWare build outputs using generic shell commands, like so:

https://github.com/lavabit/robox/blob/master/developer-ova.json#L101-L110

That being said, I don't have a problem with adding additional support for VMX manipulation to post processors which bundle a VMX file, like the `vagrant` post processor, I just think if your going to do it, it should be in addition to, not in lieu of.

**Comment by SwampDragons** [comment]
That's a really good point, @ladar. I'm glad we left this open for comment.

**Comment by arizvisa** [comment]
@ladar, what compatibility/performance options are you trying to lock in before the post-processor step happens? Are these things that we can expose as options to the VMware builders? The `vmx_data_post` option gets applied right after provisioning (specifically before the ethernet adapters get removed). So, it happens literally right before the artifacts are exported to get to the post-processing step. You can see this in all of the local builders in the file, `iso/builder.go`, right after `StepProvision`.

I don't think your example intended to demonstrate the compatibility/performance options you mentioned, but the ones that you used in `vmx_data_post` are actually straight-up usable in `vmx_data` and thus there's actually no need for you to use `vmx_data_post`. One of them can even use the `network_adapter_type` option, as Packer doesn't do anything difficult like revert `vmx_data` or anything. Insead it tries not touch anything it doesn't "understand" unless it needs to. So, everything in `vmx_data` stays is retained unless PAcker needs to use it to satisfy anything else you've specified.

Now, I think your example was to demonstrate how a local script might interfere with an artifact which can result post-processors not working. With regards to that, this is why they're processed sequentially. Tampering with the artifacts at any point can make all of the post-processors not work, so afaict that's by design. You can do something similar via the shell-local provisioner to interfere with the artifact as it's in use so that the rest of the provisioners don't work too. The only thing stopping users from going that path is common sense (but you knew that already).

Despite this being titled as just VMware, it's not VMware that's the only one susceptible to this anti-pattern. All of the local virtualization platforms, VMware, Parallels, and Virtualbox, are using a post-processing variation for the same intentions (hence the second comment in this issue). In this case you'd have just one place to modify your compatibility/performance options for each of the builder types. So in this way you can continue to copy-pasta pieces or wholes from someone else's builder rules and then have your platform-specific tweaks completely separate from them. Now your single JSON can build for all the virtualization platforms, and even tweak it for its role if you really need it to instead of using vagrant/terraform/saltstack/whatever.

**Comment by arizvisa** [comment]
But obviously it's going to have to go through a transitioning process (not suddenly being taken away as you made it appear) as users can't afford to read documentation and Packer can't afford to leave its users hanging. As an example, it's been 2 years since options like `network`, `network_adapter_type`, and `disk_adapter_type` have been around and still to this day users will instead opt to use `vmx_data` and `vmx_data_post` for. I expect the same with the `cpus` and `memory` options that were recently committed as well.

So none of the issues that have been opened to start a discussion are about literally disposing prior functionality as much as they are about introducing better designed functionality and warning users when they're using the deprecated functionality. Things will still work, you'll just be notified there's a better way of doing things. Similar to swampdragons' patch of warning people who tamper with disks in `vmx_data`.

**Comment by ladar** [comment]
@arizvisa my example was picked at random. I'd have to look through all 120+ configs, but I believe a handful of the operating systems depend upon the vmx_post_data to ensure the virtual hardware is configured properly, to avoid various glitches during provisioning. I don't recall off the top of my head what those were, but some settings, like marking a [clean shutdown](https://github.com/lavabit/robox/blob/88fcc86d833fb402ff83d110c83914b003f4864f/developer-ova.json#L74-L79) need to happen after the VM has been shutdown but before being packaged, and are only applicable in a handful of edge cases.

As for migrating VMX options to defined settings, I'm all for it. I never liked relying on the VMX options, or QEMU command line args to set CPU/MEM. It always seemed overly complicated. I've already created [a branch with my VMWare templates migrated to the new schema](https://github.com/lavabit/robox/tree/experimental/cpuconfig) (I'm waiting a little longer before making it the default). 

That said I also feel like access to those options is necessary. If needed, there is no substitute for being able to manipulate the VMX file, [given what it can do](http://sanbarrow.com/vmx.html). And removing that flexibility only makes it harder for packagers like myself to workaround unforseen problems. 

As for making changes using the shell local post processors, I'm very much against it. I only use that option as an absolute last resort. I actually prefer (adding the functionality to packer)[https://github.com/hashicorp/packer/issues/7113], because the former makes the template less reliable and less portable.

**Comment by ladar** [comment]
To summarize, adding functionality is good. Subtracting is bad. I only posted to ensure the vmx_post_data isn't removed. I have no problem with adding a post processor.

**Comment by arizvisa** [comment]
So the `cleanShutdown` option that you specified in `vmx_data_post` has the same effects in `vmx_data` since locally it's related to how VMware cleans up. `softpoweroff` is similar since shutdown is explicitliy called as part of the build (and even if you're not explicitly shutting down then the option is retained). Try it, and then `kill` your VMware Fusion process to see the effects. If you're trying to enable it prior to deployment, well...that would have the same semantics as putting it into a post-processor.

However, it seems like "ethernet0.startConnected" should be part of `vmx_remove_ethernet_interfaces` which might be an oversight on the implementor of that (but it's up to them really), and then `ethernet0.wakeonpktrcv` is set to false, which is always the case for local VMware instances unless you've changed your default config.

So all of these options that you've highlighted can totally be placed in a post-processor before you do your packaging. But, you mentioned 120+, and there's only 25 configs split up in your ladar/robox repository and since they're split up by the builder type, only a couple of them are VMware.

Ftr, if you need to deal with querying json at your shell, you can use a tool, "jq". (It's avail in most distro repositories). I used `jq '.builders | .[] | .vmx_data_post'` to dump all instances in your robox repo. You might find it handy combined with `find . -iname '*.json'` for searching through a hundred or so json templates.

**Comment by arizvisa** [comment]
@ladar, oh I also wanted to mention this since you're designing each template in your lavabit/robox project so that each template is split up by the builder type. You can also use `jq` to build .json, so that way if you care to (in the future), you can use it to combine your different builders after testing them as that way you can benefit from packer's parallel building capabilities. Ok, done advertising about `jq` I think...

**Comment by ladar** [comment]
> So the `cleanShutdown` option that you specified in `vmx_data_post` has the same effects in `vmx_data` since locally it's related to how VMware cleans up. `softpoweroff` is similar since shutdown is explicitliy called as part of the build (and even if you're not explicitly shutting down then the option is retained). 

@arizvisa I'm building with VMWare Workstation (v12), and I believe those shutdown options are cleared every reboot. 

> However, it seems like "ethernet0.startConnected" should be part of `vmx_remove_ethernet_interfaces` which might be an oversight on the implementor of that (but it's up to them really), and then `ethernet0.wakeonpktrcv` is set to false, which is always the case for local VMware instances unless you've changed your default config.

As for the rest, I can't embed comments in my JSON, and I don't recall the details about when/why they were added, but it was because it fixed some minor issue, which, if I had to guess, related to the ability for OS to (re)detect when virtual interfaces are connected/disconnected. It's an issue that is distro specific, so it might not be wise to always add that particular option.

> So all of these options that you've highlighted can totally be placed in a post-processor before you do your packaging. But, you mentioned 120+, and there's only 25 configs split up in your ladar/robox repository and since they're split up by the builder type, only a couple of them are VMware.

My configurations are broken up by provider and purpose/organization... which means all my VMWare configs are in:

https://github.com/lavabit/robox/blob/master/developer-ova.json
https://github.com/lavabit/robox/blob/master/developer-vmware.json
https://github.com/lavabit/robox/blob/master/generic-vmware.json
https://github.com/lavabit/robox/blob/master/lineage-vmware.json
https://github.com/lavabit/robox/blob/master/magma-vmware.json
https://github.com/lavabit/robox/blob/master/packer-cache.json

Upon closer inspection, it seems lhe precise total is 85, plus a handful of experimental, private configs not in that repo.

> Ftr, if you need to deal with querying json at your shell, you can use a tool, "jq". (It's avail in most distro repositories). I used jq '.builders | .[] | .vmx_data_post' to dump all instances in your robox repo. You might find it handy combined with find . -iname '*.json' for searching through a hundred or so json templates.

I appreciate the tip regarding `jq` ... I don't consider myself a `jq` master, and I find the syntax somewhat frustrating/fragile, but I do make use of in some of my maint scripts:

https://github.com/lavabit/robox/blob/master/res/scripts/add.sh
https://github.com/lavabit/robox/blob/master/res/scripts/boxes.sh
https://github.com/lavabit/robox/blob/master/res/scripts/upload.sh

I also make use of it some the scripts I use to automate [magma](https://github.com/lavabit/magma/) development.

> @ladar, oh I also wanted to mention this since you're designing each template in your lavabit/robox project so that each template is split up by the builder type. You can also use jq to build .json, so that way if you care to (in the future), you can use it to combine your different builders after testing them as that way you can benefit from packer's parallel building capabilities. Ok, done advertising about `jq` I think...

I ended up splitting my configs by builder because it was easier to manage that way. Namely, I can't run the Virtualbox and libvirt builders on the same robot at the same time (KVM conflict), and I can only run the Hyper-V config on my Windows robot, and my Parallels config on MacOS. The VMWare config is actually the only one which is capable of running on three hosts, although for practical reasons I use Linux to build VMWare machines since it's the only platform in which I have multiple robots available for building.

P.S. When I first read the description, I thought this feature was going to add VMX config capabilities to existing post processors, like the override option that is part of the vagrant post processor. Upon re-reading, and your response above, I take it you want to add a standalone post-processor for manipulation of the VMX file, which sounds like a much better idea... but I still think it should be in addition to the existing vmx_post_data option... which is where it would make sense to put generic parameters, while using the post processor to make pipeline specific changes...

**Comment by ladar** [comment]
@arizvisa you seem somewhat knowledgeable regarding the VMWare packaging/post processor logic. I'm wondering if you know the different between the various VMWare vagrant box types? I believe vmware_desktop is a merging of vmware_workation and vmware_fusion, but don't know if 'vmware' represents anything unique?

I'm also wondering what special considerations are needed by the vsphere and vmware_ovf providers? I've had someone report [difficulty using the boxes on ESXi](https://github.com/lavabit/robox/issues/6), but without details. 

I personally haven't tried deploying them to my ESXi servers, since I use different process for my production/public internet VMs... but thought you might know what the differences are, if any? As I suspect they involve the settings inside the VMX file?

**Comment by arizvisa** [comment]
@ladar, nah sorry I don't. Iirc, Vagrant's native vmware support requires you to fork over $, and due to this plus me being a Perl+Python person (as a result of the field I work in), I've just come up with different solutions for the need that Vagrant aimed to solve. 

I'd ask Vagrant's maintainers, but it's probably api related if they're not using `vmrun`. Although I'm sure that there were different default options that they're using between the different vmware box types, I'd be willing to bet that the merge of those box types consolidated the vmx options as well.

**Comment by SwampDragons** [comment]
I've been thinking about this some and I think the clarity benefit from deprecating the vmx_data_post feature on the vmware builder isn't worth the backwards incompatibility and confusion. It also doesn't make sense from the perspective that post-processors are (generally!) supposed to be generalizable, but this option only makes sense in the context of the vmware builders. I think we just need to document its use clearly. I'm going to be doing a big documentation audit of all the vmware stuff as part of the vSphere builder merge so I think we can close this.  Thanks for your conversation on it.
