### ISSUE TITLE
Packer drops preferred NIC types from Vagrant boxes

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7057]
Vagrant 2.2.2 now warns when some vulnerable NIC drivers are used, such as E1000. I am able to configure a more appropriate NIC at base box build time, with:

```json
"vboxmanage": [
    ["modifyvm", "{{.Name}}", "--nictype1", "82543GC"]
]
```

However, the Vagrant box produced by this Packer configuration completely forgets about this preference, resulting in the E1000 NIC being used when the box boots.

Can we fix Packer so that NIC types are better preserved in .BOX's?

Note: Vagrant also has a habit of dropping important configurations for further downstream box exports, so users will likely have to manually configure better NIC types there as well, with an `export.Vagrantfile` for use with `--vagrantfile` in `vagrant package`. But we could at least do a better job having Packer artifacts setup the right default configurations, out of the box so to speak.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by DanHam** [comment]
@mcandre So long as you are using Virtualbox 5.2.22 or later the security issue with the E1000 NIC type has been fixed. In other words the E1000 NIC is no longer vulnerable and as such the warnings can be ignored. 

The warning **should not** appear if you are using Virtualbox 5.2.22. The incorrect warning will  dissapear with the next version of Vagrant (see [THIS PR](https://github.com/hashicorp/vagrant/pull/10486)) and the corresponding [ISSUE](https://github.com/hashicorp/vagrant/issues/10481) for further reference.

@arizvisa The original 'fix' for this in Vagrant changed the default NIC type to 'virtio' which caused issues because of the change in the OS network device name between building the VM in Packer and running it in Vagrant. See my comment [HERE](https://github.com/hashicorp/vagrant/issues/10416#issuecomment-439958513) for reference.
While Packer may remove the hardware configuration used during the build, the installed OS still 'remembers it' in the guise of the expected network name or 'predictable network device name' - hence the desire to hard code it in some way into the box Packer creates.

As an aside, I've used the [vagrantfile_template](https://www.packer.io/docs/post-processors/vagrant.html#vagrantfile_template) option in the vagrant post-processor to 'lock-in' specific settings for both Virtualbox and VMware Vagrant boxes. This has allowed me to work around a few issues with Vagrant/Virtualbox/VMware in the past... but clearly, all of this is a bit moot as Virtualbox has now fixed the problem and the erroneous warning in Vagrant should be fixed in the next release.
