### ISSUE TITLE
Please advise on how to include build-time information as AMI tags

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/packer#7063]
Meta:
  - `packer --version`: `1.3.2`
  - Mac OS X

What I mean is if you have something like:
If one has something like:

```
...
  "provisioners": [
...
    {
...
      "json": {
        "java": {
          "install_flavor": "openjdk",
          "jdk_version": "11"
        }
      },
      "run_list": [
        "recipe[java]"
      ],
...
      "type": "chef-client"
    }
  ]
...
```

Where the exact value that is the full version of the `openjdk-11-jdk-headless_*_amd64.deb` package is not known at the start of the build. How does one supply that value as an AMI tag by the end of the build?

If I were okay with just `11`, I realize I could add that as a user variable and just pass it within the template to both the `chef-client` provisioner and the `amazon-ebs` builders' `"tags"`. But adding a user variable to (an already complex template) just to supply its value to more-than-one section feels frustrating.

I can think of a couple solutions like:
  - grepping the packer log (or a `post-processor` `manifest` ) as a `post-processor` step to find the AMI and then use a `shell-local` `post-processor` and the aws cli to update the tags
  - inspect the build instance with a `shell` provisioner and then grep the packer log as a `post-processor` step as in the above
  - inspect the `chef-client` `local-mode` node object as it appears on disk, assuming `ohai` or `chef` will populate the full value of the version of the openjdk package

But none of those seem *great* and I'd rather have a programmatic way to supply tags near the end of the build.

**Comment by SwampDragons** [comment]
I assume you don't know the full version before the build run because it's getting pulled from some mirror online by the java cookbook?  My recommendation would be to wrap your Packer build in some kind of a running script that checks/scrapes the name of the java package before you run the build, then parses it and stores the full name in a variable in Packer, which you then use for both the tags and as the provided url in the cookbook.

Unfortunately, Packer doesn't have a way to register new variables or overwrite ones you've already declared during build time. If you're strongly against a post-processor or some later CI step that's unrelated to Packer, then  your only other option is to preprocess.

That said, the github issues section is intended for feature requests and bug reports, not general usage questions. If you want more advice or a better chance of coming across a person who has had to solve the same problem as you, I'd recommend you reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), which gets a lot more eyes than github issues.

Thanks!
