### ISSUE TITLE
VirtualBox 6.0 Beta 3 fails with bad parameter "sataportcount"

### ISSUE THREAD

**Issue by ripleymj** [hashicorp/packer#7087]
virtualbox-iso builder fails when run with VirtualBox 6.0 Beta 3 because it passes an invalid parameter `sataportcount` to VBoxManage. It looks like #2429 and #2438 addressed this by adding a version check for 4.3 and 5.x.

I just recently started using Packer, I'm not sure if this is best addressed by adding a check for 6.x, checking for anything greater than 4.3, or if it's just time to deprecate < 4.3 functionality.

**Comment by SwampDragons** [comment]
I've written a patch that'll check for 6.x in addition to 5.x; would you be willing to test it for me?

Linux build:
[packer.zip](https://github.com/hashicorp/packer/files/2665322/packer.zip)

osx build: 
[packer.zip](https://github.com/hashicorp/packer/files/2665326/packer.zip)

windows build: 
[packer.zip](https://github.com/hashicorp/packer/files/2665328/packer.zip)

**Comment by ripleymj** [comment]
Yep, that looks better. Thanks for the quick fix!

Just out of curiosity, it seems like only VirtualBox 5.1 and 5.2 are currently supported, with 6.0 coming soon. At what point would it be safe to delete the <= 4.2 code and prevent this error from occurring on newer versions?

**Comment by svpernova09** [comment]
@SwampDragons thanks for the build! fixed the issue for me.

**Comment by breisig** [comment]
@SwampDragons Thanks, that build also works for me.

**Comment by aalmenar** [comment]
Hi, 

This patch build doesn't work for me:

==> virtualbox-iso: Starting HTTP server on port 8866
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Error creating hard drive: VBoxManage error: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
==> virtualbox-iso: Progress state: NS_ERROR_INVALID_ARG
==> virtualbox-iso: VBoxManage: error: Failed to create medium
==> virtualbox-iso: VBoxManage: error: Cannot register the hard disk '/packer/distro-amd64.vdi' {14c6fe80-6cdf-4d20-ad36-1e98159f7de4} because a hard disk '/packer/builds/packer-distro-amd64-virtualbox/distro-amd64.vdi' with UUID {611b8405-ce8a-440a-96d2-991ca1035a7a} already exists
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component VirtualBoxWrap, interface IVirtualBox
==> virtualbox-iso: VBoxManage: error: Context: "RTEXITCODE handleCreateMedium(HandlerArg *)" at line 462 of file VBoxManageDisk.cpp
==> virtualbox-iso: Deregistering and deleting VM...


> packer -v
1.3.4
