### ISSUE TITLE
SSH weak algorithms

### ISSUE THREAD

**Issue by sebyx** [hashicorp/packer#7088]
For old RedHat releases (as RHEL 6), if weak KEX algoritms are removed from SSH configuration, packer cannot connect to the VM anymore.

RedHat 6 release supports OpenSSH 5.3p1.
Available kexalgorithms: 
- diffie-hellman-group-exchange-sha256
- diffie-hellman-group-exchange-sha1
- diffie-hellman-group14-sha1
- diffie-hellman-group1-sha1

Removing weak kexalgorithms (*-sha1), we are left with **diffie-hellman-group-exchange-sha256**, which is not supported by packer (see kex.go).

Can you please add this kexalgoritms to the next release, so we can automate RHEL 6 builds?

**Comment by rickard-von-essen** [comment]
Packer just uses the kex's supported by the go ssh implementation. I added _won't fix_ since this not like something that will addressed. 

We could try to file an upstream issue but that will likely take a long time before it will be fixed (if ever).

If this is a big concern for you I recommend building within a confined environment and as the last step of the process disable the weak kex's.

**Comment by sebyx** [comment]
Thank you!
