### ISSUE TITLE
Question - Split a user variable

### ISSUE THREAD

**Issue by vikas027** [hashicorp/packer#7120]
I am trying to *split* as defined [here](https://www.packer.io/docs/templates/engine.html).

I have tried something like this, but it does not works as interpolation is not allowed.

```
"script": "{{ split {{ user `my_var` }} \"-\" 0 }}"
```

 Is there a way to achieve this?

**Comment by SwampDragons** [comment]
Hi @vikas027 thanks for reaching out. I don't think that any of our template functions like being nested in this way.  The intention of the `split` function was to allow you to parse variables that are created by the builder itself, like build_name.  We didn't really consider using it for user variables, since you can always just create another user variable in your `variables` section that matches what you want.

That said, we can probably clarify the docs to make this behavior more clear.

**Comment by ladar** [comment]
@vikas027 I think your going about it backwards. You should specify the components, ie and then combine them in the template. You could probably create a template variable which combines them as well.

```
{{ user `my_var1` }}-{{ user `my_var2` }}
```

For a real world example see:

https://github.com/lavabit/robox/blob/master/generic-vmware.json#L2696-L2720

**Comment by lae** [comment]
Not sure if things have changed since this issue was opened, but this seems to work, to let me access "arrays" in packer by index...

```
{
  "variables": {
    "regions": "sfo2,sgp1"
  },
  "builders": [
    {
      "type": "digitalocean",
      "region": "{{split (user `regions`) \",\" 0}}",
      "snapshot_regions": "{{user `regions`}}",
    }
  ]
}
```
