### ISSUE TITLE
Power down safety

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7240]
Packer works okay for many hypervisors and operating systems that support ACPI. However, some configurations, such as VirtualBox with MirOS (AKA MirBSD), do not have good ACPI or APM support. As a result, Packer builds either timeout or produce a corrupt build artifact, depending on how `shutdown_command` is set. Fortunately, there are some simple tweaks we can apply to better support these hypervisors and guests.

* Specify a reasonably portable default `shutdown_command` in the event that the user does not provide one, such as `sudo halt -p`. Currently, Packer treats an unconfigured `shutdown_command` (i.e., blank string) as a hard reset, which can corrupt the guest.
* Allow non-blank `shutdown_command`s to gracefully timeout, just like blank `shutdown_command` does now. Instead of failing the build with a timeout message.

For MirOS, I am trying to work around this by leaving `shutdown_command` unconfigured and moving all of my provisioning to `boot_command`, with `sudo shutdown -h -p now<enter><wait1m>`.

**Comment by mcandre** [comment]
Fine, but don't treat timeout as necessarily a failure for non-blank shutdown_commands, so that MirOS guests can build.

**Comment by SwampDragons** [comment]
I'd merge a PR for a new "no_shutdown_error" option that would default to false and when true would do your second suggestion (Allow non-blank `shutdown_command`s to gracefully timeout, just like blank `shutdown_command` does now. Instead of failing the build with a timeout message.)

**Comment by lerlacher** [comment]
I am impacted by this because one of my provisioners involves changing the user password to one that packer doesn't know. packer is then unable to SSH into the VM to issue the `shutdown_command`. (There are a variety of workarounds for this with different degrees of practicality and ugliness, which I'm not particularly keen to get into at this point.)

So I have been thinking (together with a coworker) about creating a PR / proposal with a fairly high aim of introducing a new "shutdown_type" parameter to specify whether to use the current mode of operation where the "shutdown_command" is executed on the guest via SSH, or to use something alternative. There are many ways to skin this cat, and lots of esoteric usecases to ponder. At a minimum, in addition to the current options of executing a command via SSH or halting the VM, we want to allow a "soft" poweroff assisted by the hypervisor. It seems most hypervisors delegate this to their guest tools / integration tools, whereas virtualbox uses ACPI instead.

Implementing this would be a lot of work and would make the virtualbox builder diverge from the other builders in a significant way, and in an ideal world the other builders would get a similar feature.

However, as a "minimum intervention that improves the situation", what about just using ACPI? In other words...

@SwampDragons would you merge a PR that replaces the "controlvm poweroff" with "controlvm acpipowerbutton"? I cannot think of a usecase where it would be preferable or safer to use the "pull the plug" poweroff command rather than the "send ACPI shutdown command" acpipowerbutton command.

The relevant code is here:

https://github.com/hashicorp/packer/blob/c9066f9e751588af4a65f4571c81d81a1065b52e/builder/virtualbox/common/driver_4_2.go#L151-L160

@mcandre I'm having a bit of a problem understanding your usecase. Why do you think it is undesirable to require the user to put in a sensible `shutdown_command` in your case?

**Comment by SwampDragons** [comment]
I think I'm okay with that but I'd definitely want to do some testing and research to make sure there's not some special case we'd be breaking.

**Comment by lerlacher** [comment]
Here are the relevant paragraphs of the [virtualbox manual section for controlvm](https://www.virtualbox.org/manual/ch08.html#vboxmanage-controlvm):

> VBoxManage controlvm <vm> poweroff: Has the same effect on a virtual machine as pulling the power cable on a real computer. The state of the VM is not saved beforehand, and data may be lost. This is equivalent to selecting the Close item in the Machine menu of the GUI, or clicking the VM window's close button, and then selecting Power Off the Machine in the displayed dialog. 
>  VBoxManage controlvm <vm> acpipowerbutton: Sends an ACPI shutdown signal to the VM, as if the power button on a real computer had been pressed. So long as the VM is running a fairly modern guest operating system providing ACPI support, this should trigger a proper shutdown mechanism from within the VM. 

The only special cases we could break here is where someone is using a guest OS that does not support ACPI and wants the VM to be killed off.

I don't know how we would find out if anyone is relying on that. The only idea I have to avoid this is by gating the behavior using an environment variable - e.g. `PACKER_VBOX_ACPI=1` - or going back to the more complex solution of implementing a new builder configuration option.

**Comment by SwampDragons** [comment]
Thanks for looking into that for me :) . I'd rather gate it using an explicit config option than an environment variable, but I think that you've got the right idea here. I'd merge something that adds a config option to use ACPI instead of poweroff, especially if we keep poweroff as the default.
