### ISSUE TITLE
[Bug]: Vagrant post-processor doesn't respect keep_input_artifact

### ISSUE THREAD

**Issue by danowar2k** [hashicorp/packer#7269]
Packer version: 1.3.3 (also in master branch)
Host: Windows 7 64Bit

https://github.com/hashicorp/packer/blob/9f1ec211a07f8adf342446c22b888addc6e8f54b/post-processor/vagrant/post-processor.go#L41-L51

keep_input_artifact isn't read and so it can't be respected. I don't know if there even is code that tries to respect the setting.

This is also mentioned in #6294, it seems.

**Comment by SwampDragons** [comment]
I'm going to address this for the 1.4.0 release because it'll change behavior that people may have depended on, even though it's technically a bad behavior.

**Comment by danowar2k** [comment]
No problem, I'm not depending on it, but I wanted to report it just in case.

Also, there seem to be other post-processors where keep_input_artifact isn't respected, just so you know...just search for it in the code.

**Comment by danowar2k** [comment]
Also, couldn't the function handling the behaviour be something like a common library function. It doesn't seem like keeping or deleting the input artifact would be something every post-processor would have to implement...

**Comment by SwampDragons** [comment]
> Also, couldn't the function handling the behaviour be something like a common library function. It doesn't seem like keeping or deleting the input artifact would be something every post-processor would have to implement...

Yeah that crossed my mind too. I'll have to take a look and see if there's some better way of handling this. Maybe we can add the check to the interface to enforce that all the post-processors have one.

**Comment by SwampDragons** [comment]
I looked at the vagrant code, and it appears that we're setting whether to keep the input artifact differently depending on the vagrant provider being used rather than the user setting. I need to inspect _why_ this is the case, but in the meantime, here's a list of the other Packer post-processors that don't appear to read keep_input_artifact:

alicloud-import
amazon-import
digitalocean-import
docker-push
docker-save
docker-tag
manifest
shell-local
vagrant (kinda)
vagrant-cloud
vsphere
vsphere-template

**Comment by SwampDragons** [comment]
On further reading, I think you were looking in the wrong place in the code. This is being handled in the core, not in individual post-processors, which would explain why we have so many that don't directly read this value.

I tested keep_input_artifact for the vagrant builder and it's behaving as I expect. I believe that this isn't actually an issue.

If you have a repro case where it isn't being respected, share your packer template with me -- for now though, I'm closing because I think this issues was just based on our misreading the code.

**Comment by danowar2k** [comment]
Okay no problem, one last question though...If keep_input_artifact is handled in the core (which seems reasonable), what then is this function here?

https://github.com/hashicorp/packer/blob/9f1ec211a07f8adf342446c22b888addc6e8f54b/post-processor/vagrant/virtualbox.go#L19-L21

Why does this always return false? Is this maybe a poorly named "get_KeepInputArtifactDefault" ?
(The docs for the Vagrant post-processor say that the value defaults to false) Or something completely different?

**Comment by SwampDragons** [comment]
hmm. Probably the ideal situation would be to have the user-set value override the default-set function, and only to use the default when the user hasn't set a value. I'll think on this and see if it makes sense to implement.

**Comment by danowar2k** [comment]
> hmm. Probably the ideal situation would be to have the user-set value override the default-set function, and only to use the default when the user hasn't set a value. I'll think on this and see if it makes sense to implement.

I think the code at the moment makes sense: the post-processor decides whether its modifications lead to keeping the input artifact for the next processor, and if the post-processor decides to throw away the input artifact, the user can always tell Packer to keep the input artifact anyway.

Enabling the user to throw away the input artifact even when the processor keeps it hands the responsibility for cleanup to the user. What if the artifact should be kept because it is necessary for later?

Keeping a thing instead of deleting it is always easier to justify than force deleting something.

**Comment by SwampDragons** [comment]
Yeah, I think clearer naming is a good idea no matter what.

**Comment by SwampDragons** [comment]
FYI I've got a PR here that is relevant to our conversation: #7463 

I changed the naming to hopefully be clearer, added some code comments, removed redundant instances of keep_input_artifact, and changes the behavior to allow a "default discard", "default keep", and a "forced keep" so that we're only ignoring user input in really cut and dry situations where an artifact is 100% definitely needed.
