### ISSUE TITLE
Step "StepProvision" failed

### ISSUE THREAD

**Issue by Adnanhaddad96** [hashicorp/packer#7340]
Hello,

I'm trying to split the jobs of 1. building a win-server-2016 image and then 2. installing its windows updates. I can successfully build the image but I'm not able to update it. 
Here's the log:

```
==> vmware-vmx: Restarting Machine
==> vmware-vmx: Restart script exited with non-zero exit status: 3221225794
==> vmware-vmx: Step "StepProvision" failed
==> vmware-vmx: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? ==> vmware-vmx: Stopping virtual machine...
==> vmware-vmx: Deleting output directory...
Build 'vmware-vmx' errored: Restart script exited with non-zero exit status: 3221225794

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Restart script exited with non-zero exit status: 3221225794

==> Builds finished but no artifacts were created.
Error occurred! VMWare Image has not been created.
```

Sorry if I forget to include anything, it's my first time to create an issue here :)
I appreciate all of your kind answers.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. The bad news is that this is a known bug that we're not going to fix any time soon.  It has to do with some limitations of WinRM; if the vm disconnects, we think that there's a failure. We can't handle reboots well if we aren't expecting them, and since windows updates almost always trigger a reboot, they often cause build failures. 

You can try to set `"check-registry": true` if you want to try this beta feature https://www.packer.io/docs/provisioners/windows-restart.html#registry_keys, 

If that doesn't work, you can do what folks normally do to work around this limitation, which is to perform all windows updates before Packer connects winrm, as part of your autounattend.xml.  See https://github.com/joefitzgerald/packer-windows/blob/master/answer_files/10/Autounattend.xml for an example of this behavior.

If you need any more help, I recommend reaching out to the mailing list.

I wish I had a better answer for you, but hopefully this helps you get going.
