### ISSUE TITLE
ssl certificate binding breaks on 0x80070520  after sysprepinstance

### ISSUE THREAD

**Issue by jmanuelortiz** [hashicorp/packer#7362]
Describe the problem and include the following information:

- Packer version from `Packer 1.3.4`
- Windows Server 2016

- I am including the template i am using https://gist.github.com/jmanuelortiz/ffac013e6af68e6a19c8e4445e188d38

Issue started after i added the sysprepinstance -NoShutdown as i need to change the hostname on every  instance launch.

When the packer finished to build the ami ... i go to iis site configuration and when i tried to change bindings to the site the error code 0x80070520 appears. (If i manually delete and then import the ssl to the mmc certificate console everything works fine)

When i remove the sysprep every thing comes to normal but every instance i launch is using same hostname which i want to avoid as i probably join them to a AD DC

im using following code in powershell to import the pfx file cert

Import-PfxCertificate -FilePath my.pfx -CertStoreLocation Cert:\LocalMachine\My -Password $Secure_String_Pwd -Exportable

Regards

Manuel

**Comment by SwampDragons** [comment]
Thanks for reaching out. I did a quick search, and it looks like that error code may be related to a corrupt update download.  

I've never used iis, so I don't think I'll be much help in debugging your iis or .pfx file setups. 

I don't think this is a Packer bug. I think it's a failure in one of the scripts you're calling. You may get lucky if you reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) for help, but apart from that I don't have a lot of ideas. You can try using the breakpoint provisioner to pause after your powershell call but before the instance shuts down to check the configuration. 

For now I'm going to close this because we reserve GitHub issues for bugs and feature requests. Good luck.

**Comment by jmanuelortiz** [comment]
Thanks @SwampDragons ... i will have a look this week and see with the breakpoint provisioner...

Thanks!!!
