### ISSUE TITLE
Arch Linux chroot "chmod: not found"

### ISSUE THREAD

**Issue by JamieMagee** [hashicorp/packer#7366]
- **Packer version**: 1.3.4
- **Host platform**: Arch Linux
- [Example template and output](https://gist.github.com/JamieMagee/9047d38389d048d8f935334a4b868f9d)
  
I understand that [packer-builder-arm-image](https://github.com/solo-io/packer-builder-arm-image) is a plugin, and not a part of the packer core, but my issue is with the shell provisioner in chroot.

Running on Arch Linux I am unable to run commands in the chroot. `packer-builder-arm-image` uses [the same communicator](https://github.com/solo-io/packer-builder-arm-image/blob/2a33747c943b22b1e6642a6f226f1ab88f81fb42/pkg/builder/communicator.go#L30) as [amazon-chroot](https://github.com/hashicorp/packer/blob/master/builder/amazon/chroot/communicator.go#L30).

Interestingly if I change the `execute_command` to `/bin/chmod +x {{.Path}};{{.Vars}} {{.Path}}` or to `sudo chmod +x {{.Path}};{{.Vars}} {{.Path}}` I am able to run my `inline` scripts. It fails at cleanup, but adding `skip_cleanup` allows me to complete the provisioner successfully (though I would expect it to work without these workarounds).

**Comment by SwampDragons** [comment]
Thanks for opening. This sounds like a $PATH issue on your guest system.  

The way to handle this on Packer's end would be to hardcode that /bin/chmod path, but we generally don't hardcode system utility paths like this, on purpose. It makes us more flexible across platforms. 

Because of that, my gut instinct here is that this isn't a Packer bug so much as a platform configuration quirk. If you can't figure out why your pathing is acting up, then you can continue to use the execute_command workaround, but I don't think I want to change how Packer is calling chmod. 

Thanks!
