### ISSUE TITLE
File Provisioner directory Uploading Problem with Ubuntu 16.04 as source AMI.

### ISSUE THREAD

**Issue by gulzaman-k** [hashicorp/packer#7367]
**File provisioner not working as expected**
When I run packer build packer.json command my File provisioner shows log as it successfully moves assets directory from source to destination,
here are the logs 

```
Upload dir 'assets' to '/tmp'
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] Opening new ssh session
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] Starting remote scp process:  scp -rvt /tmp
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] Started SCP session, beginning transfers...
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] No trailing slash, creating the source directory name
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] SCP: starting directory upload: assets
2019/03/04 13:28:23 packer: 2019/03/04 13:28:23 [DEBUG] SCP: starting directory upload: users
```

but when i enable the debug mode and ssh into the AMI I can't see the directory in the AMI. 
Here is my File Provisioning script.
 ```
{
    "type": "file",
    "source": "assets",
    "destination": "/tmp"
    }
```
based on the script i should have assets directory in /tmp directory but there is nothing.
**Same script was working fine with ubuntu 14.06 Source AMI.**

**Comment by SwampDragons** [comment]
Which specific ubuntu 16.04 AMI are you using?

**Comment by gulzaman-k** [comment]
> Which specific ubuntu 16.04 AMI are you using?

we are using 
**`ami-08660f1c6fb6b01e7`**

**Comment by SwampDragons** [comment]
Hi @gulzaman-k I was able to reproduce by uploading a directory to /tmp. Packer successfully uploads the files, and I verified this by connecting to the instance after the file provisioner had run. However, it appears that the tmp directory is getting cleared when the instance is shut down. I think this is an ubuntu behavior, not a Packer bug. When I upload the file to a different location, for example /home/ubuntu, the assets file still exists when I relaunch the instance from the saved AMI.

I think you just need to upload your assets to a non-tmp directory for ubuntu 16.04

Hope this helps!  Since it's not a Packer bug I'm going to close but if you need more help reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool)
