### ISSUE TITLE
Packer launched by shell-local post-processor does not detect default builders, postprocessors, provisioners

### ISSUE THREAD

**Issue by lijok** [hashicorp/packer#7481]
packer launched by packers shell-local post-processor, does not detect its default builders, postprocessors, provisioners.

`ui:     virtualbox-iso (shell-local): 2019/04/08 15:27:24 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}`
`ui:     virtualbox-iso (shell-local): 2019/04/08 15:27:24 Builder not found: virtualbox-ovf`

I am basically trying to run a post-processor shell-local command which starts another packer instance, but it fails because it doesn't detect the builder. Logs show Builders, PostProcessors and Provisioners are empty.

Placing the default config into C:\Users\User\AppData\Roaming\packer.config mitigates the issue

Version: 1.3.5
Host Platform: Win10 Pro v1809 Build 17763.379
Debug log (relevant info starts at line 470): https://gist.github.com/lijok/9a5fae20f78b93a920012997a8ee2d97
Templates used: https://gist.github.com/lijok/6bab33fbeffece5436e28af26773ad9d

Thank you

**Comment by SwampDragons** [comment]
Interesting, thanks for opening!

**Comment by SwampDragons** [comment]
Okay, I just got a chance to look into this and it's a fascinating one.  

So for context, I'm going to give a brief 101-level intro to Packer internal architecture. When you call `packer build` it kicks off more than one packer process -- one for each builder/provisioner/post-processor (plugin) that your packer template uses.  Packer knows whether it's the parent packer or one of these "child" packers based on an environment variable it sets. One of the things it doesn't bother doing if it's a "child" packer is to rediscover the default packer config. 

The reason we don't rediscover the packer config in these cases is because this redundant plugin discovery was extremely noisy in the debug logs. (here's the commit where a previous maintainer made the change to tell "child" packers not to reload the config)[ https://github.com/hashicorp/packer/commit/3935703286b638c6e6fadd97a4a36ec00312768f] . 

Anyway, the problem you're facing is that when you call packer from inside that post-processor, the "I'm a child" environment variable has been set and so we think this is another "child" packer and not a "parent" packer.

It's definitely unexpected behavior from a user standpoint. But I also think not being able to run a new build from inside a child process is not exactly a bug since there may be other strange side effects of attempting to do so.  I'm hesitant to revert the change above since it makes debug logs much more readable.

If you want to chain builds, the recommended way to do so is to call both builds from a wrapping script rather than calling one from inside the other.  That said, the secret hack you need to make your nested call work without copying the config file is to unset the environment variable `PACKER_PLUGIN_MAGIC_COOKIE` inside of your shell-local "command" before calling `packer build ./packer_templates/wim_exporter.json` 

Again, this is really not how I'd recommend chaining packer builds, so I'm not going to add this hack to the docs.  But it was a really fun exploration for me and I'm glad you opened the issue. Reach out if you find any more quirks you'd like investigated.

**Comment by lijok** [comment]
That is very interesting
Thank you very much for looking into this
