### ISSUE TITLE
I am receiving the same message as #5925 . I am with packer 1.3.5.

### ISSUE THREAD

**Issue by bcube** [hashicorp/packer#7493]
I am receiving the same message. I am with packer 1.3.5. 
[pnda_template_base.vmx.txt](https://github.com/hashicorp/packer/files/3067999/pnda_template_base.vmx.txt)

2019/04/11 17:43:01 packer: 2019/04/11 17:43:01 Lookup up IP information...
2019/04/11 17:43:01 packer: 2019/04/11 17:43:01 GuestAddress found MAC address in VMX: 00:0c:29:64:ff:e1
2019/04/11 17:43:01 packer: 2019/04/11 17:43:01 Trying DHCP leases path: /etc/vmware/vmnet8/dhcpd/dhcpd.leases
2019/04/11 17:43:01 packer: 2019/04/11 17:43:01 IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC 00:0c:29:64:ff:e1
2019/04/11 17:43:01 packer: 2019/04/11 17:43:01 [DEBUG] Error getting SSH address: IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC 00:0c:29:64:ff:e1
2019/04/11 17:43:06 packer: 2019/04/11 17:43:06 Located networkmapper configuration file using Workstation: /etc/vmware/netmap.conf
2019/04/11 17:43:06 packer: 2019/04/11 17:43:06 GuestIP discovered device matching nat: vmnet8

[Update] : When i access my vm via VNC to the port,  i can see the VM as attached. 

![packer_waiting_for_ssh](https://user-images.githubusercontent.com/7297613/56011049-8a283580-5d18-11e9-9a4c-c5e9f8f19b76.png)

![packer_waiting_for_ssh_vnc](https://user-images.githubusercontent.com/7297613/56011048-8a283580-5d18-11e9-9ca8-a7dbafa8fea1.png)

_Originally posted by @bcube in https://github.com/hashicorp/packer/issues/5925#issuecomment-482046759_

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out.  In my experience, issues connecting via SSH normally end up being "getting started" issues, rather than bugs. For these kinds of questions, it's generally better to use the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) where there are more people ready to help; the GitHub issues here are generally monitored only by a few maintainers and a small subset of community members who are generally only working on bugs or enhancements, not general "getting started" questions.

When you do write to the mailing list, they're going to need full debug logs, the packer template you're using, and probably a copy of the kickstart file you're providing to centOS.
