### ISSUE TITLE
Packer custom post processor panic crash

### ISSUE THREAD

**Issue by radekg** [hashicorp/packer#7502]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`

`1.3.5`

- Host platform

`Darwin noan.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

- Debug log output from `PACKER_LOG=1 packer build template.json`.

Error log in the gist: https://gist.github.com/radekg/d1fd719793b7c1c7042861589d5ef6e5

- The _simplest example template and scripts_ needed to reproduce the bug.

I am trying to build a post processor which would store the output of Packer in a Terraform state file. The repository is: https://github.com/radekg/packer-terraform-state-post-processor. The plugin can be built using `make build-darwin` or `make build-linux`, depending on the platform used.

To test, from the linked repo (https://github.com/radekg/packer-terraform-state-post-processor/tree/master/testdata): `packer build test.json`.

The plugin does not start, the underlying issue is:
 
```
2019/04/14 19:12:49 packer-post-processor-terraform-state: panic: gob: registering duplicate names for map[string]interface {}: "*map[string]interface {}" != "map[string]interface {}"
2019/04/14 19:12:49 packer-post-processor-terraform-state:
2019/04/14 19:12:49 packer-post-processor-terraform-state: goroutine 1 [running]:
2019/04/14 19:12:49 packer-post-processor-terraform-state: encoding/gob.RegisterName(0x304ffc9, 0x17, 0x35c5d20, 0x0)
2019/04/14 19:12:49 packer-post-processor-terraform-state: 	/usr/local/opt/go/libexec/src/encoding/gob/type.go:826 +0x4c3
2019/04/14 19:12:49 packer-post-processor-terraform-state: encoding/gob.Register(0x35c5d20, 0x0)
2019/04/14 19:12:49 packer-post-processor-terraform-state: 	/usr/local/opt/go/libexec/src/encoding/gob/type.go:874 +0x123
2019/04/14 19:12:49 packer-post-processor-terraform-state: github.com/radekg/packer-terraform-state-post-processor/vendor/github.com/zclconf/go-cty/cty.init.3()
2019/04/14 19:12:49 packer-post-processor-terraform-state: 	/Users/rad/dev/golang/src/github.com/radekg/packer-terraform-state-post-processor/vendor/github.com/zclconf/go-cty/cty/types_to_register.go:54 +0x5ac
2019/04/14 19:12:49 /Users/rad/.packer.d/plugins/packer-post-processor-terraform-state: plugin process exited
```

The only dependency explicitly using `cty` module is the `hcl2` from Terraform. I'm not sure if this is a Terraform or Packer problem.

I wonder if there is any way to use Packer with a Terraform as a dependency in a module at all.

Any pointers appreciated.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out.

I'm not sure if I have any good advice for you. I've never seen that gob error, but googling for it suggests that people have issues when they try to use pointers on certain structs. I've only had a chance to skim your code, but maybe if you use a type tfConfig.Config instead of a *tfConfig.Config here you can eliminate the error https://github.com/radekg/packer-terraform-state-post-processor/blob/master/post-processor.go#L64?

**Comment by azr** [comment]
This error happens in `"encoding/gob"` you have to register each type to gob and when the same type is registered twice, gob panics. This time it panics because the names are identical but the types a little bit different. You have to find all the calls to `gob.RegisterName` in your project and make sure there's only one.

**Comment by azr** [comment]
I usually happens in inits; one is here: https://github.com/radekg/packer-terraform-state-post-processor/blob/master/vendor/github.com/zclconf/go-cty/cty/types_to_register.go

**Comment by SwampDragons** [comment]
I'm closing for now, but if you need more help please reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) for further advice.
