### ISSUE TITLE
Use clean_resource_name in variables

### ISSUE THREAD

**Issue by danopia** [hashicorp/packer#7527]
Feature Request: I saw that `clean_ami_name` has been generified into `clean_resource_name` by #7456. It seems that generic function should now be usable from the `variables` block to help code reuse, especially with how many resource names the EBS builder accepts.

Consider this snipped present-day template:

```json
{
  "variables": {
    "pack_id": "egress-proxy"
  },

  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami_filter": { ... },
      "instance_type": "a1.medium",

      "ami_name": "{{user `pack_id`}}-{{isotime | clean_resource_name}}",
      "temporary_key_pair_name": "{{user `pack_id`}}-{{isotime | clean_resource_name}}",
      "run_tags": {
        "Name": "Packer - {{user `pack_id`}}-{{isotime | clean_resource_name}}"
      },
      "run_volume_tags": {
        "Name": "Packer - {{user `pack_id`}}-{{isotime | clean_resource_name}}"
      },
      "tags": {
        "Name": "{{user `pack_id`}}-{{isotime | clean_resource_name}}"
      }
    }
  ],

  "provisioners": [ ... ]
}
```

This currently-invalid template feels cleaner:

```json
{
  "variables": {
    "pack_id": "egress-proxy-{{isotime | clean_resource_name}}"
  },

  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami_filter": { ... },
      "instance_type": "a1.medium",

      "ami_name": "{{user `pack_id`}}",
      "temporary_key_pair_name": "{{user `pack_id`}}",
      "run_tags": {
        "Name": "Packer - {{user `pack_id`}}"
      },
      "run_volume_tags": {
        "Name": "Packer - {{user `pack_id`}}"
      },
      "tags": {
        "Name": "{{user `pack_id`}}"
      }
    }
  ],

  "provisioners": [ ... ]
}
```

```
$ packer1.4 build packer.json 
Error initializing core: error interpolating default value for 'pack_id': template: root:1: function "clean_resource_name" not defined
```

I see that #4073 has already asked for this, but it was years ago before the `clean_resource_name` abstraction happened.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! The name has been made generic to make it easier for people working with multiple builders, but the function being called underneath is still scoped to the builder. This is because each cloud has different rules for what it considers valid, so we can only know how to properly scrub the information if we're inside a specific builder.

You're definitely right that your version would be cleaner. If you're only working with isotime specifically, you can format the isotime output manually instead of using the clean_resource_name filter. [The way you format isotime](https://golang.org/pkg/time/#example_Time_Format) in golang is a bit batty, but it's doable via the template function and may end up being less sensibility-offending to you than having to repeat yourself a bunch

**Comment by SwampDragons** [comment]
Example template using isotime formatting:

```
{
	"variables":
		{
			"myvar": "packer-{{isotime \"2006-01-02 03:04:05\"}}"
		},
	"builders": [
		{
			"type": "null",
			"communicator": "none"
		}
	],
	"provisioners": [
		{
			"type": "shell-local",

			"inline": ["echo {{ user `myvar`}}"]
		}
	]
}
```

If you just wanted the date, you could do something like:
`"myvar": "packer-{{isotime \"2006-01-02\"}}"`

**Comment by SwampDragons** [comment]
Since we can't support the global scoping the way this feature is currently architected, I'm going to close this. But I appreciate the suggestion and if we end up changing how it's implemented in the future I'll keep this in mind.

**Comment by danopia** [comment]
Thanks for that sample template. Looks to support the reuse I'm looking for. Cheers!
