### ISSUE TITLE
virtualbox builder hangs

### ISSUE THREAD

**Issue by grrizzly12** [hashicorp/packer#7559]
Describe the problem and include the following information:

It appears that the virtualbox builder is broken.  I don't know if it is the new version of packer or the new version of I have a packer config file which sets the guest_additions_mode option to "Attach".  However, packer seems to be hanging at a particular point.  Below is the console output up until the point it freezes:

```powershell
Debug mode enabled. Builds will not be parallelized.
virtualbox-iso output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:\Users\abl\Desktop\vsts64\_work\1\s\packer_ca
che\afa7695602909b267b26b23c8aefe12db6ee78b2.iso
==> virtualbox-iso: leaving retrieve loop for Guest additions
```
Packer then hangs until I manually kill the process.

- Packer version from `packer version`

packer version 1.4.0

virtualbox version 6.0.6 r130049

- Host platform

Windows server 2016

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/grrizzly12/cb0e6a3c3c41c32c3f3a485625c6efb8

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out.  We have had a couple of deadlock issues with v1.4.0 so I'd definitely recommend rolling back to v1.3.5 and seeing if your problem still exists. 

Also, if you can provide a simple config that reproduces the issue, that will make this a lot easier to reproduce and debug on my end.

**Comment by grrizzly12** [comment]
@SwampDragons The reason that I didn't include a sample config is because, since the issue is that the virtualbox builder hangs when the guest_additions_mode option is set to "Attach", it should be very, very, very simple to throw together a sample config.  Just needs to have the following:

```json
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_additions_mode": "attach"
}
  ],
  "provisioners":	[

  ],
  "post-processors":	[

  ]
}
```

**Comment by SwampDragons** [comment]
>The reason that I didn't include a sample config is because, since the issue is that the virtualbox builder hangs when the guest_additions_mode option is set to "Attach", it should be very, very, very simple to throw together a sample config.

I promise I'm not arbitrarily trying to make extra work for you :). The reason we request simple working configs in the issue template is so that we maintainers can answer for ourselves any number of related questions without having to do a big back-and-forth. When I read your original post, all of these questions occurred to me:

```
- Is the guest additions url being provided as an option, and is Packer correctly grabbing the proper file location comparing the file and the logs?
- What operating system is the guest machine and is that relevant?
- What other options related to guest additions are being provided?  Guest Additions Checksum, interface, remote path? 

or even, 

- Is there a typo in the template itself that is causing this error?  (Even the best programmers get caught by simple mistakes that sometimes require an extra pair of eyeballs to see)
```

And when those questions occur to me, I know that once I start working on reproducing the issue, more questions will occur to me. All of which can be answered much more efficiently for both of us with a sample config rather than several round-trips of questions. 

I just ran my basic ubuntu + virtualbox template on my windows box with guest additions set to "attach" and was unable to reproduce, so I don't think this case is as very very very simple as you think it is. 

If you're storing your guest additions locally and providing a guest_additions_url, my guess is we're facing another side of this bug: https://github.com/hashicorp/packer/issues/7534

But without more detail on how to trigger this behavior I probably can't spend more time on this.
