### ISSUE TITLE
Vagrant builder not able to import or post-process into Vagrant box?

### ISSUE THREAD

**Issue by exception-mhowarth** [hashicorp/packer#7588]
I'm trying to use the `ubuntu/bionic64` box from Vagrant cloud and run provisioners (which I've taken out for testing) on it, and repackage this into a custom Vagrant box. Rather than using the `virtualbox-iso` builder, I thought I'd use the new `vagrant` builder to use an existing box.

I get an error message when trying to use a post-processor to import this box into Vagrant:
```
==> vagrant: Running post-processor: vagrant
Build 'vagrant' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: vagrant
```

I've tried adding `"skip_package": true` to the Packer template but I get the same error message.

I also tried taking the post-processor out all together but this just gives me a .box and does not add it to Vagrant, which I'm assuming the post-processor is supposed to do.

If I manually run Vagrant to add the box it works fine.

```
# vagrant box add package.box --name test
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test' (v0) for provider:
    box: Unpacking necessary files from: file://C:/msys64/opt/testing/packer/output-vagrant/package.box
    box:
==> box: Successfully added box 'test' (v0) for 'virtualbox'!
```

If anymore information is required let me know.
___

### Packer version
```
# packer --version
1.4.0
```
### Vagrant version
```
# vagrant --version
Vagrant 2.2.4
```
### Host platform
```
- Windows 7 Professional (Service Pack 1), 64-bit
- VirtualBox 6.0.4
```
### Debug log output and Packer template
https://gist.github.com/exception-mhowarth/d9ca0c43e712b67dd3af58588c3a50f4

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  

I believe you're seeing the expected behavior. The output of the Vagrant builder is already a vagrant box, so the Vagrant post-processor is unnecessary.

Neither the Vagrant post-processor nor the Vagrant builder automatically add the box artifact to your local Vagrant.

If you have any further questions about how to get started using the tools, the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) is probably a better place to start than the github issues, because more people see the mailing list than the issue tracker.
