### ISSUE TITLE
windows-update provisioner taking over 1 hour - ebs Creation failure

### ISSUE THREAD

**Issue by mpearce123** [hashicorp/packer#7635]
Packer Build 1.4.0
Host Platform Windows Base 2016
packer json file
[Json.txt](https://github.com/hashicorp/packer/files/3171362/Json.txt)
Packer log file
[packerlog.txt](https://github.com/hashicorp/packer/files/3171358/packerlog.txt)

I raised same issue on git fo Windows-update provisioner and they suggested raisin here as well

Tiemout creating ebs
Times are packer start to windows-update - 6 mins
windows-update search/download/install (2 updates, 1400MB) 42 mins..
windows-update reboot/ install completion/check for more updates 8 mis.
sysprep 4 mins.
Stopping the source instance fails with "amazon-ebs: Error stopping instance: RequestExpired: Request has expired.
Co-incidentally just over 1 hour has expired when the build gets to the final stage.
I assume this is some form of AWS temp credential expiry.
I have tried upping the image ebs as far as a m4.x16large to see if higher network or cpu would help the speed to no avail.
Full log attached.
Is there anyway to increase a timeout

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  Taking a look at your .json, I don't think sysprep is the problem here.. I think it's that you are sending a shutdown command in the powershell provisioner but are not setting [disable_stop_instance](https://www.packer.io/docs/builders/amazon-ebs.html#disable_stop_instance) on your builder.

If you're having trouble getting a build up and running or have more general questions, the [mailing list](https://www.packer.io/docs/builders/amazon-ebs.html#disable_stop_instance) is a better place to get help than the bug tracker, because more people are viewing the mailing list. The github issues tracker is only read by a small handful of maintainers, rather than the larger community.

Hope this helped :)
