### ISSUE TITLE
ResourceNotReady: failed waiting for successful resource state

### ISSUE THREAD

**Issue by rephric** [hashicorp/packer#7708]
Packer version = 1.3.5
Host platform = rhel7.5
Hello Hashicorp,
I am currently using a gitlab runner to create AMI's in a pipeline. I consistently am receiving this error:

`
Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state
Build '<>' errored: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state

==> Some builds didn't complete successfully and had errors:
--> <>: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state

==> Builds finished but no artifacts were created.
ERROR: Job failed: exit status 1
`
I am also making sure I am exporting the necessary variables.
$ export AWS_POLL_DELAY_SECONDS=30
$ export AWS_MAX_ATTEMPTS=3000
$ export AWS_TIMEOUT_SECONDS=3000

In my packer.yml file, I am setting two variables that I think could be causing the problem from reading other bugs.

      "kms_key_id": "arn:ijasdnfksnfkjsanfjk",
      "encrypt_boot": "true",

**Comment by agutierrezl** [comment]
Same issue here but:

Packer version = 1.4.1

**Comment by SwampDragons** [comment]
@rephric Thanks for reaching out. I think your issue is that you're providing the arn, not the kms key id.  In the example from the [docs](https://docs.aws.amazon.com/kms/latest/developerguide/viewing-keys.html)

```
$ aws kms list-keys
        
{
  "Keys": [
    {
      "KeyArn": "arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab",
      "KeyId": "1234abcd-12ab-34cd-56ef-1234567890ab"
    },
```

You want to use the key ID with this format: `1234abcd-12ab-34cd-56ef-1234567890ab`. 

I think this is a configuration error, rather than a bug, so I'm going to close for now. If you are still having trouble getting this working, reach out to our [mailing list](https://groups.google.com/forum/#!forum/packer-tool), which is a better place for general usage questions. The Github issues are only viewed by a small group of maintainers, rather than the broader community.

**Comment by minusdavid** [comment]
I'm not sure that this was the correct assessment. 

According to https://www.packer.io/docs/builders/amazon-ebs.html, "kms_key_id (string) - ID, alias or ARN of the KMS key to use for boot volume encryption."

Indeed I've been using the KMS ARN for months and it's been fine. I'm only now getting the same problem as the OP...

**Comment by minusdavid** [comment]
Just tried using the KMS ID instead and it didn't make a difference. 

It looks like the problem might be encryption related though, since the EC2 shuts down automatically before Packer can do anything...

**Comment by minusdavid** [comment]
Looks like a permission issue for me. 

I've changed the API user I'm using and changed the IAM policies...

I tried the policy at https://www.packer.io/docs/builders/amazon.html, but it's not doing it.

Ahh... I bet it's because the new user isn't defined in the KMS key policy for use of the key. That'll do it.
