### ISSUE TITLE
Unable to build vmware-iso in headless mode

### ISSUE THREAD

**Issue by bheisig** [hashicorp/packer#7715]
Hello everyone,

While using the builder `vmware-iso` with option `"headless": true` packer aborts directly after starting the virtual machine:

~~~
Error starting VM: VMware error: Error: The operation was canceled
~~~

[For more details please have a look at my gist.](https://gist.github.com/bheisig/87224832d9332697d3d0a77dd7903618) In short:

- packer 1.4.1
- Builder `vmware-iso`
- VMware Workstation 15.1
- Ubuntu 18.10 x64

Without this option, everything works as expected.

I've also tried tweaking the option `version` based on a [list of virtual hardware versions](https://kb.vmware.com/s/article/1003746) provided by VMware. There's no chance to start the machine in headless mode. Same on a Debian 9 x64.

Am I missing something? Thanks in advance.

Ben

**Comment by SwampDragons** [comment]
what happens when you run `/usr/bin/vmrun -T player start builds/mylittlehost-vmware/mylittlehost-vmware.vmx nogui` without using Packer?

**Comment by bheisig** [comment]
Almost the same:

~~~
$ /usr/bin/vmrun -T player start mylittlehost-vmware.vmx nogui
Error: The operation was canceled
~~~

…while…

~~~
$ /usr/bin/vmrun -T player start mylittlehost-vmware.vmx
~~~

…is working. I've added the file [vmware.log](https://gist.github.com/bheisig/87224832d9332697d3d0a77dd7903618#file-vmware-log) to the gist.

**Comment by SwampDragons** [comment]
That makes it seem to me like this is a vmware bug unrelated to Packer; this OS may not work with vmware in headless mode.

**Comment by bheisig** [comment]
Ok, seems valid. I've tried it with Ubuntu 18.10, 19.04 and Debian GNU/Linux 9.9. Can you recommend any OS which should work?

**Comment by SwampDragons** [comment]
This may be a better question for the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://learn.hashicorp.com/packer/); I maintain Packer but I'm not an expert in every platform.

**Comment by jamesberger** [comment]
Running into this exact issue, anyone else affected by this?

```# vmrun -T player start packer-vmware-iso.vmx nogui
Error: The operation was canceled
```

Unable to do away with the headless option:
```# vmrun -T player start packer-vmware-iso.vmx
Error: Cannot launch the UI because no display server is present in the current environment```

**Comment by bheisig** [comment]
Switching to Workstation Pro 15.1 on Ubuntu 19.04 solves the problem. Headless mode is working fine now but costs ~250 €. Not sure if it's worth it…

**Comment by jamesberger** [comment]
Ended up using a ESXi server we had sitting around for a remote host build, was able to get around the issue after that. 

It'd be nice if a free VMware product would work here though.

**Comment by DanHam** [comment]
I've run into similar issues in the past. Starting VMware in headless mode from Packer doesn't appear to initialise or start up VMware properly - hence the issue. The same is true when using the CLI `vmrun` commands. This seems to be a bug in VMware.

To 'solve' the issue I had to start VMware *once* using the GUI. This would then initialise everything correctly after which I could then close the GUI and quit VMware. After this 'start up and shutdown via the GUI' Packer would run happily in headless mode. 

It's a bit strange I know but it seemed to do the trick. I usually came across this problem straight after I had rebooted. Clearly, at this point I hadn't yet started VMware via the GUI at any point and so saw the issue...

I am using VMware Fusion Professional Version 8.5.10 (7527438).

Clearly, this issue may have been fixed with the newer versions of VMware Fusion/Workstation...

**Comment by fr34k8** [comment]
came across this in VMware Workstation 15.1.0 build-13591040 @DanHam your workaround does not apply to me

**Comment by fr34k8** [comment]
applies to me also on VirtualBox. 

im building on a few hypervisors these days and VirtualBox gives me:
`has terminated unexpectedly during startup because of signal 6` 

which is almost identical to this thing here

**Comment by vbyrd** [comment]
The issue for me was related to the fact that VMWare does some magic when accepting the evaluation license from the GUI and seemingly nowhere else.

I could install VMWare workstation completely from the CLI using flags on the bundle file:
`bash ./vmware-workstation-full-latest-blah.bundle --console --eulas-agreed --required`

But my Packer builds would continue to error out when executing **vmrun** due to no valid license:
`2020-04-03T13:48:19.951-07:00| vmx| I125: [msg.License.no_valid_license_see_website] Cannot find a license key to unlock this version of vmrun.
2020-04-03T13:48:19.951-07:00| vmx| I125+ Go to our web site at "http://vmware.com/info?id=27&build=15785246" to obtain a valid license key.
2020-04-03T13:48:19.951-07:00| vmx| I125: ----------------------------------------
2020-04-03T13:48:19.951-07:00| vmx| I125: MsgIsAnswered: Using builtin default 'OK' as the answer for 'msg.License.no_valid_license_see_website'
2020-04-03T13:48:19.951-07:00| vmx| I125: LICENSE no valid one found
2020-04-03T13:48:19.951-07:00| vmx| I125: Module 'License' power on failed.`

My solution was to monitor the process it was calling when accepting the Eval License through the GUI:
`/usr/lib/vmware/bin/vmware-setup-helper -n "VMware Workstation" -v 15.0+ -s M56JK-GY3E1-489PA-0H900-A0H16 /usr/lib/vmware/licenses/site/license-ws-150-e1-201804 /etc/vmware/license-ws-150-e1-201804`

Once I determined this, I executed it manually after a fresh install of vmware and everything worked. No GUI needed!

**Comment by SwampDragons** [comment]
Thanks for that workaround -- I'm not sure it's Packer's place to autogenerate this eval license (the legality of us automatically doing that for users seems fuzzy at best here) so I'm not sure what we can do on Packer's side except maybe document that this could be an issue. Thoughts?

**Comment by vbyrd** [comment]
I agree that documentation would be the best option. Testing headless packer builds in a dev environment as close to production-ready as possible, I like the option of not having to worry about the license. In a production environment, I would absolutely apply for a valid license before pushing my code.

It seems that the serial number is generated on install of VMware so I am not sure if my previous command would work for other users. It could be random and doesn't really matter but I'd prefer it if someone else attempts my solution and responds back if it works.
```
/usr/lib/vmware/bin/vmware-setup-helper -n "VMware Workstation" -v 15.0+ -s M56JK-GY3E1-489PA-0H900-A0H16 /usr/lib/vmware/licenses/site/license-ws-150-e1-201804 /etc/vmware/license-ws-150-e1-201804
```
At some point, I will wipe out my test server and try it again from scratch to verify.
