### ISSUE TITLE
Malformed Windows Path validation error

### ISSUE THREAD

**Issue by mobee-pdufresne** [hashicorp/packer#7718]
Hi there

Packer OS: CentOS 7
Packer Version 1.4.0

    {
    "type": "powershell",
    "remote_path": ":\\Windows\\Temp\\deploy\\base.ps1",
    "script":"{{user `packer_path`}}/playbooks/windows/scripts/base.ps1"
    },

if the path is malformed, packer still executes the JSON and when that particular Provisoner goes to execute, it hangs for a while then terminates in an unexpected EOF error.

**Comment by SwampDragons** [comment]
We could see if we can do some kind of general pre-run validation, but I suspect that this would still happen for certain path typos.  

I'll see if I can figure out how to handle this EOF and give a more useful error. I took a quick look at the winrm client code yesterday and it looks like it should be raising a reasonable error message in the situation where the copy fails, so I'm not sure why it isn't. I'll do a deeper dive this afternoon.

**Comment by mobee-pdufresne** [comment]
Hi there

all windows Paths start with an alpha character, [a-zA-Z], case insensitive.  so 26 maximum options.  you can reference the volume by it's GUID but way to advanced for Packer to be useful, nor human readable.  

IMO a quick regex to check for [a-zA-Z] prefix before the colon of the path ( [a-zA-Z]:\path\to\use\file.txt ) before packer launches should be enough.  To wait until WinRM connection is established is a bit too far along the process and I wouldn't depend on WinRM to do error checking.  

windows does support Unix Style pathing as an absolute path.  
```
\path\to\use\file.txt = c:\path\to\use\file.txt 
```
so if there is Colon prefixed before the first slash, but no Alpha character, then the path is invalid.

**Comment by SwampDragons** [comment]
Yes, like I said, we can do that check, but I think it would only solve the issue for a small number of cases. For example, if you set a remote path of `\path\too\use\file.txt` when it should be `\path\to\use\file.txt`, I think this same error would occur, and a pre-run regex can't save you from that. You'll only find out when you try to run the provisioner and the copy fails.

**Comment by mobee-pdufresne** [comment]
I'm not sure I follow your example

if the remote_path is :\path\to\follow\file.txt thats the problem and the more likely use case

I know of very few windows admins (in fact i'm the only one of the many I know) who use the unix-style pathing without the Character prefix and generally is only directly on the Console Windows (DOS or Powershell) with tab completion.

if there is a unix-style path set in the Remote_Path variable for a windows without a preceding period (2nd use case to specify relative path) - remote_path=".\\path\\to\\file.txt" then I would agree that a pre-run regex would not save you as you can't be certain if its intentional or a typo and its not Packer's Job to decide if it is or isn't.

remote_path=":\\path\\to\\file.txt" - Invalid Absolute Path
remote_path=".\\path\\to\\file.txt" - Valid Relative Path (this will place it in the default of c:\users\administrator (default path of the user launching the shell window), not Packer's problem since it is a valid path incantation otherwise)

**Comment by SwampDragons** [comment]
I understand your point. I've updated my example to use windows-style pathing because the unix-style pathing wasn't actually relevant to it.  

All I was trying to say is that it in addition to your check, we also have to properly handle the EOF error and return a useful message, because your check will not protect all users of this feature from this error.

**Comment by mobee-pdufresne** [comment]
Ah, yes. now I understand. A friendly failure.

**Comment by SwampDragons** [comment]
https://github.com/hashicorp/packer/pull/7913 fixes the EOF error and replaces it with a more useful one (the "friendly failure" we discussed)

I've thought about validating, but I have decided I don't want to get into the business of attempting to validate pathing for the remote machine, because I don't like Packer making assumptions about the remote filesystem.  Maybe later when I have more bandwidth and can do the research to make absolutely sure that our validation won't generate false positive failures, I can take a look but for now I think the "friendly failure" is enough here.
