### ISSUE TITLE
v1.4.0 and above amazon-ebs unexpected EOF with ansible provisioner

### ISSUE THREAD

**Issue by bbuivn** [hashicorp/packer#7727]
Hi,

* Packer v1.4.1
* macOS Mojave 10.14.5

I am trying to build an AMI from the following template using `shell` and `ansible` provisioners:
https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-debian-json

Debug log:
https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-packer-amazon-ebs-eof-log

The AMI is well built when we disable the ansible provisioner.
Here's the playbook and role:
playbook: https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-playbooks-packer-yml
role: 
https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-ansible-role-tasks-yml
vars:
https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-ansible-vars-yml

That template was used three months ago and worked well, I've tried all versions down from 1.4.1 to 1.3.5.
In 1.3.5 it does work as expected but all version above crash in the same fashion.

Here's the log for the build with 1.3.5 as a comparison:
https://gist.github.com/bbuivn/41414d2856a6f9a5552c5e898716c389#file-packer-1-3-5-success-built-log

I've checked the changelog from 1.4.0 and above but haven't been able to spot something related to this case, I may have missed it though.

Thanks!

**Comment by SwampDragons** [comment]
Looking at the traceback, this is happening because we aren't defining a IsUserAuthority callback here: https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L232-L244, which is causing a nil pointer dereference here: https://github.com/golang/crypto/blob/master/ssh/certs.go#L344. The weird part: you said it's a regression in v1.4.0... but you're right that we haven't changed anything related to this in that time frame, nor has the crypto library changed in any relevant way, as far as I can tell.

I can probably fix it by adding the callback but I have no idea why it wasn't broken before.  

I'll keep digging at this tomorrow.

**Comment by SwampDragons** [comment]
Can you try out the build at https://circleci.com/gh/hashicorp/packer/4293#artifacts/containers/0 and let me know if it solves your issue?

**Comment by bbuivn** [comment]
Hi @SwampDragons,

This build does work like a charm indeed!

Thanks a lot!
