### ISSUE TITLE
Feature Request: More verbose description on the type of tag being applied

### ISSUE THREAD

**Issue by shapp1** [hashicorp/packer#7772]
I'm utilizing run_tags, spot_tags, run_volume_tags, and tags for the aws builder.  The console shows the tagging process like so:

==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Owner": "John Doe"
    amazon-ebs: Adding tag: "OS": "linux"
=> amazon-ebs: Adding tags to source EBS Volumes
    amazon-ebs: Adding tag: "Owner": "John Doe"
    amazon-ebs: Adding tag: "Environment": "hr"
    amazon-ebs: Requesting spot instance 't2.small' for: 0.0175
    amazon-ebs: Waiting for spot request (sir-xxxxxxxx) to become active...
    amazon-ebs: Adding tag: "App": "test-app-01"
    amazon-ebs: Adding tag: "Beta": "true"
[..etc..]

My request is that packer output more verbose tagging text, for example, "Adding spot_tag "blah": "blah"", "Adding run_tag "blah": "blah", etc... to let the user know which block of tags to look at if a change is needed.

Thanks

**Comment by azr** [comment]
Hello there @shapp1, thanks for reporting, I like the idea, but it's not really easily doable in the current state of the code.

The tagging code is refactored into a common TagMap type that is used across builders:

https://github.com/hashicorp/packer/blob/c4f3dccc148bed4241a3b19f3f1b89824bf39a50/builder/amazon/common/tags.go#L12-L19

Since all the tagging fields are using the same underlying type. It's hard to have it log differently.

One quick'n'dirty thing we could would be to pass a specified logging func in there.

Ideally I would like to be able to pass some context for each function that logs something, but that's a much much bigger refactor...

If you have any other simpler ideas I'd be happy to discuss about them !
