### ISSUE TITLE
Packer spot auto too low

### ISSUE THREAD

**Issue by victoronto** [hashicorp/packer#7808]
- Packer version from `packer version`
 1.4.1
- Host platform
 AWS
- Packer template, and Debug log output from `PACKER_LOG=1 packer build template.json`
[here](https://gist.github.com/victoronto/49309792c4354bd13c0ab12644fe7392)

From AWS console, the spot status is :
price-too-low: Your Spot request price of 0.1294 is lower than the minimum required Spot request fulfillment price of 0.148.

**Comment by victoronto** [comment]
It seems been fixed in https://github.com/hashicorp/packer/pull/3662, but that's years ago before version 1.  I believe AWS has changed how spot bidding works, could it be possible we also need to change something?

**Comment by SwampDragons** [comment]
You're right; looks like they changed things in march: https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/

**Comment by SwampDragons** [comment]
How often has this happened to you?  Looking at our code and reading Amazon's updates about how spot pricing works, it seems like it should still work for these purposes.

**Comment by SwampDragons** [comment]
After researching and thinking about this a bit, I've decided to remove our bidding code since it seems that it's no longer relevant. When users set "auto" we'll set a max spot price of the OnDemand price and if they want to guarantee lower prices than that they can still manually set the max spot price; with bidding gone, any more nuance than that is really unnecessary. Amazon now sets the spot prices explicitly, so you pretty much know what you're going to pay based on historical trends.
