### ISSUE TITLE
Packer not recognising user variable as builder type...

### ISSUE THREAD

**Issue by deanwarren** [hashicorp/packer#7811]
Packer not recognising user variable as builder type, or at least does not appear to be expanding the variable.

- Packer version : 1.4.1
- Host platform : Windows 10, using WSL 1
- Debug log output :
```
2019/06/28 16:56:54 Loading builder: {{user `builder_type`}}
2019/06/28 16:56:54 Builder not found: {{user `builder_type`}}
2019/06/28 16:56:54 ui error: Failed to initialize build 'virtualbox-iso': builder type not found: {{user `builder_type`}}
```

- Example :
```
{
    "variables": {
        "builder_type": "virtualbox-iso"
    },
    "builders": [
        {
            "type": "{{user `builder_type`}}",
            " keyboard-configuration/layout=USA<wait>",

```

**Comment by SwampDragons** [comment]
Currently the variable interpolation happens after builders have been parsed. It might be possible to add an interpolation step specifically to the builder type (here, maybe?)[https://github.com/hashicorp/packer/blob/master/template/parse.go#L108] but I don't think we've ever had anyone want to do this before.  The builders have enough custom options that don't overlap that it's pretty hard to generalize them in a way that allows you to swap out the type.

**Comment by deanwarren** [comment]
That is a shame as the templating should be consistent across the file, not just at certain points onwards (albeit it's only the builder type not included). It is a fair point though about the options within the builders. I was going to see if I could generalise the builder, but run into this.

I think it may be useful to have general builder definitions plus specialisations for each builder - seems a shame to copy and paste. Guess I could use variables for the comment bits....

**Comment by SwampDragons** [comment]
Unfortunately, templating will never be 100% consistent across the file because certain template engines intentionally only exist for particular plugins. Interpolating the template is a complicated, multi-part process based on when the interpolated information is even available to add.

I did some tinkering and it turns out that it's possible to implement this (see the linked PR), but I'm still not convinced it's wise.  A pretty basic part of the philosophy of Packer is to make the provisioners/post-processors general and the builders specific. If you're worried about things like boot commands being bulky, you can put the boot command itself into a variable.  

I understand not wanting to copy and paste. I'm a big fan of DRY code.  But there's a balance between DRY and explicit.  This feels like it's going to tacitly endorse adding a layer of obfuscation to something that doesn't really buy the user much other than feeling good about saving a few lines of copypaste.

For what it's worth, things like boot_command can fit into their own variables so you don't have to copy tens of lines at a time of commands.

I'll think on this some more but my gut instinct is to keep things how they are and force users to be clear about what builder type their config is intended for.

**Comment by deanwarren** [comment]
Ok, and thanks for your feedback.
