### ISSUE TITLE
Packer is exiting unexpectedly every time at different step 

### ISSUE THREAD

**Issue by RahulPagare** [hashicorp/packer#7881]
Issue:

For last few weeks I’m unable to create packer template.
The issue is that while running packer for one or other step packer exits automatically and provisioner moves on to next step.
It’s like sometimes it exit with exit code 0 while installing SQL sometimes while installing VS .
I want the installation to be completed and new template gets created.

- Packer version :- 1.4
- Host platform :- I’ve tried on Windows Server 2008 R2 and Windows Server 2012

The output appeared in log file where it is exiting while installing Visual Studio .If you need i can provide complete log file
```
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Installing VisualStudio2012
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Starting Install
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Starting OtherInstallerFilePath
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Beginning wait process
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Finding the process ID '4076'...
2019/07/17 02:30:59 ui:     azure-arm: 07/17/2019 07:30:58: INFO: Process 'vs_premium' (4076) found. Waiting to finish and capturing all child processes.
2019/07/17 02:34:21 packer.exe: 2019/07/17 02:34:21 [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE=\"azure-arm\"; $env:PACKER_BUILD_NAME=\"azure-arm\"; &'c:/Windows/Temp/script-5d2ec87b-2733-d2fc-8c25-098069260e27.ps1';exit $LastExitCode }"' exited with code: 0
2019/07/17 02:34:21 packer.exe: 2019/07/17 02:34:21 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 02:34:21 [INFO] 4030 bytes written for 'stdout'
2019/07/17 02:34:21 [INFO] 237 bytes written for 'stderr'
2019/07/17 02:34:21 [INFO] RPC client: Communicator ended with: 0
2019/07/17 02:34:21 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 02:34:21 packer.exe: 2019/07/17 02:34:21 [INFO] 4030 bytes written for 'stdout'
2019/07/17 02:34:21 packer.exe: 2019/07/17 02:34:21 [INFO] 237 bytes written for 'stderr'
2019/07/17 02:34:21 packer.exe: 2019/07/17 02:34:21 [INFO] RPC client: Communicator ended with: 0
2019/07/17 02:34:21 [INFO] (telemetry) ending powershell
2019/07/17 02:34:21 [INFO] (telemetry) Starting provisioner windows-restart
2019/07/17 02:34:21 ui: ==> azure-arm: Pausing 1m0s before the next provisioner...
2019/07/17 02:35:21 ui: ==> azure-arm: Restarting Machine
2019/07/17 02:35:21 packer.exe: 2019/07/17 02:35:21 [INFO] starting remote command: shutdown /r /f /t 0 /c "packer restart"
2019/07/17 02:35:21 packer.exe: 2019/07/17 02:35:21 [INFO] command 'shutdown /r /f /t 0 /c "packer restart"' exited with code: 0
2019/07/17 02:35:21 packer.exe: 2019/07/17 02:35:21 [INFO] RPC endpoint: Communicator 
ended with: 0
2019/07/17 02:35:21 [INFO] 0 bytes written for 'stdout'
```

**Comment by LangJV** [comment]
I had this issue at one point. It turned out that when i also watched the console i would notice that the OS was restarting intermittently for certain steps and not "waiting" fully - causing it to just fail out at whatever step(s) it had gotten to when the restart happened.

Perhaps something similar is happening in your case>

**Comment by SwampDragons** [comment]
Thanks for reaching out.  Sorry you've been having a tough time getting started :) I think @LangJV's suggestion is the most likely. Try to set up your installations and updates so that they don't force auto-restarts, or look at an existing windows project to see workarounds. 

For example, in https://github.com/joefitzgerald/packer-windows/blob/master/windows_2012_r2.json you will see that the windows updates are provided as a floppy file and run during the autounattend phase so that Packer doesn't end up in a weird situation with communicator disconnects.

You may also want to look at the [check_registry](https://www.packer.io/docs/provisioners/windows-restart.html#check_registry) option on the windows-restart provisioner. This makes Packer wait until all registry keys telling the machine to reboot have been cleared, giving you a better chance that you won't get caught off guard during a reboot in a provisioning step.

Since I think this is a problem in your provisioning setup, not an issue we can resolve from Packer's side, I'm going to close for now. If you think that the problem is different than what we suggested, we need a simple template that reproduces the issue in order to spend more time looking into this. Alternatively, you can reach out to our [mailing list](https://groups.google.com/forum/#!forum/packer-tool) for advice. 

Thanks!
