### ISSUE TITLE
boot_command for parallels doesn't take affect. 

### ISSUE THREAD

**Issue by benlumia007** [hashicorp/packer#7883]
I'm having issues with parallels when using boot_command, it doesn't take affect. I tried different repositories from bento to  ubuntu, and my own and it doesn't do anything.

I'm not sure if this is the correct spot to get an answer .

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out -- For general questions like this, the better place to ask is the [mailing list](https://groups.google.com/forum/#!forum/packer-tool). Github is for bugs and feature requests, not general questions, because only the maintainers really keep up with the issue here.  You have better luck getting your question resolved if you post on the list, where more community members will see it.

You will probably need to share more information in order to get useful help: your Packer template, what platform you are using, etc.

**Comment by benlumia007** [comment]
thanks, I posted on the google group. I'll see if I get an answer from there. thanx for the info.

**Comment by benlumia007** [comment]
@SwampDragons 

I feel like its an issue with Packer ( bug ), can anyone verify if it works. I have tried older versions and it is still the same thing. 

I have parallels 14 Pro with MacOS 10.14.5 Mojave.

If there is no one to test, how can I be sure that it is or isn't a packer issue.

**Comment by SwampDragons** [comment]
If you really think it's a Packer bug, then please open a new issue with _all of the information requested in the issue template_.
