### ISSUE TITLE
Build 'virtualbox-iso' errored: Error executing Ansible: Non-zero exit status: exit status 2

### ISSUE THREAD

**Issue by zarr12steven** [hashicorp/packer#7926]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`

```
packer version : 1.4.1
```

- Host platform

```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com

- [My Gist](https://gist.github.com/zarr12steven/ee40ccdc5355c5c34d5f1ac3bde807b5)

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! 

From your ansible logs:


That packer error ` Non-zero exit status: exit status 2` just means that Packer is failing because your ansible run failed. Looking at the log lines we piped back from ansible: 

```
virtualbox-iso: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error, could not touch target: [Errno 2] No such file or directory: '/etc/modprobe.d/CIS.conf'", "path": "/etc/modprobe.d/CIS.conf"}
```

I'd say that either the /etc/modprobe.d/CIS.conf file doesn't exist or ansible doesn't have permission to access /etc/modprobe.d).

I think this is an issue with your configuration scripting, not with Packer so I'm going to close for now. I'd recommend setting a breakpoint before your ansible run and trying to run this ansible playbook by hand against your instance, in order to debug the problem most efficiently. If you have any more issues, please reach out!
