### ISSUE TITLE
Provisioner log message display method is confusing because it seems like an error message

### ISSUE THREAD

**Issue by rkttu-devsisters** [hashicorp/packer#7947]
Packer version: 1.4.2

Although it's a small, minor problem, I often feel uncomfortable because I use Packer frequently so I register an issue here as a feature request.

As shown in the attached screenshot, the output of the scripts registered in Provision step is displayed in red. It is difficult to distinguish it from real errors, because all the text is displayed in red like an error message, even if it is not an error.

![image](https://user-images.githubusercontent.com/35712113/62461572-31e1db80-b7c0-11e9-9f49-31f02d3a809e.png)

Is it possible to make appropriate improvements?

**Comment by SwampDragons** [comment]
I believe it's shown in red because it's coming through the stderr pipe, but I'll have to take a closer look to be sure.

**Comment by SwampDragons** [comment]
Yep, verified that this is happening because calling `set -x` inside your bash script streams the executed commands to stderr, not stdout. Packer makes red all the output received through the stderr pipe. You can redirect your script's stderr to stdout to fix this using the execute_command option in the shell-local provisioner: 

"execute_command": ["/bin/sh", "-c", "{{.Vars}} {{.Script}} 2>&1"],

But be warned that'll pipe "real" errors to stdout as well, so you won't get red even when you're expecting it. 

Or, you could remove the `set -x` from the script you're running.

I don't consider the current behavior a bug, so I'm going to close, but I hope the provided workaround makes you less anxious :)

**Comment by ColMelvin** [comment]
The [`PS4` environmental variable](https://pubs.opengroup.org/onlinepubs/9699969799/utilities/xcu_chap02.html#tag_02_05_03), which configures the prefix of `set -x` (xtrace) output and defaults to `+ `, offers a partial workaround by allowing the text after `+` to have a different format so it stands out in the logs.  You might try the following:
```
# `printf` used for universal compatibility; your shell may accept direct assignment
PS4=$(printf '+ \033[m')
set -x
```

One limitation of this approach is commands containing an argument with a newline will be red on subsequent lines.  I chose to reset the graphic rendition, since this will also work with `-no-color`; you could use any [graphic rendition](https://en.wikipedia.org/wiki/ANSI_escape_code#Select_Graphic_Rendition_parameters) you prefer, as Packer will reset the rendition at the end of the line _as long as it outputs in color_.

The first character of `PS4` is duplicated to show nesting levels, so there is value in putting the `+` (a printable character) before the color change; this means the `+` will still be red.  **Note:** `export PS4` may not work with nested shells as you'd expect due to mitigations for CVE-2016-7543.

**Comment by ColMelvin** [comment]
_If your shell supports it_, you might also be able to use `BASH_XTRACEFD` to redirect xtrace output to stdout; despite its name, it's not exclusive to bash, but it is not universal.  However, I've had mixed results with this approach; your mileage may vary.

One formulation uses `execute_command` though the implementation may need to vary between [shell](https://developer.hashicorp.com/packer/docs/provisioners/shell#execute_command) and [shell-local](https://developer.hashicorp.com/packer/docs/provisioners/shell-local#execute_command) provisioners:
```
execute_command = "chmod +x {{ .Path }}; BASH_XTRACEFD=3 3>&1 {{ .Vars }} {{ .Path }}" # shell
execute_command = ["/bin/sh", "-c", "BASH_XTRACEFD=3 3>&1 {{.Vars}} {{.Script}}"]      # shell-local
```

This method avoids an issue I ran into using the next method, where Packer would consistently hang indefinitely at the end of _some_ inline scripts.  It also exports `BASH_XTRACEFD`, affecting nested shells to positive and negative effect.  On the positive side, xtrace _can_ continue to show up in stdout; on the negative side, if a nested shell does not have access to FD 3 (because the FD was closed by a parent), then you may get an error or no xtrace output.  Finally, this hardcodes the FD, which could be limiting in uncommon situations.

Another formulation that avoids exporting `BASH_XTRACEFD` can be done by adding the following `inline`:
```
BASH_XTRACEFD=3
exec 3>&1
set -x
```

This method has caused Packer to consistently hang for me on a `shell-local` provisioner though, so be sure monitor for this.  However, it's also a consistent method across all provisioners and post-processors and you can add `PS4` to the mix for a fully encapsulated block.  And there's more room to dynamically allocate the FD, rather than hardcode the value; see https://stackoverflow.com/questions/8297415/in-bash-how-to-find-the-lowest-numbered-unused-file-descriptor.

**Note:** Setting `BASH_XTRACEFD=1` can cause xtrace output to appear in command substitutions (`$()`), breaking scripts.
