### ISSUE TITLE
hyperv-iso builder: use_fixed_format_vhd is documented as a boolean, but will not accept boolean values

### ISSUE THREAD

**Issue by evan-mcginnis** [hashicorp/packer#7992]
Packer 1.4.2
Windows Server 2012

Using the hyper-v iso builder, the use_fixed_format_vhd is documented as taking a boolean, but returns this error when a boolean is supplied:

"packer validate --var-file=C:\Users\Administrator\workspace\cms_pkg\workspace-azure\build\uservar_defaults.json C:\User
s\Administrator\workspace\cms_pkg\workspace-azure/build/donor_build.json"

C:\Users\Administrator\workspace\cms_pkg>packer validate --var-file=C:\Users\Administrator\workspace\cms_pkg\workspace-a
zure\build\uservar_defaults.json C:\Users\Administrator\workspace\cms_pkg\workspace-azure/build/donor_build.json
Failed to parse template: 1 error occurred:
        * variable use_fixed_vhd_format: '' expected type 'string', got unconvertible type 'bool'

Snippet of json file:

  "variables": {
    "iso_url":  "http://10.115.45.200/nfs-store/Provision/CentOS-7-x86_64-Minimal-1708.iso",
    "iso_checksum_type": "sha256",
    "iso_checksum": "918975cdf947e858c9a0c77d6b90a9a56d9977f3a4496a56437f46f46200cf71",
    "switch_name": "",
    "vm_name": "packer-centos76-g2",
    "disk_size": "70000",
    "vlan_id": "",
    "use_fixed_vhd_format": true,
    "output_directory": "output-donor"
  }

Is there a workaround for this?

**Comment by SwampDragons** [comment]
As a workaround, try putting it in quotes

**Comment by DanHam** [comment]
This is occurring because you are trying to set a bool in the *user variables section* - note the error message is prefixed with `* variable`. **All user variables must be strings** so Packer is throwing an error when it encounters your boolean. If you want to continue setting this value via a user variable, you should wrap the value you want in quotes as suggested.

You should have something like:

```json
  "variables": {
      "use_fixed_vhd_format": "true"
  },

  "builders": [
    {
      "type": "hyperv-iso",
      "use_fixed_vhd_format": "{{user `use_fixed_vhd_format`}}"
    }
  ]
```

When Packer parses the builder section of the template it will convert your user variable 'string' into the correct type for `use_fixed_vhd_format` - which, as you correctly point out, is a boolean.

User variables are always read in as strings as it is impossible to predict in advance what Type the variable is supposed to be. 

If you don't like the above, you could always set the value directly in the builder section:

```json
  "builders": [
    {
      "type": "hyperv-iso",
      "use_fixed_vhd_format": true
    }
  ]
```
