### ISSUE TITLE
Packer hangs on `Uploading VirtualBox guest additions ISO`

### ISSUE THREAD

**Issue by andrewsav-datacom** [hashicorp/packer#7998]
Packer hangs on `Uploading VirtualBox guest additions ISO` when provisioning Windows Server 2019 with Virtualbox Iso.

- Packer version: 1.4.2
- Host platform: Windows
- Debug log output, scripts and template: https://gist.github.com/andrewsav-datacom/aef68b66926b68e429d6a35d032af8fe

At the point showed in the log the packer process hangs indefinitely, never to resume.

**Comment by andrewsav-datacom** [comment]
Actually waited a bit more and it completed:

[12:38:17]==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
[12:56:35]==> virtualbox-iso: Gracefully halting virtual machine...

But why does it take so long?

**Comment by SwampDragons** [comment]
Sorry for the late response 😬 it's been a wild few weeks.

Winrm can be pretty agonizingly slow; we haven't had a chance to investigate why, but it's a known issue. Are you able to use the ["attach"](https://www.packer.io/docs/builders/virtualbox-iso.html#guest_additions_mode) mode instead of uploading as a workaround?

**Comment by SwampDragons** [comment]
Actually, looks like we know why and it's a limitation of winrm: 

https://github.com/hashicorp/packer/issues/2648#issuecomment-183472355

see #4806, #2648 for previous issues where this has come up.

I'm going to close this since I don't think there's much we can do but I think that using "attach" instead of "upload" for the guest additions is probably the right call for you.
