### ISSUE TITLE
!!! PACKER CRASH !!! - ui error: --> azure-arm: unexpected EOF

### ISSUE THREAD

**Issue by tbeavers** [hashicorp/packer#8031]
Attempting to create Windows virtual machine image on Azure via Packer and received PACKER CRASH error without much other error information with the exception of a crash.log that I have attached along with associated build file.

[crash.log](https://github.com/hashicorp/packer/files/3535028/crash.log)

[azure_windows_2019_Dev_TEST.json.txt](https://github.com/hashicorp/packer/files/3532210/azure_windows_2019_Dev_TEST.json.txt)

Packer version is 1.4.2
Host platform is Windows 10 (1809) using VS Code 1.37.0 with powershell terminal

If you need any additional information, please let me know.

Thanks for your support,

Terry

**Comment by DanHam** [comment]
@tbeavers I think the bug causing the crash you experienced has been fixed in version 1.4.3 of Packer - specifically by [THIS](https://github.com/hashicorp/packer/commit/4c09dfde872875716a1d7b77b3590ec457bf58e3#diff-168d8353ae7a59ff1b03a1ec9bab936a) change made in #7837.

Can you try with version 1.4.3 and see if the problem still exists?

**Comment by tbeavers** [comment]
Thanks DanHam!

Upgrading to packer 1.4.3 did the trick!

This is can be closed.
