### ISSUE TITLE
File provisioner fails to overwrite existing folder

### ISSUE THREAD

**Issue by joe-bowman** [hashicorp/packer#8032]
Using packer 1.4.2, the `file` provision will only overwrite the destination path (as per docs) if it is a file, but the same does _not_ apply for directories.
  
As a work around, I have a `shell` script that removes the original files before the `file` provision runs, but this is not ideal.

Source host: MacOSX High Sierra
Destination Host: Ubuntu 18.04 AMI created with EBS-Builder

**Comment by joe-bowman** [comment]
In addition (and I suspect the same underlying issue), the salt-masterless provisioner copying of `local_state_tree` doesn't update an existing folder.

**Comment by SwampDragons** [comment]
So this is a situation where I think that changing the default behavior would cause more confusion than keeping it the same, and that the appropriate way forward is to document it explicitly.

That said, I think we could probably add an "overwrite_remote_folder" option, though I'm not sure when I'll have a chance. My gut instinct is that it shouldn't be too hard for a new contributor to tackle, though.

**Comment by joe-bowman** [comment]
I'm happy to make the change, although it's unlikely to be this week, so if
anyone beats me to it, that's fine :)

**Comment by hwang381** [comment]
May I take a look at this issue as a Hacktoberfest issue? Thanks :)

**Comment by SwampDragons** [comment]
Sure thing!

**Comment by hwang381** [comment]
I opened a very early and preliminary CR for now because there needs to be a change on the `Communicator` interface which will affect a lot of other (seemingly irrelevant?) modules. If I understand things correctly, there seems to be two groups of communicators, ones that are externally visible, e.g. [enlist in the doc](https://www.packer.io/docs/templates/communicator.html), and ones that are used internally by builder, e.g. docker builder also has a communicator. If we can differentiate those two groups of communicators by different interfaces, maybe we could scope out the seemingly irrelevant changes?

Please take a look at this preliminary PR before I'd proceed with an implementation.

Thanks

**Comment by SwampDragons** [comment]
When @hwang381 looked into this, they found that it was a much bigger change than I'd thought. We've decided that the huge scope of changes necessary to make this happen is not worth the small enhancement to user experience that it represents, and are therefore closing this issue. If you absolutely must overwrite the entire directory, use the shell/powershell provisioner to delete the directory before upload. 

It is worth noting that any files with the same names seem to be overwritten properly; it's just files that exist on the target but not in the source that are left behind unchanged.

Thanks for investigating, @hwang381.
