### ISSUE TITLE
No boot_command interpolation inside -var-file

### ISSUE THREAD

**Issue by TyMac** [hashicorp/packer#8033]
Interpolation inside var-files does not appear to work. For instance:

    { 
	"boot_command": "<enter><wait><f6><esc><bs><bs>...<bs><bs><bs>/install/vmlinuz initrd=/install/initrd.gznet.ifnames=0 auto-install/enable=true debconf/priority=critical preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/{{user `ubuntu_preseed`}}.cfg <enter>",
	"generation": "1"	
    }
  
Above placed in a var-file (eg, -var-file=boot-command.json) translates to literally  ...http://{{.HTTPIP}}:{{.HTTPPort}}/... on the ubuntu boot options command line - instead of the actual IP and port.

Also, pre-defining variables in the "main" packer template appear to not get passed in to the var-file. Perhaps I'm doing something incorrectly, but if not this could be a valuable feature to allow more flexible builds.

**Comment by TyMac** [comment]
better title.

**Comment by SwampDragons** [comment]
>Also, pre-defining variables in the "main" packer template appear to not get passed in to the var-file.

Can you clarify with an example please?

**Comment by TyMac** [comment]
An example of non-functioning variable expansion when passing to the main json file to the var file could go as follows - below is an abbreviated main template where we want to pass **ubuntu_preseed** as a variable defined on the command line with the -var switch:

    {
        "variables": {
              "vm_name": "",
              "ubuntu_preseed": "",
              "git_commit": "",
              "git_branch": "",
       ...
        "builders": [
                    {
                        "type": "hyperv-iso",
                        "ubuntu_preseed": "{{user `ubuntu_preseed`}}",
                        "iso_url": "{{user `iso_url`}}",
        ...
    }

If the var is supplied on the command line - eg:

    packer -var ubuntu_preseed="preseed_1604" ... -var-file=boot-command.json ... ./main_packer.json 

the var does appear not appear to get picked up in the var file if defined as it was in the primary example - eg; boot-command.json looks like:

    { 
    "boot_command": "<enter><wait><f6><esc><bs><bs>...<bs><bs><bs>/install/vmlinuz initrd=/install/initrd.gznet.ifnames=0 auto-install/enable=true debconf/priority=critical preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/{{user `ubuntu_preseed`}}.cfg <enter>",
    "generation": "1"	
    }

**Comment by SwampDragons** [comment]
Okay, I have some results for you.

This is happening because boot_config is a "special" option that isn't interpolated during template "prepare" at the same time as the other template variables, but rather during the "build" phase. This is because the special variables like HTTPIP and HTTPPort don't exist yet during the prepare phase.

By making boot_command a variable, you're forcing it to be interpolated early, so you get meaningless values for .HTTPIP and .HTTPPort. 

There is a workaround: Use two boot_command variables. Example:

boot_command.json: 
```
{
    "boot_command_1": "<enter><wait><f6><esc><bs><bs>...<bs><bs><bs>/install/vmlinuz initrd=/install/initrd.gznet.ifnames=0 auto-install/enable=true debconf/priority=critical preseed/url=http://",
    "boot_command_2": "/{{user `ubuntu_preseed`}}.cfg <enter>"
}
```

template.json:
```
{
  "variables": {
    "ubuntu_preseed": ""
  },
  "builders": [
    {
      "boot_command": "{{user `boot_command_1`}}{{.HTTPIP}}:{{.HTTPPort}}{{user `boot_command_2`}}}}",
```

Obviously this isn't wildly elegant, but it gets the job done. As far as I can tell, (at least as of v1.4.4) the var_file is otherwise playing nicely with the template and the above example interpolates properly when ubuntu_preseed is provided via the command line.

For v1.5, we're going to be working on the way variables get shared between builders and provisioners; as part of that work I wouldn't be surprised if we also enable much smarter handling of things like the special .HTTPIP template variables. I'm going to leave this ticket open for now, but won't be actively working on it further for a few weeks or a month. I hope the workaround can tide you over until v1.5

**Comment by TyMac** [comment]
Ah ok. Did not know you could provide two boot commands! Will try it, thanks!

**Comment by SwampDragons** [comment]
The underlying golang templating engine is very powerful; you can interpolate pretty much as many variables as you'd like into individual options.
