### ISSUE TITLE
Azure with packer: "WinRM is not set up to allow remote access to this machine for management."

### ISSUE THREAD

**Issue by tbeavers** [hashicorp/packer#8055]
Using packer to try to create an Azure VM image and getting the following error when attempting to configure WinRM:

"WinRM is not set up to allow remote access to this machine for management.
azure-arm: The following changes must be made: azure-arm:
azure-arm: Create a WinRM listener on HTTP://* to accept WS-Man requests to any IP on this machine.
azure-arm: Configure LocalAccountTokenFilterPolicy to grant administrative rights remotely to local users."

- Packer version is 1.4.3
- Host platform is Windows 10 (1809) using VS Code 1.37.0 with powershell terminal

Trying to use the following powershell script to provision WinRM:

enable-psremoting
winrm quickconfig
Enable-WsManCredSSP -Role Server –Force
Enable-WSManCredSSP -Role Client -DelegateComputer * -Force
Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 2048
Set-ExecutionPolicy RemoteSigned -Force

Found a couple of links for configuring locally, but nothing for Azure.

I am a newbie to packer and Azure, so any help resolving this issue would be gratefully appreciated.

Thanks in advance for your support,

Terry

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! Normally If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help. This is because the GitHub issue tracker is only reviewed by the core Packer maintainers, rather than the greater community, and sometimes we're not the best at helping people get bootstrapped compared to folks who have recently tried to do the same thing as you.

Have you taken a look at the the examples in the code? https://github.com/hashicorp/packer/tree/master/examples/azure

Here's a blog post on setting up winrm within Azure -- you do need to do a bit of work before the packer run, inside the portal to make sure ports are opened, and that may get extra complex if you're behind a proxy.  https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-configure-winrm-after-vm-creation

There's a chance that you can work around this issue by picking a different windows server to start from; If you're new to Packer and Azure it's worth it to try starting from a known-good config like the one in the examples section and finessing from there.

Hope this helps, and if you're still struggling reach out to that mailing list :)

**Comment by tbeavers** [comment]
Thanks for your direction Megan.  I will try the resources you provided and hopefully get the issue resolved.
