### ISSUE TITLE
Pre baked kickstart scripts for vmware-iso builder

### ISSUE THREAD

**Issue by jdcarroll** [hashicorp/packer#8100]
From what I have understood about the philosophy of packer is to fully automate the creation of images for on premise data centers or in the cloud.  When it comes to the cloud and there provided image marketplace the ability to go from connectable instance to provisioner is seamless. This is because the cloud provider makes the assumption that user is going to want to launch into an instance at a working state.  When it comes to on premise architecture we need to configure the installation via boot command or autounattend or kick start script. my suggestion would be to add this in as overwritable default with the option to target a particular OS.

**Comment by rickard-von-essen** [comment]
Allow me to take on the sceptical hat 🎩.

These kickstart/preseed/autounatended.xml files will be tied to a specific version OS/distribution, communicator and disk device settings. Also they will be hard to maintain and will break over time unless they have a lot of users (that will catch and fix the errors) or an automated build and test system that will verify the quality.

Another way to help new users to get started would be to do a general doc page describing for each these files how to generate them and link to relevant documentation and well maintained examples.

Thats my cents

**Comment by SwampDragons** [comment]
Super valid points, as always, @rickard-von-essen. I definitely don't want this idea, which is supposed to be helpful, to cause the maintainers major headaches.

I think this came up originally because of the idea that sometimes new users come to Packer without realizing they need a preseed at all (either that, or I jumped to thinking about that during the conversation because it's happened a fair amount to me recently where I see "why doesn't this connect" issues and the answer is "you never supplied a preseed file"). I wonder if there's a way we could to a check, and if no http_dir or floppy_files are set, then to warn that there doesn't seem to be a preseed?

I definitely like the idea of having boot-command configuration and preseed files much better documented. I've been meaning to do this for a long time.

**Comment by SwampDragons** [comment]
I think this can be closed -- we created detailed "getting started" guides [here](https://www.packer.io/guides/automatic-operating-system-installs) which have been live for some time.
