### ISSUE TITLE
Powershell provisioner hangs when the console output is HUGE!

### ISSUE THREAD

**Issue by baghbidi** [hashicorp/packer#8126]
- Packer version from `packer version`: 1.4.3
- Host platform: Windows Server 2016

So Powershell provisioner was hanging on a msbuild command, tried the commands that have been running in the provisioner on a VM and they worked well - no console prompts, ... .

Set PACKER_LOG=1 and here is the last message I got before hanging forever:
```
2019/09/18 20:05:00 packer.exe: 2019/09/18 20:05:00 [INFO] command 'powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-5d828b94-aeeb-4c54-5ea6-364893a9458a.ps1"' exited with code: 0
2019/09/18 20:05:00 packer.exe: 2019/09/18 20:05:00 [INFO] RPC endpoint: Communicator ended with: 0
```
After investigating for a whole day, realized that the msbuild log before that RPC endpoint message was HUGE... around 200KB. Imagine a line of log that is 200KB. So I changed my msbuild command parameters and added `/v:q` (which means quiet) and it worked!

Not sure if it's an issue on WinRM side or Packer.

**Comment by azr** [comment]
Hello there thanks for reporting; I _think_ this is due to winrm being very very slow.
A related issue: https://github.com/hashicorp/packer/issues/2648

And if I am being correct then there is nothing we can do about this issue.
[Explanation here](https://github.com/hashicorp/packer/issues/2648#issuecomment-398868487).

So I will close this issue. Again please comment here if you think I am wrong; we'll reopen.
