### ISSUE TITLE
azure-arm: IMAGE_STATE_UNDEPLOYABLE - Non terminating packer error?

### ISSUE THREAD

**Issue by LazzariPaolo** [hashicorp/packer#8128]
**Packer Version** : 1.4.0
**Host machine** : Windows 10

**Issue:**

I ran a Packer build script using the *azure-arm* builder. 
As a base image, I am using the WindowsServer 2016-Datacenter image.

The build of my image is successful, however in the build output I see the following:

```
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: 
C:\Users\paolo\AppData\Local\Temp\powershell-provisioner224753973
azure-arm: IMAGE_STATE_COMPLETE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
```

I am running into some network issues when using the base image resulting from this Packer build, and I am wondering whether something went wrong during the Packer build.
What do the following error stacks:

> azure-arm: IMAGE_STATE_UNDEPLOYABLE

indicate?

In my Packer build file, I am using the following provisioners:

```
      {
        "type": "windows-restart",
        "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
      },
      {
        "type": "powershell",
        "inline": [
          "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
          "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
        ]
      }
```

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  

`IMAGE_STATE_UNDEPLOYABLE` is coming from your Powershell script (`Write-Output $imageState.ImageState`) , not from Packer.  The reason you see it in the Packer logs is because we try to stream all of the stdout from your powershell commands so you can see what the output of your script is. 

Since this isn't a Packer issue, I'm going to close the ticket, but if you have any more general questions, 
reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help; way more people read those lists than the issue tracker, so you're likely to get an answer much faster.
