### ISSUE TITLE
Unable to rebuild vagrant box with ansible customisations

### ISSUE THREAD

**Issue by nhojpatrick** [hashicorp/packer#8148]
#### Overview of the Issue

Several vagrant boxes that I use have an older version of virtualbox tools. I want to rebuild them with a newer version of virtualbox tools so improve boot up speed on 1st usage.

I also want to install/upgrade ansible on those boxes so that also reduces 1st uage boot times.

Several of my use cases are within ci/cd pipelines and i'm trying to reduce the vagrant box 1st boot time, so wanting to use packer to rebuild public boxes automatically.

#### Reproduction Steps

packer build template.json

### Packer version

1.4.2
1.4.3

### Simplified Packer Buildfile

https://gist.github.com/nhojpatrick/f7131147c0f02d26135fb806a9a2ba76

### Operating system and Environment details

Mac

### Log Fragments and crash.log files

For 1.4.2 and 1.4.3 output see below, each has different issues.
https://gist.github.com/nhojpatrick/f7131147c0f02d26135fb806a9a2ba76

**Comment by nhojpatrick** [comment]
Updated my gist with output from 1.4.1 and also for #8019 https://circleci.com/gh/hashicorp/packer/12898?fbclid=IwAR0MhZt1cW7ezrbLD7lDBl_6xVlq1BmrYz1tEvZFk6YoZGdg213SvCsXRbE#artifacts/containers/0

#8019 doesn't have the vagrant error, but still has the sudo ansible error.

**Comment by SwampDragons** [comment]
I think this is an Ansible question, not a Packer one.  you'll need to set up your [extra_arguments](https://www.packer.io/docs/provisioners/ansible.html#extra_arguments) field in the packer template to either provide the Ansible password in plaintext You can set this using an environment variable or read it in from another secure location and reference it as a user variable, but make sure to put it into the [sensitive-variables](https://www.packer.io/docs/templates/user-variables.html) field on the template if you do:

```
  "extra_arguments": [
    "--extra-vars", "ansible_become_pass=YOUR-PASSWORD-HERE"
  ]
```

Or you can use Ansible's vault to do something similar. This looks like a useful post on how to do that: https://www.cyberciti.biz/faq/how-to-set-and-use-sudo-password-for-ansible-vault/

Since I think all the vagrant builder issues have been addresses, I'm going to close but if you still have trouble getting this to work I'd recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help.

**Comment by nhojpatrick** [comment]
so with vagrant i do `vagrant up`, then `vagrant ssh`, then `sudo COMMAND` it works.
with vagrant and ansible I also do `vagrant up` with the playbook with tasks using `become: true`.

how do I achieve the same passwordless sudo with packer when booting a vagrant box and executing ansible?

packer seams to boot and configure vm's differently to when vagrant boots and configures vm's that are in fact the same vagrant box. what works by default with vagrant i'ld like to replicate when packer is wrapping vagrant.

**Comment by SwampDragons** [comment]
You can modify the command we use to run ansible to prefix it with sudo by updating the [command](https://www.packer.io/docs/provisioners/ansible.html#command) template option in the ansible provisioner, but I think that's an antipattern. 

Packer uses Vagrant's same connection settings to connect to the box. If you have a specialized vagrantfile with specialized connection settings that you want Packer to use, you can provide it and Packer will respect it. 

> how do I achieve the same passwordless sudo with packer when booting a vagrant box and executing ansible?

Passwordless sudo is only set via the sudoers file on the vm you're connecting to. It's possible that your passwordless sudo was working for a different user?
