### ISSUE TITLE
WinRM driver fails to connect

### ISSUE THREAD

**Issue by bernyrd-cyber** [hashicorp/packer#8150]
#### Overview of the Issue

WinRM fails to connect and packer build times out.

#### Reproduction Steps

`packer build -ver-file ${vars} ${config}`

I attempt with and without WinRM security. It seems that WinRM and PowerShell remoting expects at least self-signed certificates and allows you to ignore them. By hand I could get no other configuration but that to work.

It pains me to open this issue, but I can not find any usable documentation on this setup anywhere else. It is entirely possible I am doing something wrong, but I just fixed WinRM so that I can access the guest by hand.

### Packer version

1.4.3.

### Simplified Packer Buildfile
``` json
{
	"name": "windows_2012r2_base",
	
	"cpus": "2",
	"memory": "4096",
    "disk_size": "262144",
	
    "install_media": "",
    "install_media_checksum_type": "sha512",
    "install_media_checksum": "",
	"answer_media": "./media/windows_2012r2_base_setup.iso",
	"scripts_dir": "./media/windows_2012r2_base_setup",
	
	"output_directory": ".\\output\\win2012r2\\"
}
```

``` json
{
    "variables": {
		"name": null,
        "cpus": null,
        "memory": null,
        "disk_size": null,
        "install_media": null,
		"install_media_checksum_type": "file",
		"install_media_checksum": "{{ user `install_media` }}.sum",
		"answer_media": null,
		"scripts_dir": null,
		"output_directory": ""
    },
    "builders": [
    {
        "vm_name": "{{ user `name` }}",
        "type": "hyperv-iso",
        "output_directory": "{{ user `output_directory` }}",

        "iso_url": "{{ user `install_media` }}",
        "iso_checksum_type": "{{ user `install_media_checksum_type` }}",
        "iso_checksum": "{{ user `install_media_checksum` }}",
		"secondary_iso_images": [
			"{{ user `answer_media` }}"
		],

		"cpus": "{{ user `cpus` }}",
		"memory": "{{ user `memory` }}",
        "disk_size": "{{ user `disk_size`}}",
		"generation": 2,
		"enable_secure_boot": "true",

		"boot_wait": "0s",
		"boot_command": [
			"a<wait>a<wait>a"
		],
        "shutdown_command": "shutdown",

        "communicator": "winrm",
        "winrm_username": "Administrator",
        "winrm_password": "",
        "winrm_host": "",
        "winrm_port": 5985,
        "winrm_timeout": "60m",
        "winrm_insecure": "true",
        "winrm_use_ntlm": "false",
        "winrm_use_ssl": "true"
    }
    ]
} 
```

### Operating system and Environment details

Windows 2012 R2 with Hyper-V.

### Log Fragments and crash.log files

Unable to provide at this time, will try to update.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! It sounds like this is a "getting started" type issue, and for that I generally recommend learning by example. 

If you want to see a highly functional example of a windows build using winrm with the hyperv-iso builder, take a look at the builder defined [here](https://github.com/StefanScherer/packer-windows/blob/my/windows_2012_r2.json#L3-L31), particularly the winrm enable and disable scripts referenced [here](https://github.com/StefanScherer/packer-windows/blob/my/windows_2012_r2.json#L13-L14) 

Generally the windows workflow is to use an [autounattend file](https://github.com/StefanScherer/packer-windows/blob/my/answer_files/2012_r2/Autounattend.xml) which sets up winrm for you on the guest. If you want to perform windows updates, it's important to _disable_ winrm until the update cycle is complete. Once updates are complete, you can enable winrm using an enable script.  In this particular example, enabling winrm is handled as part of the [windows update](https://github.com/StefanScherer/packer-windows/blob/my/scripts/win-updates.ps1) script called by the autounattend file, but as you can see in the autounattend file linked above, if you don't want to do updates you can uncomment a chunk of that file to enable winrm from the beginning.

Since this is a "getting started" question and not a bug or feature request, I'm going to close but if you continue to have issues getting winrm working, please reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool)

**Comment by bernyrd-cyber** [comment]
Hello, I saw the request to not ask questions. I have looked at all those resources and had all of them fail. Notably I do have a working `autounattend.xml` and do have scripts that set up WinRM.

The issue is prompted partially by my inability to use generation 1 VMs. All of the examples target those. So if you think I will get better results from the mailing list I will use that, but perhaps leave this open and edit it so that the examples are eventually updated? That was kind of my intent in opening the issue.

**Comment by SwampDragons** [comment]
I notice in your config that you're telling Packer to use port 5985, which is normally used for the HTTP connection, whereas 5986 is used for HTTPS. You've also set winrm_use_ssl, which means we're going to try to connect via HTTPS.

**Comment by SwampDragons** [comment]
I've reopened because rather than having an example for each builder, it might make sense to add examples of the configuration that you need to perform for each communicator on the communicators docs page. https://www.packer.io/docs/templates/communicator.html#winrm

I will try to add some simple docs there.

**Comment by bernyrd-cyber** [comment]
Thanks! I think that is a good way to structure it. I retried with the correct port (I think I had used it in the past, but forgot to change it back). I still receive a failure. It is not clear if there are "normal" scripts I should be using. I see different scripts bundled in with random repos on Github. Packer still hangs.

``` powershell
$DnsName = $env:ComputerName
$Cert = New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My -DnsName $DnsName -Verbose
$Password = ConvertTo-SecureString -String $DnsName -Force -AsPlainText -Verbose

Export-Certificate -Cert $Cert -FilePath "C:\$DnsName.cer" -Verbose
Export-PfxCertificate -Cert $Cert -FilePath "C:\$DnsName.pfx" -Password $Password -Verbose

$CertThumbprint = $Cert.Thumbprint

Enable-PSRemoting -Force -Verbose
Set-Item WSMan:\localhost\Client\TrustedHosts * -Force -Verbose
New-Item -Path WSMan:\localhost\Listener -Transport HTTPS -Address * -CertificateThumbprint $CertThumbprint -Force -Verbose
Restart-Service WinRM -Verbose

New-NetFirewallRule -DisplayName "Windows Remote Management (HTTPS-In)" -Name "WinRMHTTPSIn" -Profile Any -LocalPort 5986 -Protocol TCP -Verbose
```

I'm then able to connect with:

``` powershell
Enter-PSSession -ConnectionUri https://$ip:5986 -Credential Administrator -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)
```

**Comment by SwampDragons** [comment]
There aren't "normal" scripts you should be using; you should be configuring WinRM however is appropriate for your instance, and then telling Packer how to connect via the various options.

**Comment by bernyrd-cyber** [comment]
I see, and think there needs to be some attention to how packer connects in the docs. I am at my wits end. I realized perhaps packer does not attempt to find the VM's IP address and so I set a definite name for `winrm_host` and enabled NetBIOS. That did not work, so I set a static IP which also did not work.

Static IP set by hand but could be done with WMI.

``` powershell
# Requires a reboot, so added to answers file for now.
#Rename-Computer -NewName "win-2012r2-base"
$DnsName = $env:ComputerName
$Cert = New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My -DnsName $DnsName -Verbose
$Password = ConvertTo-SecureString -String $DnsName -Force -AsPlainText -Verbose

Export-Certificate -Cert $Cert -FilePath "C:\$DnsName.cer" -Verbose
Export-PfxCertificate -Cert $Cert -FilePath "C:\$DnsName.pfx" -Password $Password -Verbose

$CertThumbprint = $Cert.Thumbprint

Enable-PSRemoting -Force -Verbose
New-Item -Path WSMan:\localhost\Listener -Transport HTTPS -Address * -CertificateThumbprint $CertThumbprint -Force -Verbose
Restart-Service WinRM -Verbose

# FPS (File-Printer-Sharing) is publicly allowed whereas NETDIS
# (network discovery) is not.
Set-NetFirewallRule -Name "FPS-NB_Name-In-UDP" -Enabled True -Verbose
New-NetFirewallRule -DisplayName "Windows Remote Management (HTTPS-In)"	-Name "WinRMHTTPSIn" -Profile Any -LocalPort 5986 -Protocol TCP -Verbose
```

**Comment by SwampDragons** [comment]
I've finished some docs updates. Hopefully you'll find them helpful, particularly https://github.com/hashicorp/packer/pull/8183/files#diff-96f156b591fe78114052718b80d6536a
