### ISSUE TITLE
starlark support

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/packer#8168]
#### Feature Description

Provide support for starlark based template files

#### Use Case(s)

Don't wait hcl/hcl2 and use already useful configuration language

**Comment by SwampDragons** [comment]
Hi, thanks for the suggestion. @azr is actively working on HCL2 at this point and I'm not interested in splitting our energy to work on a different configuration language at the same time. I know it's been a long and frustrating wait for people, but I promise it's almost over. 

Since we're not interested in implementing this I'm going to close but I do appreciate the suggestion.

**Comment by vtolstov** [comment]
Does it possible to handle input via plugin? Builders, provisioners and post-processors already can be plugins. Why not be able to handle via plugin input?

**Comment by SwampDragons** [comment]
This is a cool idea, and off the top of my head I can't think of any reasons not to, but it is not something we're not actively working on at this time. I know people have written wrappers for Packer that convert a yaml config into the json template that Packer can read, and this seems like less work than rearchitecting Packer's core to accept multiple kinds of plugins.

**Comment by vtolstov** [comment]
i'm open for discuss =).
I have two variants - handle input via plugins, or create packer convert command that use input file in yaml/starlark or something else and create json(and later hcl) template.
So when someone have problems we already have full official packer template file to investigation.
What you think?

**Comment by vtolstov** [comment]
variant with command more simple i think so we need unmarshal []byte slice to taget packer struct.

**Comment by SwampDragons** [comment]
I just don't think this is something that I want to have to maintain as part of the Packer core.
