### ISSUE TITLE
Unattended Windows 2012 R2 installation hangs at "Waiting for WinRM to become available"

### ISSUE THREAD

**Issue by gauravgoel1989** [hashicorp/packer#8171]
I am running unattended Windows server 2012 R2 installation through Packer and have 2 different templates. One with only the variable and builder declarations and it uses an autounattend.xml file for installation. The installation runs successfully and produces a final VM. On the other side, I have used same template and added post processor and provisioner to export the VM to AWS. However, this time the installation gets stuck at "Waiting form WinRM to become available". I have tried using additional parameters like winrm_insecure, winrm_use_ssl and winrm_port but none of them helped.

I am unable to understand why two different templates with same ISO image, autounattend.xml file, and enable-winrm script are behaving differently.

The local firewall in the VM is turned off by autounattend.xml file.

Please refer the attached zip file for my scripts/templates
[packer-issue.zip](https://github.com/hashicorp/packer/files/3667610/packer-issue.zip)
.
Any help is appreciated.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! In general, winRM connection questions are not bugs with Packer, so the github bug tracker isn't going to get you the kind of help and support you need to fix it. I'd recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help, because both of those have a lot more active readers than the bug tracker, which is only read by a small handful of maintainers.  I'm currently working on improving the docs around winRM but until that gets published, your best bet is to start working from an already-working source, like https://github.com/StefanScherer/packer-windows
