### ISSUE TITLE
Podman Support?

### ISSUE THREAD

**Issue by bshelton** [hashicorp/packer#8187]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

Would a podman builder be something that would be accepted if a pull request was put in? I'm starting to see people running rhel switching from Docker to Podman.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by SwampDragons** [comment]
We're trying not to add more third party builders to the Packer core, but if you want to create a third party plugin podman builder and make a docs PR, we will happily link to it.

Docs for creating third party builders: https://www.packer.io/docs/extending/custom-builders.html
Page where we link third party builders: https://www.packer.io/community-tools.html#community-builders

**Comment by SwampDragons** [comment]
If you get stuck, I'd also be happy to offer pointers and guidance. The reason we want to try to limit new builder merges is because the team of maintainers doesn't have the bandwidth to support any more ourselves.

**Comment by SwampDragons** [comment]
Closing since this was really a question and it's been answered. If you want more help developing the builder, or want to make a docs PR to add your builder to our website, just reach out :)

**Comment by theodoregoetz** [comment]
Just so @SwampDragons is aware, podman and buildah seem to be the future of containerization on linux since it solves docker security issues that Red Hat folks have been compaining about for a long time. More specifically, buildah is the tool that packer should probably use to build container images, but it's under the same umbrella as podman.

It may be time for the packer team to evaluate buildah and podman for inclusion into the core to ensure that packer stays relevant in the future.

That said, podman's CLI is almost 100% compatible with docker and a rough test shows that the docker builder almost suffices. It currently seems to get hung up on copying files into the container. Using the docker shell provisioner with a script yields an error that reads "docker: Error: cannot copy into running rootless container with pause set - pass --pause=false to force copying".
