### ISSUE TITLE
Warning: You are using Azure Packer Build to create VHDs which is being deprecated

### ISSUE THREAD

**Issue by LazzariPaolo** [hashicorp/packer#8217]
When building a standard, non managed VHD for Azure with Packer, the build output includes the following message:

> ==> azure-arm: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage

I checked the doc page but could not find information regarding when the builder for VHDs will be deprecated.

When will it be deprecated?

**Comment by paulmey** [comment]
Azure wants everyone to move to using managed images and managed disks because they hide the complexity with respect to storage account performance. Managed disks can be [exported to a VHD](https://docs.microsoft.com/en-us/azure/virtual-machines/scripts/virtual-machines-linux-cli-sample-copy-managed-disks-vhd).
What if we removed VHD support but added a post-provisioner that can automate the export to a storage account?

As for a date, we don't have a hard deadline, just a wish to untangle the mess it currently is.

**Comment by LazzariPaolo** [comment]
Why not support both?

Sure, the managed disk can be exported to a VHD, but then one also has to clean up and remove the managed disk...

**Comment by Dipluz** [comment]
I would love to be able to build a managed disk in my packer template.

**Comment by nywilken** [comment]
@LazzariPaolo, thanks for reaching out. I believe the initial question around the deprecation warning has been answered. Based off the conversation it doesn't look like there is any actionable items at this time (other than keeping an eye for the deprecation). I am going to close this issue. 

If anything changes around support for VHD builds or if you find your are running into an issue with the builds please feel free to open a new issue so we can help out. Cheers!
