### ISSUE TITLE
ability to provide regexp inside iso_checksum_url and iso_urls/iso_url

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/packer#8235]
When you want to maintain multiple images main problem that you need to periodically change iso path (because version changes) and sometimes iso checksum file location (inside url).
What you think about adding ability to use inside url regex, and add additional variable to control how to interpret it?
If variable true we try to get dir index via http and extract url link via regexp based on href + regex ?
If multiple matches found - get last via lexicographical order? As i see mostly software versions is easy to order via strings.Sort

**Comment by SwampDragons** [comment]
I can see how this would be useful, but I don't love the idea of having to handle multiple iso matches and pick the right one, or of having to handle regular expressions in an already complicated parsing syntax. This seems like the kind of feature that should really be handled by a wrapping script rather than inside of Packer itself. This seems like a cool idea but I think the maintenance burden would be too high for me to want to take on right now.
