### ISSUE TITLE
builder: vagrant - manage virtualbox VM

### ISSUE THREAD

**Issue by lioramilbaum** [hashicorp/packer#8239]
#### Feature Description

When vagrant builder launch a VirtualBox VM, I would like to specify how much memory and cpus to allocate the VM.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! You can already do this by using the [template](https://www.packer.io/docs/builders/vagrant.html#template) option to provide a vagrantfile template with the necessary fields.

Create a file that contains the following (this is the current default template): 

```
Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
	source.vm.box = "{{.SourceBox}}"
  end
  config.vm.define "output" do |output|
	output.vm.box = "{{.BoxName}}"
	output.vm.box_url = "file://package.box"
  end
  {{ if ne .SyncedFolder "" -}}
  		config.vm.synced_folder "{{.SyncedFolder}}", "/vagrant"
  {{- else -}}
  		config.vm.synced_folder ".", "/vagrant", disabled: true
  {{- end}}
end
``` 

and add the lines for configuring memory and CPU -- Vagrant docs for this can be found here:
https://www.vagrantup.com/docs/virtualbox/configuration.html#vboxmanage-customizations

Then save it and give the path to the new template in the "template" option linked above.

It would definitely be nice to make this directly configurable instead of needing a custom template, but since it's doable right now with this workaround, it'll be a low priority fix on my end. The best way to get nice-to-have changes like these is to open a pull request :)

**Comment by lioramilbaum** [comment]
Thanks. Will take a look at it.
