### ISSUE TITLE
amazon-import -  ClientError: Unable to determine kernel version

### ISSUE THREAD

**Issue by breisig** [hashicorp/packer#8302]
#### Overview of the Issue

I am trying to import my CentOS 8 VM image using packer 1.4.4 to AWS and the following error messages occur. But if I try to import a CentOS 7 vm to AWS, It has no issues.

```
    virtualbox-ovf (amazon-import): Uploading output-virtualbox-ovf\packer-awsdevelopment.ova to s3://imagevmplace/packer-import-1572541471.ova
    virtualbox-ovf (amazon-import): Completed upload of output-virtualbox-ovf\packer-awsdevelopment.ova to s3://imagevmplace/packer-import-1572541471.ova
    virtualbox-ovf (amazon-import): Started import of s3://imagevmplace/packer-import-1572541471.ova, task id import-ami-0a982d965114f8228
    virtualbox-ovf (amazon-import): Waiting for task import-ami-0a982d965114f8228 to complete (may take a while)
Build 'virtualbox-ovf' errored: 1 error(s) occurred:

* Post-processor failed: Import task import-ami-0a982d965114f8228 failed with status message: ClientError: Unable to determine kernel version., error: ResourceNotReady: failed waiting for successful resource state

==> Some builds didn't complete successfully and had errors:
--> virtualbox-ovf: 1 error(s) occurred:

* Post-processor failed: Import task import-ami-0a982d965114f8228 failed with status message: ClientError: Unable to determine kernel version., error: ResourceNotReady: failed waiting for successful resource state

==> Builds finished but no artifacts were created.
```

Again, if I try to import my CentOS 7 vm, it has no issues to successfully uploads.

### Packer version

Packer v1.4.4

### Operating system and Environment details

Running packer 1.4.4 on the latest Windows 10 to build a CentOS 8 image to import to AWS.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Looks like you're not the only one with this issue; I found some posts on the AWS forums with people asking the same questions. 

Looking at Amazon's docs on import/export requirements, the CentOS versions you're able to import are:
> CentOS 5.1-5.11, 6.1-6.8, 7.0-7.6 (6.0 lacks required drivers)

I'd recommend opening a support ticket with Amazon asking them to allow CentOS 8 imports.

In the meantime, it looks like people have had success building from a CentOS ami already on amazon either using the ebs builder or the ebssurrogate builder:    https://www.reddit.com/r/aws/comments/dek12y/centos_8_import/ even seems to have a person who's started wtih a centos7 ami, used ebssurrogate to build centos8, and generated a functioning Centos 8 ami from that. 

Unfortunately, since this is squarely on the Amazon side of things, Packer can't fix this for you :(
