### ISSUE TITLE
Qemu builder is not adding the minimal configuration when a new drive/device appears in qemuargs

### ISSUE THREAD

**Issue by bugbuilder** [hashicorp/packer#8379]
Hi,

I was working to create a qemu image. I based this work on [bento](https://github.com/chef/bento/tree/master/packer_templates/sles) and as part of the build I need to pass an [iso](https://github.com/chef/bento/blob/master/packer_templates/sles/http/sles-15-sp1-x86_64-autoinst.xml#L4-L12) with additional packages, if you check its virtualbox-iso builder, you could see that the configuration is using an [additional args ](https://github.com/chef/bento/blob/master/packer_templates/sles/sles-15-sp1.json#L31-L45) to accomplish it.

So, I set the qemuargs with this addtional iso so the autoyast could find it.
```json
"qemuargs": [
  ["-drive", "file={{user `mirror`}}/{{user `packages_iso`}},format=raw,if=none,id=cdrom0,readonly=on"],
  ["-device", "virtio-scsi-pci,id=scsi0"],
  ["-device", "scsi-cd,bus=scsi0.0,scsi-id=0,lun=1,drive=cdrom0"]
 ]
```
Sadly this would overwrite the [logic](https://github.com/hashicorp/packer/blob/98c94ab8cb3be5421c607bde176bca33d9454e8e/builder/qemu/step_run.go#L104-L146) of the disk interface because [drive/device](https://github.com/hashicorp/packer/blob/98c94ab8cb3be5421c607bde176bca33d9454e8e/builder/qemu/step_run.go#L259-L270) is present in qemuargs.

I fixed this, adding the virtio interface:
```json
"qemuargs": [
  ["-drive", "file=../../builds/packer-{{user `template`}}-qemu/{{user `template`}},if=virtio,cache=writeback,discard=ignore,format=qcow2"],
  ["-drive", "file={{user `mirror`}}/{{user `packages_iso`}},format=raw,if=none,id=cdrom0,readonly=on"],
  ["-device", "virtio-scsi-pci,id=scsi0"],
  ["-device", "scsi-cd,bus=scsi0.0,scsi-id=0,lun=1,drive=cdrom0"]
 ]
```

Related issues:[6804](https://github.com/hashicorp/packer/issues/6804)

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out.  The QEMU builder is one of our community-supported builders, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it, but otherwise it'll probably be fairly low priority for us to look into, especially since it does have a workaround (I do understand that the workaround is clunky and shouldn't have to happen, so this is something we'd like to fix, it's just a matter of finding the time).

**Comment by bugbuilder** [comment]
Thanks for the feedback @SwampDragons, this issue is already fixed. You could check the PR #8380

**Comment by SwampDragons** [comment]
Yeah, just came across it. This is what I get for reviewing weekend emails in the order in which I receive them. I'll review now :D
