### ISSUE TITLE
SHA256 doesnt match

### ISSUE THREAD

**Issue by KorruptedPineapple** [hashicorp/packer#8409]
#### Overview of the Issue
I apologize if my bug reporting is haphazard, I'm new to github/(proper) development.

Essentially the SHA256 generated from the unzipped binary does not match the SHA256 provided on the download page.

#### Reproduction Steps

Download the zipped binary, un-zip, check SHA256 checksum.

### Packer version

packer_1.4.5_windows_amd64

**Comment by nywilken** [comment]
Hi @KorruptedPineapple no need for apologies. The body of the issue was very clear. Thanks for including your reproduction steps. The SHA256 checksum is for the released deliverable `packer_1.4.5_windows_amd64.zip` and not the extracted binary. If you run the checksum against the zip file you should find that everything checks out. 

Verifying on a Linux machine
```bash
> wget https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_SHA256SUMS
> wget https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_windows_amd64.zip
> sha256sum -c packer_1.4.5_SHA256SUMS --ignore-missing                                                                                                                                                    packer_1.4.5_windows_amd64.zip: OK
```

**Comment by KorruptedPineapple** [comment]
Thank you @nywilken ! Is it industry standard to verify checksums against the deliverable and not against the executable?
