### ISSUE TITLE
unknown configuration key: "galaxy_command"

### ISSUE THREAD

**Issue by kevingunn-wk** [hashicorp/packer#8410]
#### Overview of the Issue

Running `packer validate` against a template with the key `galaxy_command` under the `ansible-local` provisioner causes the validation to fail:

`unknown configuration key: "galaxy_command"`

#### Reproduction Steps

 - Add `ansible-local` as a provisioner
 - set `galaxy_command`
 - Run `packer validate template.json`

### Packer version

From `1.4.5`

### Simplified Packer Buildfile

Snippet of the template:
```
"provisioners": [
        {
            "type": "shell",
            "inline": [
                "sudo mkdir -p /opt/packer-provisioner-ansible-local/jira",
                "sudo chmod 1777 /opt/packer-provisioner-ansible-local"
            ]
        },
        {
            "type": "ansible-local",
            "playbook_file": "{{user `ansible_path`}}",
            "galaxy_file": "{{user `galaxy_file_path`}}",
            "playbook_dir": "../",
            "command": "PATH=$PATH:~/.local/bin & ANSIBLE_REMOTE_TEMP=/opt/packer-provisioner-ansible-local PYTHONUNBUFFERED=1 ansible-playbook",
            "galaxy_command": "PATH=$PATH:~/.local/bin ansible-galaxy",
            "extra_arguments": [
                "-vvvv" ,
                "--become",
                "--become-method=sudo",
                "--become-user=root"
            ]
        }]
```

### Additional Details

Looking at previous PRs, looks like a fix was proposed in PR #5105 but was never finished because it needed a "fixer". Another reference to the same issue is in #5100. Documentation was first added in #5104.

However, looks like recently documentation was updated to use the command `galaxy_command` instead of the working `galaxycommand` - see PR #8314 

It would seem the best course of action is to revert the documentation, then work on adding a mapping to `galaxy_command`.

**Comment by nywilken** [comment]
Hi @kevingunn-wk thanks for opening up this issue, and accompanying PR. Looking into the provisioners (ansible, and ansible-local) I see that the galaxy command is mapped two different ways 

https://github.com/hashicorp/packer/blob/d15f43e4eb9a7fb3d1a5e0c51d4bde2fceae5f83/provisioner/ansible/provisioner.go#L67

https://github.com/hashicorp/packer/blob/29d6c05ef87e0296d970b70a88234a39a9e3c4a6/provisioner/ansible-local/provisioner.go#L70

Which is what may have lead to the confusion around the documentation PR change where `galaxycommand` was renamed to `galaxy_command`. It may help to update the `ansible-local` provisioner to have parity with the remote `ansible` provisioner so that users are not confused; especially since both provisioners share the `galaxy_file` attribute. 

The original PR where this fix was being made was closed due to inactivity. Any chance you would be up for running with that PR and adding the needed fixer? The fixer would look similar to the following [Powershell Fixer](https://github.com/hashicorp/packer/blob/master/fix/fixer_powershell_escapes.go) but for the Ansible provisioner for the `galaxy_command` and `galaxycommand` attributes.
