### ISSUE TITLE
Long tasks result in logging frozen and provisioner stdout blocked

### ISSUE THREAD

**Issue by howels** [hashicorp/packer#8426]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

We have found that with both Virtualbox and QEMU builders, Packer will run an Ansible playbook but often freeze mid-way through if we log a lot of data. When frozen like this Packer will not respond with CTRL+C and must be sent a "kill -9" to abort the build.

#### Reproduction Steps

Run the Ansible-Local provisioner and produce several thousand lines of log output.

### Packer version
1.4.3

### Simplified Packer Buildfile

Any Ansible-local provisioner which produces a lot of output.

### Operating system and Environment details

CentOS 7 VM on CentOS 7 host.

### Log Fragments and crash.log files

No log output produced, as log freezes when this occurs even with debug logging enabled.

**Comment by azr** [comment]
Hello @howels thanks for openning; I think this could have been fixed by https://github.com/hashicorp/packer/pull/8356 I recently tagged a nightly release of packer; could you please tell us if the binaries you can find [here](https://github.com/hashicorp/packer/releases/tag/nightly) work in your test case ? 

I think we won't but otherwise we need more infos to debug this ! Like a simplified buildfile.

**Comment by howels** [comment]
You are a :star2: 

Running build using this pre-1.5.0 nightly build right now.

**Comment by howels** [comment]
The new binary now gives me an error whilst doing the QEMU disk resize:

`==> test: Error creating hard drive: QemuImg error: qemu-img: warning: Shrinking an image will delete all data beyond the shrunken image's end. Before performing such an operation, make sure there is no important data there.
==> test: qemu-img: Use the --shrink option to perform a shrink operation.`

**Comment by howels** [comment]
The above error was caused by the QEMU builder now assuming that disk sizes are Bytes instead of Megabytes. Once I made this change I am greeted by another error, QEMU cannot get a write lock on the disk image once it is resized. I am continuing to test.

**Comment by howels** [comment]
I am also hitting an error with the QEMU builder, where the QEMU argument over-rides which worked in 1.4.3 are now ignored, resulting in double arguments which conflict.

**Comment by howels** [comment]
I have logged the QEMU issues regarding over-rides (or failing to over-ride) in https://github.com/hashicorp/packer/issues/8436

**Comment by azr** [comment]
Hey @howels thanks for confirming ! Because your QEMU issue is a different one I think we can close this one !

**Comment by howels** [comment]
Sorry. I have tried to test this but the instant I tried 1.5.0 I hit breaking bugs in the QEMU implementation which prevent me from testing. There have been serious QEMU builder regressions between 1.4.3 and the 1.5.0 nightly that you posted - if these can be resolved then I can re-test.

**Comment by howels** [comment]
> Hey @howels thanks for confirming ! Because your QEMU issue is a different one I think we can close this one !

Please note that I am unable to confirm if this fixes the issue.

**Comment by tjmcs** [comment]
@azr, it seems to me that this issue should remain open until it can be confirmed that the nightly build you referenced does indeed fix this problem. As I understand it, @howels has not been able to confirm that the changes in that build do resolve his issue because of other bugs he has encountered in that build.

Can you please reopen this issue until @howels can confirm that the build you refenced does indeed fix this problem, @azr?

**Comment by howels** [comment]
Issue resolved! Thanks everyone.
