### ISSUE TITLE
Add huaweicloud-ecs as a new third party builder plugin

### ISSUE THREAD

**Issue by zengchen1024** [hashicorp/packer#8487]
#### Feature Description

Could add [huaweicloud-ecs](https://github.com/huaweicloud/packer-builder-huaweicloud-ecs) as a new third party builder plugin? It would be great to add it bellow the list of [**Community Builders**](https://packer.io/community-tools.html#community-builders). Thanks very much!!!

**Comment by zengchen1024** [comment]
@SwampDragons Thank you!!!

**Comment by PumpkinSeed** [comment]
@zengchen1024 Is there any reason to have the vendor folder in the repository?

**Comment by zengchen1024** [comment]
@PumpkinSeed Should I remove it? I see many projects have vendor directory too, like [vultr packer builder plugin](https://github.com/vultr/packer-builder-vultr). Thank you for your reviewing and also submitting a pr to packer.

**Comment by PumpkinSeed** [comment]
> @PumpkinSeed Should I remove it? I see many projects have vendor directory too, like [vultr packer builder plugin](https://github.com/vultr/packer-builder-vultr).

I prefer to leave the vendor folder out from git. The reason behind this, because the project builds it's own vendor folder, so the used libraries like the builder doesn't have to. Because of this we spare some storage capacity. Also if you use go modules than the go.sum stores the necessary version restrictions. 
The main purpose behind the versioned vendor folder is what if the third-party tool get removed from. In this case it's good if you have a local copy in the repository, but it's not a common behaviour, so the repositories don't get remove just the sake of fun. 
Based on these information you can decide to keep it. :)

> Thank you for your reviewing and also submitting a pr to packer.

You're welcome.
