### ISSUE TITLE
用命令行工具打渠道包，提示Error: Invalid Signature

### ISSUE THREAD

**Issue by Govien** [hashicorp/packer#8546]
先使用AndResGuard混淆资源，再用packer的命令行工具打渠道包，提示Error: Invalid Signature，有人遇到这个问题吗

**Comment by nywilken** [comment]
Hi @Govien are you still running into an issue? If so, can you please open a new issue using the following [Bug Template](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) with the appropriate information so that we can best help. If you're issue is a question you might want to try asking the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help, since issues are mostly only read by maintainers.
