### ISSUE TITLE
Provisioner failing at  SysprepInstance.ps1 windows server 2016

### ISSUE THREAD

**Issue by bumblebee939** [hashicorp/packer#8596]
This is my first time ever posting on github, so please pardon me if I am not in the right place.

pakcer version -1.4.4
client - mac OS

I am running into an issue at the sysprepinstance step with exitcode 16001. I believe its killing the winrm connection when I run sysprepinstance even with -noshutdown flag, but I am not sure how to correct this one.

I have looked into previous posts, the one close was #6173 but could not find a solution there, can you please point me in the right direction ? If I remove the sysprepinstance its moving along

Here  is the piece of code that is failing.
"provisioners": [
  {
    "type": "powershell",
    "inline": [ "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule", "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -Noshutdown" ]
           
  }

Here is my error

==> windows-server-2016: Connected to WinRM!
==> windows-server-2016: Provisioning with Powershell...
==> windows-server-2016: Provisioning with powershell script: /var/folders/7c/wx7srrg56qz2xwnjcvf4tq0r0000gp/T/powershell-provisioner786008253
    windows-server-2016:
    windows-server-2016: TaskPath                                       TaskName                          State
    windows-server-2016: --------                                       --------                          -----
    windows-server-2016: \                                              Amazon Ec2 Launch - Instance I... Ready
==> windows-server-2016: Provisioning step had errors: Running the cleanup provisioner, if present...
==> windows-server-2016: Terminating the source AWS instance...
==> windows-server-2016: Cleaning up any extra volumes...
==> windows-server-2016: No volumes to clean up, skipping
==> windows-server-2016: Deleting temporary keypair...
Build 'windows-server-2016' errored: Script exited with non-zero exit status: 16001.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> windows-server-2016: Script exited with non-zero exit status: 16001.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by nywilken** [comment]
Hi there, sorry for not getting back sooner. GitHub issues are always a good first place to start so  thanks for reaching out.  Issues are mostly only read by maintainers and used for tracking bugs or enhancements on Packer so we will try to help out with questions when we can.

Regarding the issue, it appears that the script is exiting with a non-zero exit code so Packer is exiting because the script seems to be failing. For valid non-zero exit codes there is the [valid_exit_codes](https://packer.io/docs/provisioners/windows-shell.html#valid_exit_codes) option but that may not apply in this case.  As the error code 16001 tends to denote an "An unknown error has occurred." Have you checked that the powershell script executes successfully?

If you are still having an issue, I recommend asking the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help with sysprep related issues.

**Comment by SwampDragons** [comment]
Since I believe this question is configuration-related and will be solved by either fixing your sysprep script or by adding 16001 to a list of valid exit codes, I'll close. If you continue to have issues troubleshooting, you may want to run using the --debug flag, or use a breakpoint provisioner, to figure out what is going wrong with your script. 

If you believe there's something wrong with Packer still, we can reopen and continue to investigate.
