### ISSUE TITLE
Support Publish Managed Images to Azure Shared Image Gallery in a different subscription

### ISSUE THREAD

**Issue by aymond** [hashicorp/packer#8608]
#### Feature Description

Support publishing image to Shared Image Gallery deployed in separate subscription to where the images are being built.

#### Use Case(s)

Enterprise setups may have Shared Image Gallery which provides hardened images to multiple subscriptions.
AZ CLI has the ability to provide --subscription as an argument when creating gallery image definition and image version

**Comment by rahulsen** [comment]
Will this be part of the 1.5.2 release milestone ?

**Comment by SwampDragons** [comment]
We haven't had a chance to evaluate it to see if we can do it by then, but if you definitely want to see it in that milestone PRs are always welcome :D

**Comment by nywilken** [comment]
Hello :wave: thanks again for reporting, this should be fixed by #9875 ; some test binaries are available via the link below if you would like to test and confirm that the feature works as expected. Thanks!

https://app.circleci.com/pipelines/github/hashicorp/packer/6995/workflows/b846f4fe-7a13-4789-95d5-23a0e3b11c35/jobs/78838/artifacts
