### ISSUE TITLE
Waiting for SSH To become available for CentOS8

### ISSUE THREAD

**Issue by santhoshganesan** [hashicorp/packer#8628]
==> hyperv-iso: Creating build directory...
==> hyperv-iso: Retrieving ISO
==> hyperv-iso: Trying C:/San/SV65/CentOS/CentOS-8.1.1911-x86_64-boot.iso
==> hyperv-iso: Trying file://C:/San/SV65/CentOS/CentOS-8.1.1911-x86_64-boot.iso?checksum=sha256%3A7fea13202bf2f26989df4175aace8fdc16e1137f7961c33512cbfad844008948
==> hyperv-iso: file://C:/San/SV65/CentOS/CentOS-8.1.1911-x86_64-boot.iso?checksum=sha256%3A7fea13202bf2f26989df4175aace8fdc16e1137f7961c33512cbfad844008948 => C:\San\SV65\hyper-packer\hyper-packer\packer_cache\90f663ae9e6efa846d32fef93d7a21fac2d5236a.iso
==> hyperv-iso: Starting HTTP server on port 8611
==> hyperv-iso: Creating switch 'vSwitch' if required...
==> hyperv-iso:     switch 'vSwitch' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive C:\San\SV65\hyper-packer\hyper-packer\packer_cache\90f663ae9e6efa846d32fef93d7a21fac2d5236a.iso ...
==> hyperv-iso: Mounting os dvd drive C:\San\SV65\hyper-packer\hyper-packer\packer_cache\90f663ae9e6efa846d32fef93d7a21fac2d5236a.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Determine Host IP for HyperV machine...
==> hyperv-iso: Host IP for the HyperV machine: 169.254.78.116
==> hyperv-iso: Attempting to connect with vmconnect...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Waiting 5s for boot...
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for SSH to become available...

And at VM side:

dracut-initqueue timeout - starting timeout scripts
Could not boot.
/dev/root/ doest not exist
Entering emergency mode..

**Comment by santhoshganesan** [comment]
further failed to to start switch root

**Comment by nywilken** [comment]
Hi @santhoshganesan thanks for reaching out here. Looking at the information you provided towards the bottom of your post :point_down: there appears to be an issue with booting the machine after the boot command. 

```dracut-initqueue timeout - starting timeout scripts
Could not boot.
/dev/root/ doest not exist
Entering emergency mode.
```
If you haven't already please check the contents of your boot_command and or preseed file for any possible commands that may result in leaving the VM in a non bootable state.  

I'd recommend on using the community for asking further questions on this issue :smile: https://www.packer.io/community.html

I'm going to close this one for now; but if you suspect this may be a bug with Packer and Centos 8.1 please use the [Bug Report Template](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) to create a new issue with all the requested information so that we can better assist. Cheers.
