### ISSUE TITLE
Issue: WinRM times out

### ISSUE THREAD

**Issue by GloverChris** [hashicorp/packer#8650]
Hello, I have a problem where WinRM is not connecting to an instance. I took a look at your documentation before submitting this issue and it was not helpful for my situation.

Things Ive done in the trouble shooting:

- Allow all ingress and egress traffic on the SG attached
- Validated that ec2 is getting a public IP
- Was successfully able to RDP to instance
- Looks at debug logs however the following consistently shows : [1] The following link includes debug log including all code for standing up the builder I want.

Things I have noticed: 
It seems as if the user_data_file isnt running on the host. Data backing this assumption is the fact that I cannot ping WinRM ports on the server and I have validated that I dont see the reg keys in windows registry that Im setting as part of WinRM configuration.

[1]
https://gist.github.com/GloverChris/d28280d41278d4a7753b77cc248ec2ac

**Comment by nywilken** [comment]
Hi @GloverChris thanks for reaching out. It is possible that the user_data file has not executed so winrm is not setup within the timeout window you are setting 15m. We generally default the timeout to 30m because WinRM can take time. As you are working on AWS you may want to set a longer timeout; I've seen the cloud_int process take a little time to kick off.

Seeing as you are able to connect to via RDP, you may want to try bumping the winrm_timeout to something extreme `120m` then via RDP connect and check the AWS cloud init logs to ensure that the user_data_file executes without issues.

If you run the `SetupWinRM.ps1 ` script manually via RDP is Packer able to connect via WinRM? 

Note: manually running of the SetupWinRM.ps1 should not be needed for Packer, but I would like to try and determine if it is a connectivity issue or just an issue with WinRM not being ready.

**Comment by SwampDragons** [comment]
Hi again! Thanks for reaching out. 

By default, you aren't allowed to connect via WinRM via any user other than the Administrator user. There's some Windows-side configuration you have to do, I think it's possible to do but I personally haven't done it.  Normally when I run windows builds I just use the Administrator user for this reason. 

When I changed your user to Administrator in the Packer config and your SetupWinRM.ps1 file, Packer was able to connect. 

I'm going to close since I was able to reproduce and then tweak your config to get it working, and this is a general WinRM issue not a Packer one. If you end up needing more help with this kind of initial configuration, the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

Thanks!

**Comment by GloverChris** [comment]
Thanks @SwampDragons ! you are once again super awsome!
