### ISSUE TITLE
AWS MaxRetries config not set after #7230

### ISSUE THREAD

**Issue by fly1028** [hashicorp/packer#8706]
The commit as part of #7230 https://github.com/hashicorp/packer/pull/7230/commits/4a2773f8fa3e362a0a22ff9d02996be259f19969

removed the MaxRetries setting from the AWS config. 

The MaxRetries used to be 11 at least in the previous version we were using : https://github.com/hashicorp/packer/blob/v1.2.1/builder/amazon/common/access_config.go#L99

And now, it is reverted back to the default = 3.

I feel like this should at least be set back to 11 after resolving #7053.

The statement in #7230 regarding 

> AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS will be set and used for all calls 

is not true as far as I can tell. These settings only impact waiters but not for retrying requests being throttled by AWS. We cannot use v1.5.1 as is without running into throttling issues which was way better with v1.2.1

Ideally, I think the MaxRetries should be exposed to user similar to how AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS work today.

**Comment by azr** [comment]
Hey @fly1028, thanks for reporting; and sorry this is affecting you; I'm looking into it right now.

**Comment by azr** [comment]
Hello there, again; I have opened #8709 to address this; basically it allows to add a `max_retries` to all aws builders; could you please tell me wether that fixes the issue for you ?

Binaries can be found here: https://circleci.com/gh/hashicorp/packer/32802#artifacts/containers/0

**Comment by fly1028** [comment]
I'm wondering if this should be exposed similar to AWS_MAX_ATTEMPTS and AWS_POLL_DELAY_SECONDS so that all retries for waiters and requests can be configured the same way and documented in the same place. 

#8709 address the problem but that requires people to make changes to all their packer templates in order to use a different MaxRetries.

The order problem with #8709 is the fact that the method func (c *AccessConfig) Session() (*session.Session, error) in builder/amazon/common/access_config.go is not only used in AWS builders. So users may be configuring max retries in the AWS builder and not expecting other use cases also be impacted. To me this is really a global MaxRetries settings not specific to AWS builders.

**Comment by azr** [comment]
Hello @fly1028, thanks for this ! Could you please describe to us what your are doing with Packer with this feature ? I think I/we want to get a better picture so that we can try to make the best possible solution.

___


> The other problem with #8709 is the fact that the method func (c *AccessConfig) Session() (*session.Session, error) in builder/amazon/common/access_config.go is not only used in AWS builders.

`(c *AccessConfig) Session() (*session.Session, error) in builder/amazon/common/access_config.go` is only used in AWS builders, for all builders. Each build has a different session; so there should be no spilling effects and every build should get a `max_retries` setting. We liked that approach because it is similar to [what Terraform is doing.](https://www.terraform.io/docs/providers/aws/index.html#max_retries)

In packer we have been trying to get rid of global/env variables that set everything. But with HCL support and #8588 a variable will be settable from env, you will be able to create an env var, for example:

```hcl
variable "max_retries" {
  type = number
  default = 11
}

// that can be used like so:
source "amazon-ebs" "example" {
  max_retries = var.max_retries
  // .......
```

And this max_retries variable could be set from an `PKR_VAR_max_retries` env var. The only issue here seems to be that you would have to set it for all builders you have ? Do you have a lot ?

In packer 'not HCL' you could also do:

```json
"variables": {
    "max_retries": "{{env `AWS_MAX_ATTEMPTS `}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "max_retries": "{{user `max_retries`}}",
