### ISSUE TITLE
Support Proxmox Builder storage_pool_type on cephrbd

### ISSUE THREAD

**Issue by ernstae** [hashicorp/packer#8710]
#### Feature Description

Many Proxmox VE users will use a ceph storage pool for their virtual machines. Please consider supporting new VM creation where `storage_pool_type` can be set to `cephrbd` and `vstorage_pool` the name of the cephrbd storage.

Currently, `storage_pool_type` supports only  `[lvm, lvm-thin, zfspool, directory]`

#### Use Case(s)

Ceph is supported as primary storage in Proxmox VE, and should be supported in Packer.

**Comment by dsyorkd** [comment]
One workaround I have found is to create the cephfs storage pool, so you get the auto cephfs mount, then just create a Directory storage pool mapped to the mount location of cephfs, using the directory method gives you all the goodie features on creation, else you can try the next solution:

To get the rbd setup with packer is to just have it create the drive/image in local storage, then as part of a post processing step in a local shell on the Proxmox host, ` "ssh root@{{user `proxmox_host` }} qemu-img convert -f qcow2 -O raw vm-disk-1001.qcow2 rbd:data/vm-disk-1001`:

-  -f qcow2 is the default disk format of the disk created by packer, 
-  -O is the output format, just make sure the rbd pool data exists and is mapped to a storage pool in Proxmox. 
- in my example I'm prepending ssh root@{{user `Proxmox_host` }} to the command since I execute the packer build remote from the Proxmox cluster

After that you'll need to change the mapping in the vm's conf file, change this line `scsi0: local:vm-disk-1001` where local is the storage pool you configured packer to use, to `scis0: ssd-vm-pool:vm-disk-1001` :
- ssd-vm-pool is the name of the storage pool in Proxmox cluster not the rbd pool name
- vm-disk-1001 is the disk `qemu-img convert` converted and stored in the rbd pool 

This takes only roughly four to five lines in my post config

This is definitely a must have in Packer though, Ceph is a first class citizen in Proxmox so the Packer builder should also represent this.

**Comment by carlpett** [comment]
Hey,
The change itself is really minor, I just don't have an environment to test it on, so it's been lying around in the backlog. I can submit a PR if either of you (@ernstae or @dsyorkd) could do acceptance testing on it?

**Comment by dsyorkd** [comment]
Sure, I’m actually working on my templates this week, so this would be a perfect time to test.

**Comment by carlpett** [comment]
Thanks! Please have a look at #9418

**Comment by sylviamoss** [comment]
Here're the binaries to test @carlpett's solution:  https://circleci.com/gh/hashicorp/packer/59713#artifacts/containers/0

**Comment by dsyorkd** [comment]
Built and tested on macOS Catalina `10.15.4`
go: `version 1.13.7 darwin/amd64`
Proxmox: `pve-manager/6.2-6/ee1d7754 (running kernel: 5.4.41-1-pve)`
Ceph: `ceph version 14.2.9`

Built several Proxmox templates last night, cephfs and rbd are working fine in my testing.
