### ISSUE TITLE
Feature Request: File provider automatically create child sub directories

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#8721]
#### Feature Description
When using the file provider to upload a directory with child dirs, the provisioner should automatically create the child dirs if they do not exist
#### Use Case(s)
Currently, you have to manually create the directories beforehand by running a shell provisioner.
Or by tgz the folders beforehand and untaring them afterwards - this is not elegant.

Having the create folder work done by the provisioner would simplify the packer.json giving a more elegant code

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I can see why this would be useful -- it would definitely be a better user experience not to have to explicitly create the whole directory tree. The problem is that implementing this feature would require Packer to know what the guest operating system is. That's something we avoid whenever possible because it adds a massive amount of complexity and maintainability cost to the code. 

I think for now/for the foreseeable future, we just don't have the team bandwidth to maintain this kind of feature, so I am going to close. Thanks again for the suggestion, though.
