### ISSUE TITLE
vsphere-iso multiple disk support

### ISSUE THREAD

**Issue by CHentke** [hashicorp/packer#8749]
After adding the possibility to add multiple nics (which was requested in #8739) to a VM in vsphere-iso it would be very useful to get same functionality concerning disks.

For this feature there is still a pull request in the old project from JetBrains: https://github.com/jetbrains-infra/packer-builder-vsphere/pull/113/files

#### Feature Description

Adding multiple disks to a VM in the config file

#### Use Case(s)

Create a separate OS and SWAP Disks for VMs and configure them during the os installation process.

**Comment by dasmokedog** [comment]
This single ability, or lack of, is what prevents us from using this new builder. We developed our internal MSB by using the CIS MSB as the starting point. This requires certain directories be placed on their own partition. We went a step further and placed them on their own VMDK which results in all variant of Linux OSs we support having 5 vmdks. This was also based on VMWare informing us that with version 6.5 performance is improved using multiple VMDKs vs 1 VMDK that is partitioned up. This makes sense because with multiple disks you can do read/write operations on all disks at the same time vs being queued.
