### ISSUE TITLE
ebs builder - spot_price parameter should have auto as default value

### ISSUE THREAD

**Issue by karl-cardenas-coding** [hashicorp/packer#8791]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

Currently for the EBS builder, when using spot instances the user has the option of specifying the maximum spot price threshold. This is achieved through the `spot_price` parameter. However, the default value for this parameter is `0`, which is the equivalent of using on-demand price.  Due to the user wanting to user spot instances to reduce cost, it makes sense to have the default value be `auto`.

#### Use Case(s)

Any user wanting to user spot instances and is comfortable letting Packer use its logic to determine the best spot price.

**Comment by SwampDragons** [comment]
Hi! We deprecated an "auto" feature after Amazon made changes to their spot pricing which made the analysis a lot less useful. https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/

**Comment by SwampDragons** [comment]
Sorry, pressed "enter" before I was done with my thought. We used to have an "auto" option which would calculate a bid based on recent bid history. But Amazon switched their pricing system in 2018. Now there's not really any such thing as "bidding" in their cloud. You always just have to pay the current spot price, and they will launch the image at that price unless it exceeds your maximum price. Setting spot_price to 0 means that the max spot price is the on demand price, yes, but that doesn't mean that you are bidding, or going to be paying, the on demand price. 

I suspect that different organizations have very different ideas about what a reasonable default "max" would be, so I'm not sure that setting an auto "max" threshold makes sense since it's such an organization-specific thing. Saying "the spot instance should definitely not cost more than it would cost if you just ran it on demand" makes sense to me, but I'm curious what you think would be a better solution that wouldn't cause undue spot rejections. Double the recent historical spot price? a few cents more than the recent historical price?

**Comment by karl-cardenas-coding** [comment]
@SwampDragons Gotcha, I think I'm picking up what you're saying. Although 0 is the default, and worded as on_demand in the API, that's not really the accurate. So to me, this sounds more like an API documentation update, as current documentation does not reflect the new reality.

https://packer.io/docs/builders/amazon-ebs.html#spot_price
