### ISSUE TITLE
inspec provisioner is unable to write to a file in xml or json

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#8865]
Issues on GitHub are intended to be related to bugs or feature requests, so we
recommend using our other community resources instead of asking here if you
have a question.

- Packer Guides: https://www.packer.io/guides/index.html
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community.html

**Comment by AvinashSeelam** [comment]
{
      "type": "inspec",
      "inspec_env_vars": ["CHEF_LICENSE=accept"],
      "profile": ".\baseline.rb",
      "extra_arguments": [
        "--ssl",
        "--reporter",
        "cli",
        "junit:c:\temp\test.xml"
      ]
    }

**Comment by nywilken** [comment]
Hi :wave: thanks for reaching out. Inspec is one of our community-supported plugins, which means that the HashiCorp maintainers don't spend much engineering time on it. Have you tried asking the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help? 

If you are still running into issues and suspect that there might be a bug please provide us with the following information so that we can best try to help: 

Packer version from `packer version`
Host platform
Full debug log output from `PACKER_LOG=1 packer build template.json`
Please paste this in a gist https://gist.github.com
The simplest complete example template and scripts needed to reproduce the bug.
Include these in your gist https://gist.github.com

Thanks!

**Comment by justyns** [comment]
FWIW this is working for me on MacOS and Linux.  I am using a provisioner like this:

``` json
{
    "type": "inspec",
    "inspec_env_vars": [ "CHEF_LICENSE=accept"],
    "profile": "https://github.com/dev-sec/linux-baseline",
    "extra_arguments": [
      "--reporter",
      "cli",
      "junit:.junit/dev-sec-linux-baseline.xml"
    ]
  }
```

After packer finishes running, I have a `.junit/dev-sec-linux-baseline.xml` file in my current directory.

My versions:

```
$ packer version
Packer v1.6.0
$ inspec version
4.18.39
```
