### ISSUE TITLE
Better default for boot_key_interval

### ISSUE THREAD

**Issue by sevenbill** [hashicorp/packer#8930]
#### Overview of the Issue
Typing over vnc is too slow. While 100ms isn't the worst initial guess, perhaps a better default would be to use human typing speed as a reference point.
1 second / 20 Words per minute * 5 characters / word = 10ms/character

"boot_key_interval": "10ms"

#### Reproduction Steps

Any packer.json with a long `boot_command`

### Packer version

1.5.4

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

The reason this key interval is set to a much-longer-than-typing-speed value is that the default is intended to work for most shared build infrastructure setups, where various spiky resource usages can mean that shorter delays would cause failures; We decided that it was better to have a long, slow default here than to unnecessarily cause build failures because of a shorter delay meaning a missed keypress, forcing users to find and tweak this one lever that many of them probably never want to even have to know about.

And if that default doesn't work for you, that's okay! That's why we made it configurable. But given that Packer doesn't have a great way of knowing whether it's on shared build infrastructure versus a personal workstation where a 5-10ms interval is likely totally appropriate, I think it's more prudent to air on the side of caution and let users configure to a speedier interval when that works for them.
