### ISSUE TITLE
packer image build fails with waiting for ip

### ISSUE THREAD

**Issue by meghamanjappa** [hashicorp/packer#8937]
Hi,,
i am very new to vmware and trying to create a simple windows server 2019 image from packer.
everytime the build fails at waiting for IP. 
It installs OS and i can see it runs some commands in the cmd but it stucks after opening server manager.
![image](https://user-images.githubusercontent.com/43515961/77304660-c763b880-6d1a-11ea-846a-370773e39cc4.png)

below is the json file. not sure where i am going wrong
{
	"builders": [{
		"type": "vsphere-iso",

		"vcenter_server": "**********",
		"username": "******************",
		"password": "***********************",
		"insecure_connection": "true",

		"cluster": "cluster1",
		"network": "vm_network",
		"datastore": "datastore1",

		"communicator": "winrm",
		"winrm_username": "Administrator",
		"winrm_password": "Password",

		"convert_to_template": "true",

		"vm_name": "windows2019",
		"guest_os_type": "windows9Server64Guest",

		"CPUs": "2",
		"RAM": "4096",
		"RAM_reserve_all": true,
		"firmware": "bios",

		"disk_controller_type": "lsilogic-sas",
		"disk_size": "40960",
		"disk_thin_provisioned": true,

		"network_card": "vmxnet3",
		"boot_order": "disk,cdrom",

	   "iso_paths": [
          "[datastore1] windows2019.iso",
          "[datastore1] VM-tools.iso"
        ],
  
        "floppy_files": [
            "Autounattend.xml",
            "test2016/disable-network-discovery.cmd",
            "test2016/enable-rdp.cmd",
            "test2016/enable-winrm.ps1",
            "test2016/install-vm-tools.cmd",
            "test2016/set-temp.ps1"
        ]
      }
    ],
  
    "provisioners": [
      {
        "type": "powershell",
        "scripts": ["Install-VMwareTools.ps1"]
      }
    ]
   
  }

**Comment by animatco** [comment]
That I know of you have 2 options, either install the vmtools earlier (thru the autounattend) or change the NIC to the E1000.

**Comment by meghamanjappa** [comment]
i have tried with NIC to E1000 , is is saying unknown type.
i have tried attaching vmtools .iso as a floppy and installing it through autounattend but still i am getting stuck at server manager.  On the console it says vmware tools not installed

**Comment by SwampDragons** [comment]
That sounds like your autounattend isn't properly installing the tools.

**Comment by meghamanjappa** [comment]
i have followed this guillermo-musumeci/packer-vsphere-iso-windows link.. everything else is installing successfully but not the vmware tools..  is there any hardware dependencies , where am i going wrong!

**Comment by SwampDragons** [comment]
Unfortunately, I don't know. in these situations I generally recommend that you try to get the build working _without Packer_ to figure out where the installation is going wrong. This doesn't sound like a Packer bug to me, though the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) may have further advice on how to debug your autounattend file. 

Since this isn't something I think is actionable from a "fix a bug in Packer" perspective, I'm going to close. If you think that's wrong and there is something wrong with Packer that needs fixing, we can reopen but I'm going to need a compelling case that it isn't just an issue with the autounattend. Maybe you could open an issue against guillermo-musumeci/packer-vsphere-iso-windows and get some advice, since you're using their repo. 

Good luck!
