### ISSUE TITLE
Variables set later in the command don't override variables set earlier

### ISSUE THREAD

**Issue by xtimon** [hashicorp/packer#8974]
## Overview of the Issue

I define default variables in variables.json file. Some of the variables from the file I override with cli later.

#### Reproduction Steps

1. Define variables in variables.json file:

{
  "ami_name": "Debian10",
  "ami_version": "2.9.0"
}

2. Then try to override ami_version attribute with cli setting it later:

packer build -var-file=variables.json -var 'ami_version=test_build' template.json

### Packer version

From `1.5.5`

### Simplified Packer Buildfile

TBD later

### Operating system and Environment details

Amazon-ebs builder, on Ubuntu 18.04 x64

### Log Fragments and crash.log files

It doesn't fail. But doesn't work according to the documentation: https://packer.io/docs/templates/user-variables.html

**Comment by nywilken** [comment]
Hi @xtimon thanks for reaching out. This issue was reported in #8961, and has been fixed in #8964. 

Please see @SwampDragons comment for a link to patched binaries https://github.com/hashicorp/packer/issues/8961#issuecomment-605309537

I’m going to close this issue because it is a duplicate that has been resolved. But if after testing you find that you are still running into problems  please leave comment on this issue and I will reopen so that we can help get things squared away. Thanks!
