### ISSUE TITLE
CLI provided vars no longer override vars file values

### ISSUE THREAD

**Issue by unacceptable** [hashicorp/packer#8978]
#### Overview of the Issue

I Will provide more info before I go to bed.

#### Reproduction Steps

to do

### Packer version

Packer v1.5.5

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by sylviamoss** [comment]
Hello there! This is similar to https://github.com/hashicorp/packer/issues/8961 and was already fixed by https://github.com/hashicorp/packer/pull/8964.  The fix will go out in the next release! 
Until then, you can use our nightly version. You can find the binaries [here](https://github.com/hashicorp/packer/releases/tag/nightly).

I'm closing this issue for now. Feel free to reach out if you have any questions or problems.

**Comment by unacceptable** [comment]
Thanks for the info @sylviamoss!
