### ISSUE TITLE
Some features disabled when creating a RHEL Azure VM

### ISSUE THREAD

**Issue by hugo-paredes** [hashicorp/packer#8991]
I'm creating a RHEL managed image in using Azure-ARM. The build itself seems to work fine: the image is created and I can create a VM with it.

The `template.json` file:
```json
{
    "variables": {
        "subscription_id": "{{env `ARM_SUBSCRIPTION_ID`}}",
        "image_purpose": "solr",
        "managed_image_resource_group_name": "myResourceGroup",
        "image_publisher": "RedHat",
        "image_offer": "RHEL",
        "image_sku": "7.7",
        "image_version": "latest",
        "location": "West Europe"
    },
    "builders": [
        {
            "type": "azure-arm",
            "subscription_id": "{{user `subscription_id`}}",
            "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
            "managed_image_name": "{{user `image_offer` | lower}}-{{user `image_purpose`}}-{{isotime | clean_resource_name}}",
            "os_type": "Linux",
            "image_publisher": "{{user `image_publisher`}}",
            "image_offer": "{{user `image_offer`}}",
            "image_sku": "{{user `image_sku`}}",
            "image_version": "{{user `image_version`}}",
            "azure_tags": {
                "dept": "Engineering",
                "task": "Image deployment"
            },
            "location": "{{user `location`}}",
            "vm_size": "Standard_DS2_v2"
        }
    ],
    "provisioners": [
        {
            "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
            "type": "shell",
            "script": "script.sh",
            "skip_clean": true
        },
        {
            "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
            "inline": [
                "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
            ],
            "inline_shebang": "/bin/sh -x",
            "type": "shell",
            "skip_clean": true
        }
    ]
}
```
The `script.sh` file:

```bash
#!/bin/sh -x

SOLR_VERSION=8.5.0

yum update -y
yum install -y java-1.8.0-openjdk wget

cd /tmp
wget http://apache.40b.nl/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz
tar xzf solr-${SOLR_VERSION}.tgz solr-${SOLR_VERSION}/bin/install_solr_service.sh --strip-components=2
bash ./install_solr_service.sh solr-${SOLR_VERSION}.tgz

systemctl stop firewalld
systemctl disable firewalld
```

The end part of the build output:
```bash
==> azure-arm: Provisioning with shell script: /tmp/packer-shell681032167
    azure-arm: WARNING! The waagent service will be stopped.
    azure-arm: WARNING! All SSH host key pairs will be deleted.
    azure-arm: WARNING! Cached DHCP leases will be deleted.
    azure-arm: WARNING! root password will be disabled. You will not be able to login as root.
    azure-arm: WARNING! /etc/resolv.conf will be deleted.
    azure-arm: WARNING! packer account and entire home directory will be deleted.
    azure-arm: 2020/04/03 14:41:26.602202 INFO Examine /proc/net/route for primary interface
    azure-arm: 2020/04/03 14:41:26.604391 INFO Primary interface is [eth0]
==> azure-arm: Querying the machine's properties ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-zmv6nhiu6z'
==> azure-arm:  -> ComputeName       : 'pkrvmzmv6nhiu6z'
==> azure-arm:  -> Managed OS Disk   : '/subscriptions/9faac4cb-9dc7-4672-85f6-44027ead7635/resourceGroups/PACKER-RESOURCE-GROUP-ZMV6NHIU6Z/providers/Microsoft.Compute/disks/pkroszmv6nhiu6z'
==> azure-arm: Querying the machine's additional disks properties ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-zmv6nhiu6z'
==> azure-arm:  -> ComputeName       : 'pkrvmzmv6nhiu6z'
==> azure-arm: Powering off machine ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-zmv6nhiu6z'
==> azure-arm:  -> ComputeName       : 'pkrvmzmv6nhiu6z'
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'packer-Resource-Group-zmv6nhiu6z'
==> azure-arm:  -> Compute Name              : 'pkrvmzmv6nhiu6z'
==> azure-arm:  -> Compute Location          : 'West Europe'
==> azure-arm:  -> Image ResourceGroupName   : 'myResourceGroup'
==> azure-arm:  -> Image Name                : 'rhel-solr-2020-04-03T14-33-05Z'
==> azure-arm:  -> Image Location            : 'westeurope'
==> azure-arm: Deleting resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-zmv6nhiu6z'
==> azure-arm: 
==> azure-arm: The resource group was created by Packer, deleting ...
==> azure-arm: Deleting the temporary OS disk ...
==> azure-arm:  -> OS Disk : skipping, managed disk was used...
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> Additional Disk : skipping, managed disk was used...
==> azure-arm: Removing the created Deployment object: 'pkrdpzmv6nhiu6z'
==> azure-arm: ERROR: -> ResourceGroupNotFound : Resource group 'packer-Resource-Group-zmv6nhiu6z' could not be found.
==> azure-arm:
Build 'azure-arm' finished.

==> Builds finished. The artifacts of successful builds are:
--> azure-arm: Azure.ResourceManagement.VMImage:

OSType: Linux
ManagedImageResourceGroupName: myResourceGroup
ManagedImageName: <image name>
ManagedImageId: <some ID>
/myResourceGroup/providers/Microsoft.Compute/images/rhel-solr-2020-04-03T14-33-05Z
ManagedImageLocation: westeurope
```

After the image is created, I go to the Azure Portal and create a VM based on this image.
It all goes well until I get to the Management section where the option `Login with AAD credentials` is disabled. Also, the cloud init and the generation selection options are disabled.

Is this normal or am I missing something?

**Comment by hugo-paredes** [comment]
Hi there.
To bump up this issue/question.

**Comment by SwampDragons** [comment]
Sorry we haven't had a chance to investigate this. I am afraid I don't know the answer off the top of my head, and I'm not sure when I'll have a chance to do a deep dive. Have you tried reaching out to the mailing list?  https://groups.google.com/forum/#!forum/packer-tool

**Comment by nywilken** [comment]
Hi @hugo-paredes I am not familiar with AAD credentials on Azure, but looking at the provided config and scripts I don't see any reference to the vm extension needed for the AD login on Linux https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad

Have you tired installing the vm extension on a vm provisioned from the image to see if the options for AAD login become available?

**Comment by gm27rjpm** [comment]
Hello @SwampDragons, @nywilken,

I'm facing a similar issue while trying to build a Linux golden image using packer. Could you guys please look into my below query and suggest for a solution?

How CentOS Golden Image is created?
1. Execute a packer build script to create an intermediate image (which is only for converting standard root partition to LVM) 
2. With the intermediate image, I'm provisioning all my other tasks such as creating LVM partitions, OS security, hardening, CIS benchmark standards, Patch update etc., on this image to create a resultant golden image.

My problem here is I'm unable to use a fresh centos image available from https://cloud.centos.org site in Azure as like I did for other cloud environments. So, after a long try, I decided to use OpenLogic CentOS image as my source image. 

I'm able to create an intermediate image provisioned by using SSH communicator with "ssh_username" and "ssh_password" as authentication parameters. But when the packer attempted to build a golden image by using that intermediate image, it fails to provision with "ssh handshake error".

I wonder I have created a golden image last month without passing any "ssh_password" parameter in the packer build json file.
Attached that file for your reference.
[packer-azure-build-script.txt](https://github.com/hashicorp/packer/files/4591263/packer-azure-build-script.txt)

Even I tried to copy an ssh public key inside the intermediate image while provision using ansible roles and attempted to authenticate to the golden image by respective private key in packer builder script using the below configuration. It fails.
  "communicator": "ssh",
    "ssh_username": "centos",
    "ssh_private_key_file": "xxx.pem"
    "ssh_timeout": "20m",
    "pause_before_connecting": "10m"

Because the below "deprovisioning" command executed at the final stage of the intermediate image, removes all the ssh host key pairs available in it. 

![image](https://user-images.githubusercontent.com/54054180/81262083-ca143600-905a-11ea-9a7e-539bc3bbebed.png)

Please find the below error snip and packer logs attached for your reference.
![image](https://user-images.githubusercontent.com/54054180/81265011-f8484480-905f-11ea-8723-a37c00830b54.png)
![image](https://user-images.githubusercontent.com/54054180/81265070-11e98c00-9060-11ea-92b5-aa0f043823b2.png)

[packer-build-logs.txt](https://github.com/hashicorp/packer/files/4591327/packer-build-logs.txt)

I knew it was a lengthy post. But sorry I want to explain you clearly.

Please let me know if you have any suggestion.

Regards,
Guru Mohan G

**Comment by gm27rjpm** [comment]
Dear all,

I tried to launch a vm using the intermediate image from Azure portal manually. While launching VM itself, I have given the ssh_username and ssh_password.
But it is not accepting the same credentials which I have given during the VM launch time.

What should be modified in my packer script to accept the password given?

Regards,
Guru Mohan G

**Comment by gm27rjpm** [comment]
Hi All,

Kindly ignore my above post. I have fixed the ssh handshake issue.

Thank you!

Regards,
Guru Mohan G

**Comment by SwampDragons** [comment]
Closed since we haven't heard back from OP since May, so I'm hoping @nywilken's question led you to a solution. If it didn't, and there's something else going on, just let us know and we can reopen.
