### ISSUE TITLE
Storage Account Type - SSD Not Generating - Default Standard HDD Appears

### ISSUE THREAD

**Issue by babu2082** [hashicorp/packer#9010]
Storage Account type of Images generated through Packer is always Standard HDD. 

Is there any possibilities to generate the Image with SDD storage account type ?

If so which attribute, do I need to use in Packer Template ?

I have already tried with the below attribute, but its still generated as Standard HDD.

 "managed_image_storage_account_type": "Premium_LRS",

Let me know the possibilities on this.

**Comment by nywilken** [comment]
Hi @babu2082 thanks for reaching out. Setting `managed_image_storage_account_type` to Premium_LRS with a `vm_size` that supports Premium storage like the `Standard_DS2_v2` should result in a SSD backed instance. The default `vm_size` is `Standard_A1` which does not support Premium storage. What VM size(s) have you tired?  

If you are using a supported VM size - see [here](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/) for a list of SSD supported VMs -  
 and still running into issues please attach your redacted build configuration along with the Packer debug logs for your build `PACKER_LOG=1 packer build template.json` to help us better understand what might be going on. Cheers!

**Comment by babu2082** [comment]
Below are the attributes that I have it in Packer Template

 **"location": "westeurope",
  "vm_size": "Standard_DS2_v2",
  "managed_image_storage_account_type": "Premium_LRS"**

But I could see the generated images in Shared Image Gallery still shows the Standard HDD.

Attached you the screenshot of the Image in Shared Image Gallery. Will upload the log once the build is completed.

![sdd](https://user-images.githubusercontent.com/59554116/78637652-7bd11300-78b3-11ea-9f09-2fa149ab644b.png)

**Comment by babu2082** [comment]
Just though to add an additional information to the above.
 
I have checked the Source Image, where it shows as Premium SSD. But the same image it shows as Standard HDD in Shared Image Gallery. 

Attached you the screenshot of both the image.

Also I would like to know is there anyway to specify Standard SSD ?

![ssdpacker](https://user-images.githubusercontent.com/59554116/78650117-2141b200-78c7-11ea-8177-813473f1a743.png)

**Comment by nywilken** [comment]
Hi @babu2082 thanks for the extra information - super helpful. I had a moment to take a look at this issue and I see that Packer does not currently send the storage type when publishing to the SIG so it is defaults to the Standard_LRS. 

I believe the fix is simply setting the `StorageAccountType` to the value of the ManagedImageStorageAccountType in the [step_publish_to_shared_image_gallery)](https://github.com/hashicorp/packer/blob/f0840f55d0b6f2ed54dbc9b6a69051cda89adfab/builder/azure/arm/step_publish_to_shared_image_gallery.go#L63) code block. I have not looked through all the code to confirm that, but the value at a minimum needs to be set there.

**Comment by peterlindsten** [comment]
Related: #10313
