### ISSUE TITLE
VSphere-ISO builder: Option to disable I/O Devices

### ISSUE THREAD

**Issue by stayfrostnl** [hashicorp/packer#9025]
Hello,

Is there any option in the VSphere-iso builder to disable I/O Devices(e.g. floppy_disk_controller) so that this is not enabled in the template after creation?

**Comment by SwampDragons** [comment]
The builder automatically removes the floppy devices before marking the machine as a template. I did find an old knowledge base article that says for some older systems the drive availability is read directly from the BIOS and needs to be set there: https://kb.vmware.com/s/article/2045015, but that's something you'll have to handle from within the system yourself since Packer doesn't know about what guest OS you're using.

**Comment by SwampDragons** [comment]
Is this what you're experiencing? Or is there some other way of disabling it that you're looking for?

**Comment by stayfrostnl** [comment]
Yea, It seems like my problem. We are using Centos 7 with a ks.cfg to create the template. But when I convert the template back to a VM and enter the BIOS, these Device are still enabled.

This is one of the manual steps we are still doing after Packer has run. So I am looking for a way to automate that. 
![Screenshot from 2020-04-09 08-29-01](https://user-images.githubusercontent.com/16762943/78864634-460b6600-7a3c-11ea-9a78-5c79315b68a5.png)

**Comment by SwampDragons** [comment]
I don't think we have feature to boot into bios settings from the vsphere-clone builder, though [this article](https://kb.vmware.com/s/article/1004129) has some tips on how to modify your vmx file to automatically boot into the bios. But I don't think manual VMX options will let you navigate the bios to remove the controller. If you want and are willing to test, I can try to add a boot_command step to the vsphere-clone builder, and you can see if you can use the boot command to automate whatever steps you need to do in the bios. Interested in trying?

**Comment by stayfrostnl** [comment]
Thx for the article. Yes, I am interested in trying.

**Comment by SwampDragons** [comment]
Here's a build that enables a boot_command for the clone option: https://circleci.com/gh/hashicorp/packer/45634#artifacts/contianers/0 I think that this, plus setting the vmx file option to boot into the bios, should allow you to disable the floppy file.

**Comment by stayfrostnl** [comment]
Does that work with the VSphere-iso builder? The current boot command we are using:

        "<esc>",
        "<wait>linux inst.ks=hd:/dev/fd0:ks7.cfg<enter>"

**Comment by SwampDragons** [comment]
boot_command already worked for vsphere-iso; the linked binary adds it for the vsphere-vmx so that you can hopefully send commands over vnc when you boot into the bios using the vmx output from the previous build as a source in the vmware-vmx builder.

**Comment by SwampDragons** [comment]
Hi, I've never heard back from you here -- are you still interested in seeing if you can get this use case working with a boot-command on VSphere clone, or should I close this and the associated PR? I don't have the bandwidth to push this forward right now.

**Comment by ctorkington-craven** [comment]
I really like the idea of this feature for vsphere-iso.
if I add the "bios.forceSetupOnce":"TRUE" to the new configuration_parameters section (love this new feature!!), it does not apply to the VM, so it does not boot into BIOS. Am I doing something wrong?
Once I cabn get it to boot into BIOS, then I'll attempt the boot_command key strokes for configuration.

**Comment by ctorkington-craven** [comment]
I have a had a little look into this from the VMware side:-
I created a VM and set the 'Force BIOS Setup' in the GUI. 
It seems this does not create a .vmx entry (Advanced Configuration), so is not covered by the "configuration_parameters" option available in 1.6.0
Using PowerCLI I can see that 'EnterBIOSSetup' is under 
(get-view $VM).config.bootoptions
along with BootOrder, BootDelay, EFISecureBootEnabled.
As boot_order and firmware are in the same configuration area which is outside of "configuration_parameters" could you add a new option for 'EnterBIOSSetup', or possibly create a boot_configuration_parameters to cover all of these settings?

I can submit this as a new feature request if thats helpful

**Comment by SwampDragons** [comment]
It looks to me like booting into bios is is already available by setting the firmware option in the vsphere builder config: https://www.packer.io/docs/builders/vmware/vsphere-clone#firmware ... so that part is already doable, it appears.

The name of this group of things inside the vmware library we use is "VirtualMachineBootOptions" and contains the following options: 

```
type VirtualMachineBootOptions struct {
	DynamicData

	BootDelay           
	EnterBIOSSetup       
	EfiSecureBootEnabled 
	BootRetryEnabled     
	BootRetryDelay      
	BootOrder           
	NetworkBootProtocol 
}      
```

**Comment by SwampDragons** [comment]
We could probably add a pure pass-through to this. Under the hood right now Packer is just using the "firmware" option to set that bios/efi stuff on this struct. 

Relevant code is https://github.com/hashicorp/packer/blob/892413b7ea4daa0b8a984c43047e9312d272dba7/builder/vsphere/driver/vm.go#L139-L147

and https://github.com/hashicorp/packer/blob/master/builder/vsphere/iso/step_create.go#L155-L170. for the new vm workflow in the iso builder, but will take some more investigation about whether it can be set for cloning rather than creating new VMs.

**Comment by SwampDragons** [comment]
Ah, I found it -- it's the "Reconfigure" method on the VirtualMachine type.  That takes the VirtualMachineConfigSpec, which takes that "VirtualMachineBootOptions" struct above. Looks like while "firmware" is documented for vsphere-clone it's not actually being used, so that definitely needs to be fixed.
