### ISSUE TITLE
Not Getting public IP for the VM which is getting created

### ISSUE THREAD

**Issue by purnimaY** [hashicorp/packer#9083]
Hi,

I am trying to create a Linux VM in Azure. But the created VM is always taking private IP 
 Network Connection  : 'PrivateEndpoint'. Please suggest is there any way to make this Network Connection Public.
Please suggest why this issue is coming?

**Comment by nywilken** [comment]
Hi @purnimaY sorry to hear you are running into issues here. It is hard to help without having any build configuration or log data present in the issue. Have you had a chance to review the Azure builder documentation for the config options you are using? 

There is a [private_virtual_network_public_ip](https://www.packer.io/docs/builders/azure-arm.html#private_virtual_network_with_public_ip) option that you might need to set, but I can't say for sure.Cheers!

GitHub is intended for tracking Packer bugs and enhancements. As such I’m going to close this issue, and recommend that you try asking the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help, since issues are mostly only read by maintainers.
