### ISSUE TITLE
Add NVIDIA vGPU configuration support for vSphere-ISO provisioner

### ISSUE THREAD

**Issue by seanpmassey** [hashicorp/packer#9122]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

Add support for configuring NVIDIA vGPU for new VMs in the vSphere-ISO provisioner.  NVIDIA vGPU is presented to VMware virtual machines as a shared PCI device that can be added through the VM settings in vSphere or programmatically.

Key inputs for this would be:
GRID Profile

Sample code for doing this in PowerCLI: http://www.virtu-al.net/2015/10/26/adding-a-vgpu-for-a-vsphere-6-0-vm-via-powercli/

#### Use Case(s)

The vSphere-ISO provisioner supports most VM hardware.  One notable absence is support for adding Shared PCI devices to new VMs that are being provisioned.  Adding vGPU support would enable end-to-end automated builds for machines that utilize vGPU.  Specific use cases for this would be building templates/gold images for GPU-enabled desktops and virtualized HPC/AI/ML/DL workloads.

**Comment by nywilken** [comment]
Hi @seanpmassey thanks for reaching out. You will be happy to know that there is an open request for vGPU support https://github.com/hashicorp/packer/issues/8872 and a PR that is in review https://github.com/hashicorp/packer/pull/8946 with dev binaries available for testing [here](https://app.circleci.com/pipelines/github/hashicorp/packer/4622/workflows/1a90ebeb-7a82-4f4c-a140-f8a9503cfdf1/jobs/45877/artifacts)

I'm going to close this issue since it is a duplicate. But feel free to add any new comments or additional asks around vGPU support to issue #8872. Cheers!

**Comment by seanpmassey** [comment]
Hi @nywilken!  Thank you for the quick answer and additional info.  I did a few searches for NVIDIA and vGPU, and I didn't see anything.
