### ISSUE TITLE
Packer Runs In a Subscription - SIG In Another Subscripion - Error Thrown

### ISSUE THREAD

**Issue by babu2082** [hashicorp/packer#9158]
#### Overview of the Issue

We have two different subscription. Running the packer with a Service Connection created in one Subscription. But trying to publish the Image in another subscription.

In this case, packer throws error at the initial stage itself "Build 'azure-arm' errored: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group shared-image-gallery-rg"

So my question here is, first of all is it possible to perform like this ?

In case if possible, what access and where we need to provide that supports this action.

**Comment by nywilken** [comment]
Hi @babu2082 thanks for reaching out. Support for publishing to a SIG in another subscription is not yet supported. We have an open feature request for adding this support #8608. I don't have a timeline for when we will be able to add this feature, but we do prioritize reviews if you wanted to open a PR with the necessary changes. 

 I'm going to close this issue since it is a duplicate. But please feel free to add any new comments or additional asks around this request to #8608. Cheers!
