### ISSUE TITLE
Build from Cache

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/packer#9164]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

This is the same request from issue #1995, which is now locked and closed.  Lots of people want this feature but the issue was closed without any description or reason.

I'm working on developing a number of lengthy provisioning scripts to produce an ARM image using Packer and packer-builder-arm.  I'd like packer to cache the extracted image in the build stage so that I don't have to spend 3 minutes waiting unnecessarily at every script rerun.  Thank you :)

**Comment by SwampDragons** [comment]
Hi, thanks for opening.

To clarify -- are you, like in that other issue, hoping for some kind of cacheing between each provisioner step so that if the provisioning script fails you can restart from the last known-good state? 

In other words, you want Packer to export an image artifact between each provisioner and keep the last artifact before failing?  This would definitely be a huge undertaking. Not saying it can't be done, just that I'm not sure when the team would have a chance to work on it. 

There may be a lighter-weight way to get what you need, though. We have a pretty large number of debug options to help users tinker and get their builds into a working state. The `--debug` flag, which stops between each provisioner in order to allow you to check on your machine, the `breakpoint` provisioner, which allows you to pause at specific provisioning steps so you can get into your machine and see what's going wrong, the `on-error=ask|abort|retry` flag, which allows you to pause after a failed run and either stop Packer from cleaning up the bad artifact, or retry the failed provisioning step. We also have a new flag `max_retries` which applies to all provisioners and which allows you to set a number of retries that a provisioner can perform so that things like download failures because of network issues don't fail a long-running build. 

We also recommend breaking up long-running builds into smaller chunks to create your own "save points", and tying builds together in a pipeline. The output artifact from one can become the input artifact to another. If you know your build is failing at a specific point, you can save off the image right before hand and then use a second packer template to debug the failing part. It sounds like you're hoping for essentially that, but where we instead "save" at every single provisioning step. In a debug scenario this may make sense, but in a true build scenario this would cost a lot of time and disk space. 

I do think it's a cool idea, but we've got our major refactor/feature work mapped out for the near future and this probably won't bump anything off that map. So it may be a while. I'd recommend trying one of the above workarounds in the meantime.

**Comment by micchickenburger** [comment]
Thanks for the reply!  While an image artifact between each provisioner would be great, just caching the extracted build image would save a lot of time, e.g.:

```json
{
  "variables": { },
  "builders": [{
    "type": "arm",
    "file_urls" : ["http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.4-preinstalled-server-arm64+raspi4.img.xz"],
    "file_checksum_url": "http://cdimage.ubuntu.com/releases/18.04/release/SHA256SUMS",
    "file_checksum_type": "sha256",
    "file_target_extension": "xz",
    "file_unarchive_cmd": ["unxz", "$ARCHIVE_PATH"],
    "image_build_method": "reuse",
    "image_path": "output.img",
    "image_size": "2G",
    "image_type": "dos"
  }],
  "provisioners": [ ... ]
}
```

**Comment by SwampDragons** [comment]
Ah, I think I see. That would be a feature request to open against the plugin itself, which I believe in your case is https://github.com/mkaczanowski/packer-builder-arm.

**Comment by SwampDragons** [comment]
Since we don't manage that plugin, I'm going to close this issue since it's not actionable on this repo. Let me know if we can do anything for you from this side, though :) Thanks!
