### ISSUE TITLE
Non informative message about variables in HCL2

### ISSUE THREAD

**Issue by arren-ru** [hashicorp/packer#9168]
I defined specification in simple way:
```hcl
variable "target" { }

source "lxd" "arch" {
  image = "archlinux"
  output_image = var.target
}

build {
  sources = [ "lxd.arch" ]
}
```

Running `packer build -var 'target=test' .` reports:
```text
Error: Variables not allowed

  on <value for var.target from arguments> line 1:
  (source code not available)

Variables may not be used here.

==> Builds finished but no artifacts were created.
```

I can not understand this error as related to wrong specification of variable. I had to reread the documentation about variable specification but didn't find any errors and finally I randomly found that error disappears if I add `type = string` to the variable declaration block.
It is not obvious.

**Packer version: 1.5.6**

**Comment by nywilken** [comment]
Hi @arren-ru we will see what can be done to give the error messaging a little more context. The issue here is that without giving the variable block a type it defaults to the null type so when given a value of `test` the HCL parse will try to evaluate `test` as it is an HCL variable because it doesn't know it's expected type.

If however, you quote the value as in ` packer build -var 'target="test"' . ` the HCL parser will understand that it is meant to be a string and will handle the value properly - no need to specify `type = string`. 

Lastly, type constraints such as `type = string` are a good way for validating that the give value is of the expected type and should be used as a good practice. Given your example above, with no type constraint, you could easily assign target ` packer build -var 'target=1' . `  a number and it would not cause an issue for the parser, but probably not work as expected for your build.

**Comment by arren-ru** [comment]
@nywilken thanks for explanation, that was what I suspect about that error, but I think would be better to specify variable type in any case, so make it kind of strict typing.
