### ISSUE TITLE
source_ami_filter with platform set to Cent OS produces no matches

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/packer#9274]
#### Overview of the Issue

Setting the `platform` value in the `source_ami_filter` to `Cent OS` produces no matches. It should produce many matches.

#### Reproduction Steps

`packer build`

### Packer version

1.5.6

### Simplified Packer Buildfile

```hcl
source_ami_filter {
  filter {
    key   = "platform"
    value = "Cent OS"
  }

  owners      = ["567035441877"]
  most_recent = true
}
```

### Operating system and Environment details

Ubuntu 18.04

### Log Fragments and crash.log files

>Build 'amazon-ebs' errored: No AMI was found matching filters: {
  Filters: [{
      Name: "platform",
      Values: ["Cent OS"]
    }],
  Owners: ["567035441877"]
}

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

I was really surprised by this and went to do some digging.  It turns out to be a super confusing aspect of the AWS API. The "platform" filter used by the underlying describe-images command (api reference (here)[https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html]) is not the same as the "Resource Attributes" used when you search for an AMI via filters in the ec2 console.  In the describe-images call, "platform" can either be "windows" or unset. Granular flavors of linux aren't valid inputs here.

Not only will the filter "platform" not work for CentOS here, it also won't work for anything else other than "windows" (I tested with all kinds of different filters to try to verify this behavior). We tend to recommend you use the ami name with some globbed element, plus the owners field, to get the AMI you want. 

Sorry I can't give a more satisfying answer here. I agree that the AWS api can be a bit of a mind-bender. I could probably have the team add some kind of input validation to make sure that the platform field isn't mis-used, given that this is very confusing behavior on the AWS side, but it's not actually "fixable" other than that.

**Comment by mschuchard** [comment]
This does sound like a failure of the AWS API more than anything else. I was just using `platform` as an additional field to fine tune the search. Thanks for the info, and I will close.
