### ISSUE TITLE
More information about SSH options "ssh_private_key_file" and "ssh_keypair_name"

### ISSUE THREAD

**Issue by matteoiacovitti** [hashicorp/packer#9308]
Hello,

I am currently building a template for packer 1.5.6 and was wondering if I could get more info on how SSH works regarding Public/Private Keys

1. for `ssh_keypair_name` it says, if specified, this is the key that will be used for SSH with the machine. So does this mean I put the file name with/without the extension, or the SHA256 data itself? or the full path?

2. it also says `ssh_private_key_file` or `ssh_agent_auth` must be specified when `ssh_keypair_name` is utilized. So does this mean that I must have the option `ssh_keypair_name` in the template as well? and is it the absolute path or relative path?

3. How does packer use the key? Currently, I am using the Fedora CoreOS to build a VM and its ignition file creates the public key into the folder /home/USER/.ssh/authorized_keys.d/ignition. Will Packer understand this or is that determined by the OS?

Thanks in advance :D

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

Apologies for the confusing docs. We're working on a way to make them clearer. Not all options are valid for all builders, and we have yet to get that to be reflected properly. 

ssh_keypair_name is specific to the AWS cloud and I think some other of the cloud builders -- the idea is that you've pre-created named keys and saved them to the cloud. Packer then references the keypair in order to connect. You give Packer the path to the `private_key_file` locally and AWS or whichever cloud looks up the public key that matches the name you gave them, and puts that on the vm at launch time. 

In the situation where you aren't using a cloud with named pre-uploaded keys, there's an assumption that your preseed file is setting up the key (example: https://stackoverflow.com/questions/33113363/debian-preseed-late-command-not-executed) 

Hope this helps a bit.

**Comment by matteoiacovitti** [comment]
@SwampDragons Thanks for the replay

Yes. My public key is created using ignition, which is what Fedora CoreOS uses similar to the Debian preseed file

Not sure if you're familiar with it, but here is the section where it adds the key to the user, core

```
"passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAAB3NzaC1yc2[...]UoXptS7lXpQ47f Dev Master"
        ]
      }
    ]
  },
```
I will try my test without `ssh_keypair_name`

**Comment by matteoiacovitti** [comment]
@SwampDragons It worked! Thanks :D
