### ISSUE TITLE
Build only selected builders and ignore the rest

### ISSUE THREAD

**Issue by djmgit** [hashicorp/packer#9337]
#### Feature Description

There should be an option/feature to evaluate builders selectively rather than processing all the builders. For example an command line argument specifying the desired builders to be built or a global key which takes a list of builders to be built (might default to all).
This is in similar lines to issue #6489.

#### Use Case(s)

As of now my use case is specific to AWS builder. I have AWS infrastructure running in different regions and I wish to build images using Packer. Lets say I define builders dedicated to different regions in my template. Now I might need to update image in some of the regions but not all by help of the corresponding provisioners. I can always separate the builders into different files and loop over them selectively but that would increase the time of the entire process.

Is there any other way to achieve the above that I am missing?

**Comment by nywilken** [comment]
Hello @djmgit thanks for reaching out. Packer has the ability to selectively build only certain builders via the `--only` command line option. There is also a corollary option `--except` that allows a user to specify which builders and post-postprocessors to ignore.

Have you had a chance to look at `--only` or `--except` build options? 

For your particular use case by using named-builds, which is to give builders a specific name like `"name": "aws-west-build"`, you should be able to tell Packer to only build a specific builder using the command
 ```packer build --only=aws-west-build```

The use of named-builds  is important here because by default a build is named after its type, but since all of your builders are AWS builders you must use named-builds so Packer knows which build you are referring to. 

Here are a few links to our documentation you might find help 
https://www.packer.io/docs/commands/build/#options
https://www.packer.io/docs/templates/builders/#named-builds)

**Comment by SwampDragons** [comment]
I believe Wilken has answered this thoroughly, so I'm going to close the issue to make sure it doesn't go stale. If the --only flag doesn't suit your needs, we can reopen.
