### ISSUE TITLE
[azure-arm] force flag not respected

### ISSUE THREAD

**Issue by rolandjohann** [hashicorp/packer#9355]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Running the same build twice evenn with provided `-force` flag leads to
```
Build 'azure-arm' errored: the managed image named [...] already exists in the resource group [...], use the -force option to automatically delete it.
```

#### Reproduction Steps

`PACKER_LOG=1 packer build -debug -force -var 'subscription_id=[...]' .` with hcl provided below

### Packer version

From `packer version`: 1.5.6

### Simplified Packer Buildfile
<details>
  <summary>build.pkr.hcl</summary>

```hcl
variable "subscription_id" {
  type = string
}

source "azure-arm" "ubuntu" {
  subscription_id = var.subscription_id

  managed_image_resource_group_name = "[...]"
  managed_image_name = "[...]"
  os_type = "Linux"
  image_publisher = "Canonical"
  image_offer = "UbuntuServer"
  image_sku = "16.04-LTS"

  azure_tags = {
    owner = "team"
  }

  location = "West Europe"
  vm_size = "Standard_D4s_v3"

  # for dev purposes
  ssh_private_key_file = "~/.ssh/some_ephemeral_key"
  async_resourcegroup_delete = true
}

build {
  sources = [
    "source.azure-arm.ubuntu"
  ]

  provisioner "shell" {
    script = "./setup.sh"
  }

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang = "/bin/sh -x"
  }
}
```
</details>

### Operating system and Environment details

MacOS 10.15.2

### Log Fragments and crash.log files

```
2020/06/03 17:26:22 Build debug mode: true
2020/06/03 17:26:22 Force build: true
...
==> Some builds didn't complete successfully and had errors:
2020/06/03 17:26:23 machine readable: azure-arm,error []string{"the managed image named [...] already exists in the resource group [...], use the -force option to automatically delete it."}
```

**Comment by nywilken** [comment]
Hi @rolandjohann thanks for reaching out. Support for the `-force` flag with HCL builds was added in https://github.com/hashicorp/packer/pull/9234 and is set to be released in v1.6.0. The fix is available in our Nightly release binaries if you would like to access the feature before the official release. 

https://github.com/hashicorp/packer/releases/tag/nightly

Seeing as this has been resolved I am going to close this issue. But if you give the binaries a try and find that you are still running into problems with the `-force` flag leave a comment and I will gladly reopen. Cheers!
