### ISSUE TITLE
CIS Windows 2019 Azure Images not supported by Packer

### ISSUE THREAD

**Issue by amarkulis** [hashicorp/packer#9363]
In order to connect to a CIS DataCenter 2019 image you must execute winrm quickconfig -q before packer is able to use its provisioners.  There is no builder that is able to execute commands during the provisioning process in windows in Azure.  AWS supports this via the user_data_file but Azure's custom_data_file does not execute on provisioning.

**Comment by SwampDragons** [comment]
Last time I looked into this for someone, I believe I found that the custom_data_file doesn't execute because the Windows Azure images don't have cloud init. This isn't something Packer can solve. You'll need to either manually modify the image before running Packer against it, or you'll need to start from a non-hardened image and harden it yourself.  There's nothing Packer can do to work around this for you. See #8626 for context.

**Comment by amarkulis** [comment]
@SwampDragons I do agree with you that this is an Azure issue... BUT, technically you can run a custom script extension on a freshly provisioned server so if packer had a builder for azure extensions then people could execute via the custom scripts extension. I am sure there are other use cases where people would like to be able to run an azure extension on deployment as well like disk encryption.

**Comment by SwampDragons** [comment]
Let's discuss that as a possible solution over on #8626
