### ISSUE TITLE
conditional in ansible provisioner command triggers "no such file or directory"

### ISSUE THREAD

**Issue by amorcomb-west** [hashicorp/packer#9471]
#### Overview of the Issue

Attempting to run a script prior to execution of the ansible playbook. If condition is true, run the script.

        {
             "type": "ansible",
             "command": "if [ true ]; then {{ pwd }}/script.sh; fi",
             "playbook_file": "{{ user `playbook_dir` }}/{{ user `os` }}/playbook.yml",
             "extra_arguments": ["-e", "var = some_value", "-v"]
            
        }

Calling the script without the conditional yields a successful run:

        {
             "type": "ansible",
             "command": "{{ pwd }}/script.sh",
             "playbook_file": "{{ user `playbook_dir` }}/{{ user `os` }}/playbook.yml",
             "extra_arguments": ["-e", "var=some_var", "-v"]
            
        }

amazon-ebs: output will be in this color.

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: test
    amazon-ebs: Found Image ID: ami-0...
==> amazon-ebs: Creating temporary keypair: packer_5e...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-0...
==> amazon-ebs: Waiting for instance (i-0...) to become ready...
...

#### Reproduction Steps

$ packer build -var-file=variables.json my_ami.json

### Packer version

1.5.6

### Operating system and Environment details

MacOS 10.12.5

### Log Fragments and crash.log files

amazon-ebs: output will be in this color.

1 error(s) occurred:

* Error running "if [ true ]; then /Path_to_Script/script.sh; fi --version": fork/exec if [ true ]; then /Path_to_Script/script.sh`; fi: no such file or directory

**Comment by xjables** [comment]
The "command" parameter runs the given value via the [golang exec library](https://golang.org/pkg/os/exec/#Command). You're MacOS version is unix-like so I imagine it's running exec() somewhere under the hood.  exec() cannot run a script string as you have laid it out here.  It expects an executable.  That's why your second case runs but the first one doesn't.

I assume that you are in some way calling ansible-playbook in `script.sh`.  If you are able to, I recommend that you put that conditional check in the script.sh.  There is small 'gotcha'.  Packer checks the ansible version you have installed, so if you are not directly passing incoming command line args to ansible-playbook, you'll need to deal with the case where Packer tries to invoke this script as "./script.sh --version", like so:

```
#!/bin/bash
# script.sh

SOME_CONDITION=false  # Set this via the logic you want ansible to run on

if [ $1 == "--version" ] || $SOME_CONDITION; then
	ansible-playbook "$@"
else
	echo "Ansible will not be run because the condition failed"  #You can log to the terminal output if you want
	# exit 1 # If you want the build to fail, you can exit non-zero
fi

```

Note that the "--version" gotcha is in the error output you posted: 

> "if [ true ]; then /Path_to_Script/script.sh; fi **--version**": fork/exec if [ true ]; then /Path_to_Script/script.sh`; fi: no such file or directory

Packer is trying to run "*if [ true ]; then /Path_to_Script/script.sh; fi*" as if it is an executable and passing "--version" to it.  That is why you are getting a "file not found error".  It's looking for a file by the name of "if [ true ]; then ....", which, of course, doesn't exist (in a world that's not on fire).

If you are not able to include this check in the `script.sh` as I have suggested, then write a light wrapper for it exactly like above, except change out `ansible-playbook` for `./script.sh`.

The below example was built on `Packer 1.5.6` with "command" set to "./script.sh" with the modifications from above:

```
...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with Ansible...
    amazon-ebs: Setting up proxy adapter for Ansible....
==> amazon-ebs: Executing Ansible: ./script.sh -e packer_build_name=ubuntu18 -e packer_builder_type=amazon-ebs -e ansible_ssh_private_key_file=/tmp/ansible-key464995335 --ssh-extra-args -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible317482938 /home/${USER}/Repositories/golden/ansible/os_package_installs.yml
    amazon-ebs: Ansible will not be run because the condition failed
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI GoldenAMI-Ubuntu18-40 from instance i-00000000000000000
    amazon-ebs: AMI: ami-00000000000000000
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.
...
```

**Comment by SwampDragons** [comment]
This is exactly right; exec expects a binary. I'll update the documentation to make this clearer :)
