### ISSUE TITLE
From which version does "iso_checksum_type" configure key obsolete? 

### ISSUE THREAD

**Issue by jiatongw** [hashicorp/packer#9501]
Hi, based on the doc https://www.packer.io/docs/builders/vmware/vsphere-iso, I see that `iso_checksum_type` is obsolete and can be omitted.
`The type of the checksum can also be omitted and Packer will try to infer it based on string length`

Questions:

1. Does it only apply to `VMware builder`?
2. From which packer version does this change to be effected? 

Thanks!

**Comment by nywilken** [comment]
Hi @jiatongw thanks for reaching out. The support for the `iso_checksum_type` field was dropped in version[ 1.6.0](https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#160-june-09-2020) of Packer. It was dropped for all builders including VMWare.

When a configuration option is dropped we will provide a fixer via the `packer fix` command that can be used to fix any existing Packer template files. 

Since this is issue is labelled as a question I am going to close it. But If you are running into issues with the latest version of Packer please reach out and we will try our best to help out.

**Comment by jiatongw** [comment]
@nywilken For older packer version, Will this work?
`iso_checksum: "946a6077af6f5f95a51f82fdc44051c7aa19f9cfc5f737954845a6050543d7c2" `

Or I must specify the type:
`iso_checksum: "sha256:946a6077af6f5f95a51f82fdc44051c7aa19f9cfc5f737954845a6050543d7c2" `

**Comment by nywilken** [comment]
For older versions of Packer you can still use the `iso_checksum_type` to specify the type of the checksum. It is only in new versions of Packer where `iso_checksum: "sha256:946a6077af6f5f95a51f82fdc44051c7aa19f9cfc5f737954845a6050543d7c2" ` is valid. 

With that said, if the type is not specified the checksum type will be inferred by the length of the value of `iso_checksum` So `iso_checksum: "946a6077af6f5f95a51f82fdc44051c7aa19f9cfc5f737954845a6050543d7c2" ` is all that is needed for standard types. This statement is also true for Packer 1.6.0+.

**Comment by jiatongw** [comment]
Thank you!
