### ISSUE TITLE
IP address does not work. Can we set no_proxy?

### ISSUE THREAD

**Issue by hybmg57** [hashicorp/packer#9506]
IP address does not work unless I have no_proxy set. Can we set `ssh_no_proxy` option? so if it's true then it will set no_proxy for newly created instance?

In the meanwhile how can we get around this issue?

**Comment by SwampDragons** [comment]
Hi, thanks for opening. I just implemented something similar for the winrm communicator, so I should be able to do this for SSH too. I'll try to take a look before the next release.

**Comment by SwampDragons** [comment]
In the meantime, you can set up the ssh config to correctly use your proxy.

**Comment by hybmg57** [comment]
How do I set ssh config to set newly created ec2 ip?

**Comment by SwampDragons** [comment]
Packer will detect the IP and put it into the config for you automatically; in order to proxy the commands properly, you'll need to set the options: ssh_proxy_host, ssh_proxy_port, ssh_proxy_username, and ssh_proxy_password. Docs for these options can be found here:

https://www.packer.io/docs/communicators/ssh#ssh_proxy_host

**Comment by SwampDragons** [comment]
Looking at this, I believe that the no_proxy is a winrm specific workaround for the fact that the winrm config can't handle proxies well. The correct way to handle this issue is to properly set up the packer config to use a proxy; if you can't get this set up or think there's a bug in our proxy code, we'll take a look.

**Comment by SwampDragons** [comment]
Closing since I didn't get a response. We can reopen/open a new issue if it turns out there's a use case where configuring the proxy settings in the communicator is not sufficient.
