### ISSUE TITLE
Setting encrypt_boot false does not ensure boot volume is unencrypted

### ISSUE THREAD

**Issue by Nuru** [hashicorp/packer#9529]
#### Overview of the Issue

Using the [Amazon EBS Builder](https://www.packer.io/docs/builders/amazon/ebs), setting `"encrypt_boot": false` is not sufficient to create an unencrypted AMI when the account has EBS encryption enabled by default. (Setting `launch_block_device_mappings` with the root volume `"encrypted": false` does not help.)

The instance is still launched with an encrypted boot volume which in turn generates an encrypted snapshot and an encrypted AMI. 

#### Reproduction Steps

1. Enable EBS encryption by default (note that this only affects the current region):
```
aws ec2 enable-ebs-encryption-by-default
{
    "EbsEncryptionByDefault": true
}
```

2. Try to buid an AMI with `"encrypt_boot": false` and shared to another account

```
packer build min.json
```

Fails with error:

```
Build 'amazon-ebs' errored: Error modify AMI attributes: InvalidParameter: Snapshots encrypted with the AWS Managed CMK can’t be shared. Specify another snapshot.
```

### Packer version

Packer v1.6.0

### Simplified Packer Buildfile

<details><summary>min.json</summary>

```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "test-packer-encrypt-boot",
      "ami_users": ["137112412989"],
      "ami_description": "test AMI",
      "encrypt_boot": false,
      "force_deregister": "true",
      "force_delete_snapshot": "true",
      "associate_public_ip_address": "true",
      "shutdown_behavior": "terminate",
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "amzn2-ami-hvm-*-x86_64-gp2",
          "root-device-type": "ebs"
        },
        "owners": [
          "amazon"
        ],
        "most_recent": true
      },
      "instance_type": "t3.medium",
      "ssh_username": "ec2-user"
    }
  ]
}
```
</details>

**Comment by nywilken** [comment]
Good to know, thanks! We’ll take a look when we get a chance.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I think this is the documented behavior; when you enable-encryption-by-default, you force all instances launched to be encrypted. https://docs.aws.amazon.com/cli/latest/reference/ec2/enable-ebs-encryption-by-default.html

If you want to create an unencrypted image, you'll have to either disable encryption by default, or build in a different region where it isn't enabled. 

Since I don't think there's anything Packer can do about this, I'm going to close. Please reach out if you have any further issues!
