### ISSUE TITLE
Azure VHD is being deprecated warning message points to a documentation that does not exist

### ISSUE THREAD

**Issue by haokanga** [hashicorp/packer#9530]
#### Overview of the Issue

When building an Azure VM image VHD with `azure-arm`, a following warning message displays
```
azure-arm: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage
```

http://aka.ms/packermanagedimage points to https://www.packer.io/docs/builders/azure#vhd-or-managed-image which is a section that does not exist. There is supposed to a section titled "VHD or Manage Image". This documentation page https://www.packer.io/docs/builders/azure has no mentioning of the term "VHD" nor "Managed image".

As a result, this warning email is not actionable for the users at all. Users do not know what are managed images and how to transform a worked VHD solution into a manage-image solution.

#### Reproduction Steps

packer build with `azure-arm`

### Packer version

1.6.0

### Simplified Packer Buildfile
https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1604.json#L30-L55

### Operating system and Environment details
OS and environment are not relevant to this broken documentation link issue. 

### Log Fragments and crash.log files
No log relevant.

**Comment by nywilken** [comment]
Hi @haokanga thanks for pointing this out. The error message is out of date for sure and should be updated to point to the Azure ARM builder configuration options section https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options. PRs are welcomed if you are interested in updating the docs. Otherwise we will work on getting this updated in time for the next release. Sorry for any confusion.
