### ISSUE TITLE
[azure arm] Be able to change storage type before managed image is created

### ISSUE THREAD

**Issue by frankzo** [hashicorp/packer#9535]
### Feature Description

We would like to be able to build using a Azure Premium_LRS disk but after the build is ready we would like to store it as Standard_LRS obviously to save costs while maintain multiple versions.  

#### Use Case(s)

We build images that benefit greatly from Premium_LRS since build-time is cut in half for some images.  Premium_LRS comes with a higher price than Standard_LRS; it makes sense to store the images files as "Standard_LRS" since we are pushing to the Image Gallery too and we only maintain a few versions of the Image resource.

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. To confirm you would like to have an option to build managed images using a Premium_LRS storage type `managed_image_storage_account_type` but have them stored as a Standard_LRS without using an Image Gallery, is that correct? 

I ask because currently any managed image published to an Image Gallery will default to the Standard_LRS storage account type.

**Comment by frankzo** [comment]
Hi,
Correct. 
When packer finishes it creates a managed image and pushes it to the gallery. I cannot only push to the gallery since it needs a managed image to do so. 
I use this line to us a premium disk during build: `"managed_image_storage_account_type": "Premium_LRS"`. But when the VM is shut down and a image resource is being created, I would like to have the option to first convert it to Standard_LRS. Sothat the managed image is stored on less expensive storage.

**Comment by frankzo** [comment]
Any updates on this one?

**Comment by SwampDragons** [comment]
Not yet, sorry. We're a small team with a very long TODO list.  If this is urgent for you, we do always try to prioritize reviewing pull requests.
