### ISSUE TITLE
Packer/go-getter not using file contents checksum before downloads into `packer_cache` wastes bandwidth and disk space

### ISSUE THREAD

**Issue by dragon788** [hashicorp/packer#9595]
#### Overview of the Issue

I performed a build of a Windows VM using the evaluation ISO from a template using Packer 1.4.5, then I upgraded Packer to 1.6.0 which required me to remove the `iso_checksum_type` from the templates. When building the template again I would have expected it to use the ~4GB ISO that was already fetched because NOTHING about the ISO itself changed, it has the same SHA1 checksum in the template, and is pulled from the same URL, but Packer downloaded a new version to a new name in the cache. Once the download completed I verified using `sha1sum *.iso` in the `packer_cache` folder to confirm that it WAS the same contents, just with a different name.......

#### Reproduction Steps

Using a version of Packer that supports `iso_checksum_type` build a template that fetches an ISO and then remove the `iso_checksum_type` and it will probably download the ISO again. There doesn't appear to be a hashing of the local files or a locally saved checksum of a downloaded that could be used to verify whether the checksum provided for a remote file is already satisfied locally or if the local file is partially corrupted and a new download actually needs to happen.

### Packer version

1.4.5 to 1.6.0 is when I encountered the issue.

**Comment by azr** [comment]
Hey @dragon788, thanks for opening, yes, sorry this is wasting your bandwidth and space. There were reasons behind these changes.

We removed the redundant `iso_checksum_type` field which was causing some bug and misunderstanding from our users. It's all in the changelog:

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#160-june-09-2020

About cache files changing paths:

A bug was making Packer redownload similar isos https://github.com/hashicorp/packer/issues/6991 also loosing some bandwidtch/space, another bug was making some ISOs files collide for some builds and we fixed those in #6999 together with many other checksumming bugs/issue, we had to rework how the caching worked a little in order to fix everything, this is why you had a cache miss.

This might not be your case but we can argue that *most* of Packer users have unlimited and very fast internets/space facilities, which is why we did not try prevent this.

Hopefully this should not change in the future. 🙂 

I'm going to go ahead and close this issue as a won't fix !
