### ISSUE TITLE
Vsphere-iso iso from content library

### ISSUE THREAD

**Issue by ctorkington-craven** [hashicorp/packer#9687]
Could you add the ability to install the OS from an ISO mounted in vcenter content library?

Currently I have several geographically dispersed vcenters with ISO images (OS and vmtools) for Packer template builds. The ISOs are on datastores manually copied into place.
If the ISOs were in a content library they could be replicated around and less need for users accessing datastore files directly.

**Comment by arizvisa** [comment]
Ftr, it might be as simple as adding an abstraction which uses govmomi's library_item api to check the item's type for "iso", locking the item (with the api), and then just using the path that you get to do the install. After usage, the lock can then be released. I think the "type" of an item is different between versions of vSphere because the only ones I've seen are "iso", "ovf", and "vm-template".

Content libraries are essentially a pub/sub interface for sets of files on a datastore so you're still having to access the datastore's files directly anyways (only you get locking so people can't tamper with the file out from underneath you). So you still get a regular kind of path from it that you can use in the typical way.

I had to figure this out for an issue I reported in hashicorp/terraform-provider-vsphere#1126, so just letting others know...

**Comment by sylviamoss** [comment]
Hey there! A possible workaround until I implement something to make it easier, you can get the datastore path of the ISO that's inside a content library and use it in the [iso_paths](https://www.packer.io/docs/builders/vmware/vsphere-iso#iso_paths) option. 
To get the datastore path you can use `govc`. 
```
# to get the library_id
govc library.info
# to get the ISO datastore path
govc library.info -L /library_id/item_name/iso_file
```
