### ISSUE TITLE
After bsod can't make build process

### ISSUE THREAD

**Issue by demony** [hashicorp/packer#9700]
First time it was an error and bsod.

Now  i'm trying start build again and get this:

-------------------
D:\udacity\devops_course\devops\packer-templates>packer build -only=virtualbox-so application-server.json
==> Builds finished but no artifacts were created.

--------------------

D:\udacity\devops_course\devops\packer-templates>set PACKER_LOG=1
D:\udacity\devops_course\devops\packer-templates>packer build -force -only=virtualbox-so application-server.json

2020/08/03 17:21:03 [INFO] Packer version: 1.6.0 [go1.13.12 windows amd64]
2020/08/03 17:21:03 Checking 'PACKER_CONFIG' for a config file path
2020/08/03 17:21:03 'PACKER_CONFIG' not set; checking the default config file path
2020/08/03 17:21:03 Attempting to open config file: C:\Users\demon\packer.config
2020/08/03 17:21:03 [WARN] Config file doesn't exist: C:\Users\demon\packer.config
2020/08/03 17:21:03 Setting cache directory: D:\udacity\devops_course\devops\packer-templates\packer_cache
cannot determine if process is in background: Process background check error: not implemented yet
2020/08/03 17:21:03 [ERR] Checkpoint error: EOF
2020/08/03 17:21:04 Build debug mode: false
2020/08/03 17:21:04 Force build: true

2020/08/03 17:21:04 On error:
==> Builds finished but no artifacts were created.
2020/08/03 17:21:04 Waiting on builds to complete...
==> Builds finished but no artifacts were created.
2020/08/03 17:21:04 [INFO] (telemetry) Finalizing.
2020/08/03 17:21:05 waiting for all plugin processes to complete...

What can i do to start build?
Thnx.

**Comment by sylviamoss** [comment]
Hey there! Thanks for reaching out. We’ll take a look when we get a chance.
Until then, could you provide us a minimal version of the json template you're using?

**Comment by demony** [comment]
> Hey there! Thanks for reaching out. We’ll take a look when we get a chance.
> Until then, could you provide us a minimal version of the json template you're using?

I'm using https://github.com/udacity/devops-intro-project/blob/master/packer-templates/application-server.json
My steps are from here  - https://github.com/demony/devops-intro-project

At first start "packer" it asked me about problems with format of my json. (pleas rum "fix" and so on ) 
But  after bsod it does't ask me again (it is seems to me that it is not trying to read a file application-server.json).
(bsod was not because of "packer" but because of another soft)

I thot that it is all cashe problems, tried to clear it but ut doesn't help(

P/S/
My host system - win10 x64

**Comment by SwampDragons** [comment]
It doesn't appear that you've successfully called "packer fix" to update that template. At a minimum, you'll need to change these lines: 

```
        "iso_checksum": "b17d7c1e9d0321ad5810ba77b69aef43f0f29a5422b08120e6ee0576c4527c0e",
        "iso_checksum_type": "sha256",
```

to 

```
        "iso_checksum": "sha256: b17d7c1e9d0321ad5810ba77b69aef43f0f29a5422b08120e6ee0576c4527c0e",
```

You also haven't properly set the verbose logging, or I'd see a lot more logs which might help us debug better. I've never heard of Packer causing a windows BSOD so I wonder if there's something else going on with your computer.  

I'd recommend asking other people taking your udacity devops course for help; the github issue tracker for Packer is only followed by the tools' maintainers rather than the larger community, and it is dedicated to bugs and feature requests, rather than "getting started" questions for people learning the tool; we do have a community forum at https://discuss.hashicorp.com/c/packer that is a better venue for this kind of question.

**Comment by demony** [comment]
Ohhh... my fault.
I've entered wrong parameter
wrong = packer build -force -only=**virtualbox-so** application-server.json
**correct** = packer build -force -only=**virtualbox-iso** application-server.json

I'm sorry to trouble you(
