### ISSUE TITLE
vsphere-template post-processor -> Failed - the task was cancelled by a user

### ISSUE THREAD

**Issue by djordje-petrovic** [hashicorp/packer#9719]
Here's our post-processors chain:

> "post-processors": [
>     [
>         {
>             "cluster": "{{ user `vsphere_cluster` }}",
>             "datacenter": "{{ user `vsphere_datacenter` }}",
>             "datastore": "{{ user `vsphere_datastore` }}",
>             "disk_mode": "{{ user `vsphere_disk_mode` }}",
>             "host": "{{ user `vsphere_host` }}",
>             "insecure": "{{ user `vsphere_insecure` }}",
>             "only": [
>                 "vmware-iso"
>             ],
>             "options": [
>                 "--memorySize:{{ user `name` }}-{{ user `operating_system` }}-{{ user `uuid` }}={{ user `vsphere_options_memory` }}",
>                 "--numberOfCpus:{{ user `name` }}-{{ user `operating_system` }}-{{ user `uuid` }}={{ user `vsphere_options_cpus` }}"
>             ],
>             "password": "{{ user `vsphere_password` }}",
>             "type": "vsphere",
>             "username": "{{ user `vsphere_username` }}",
>             "vm_folder": "{{ user `vsphere_vm_folder` }}",
>             "vm_name": "{{ user `name` }}-{{ user `operating_system` }}-{{ user `uuid` }}",
>             "vm_network": "{{ user `vsphere_vm_network` }}"
>         },
>         {
>             "datacenter": "{{ user `vsphere_datacenter` }}",
>             "folder": "{{ user `vsphere_folder` }}",
>             "host": "{{ user `vsphere_host` }}",
>             "insecure": "{{ user `vsphere_insecure` }}",
>             "only": [
>                 "vmware-iso"
>             ],
>             "password": "{{ user `vsphere_password` }}",
>             "type": "vsphere-template",
>             "username": "{{ user `vsphere_username` }}"
>         }
>     ],
>     {
>         "type": "manifest"
>     }
> ]

This worked till recently. Now vsphere-template pp won't save template. It starts and fails with only error/message on vsphere 
saying 

> Export VM Failed - the task was cancelled by a user

There is nothing conclusive in esxi logs or packer debug log. Any clues?

**Comment by SwampDragons** [comment]
Hi! Thanks for opening an issue. I think I need a little more information from you:

> This worked till recently.

If you didn't upgrade Packer at the time this stopped working, and this seemingly stopped working overnight, it's unlikely to be a Packer bug and much more likely to be that someone at your company changed some setting in your vSphere cluster. This is my current theory because `the task was cancelled by a user` is a VMware error message, not a Packer one. You can search their forums or google to find some information on what normally causes that error message. 

If it did stop working at the same time as a Packer upgrade, it is possible that it's a Packer issue but I need to know what version you used before and what version you upgraded to.

If it is a Packer bug, we really do need the things requested in the issue template so we can have the best possible chance of reproducing the issue: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com

Thanks!

**Comment by djordje-petrovic** [comment]
@SwampDragons it started after updating Packer from 1.5.1 to 1.6.0. I've tested 1.6.1 also and behavior is the same.
I'm aware the error itself is esxi error but we have not made any changes to that host. So here are the details:

- Packer v1.6.1
- Host platform is Ubuntu 18.04.4 LTS
- https://gist.github.com/djordje-petrovic/1ea22357aed84c8413296bbac399b926#file-gistfile1-txt-L4104-L4109

There are no errors in that debug output. As far as Packer is concerned that post processor finished successfully. 
From what I've read in vmware docs this error frequently occurs when there is checksum mismatch on iso but there no any clues for this in our logs.

**Comment by SwampDragons** [comment]
Okay, I took a look at the git history for the vsphere-template post-processor to try to figure out what's going on here. The only real functionality change to this postprocessor was in https://github.com/hashicorp/packer/pull/8511

I think the defaulting here failed. Can you try to set `"register_vm": true` and tell me if that solves the issue for you? If it does, I'll go in and figure out how to fix the defaulting for this post-processor.

**Comment by djordje-petrovic** [comment]
Just dropping by to confirm adding "reregister_vm": true to post-processor does fix this issue. @SwampDragons thanks!

**Comment by SwampDragons** [comment]
Glad to hear it! Thanks for the confirmation.
