### ISSUE TITLE
Docker provisioner caching

### ISSUE THREAD

**Issue by droopy4096** [hashicorp/packer#9758]
#### Description

as per issue #1995 packer lacks the ability to use Docker cache (or any cache) for image building

#### Use Case(s)

At the moment I'm refactoring Microsoft Azure Pipeline Agent packer template to build container images (vs VM images) and finding the process to be overly tedious as build itself takes about 30min and with failures happening closer to the end of the build one has to spend extra 30min starting from start instead of recycling what already had been successfully built.  There is no way to iterate fast without some sort of caching of all the "good" steps/layers. 

#### Potential configuration

potentially having an option `--with-cache=XXX` save hashes for each step as tarballs (or other kind of blobs) under the `XXX` directory, along with the metadata for that step. upon re-run packer should be able to determine existence of cache for each step and use that.

**Comment by SwampDragons** [comment]
Architecturally speaking, this would be a complex change for Packer because of the fact that Packer is generally meant to manage VMs and not containers, and the builders which manage vm lifecycle only have limited knowledge of what the provisioners are doing. It probably wouldn't be impossible, but I think it would require a lot of work. I'll look into what it would take but don't expect anything in the next release or two.

In the meantime, you can manually create a similar effect by creating a Packer pipeline -- the example in our [docs](https://www.packer.io/guides/packer-on-cicd/pipelineing-builds) is for a virtualbox build but it is entirely applicable to Docker builds. The basic idea is that rather than a single Packer template, you create several where the output from one is the input to another, and each one only runs one or a small cluster of provisioners at a time. If this feels onerous for you, consider switching to HCL templates, which will use substantially less copy/paste because you can reuse build sources.

Here's an example of an hcl docker pipeline:

Create a directory, and inside create the following files:

sources.pkr.hcl
```hcl
source "docker" "example" {
  commit = true
  // any other configuration you want for your docker containers
}
```

build.pkr.hcl
```hcl
build {
  name = "step1"

  source "source.docker.example" {
    image = "ubuntu"
  }

  provisioner "shell" {
    inline = ["echo doin a heckin provision"]
  }

  post-processor "docker-tag" {
    repository = "ubuntu"
    tag = ["step-1-output"]
  }
}

build {
    name = "step2"

    source "source.docker.example" {
      // this can be the artifact from the step_1 build. You can retrieve this
      // from the manifest file produced in the step 1 build
      image = "ubuntu:step-1-output"
      // disable the pull if your image tag only exists locally
      pull = false
    }

    provisioner "shell" {
      inline = ["echo another provision"]
    }
}
```

pipeline.sh
```sh
#!/bin/bash
packer build -only='step1*' .
packer build -only='step2*' .
```

To run the pipeline, call pipeline.sh. You can add error checking to this script to abort if there's an issue with a build. You can create as many build steps as you want. Each can either inhabit one file, as shown here, or live in their own files in the directory. 

Hope this helps!

**Comment by SwampDragons** [comment]
Related to #9008

**Comment by droopy4096** [comment]
Thank you @SwampDragons, I did consider outlined approach but considering the sheer volume of components I have to deal with what I *may* gain on build times I will lose plenty on maintenance of the code. not to mention explosion of container layers under this scenario. Perhaps container building should be split out into it's own tool since admittably it introduces it's own set of unique challenges.
