### ISSUE TITLE
Add ability to set manual mac address in vsphere-clone builder

### ISSUE THREAD

**Issue by rconde01** [hashicorp/packer#9862]
#### Description
As a followup to question asked here:
https://groups.google.com/g/packer-tool/c/P4GV5e6ojKU

The vsphere-iso builder has the capability to set a manual mac address, but the vsphere-clone build does not even though this is possible in vsphere. It would be useful to have this capability in vsphere-clone as well.

#### Use Case(s)

Any time you want to use a fixed mac address it would be useful to be able to set that when building off a template/vm instead of only just an iso.

#### Potential configuration

```
network_adapters {
   mac_address = "00:00:00:00:00:00"
}
```

**Comment by sylviamoss** [comment]
Thanks @rconde01! We'll try to take a look for the next release.

**Comment by sylviamoss** [comment]
By the way, if someone is interested. I think this a good first issue. If I'm right all it has to be done is to pass the new mac address to `types.CustomizationAdapterMapping` here https://github.com/hashicorp/packer/blob/master/builder/vsphere/clone/step_customize.go#L185

**Comment by sylviamoss** [comment]
Hey there! I've implemented the solution and actually you don't net to set the `mac_address` option inside the customization block, you can set it straight forward. In order to make it work you need to also set the `network` option. 
Here the binaries you can try out: https://app.circleci.com/pipelines/github/hashicorp/packer/7147/workflows/1a719b9f-c44a-4f37-a266-30e75f8fe102/jobs/80925/artifacts
