### ISSUE TITLE
ssh_private_key_file not documented in SSH communicator doc page

### ISSUE THREAD

**Issue by harisund** [hashicorp/packer#9889]
https://www.packer.io/docs/communicators/ssh doesn't seem to have `ssh_private_key_file` option. 

However, even in the latest packer build `ssh_private_key_file` is still the way to specify a key.

Is this just a mistake in some doc clean up that happened recently, or is the removal of `ssh_private_key_file` from the documentation a precursor to some bigger upcoming change that will remove the key as a valid option all together?

**Comment by nywilken** [comment]
Hi @harisund thanks for reaching out here. The `ssh_private_key_file` option is indeed supported and will continue to be for the far future. 

The change to remove `ssh_private_key_file` along with some other options from the documentation was intentional as not all builders support the option.  See https://github.com/hashicorp/packer/pull/9513 for more details. 

With that said, I see how this can be confusing so I created a quick PR to help clarify things up a bit. Please let me know if the added note is helpful.

**Comment by harisund** [comment]
@nywilken , in my case I use the qemu builder. However, I am not able to find any reference to ssh_private_key in the qemu doc page - https://www.packer.io/docs/builders/qemu

Should I open a separate issue for that? 

But regardless, thank you for the update

**Comment by nywilken** [comment]
Sorry for the quick close by merging the PR. I'll reopen so that we can track the docs for any builders that might be missing the specific SSH options. 

Thanks for the clarification.
