### ISSUE TITLE
ESXi 7 packer support

### ISSUE THREAD

**Issue by bigfoot50** [hashicorp/packer#9901]
Hi,

is it possible to use ESXi7 free with packer and if yes how?

With ESXi7 there is no VNC Support. Tests with modified old scripts doesn´t work.

Regards 

Adrian

**Comment by sylviamoss** [comment]
Hey there! This is already being tracked here https://github.com/hashicorp/packer/issues/6482 and I've been working on this here https://github.com/hashicorp/packer/pull/9895.
I'm still trying to understand whether my changes will work for a free tier or not. You can test out the binaries and let me know the results, it will be great if it works. Here the binaries: https://app.circleci.com/pipelines/github/hashicorp/packer/7051/workflows/5bf4b0d2-6177-405b-8cd7-6679ee23c7fa/jobs/79593

Because is a duplicate, I'll close this issue. For further updates about this, I kindly ask you to follow up on the other issue and the PR.
