### ISSUE TITLE
Builds finished but no artifacts were created when variable blocks are Incuded

### ISSUE THREAD

**Issue by TejaswiniTharigopula2295** [hashicorp/packer#9929]
Packer Version 1.6.1

I'm trying to include variable blocks with json format

foo.pkr.json

{
  "variable": {
      "project_id": {
           "type": "string",
            "description": "Project ID in GCP",
            "default": ""
          }
    }
}

foo.pkrvars.json

{
 "project_id": "xxx"
}

when I run packer build -var-file="foo.pkrvars.json" . 

getting output as 

==> Builds finished but no artifacts were created.

**Comment by sylviamoss** [comment]
Hey there! So, I guess you should be using an HCL2 template instead of JSON in order to use the `foo.pkrvars.json`, the command line your using and to define the `project_id` variable as you did. 

I suggest you create a `variables.pkr.hcl` file with: 
```hcl
variable "project_id" { 
  type    = string   
  description = "Project ID in GCP"
  default = ""
}
```

And upgrade your JSON template to HCL2 using the [hcl2_upgrade](https://www.packer.io/docs/commands/hcl2_upgrade) command.

To keep working with JSON, you can the template with the correct form of the variables block like: 
```json
{
    "variables": {
           "project_id": ""
      }
}
```
and build the VM with the command: `packer build -var 'project_id=xxx' foo.json`

I suggest checking out the docs about user variables in JSON templates [HERE](https://www.packer.io/docs/templates/user-variables) and also the one about user variables in HCL2 [HERE](https://www.packer.io/docs/from-1.5/variables).

I'll close the issue but feel free to follow up with questions if you need some help.

**Comment by TejaswiniTharigopula2295** [comment]
Hey thanks updating to hcl2 solved my issue

<https://ggktech.com/>
Thanks,
Tejaswini Tharigopula

________________________________
