### ISSUE TITLE
Floppy filename capitalized

### ISSUE THREAD

**Issue by StefanZi** [hashicorp/packer#9961]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

One of the `floppy_files` specified in my build is renamed to a filename with all capital letters by mistake and thus breaking further automation on the built Linux OS.

#### Reproduction Steps

1. Use buildfile from gist
2. `resources/scripts` folder contains 3 files:
```
post_install.sh
vbt_change.sh
vbt_init.sh
```
3. `vbt_init.sh` will only be present as `VBT_INIT.SH` on the mounted floppy drive. Same goes for renamed `vbt-init.sh`

### Packer version

- Packer v1.6.2, installed via chocolatey

### Simplified Packer Buildfile

https://gist.github.com/StefanZi/3b6c29db39a71e3696766bcb612151d3

### Operating system and Environment details

- Packer running on Windows 10 1901 (18363.1082)
- called from system CMD
- VCSA: 7.0.0.10700
- Buildhost: VMware ESXi, 7.0.0, 16324942
- Using Visual Studio Code editor (1.49.1)

### Log Fragments and crash.log files

On creation filename is correct:
```
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying directory: resources/cloudinit/
    vsphere-iso: Adding file: resources\cloudinit\meta-data
    vsphere-iso: Adding file: resources\cloudinit\user-data
    vsphere-iso: Copying directory: resources/scripts/
    vsphere-iso: Adding file: resources\scripts\post_install.sh
    vsphere-iso: Adding file: resources\scripts\vbt_change.sh
    vsphere-iso: Adding file: resources\scripts\vbt_init.sh
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
```

### Additional info

Seems to be an issue of `init` in the filename, renaming the file to `vbt_initialize.sh` solved the issue.

**Comment by sylviamoss** [comment]
Hello there! I did some digging to understand what was going here and is actually how FAT works. 
To avoid this to happen you can define an option in our mount command to make short names (8 characters or less) like `vbt_init.sh` lowercase. The mount command would be `sudo -S mount -t vfat -o shortname=lower /dev/fd0 /mnt`. 

You can find some reference of what I'm talking about in https://linux.die.net/man/8/mount and https://en.wikipedia.org/wiki/8.3_filename.

Since there's nothing to do from Packer side, I'll close this issue.  Let me know if there's anything else I can help with.
